* Adjust slapd init file (Bug #34440) * Don't pass --pidfile for --start --test action, fails if file is invalid * Don't pass --pidfile for --start action, is ignored anyway * Don't pass --pidfile & --exec for stop action as --exec gets ingored then * Run stop --pidfile first and retry with stop --exec if slapd still runs * Don't sleep and hope, rather send a final KILL signal if slapd still runs * Output the retry/refused messages of start-stop-daemon --stop -v * log debug output to syslog in case db_stat fails
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.2/ucs-3.2-2@49967 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/management/univention-ldap/conffiles/etc/init.d/slapd b/management/univention-ldap/conffiles/etc/init.d/slapd
--- a/management/univention-ldap/conffiles/etc/init.d/slapd
+++ b/management/univention-ldap/conffiles/etc/init.d/slapd
@@ -24,6 +24,16 @@ SLAPDCONF=/etc/ldap/slapd.conf
 
 bdbrecover ()
 {
+	local back_bdb_version
+	local DBRECOVER
+	local DBSTAT
+	local dbstat_output
+	local dbstat_rc
+	local bdb_version
+	local stale_locks
+	local logger_tag
+	local line
+
 	log_action_begin_msg "Check database: "
 	# determine libdb version that back-bdb.so was linked against
 	back_bdb_version="$(/usr/bin/ldd /usr/lib/ldap/back_bdb.so | sed -n 's|.*/usr/lib/libdb-\([0-9.]*\).so.*|\1|p')"
@@ -31,14 +41,16 @@ bdbrecover ()
 	DBSTAT="/usr/bin/db${back_bdb_version}_stat"
 	if [ -e "${DBRECOVER}" ]; then
 		# check if the db_stat version works on the database environment
-		dbstat_output=$("${DBSTAT}" -h /var/lib/univention-ldap/ldap -Ne 2>/dev/null)
-		if [ $? = 0 ]; then
-			if echo "$dbstat_output" | grep -q 'Environment version'; then
+		dbstat_output=$("${DBSTAT}" -h /var/lib/univention-ldap/ldap -Ne 2>&1)
+		dbstat_rc=$?
+		if [ "$dbstat_rc" = 0 ]; then
+			bdb_version=$(echo "$dbstat_output" | sed -rn 's/^([^\s]+)\s+Environment version$/\1/p')
+			if [ -n "$bdb_version" ]; then
 				# check for stale locks or stale futexes
 				stale_locks=$("${DBSTAT}" -h /var/lib/univention-ldap/ldap -Nc | sed -rn 's/([0-9]*)\t*Number of current locks/\1/p')
 				if [ "$stale_locks" != 0 ]; then
 					log_action_msg "WARNING"
-					log_action_msg "WARNING: There are stale locks in LDAP backend Berkeley DB"
+					log_action_msg "WARNING: There are $stale_locks stale locks in LDAP backend Berkeley DB (version $bdb_version)"
 					log_action_msg "WARNING: If slapd does not respond, manual LDAP dump/restore may be necessary"
 					log_action_begin_msg "Continuing BDB database check: "
 				fi
@@ -47,10 +59,18 @@ bdbrecover ()
 			else
 				log_action_msg "/var/lib/univention-ldap/ldap BDB Version does not seem to match the one back-bdb uses"
 				log_action_msg "Skipping ${DBRECOVER} to avoid damage"
+
+				logger_tag="slapd db${back_bdb_version}_stat"
+				logger -t "$logger_tag" "BDB file version detection faild:"
+				echo "$dbstat_output" | while read; do logger -t "$logger_tag" "$REPLY"; done
 			fi
 		else
 			log_action_msg "Could not determine BDB version of /var/lib/univention-ldap/ldap"
 			log_action_msg "Skipping ${DBRECOVER} to avoid damage"
+
+			logger_tag="slapd db${back_bdb_version}_stat"
+			logger -t "$logger_tag" "command failed ($dbstat_rc):"
+			echo "$dbstat_output" | while read line; do logger -t "$logger_tag" "$line"; done
 		fi
 	else
 		log_action_msg "back-bdb was linked against ${back_bdb_version}, but db${back_bdb_version}-util package does not seem to be installed"
@@ -144,7 +164,7 @@ case "$1" in
 		check_autostart ldap ldap/autostart
 	fi
 	# check that no slapd is running
-	if ! start-stop-daemon --start --quiet --pidfile "$pidfile" --exec $DAEMON	--test > /dev/null; then
+	if ! start-stop-daemon --start --quiet --exec $DAEMON --test > /dev/null; then
 		log_action_msg "LDAP server already running"
 		exit 2
 	fi
@@ -167,7 +187,7 @@ for p in configRegistry.get('slapd/port/ldaps', '7636').split(','):
 print '\turis="%s"' % ' '.join(uris)
 if configRegistry.get('ldap/maxopenfiles'):
 	print '\t\tulimit -n %s' % configRegistry['ldap/maxopenfiles']
-@!@		start-stop-daemon --start --quiet --pidfile "$pidfile" \
+@!@		start-stop-daemon --start --quiet \
 			--exec $DAEMON -- -h "${uris}"
 	rvalue=$?
 	log_action_end_msg $rvalue
@@ -200,20 +220,40 @@ if baseConfig['ldap/server/type']=="master":
 	;;
   stop)
 	log_action_begin_msg "Stopping ldap server(s): slapd "
+	## first try with pidfile
 	start-stop-daemon --stop --quiet --oknodo --retry 10 \
-		--pidfile "$pidfile" \
-		--exec /usr/sbin/slapd 2>&1
+		--pidfile "$pidfile" -v | grep -E '(retry|refused)'
+	## check process (instead of [ $? -eq 2 ])
+	pid=$(pgrep -x slapd)
+	if [ -n "$pid" ]; then
+		## try via executable name
+		log_action_msg "WARNING: Slapd still running ($pid), terminating via executable name"
+		start-stop-daemon --stop --quiet --oknodo --retry 10 \
+			--exec $DAEMON -v | grep -E '(retry|refused)'
+		## check again
+		pid=$(pgrep -x slapd)
+		if [ -n "$pid" ]; then
+			## start-stop-daemon -retry should have send a KILL, this is just a safety belt.
+			log_action_msg "WARNING: Slapd still running ($pid), sending KILL"
+			killall -9 slapd > /dev/null 2>&1
+		fi
+	fi
 	log_action_end_msg 0
 	;;
   restart|force-reload)
 	log_action_msg "Restarting ldap server(s)"
 	$0 stop
-	sleep 2 # give it some time to die
 	$0 start
 	;;
   force-stop)
 	log_action_begin_msg "Stopping ldap servers (forced) "
 	killall slapd > /dev/null 2>&1
+	## check
+	pid=$(pgrep -x slapd)
+	if [ -n "$pid" ]; then
+		log_action_msg "WARNING: Slapd still running ($pid), sending KILL"
+		killall -9 slapd > /dev/null 2>&1
+	fi
 	log_action_end_msg 0
 	;;
   crestart)
@@ -226,15 +266,30 @@ if baseConfig['ldap/server/type']=="master":
 	;;
   graceful-stop)
 	log_action_begin_msg "Sending HUP to ldap server(s): slapd "
-	start-stop-daemon --stop --quiet -s HUP --retry 120 \
-		--pidfile "$pidfile" \
-		--exec /usr/sbin/slapd 2>&1
+	signal_plan="HUP/120/TERM/30/KILL/2"
+	## first try with pidfile
+	start-stop-daemon --stop --quiet --oknodo --retry="$signal_plan" \
+		--pidfile "$pidfile" -v | grep -E '(retry|refused)'
+	## check process (instead of [ $? -eq 2 ])
+	pid=$(pgrep -x slapd)
+	if [ -n "$pid" ]; then
+		## try via executable name
+		log_action_msg "WARNING: Slapd still running ($pid), sending HUP via executable name"
+		start-stop-daemon --stop --quiet --oknodo --retry="$signal_plan" \
+			--exec $DAEMON -v | grep -E '(retry|refused)'
+		## check again
+		pid=$(pgrep -x slapd)
+		if [ -n "$pid" ]; then
+			## start-stop-daemon -retry should have send a KILL, this is just a safety belt.
+			log_action_msg "WARNING: Slapd still running ($pid), sending KILL"
+			killall -9 slapd > /dev/null 2>&1
+		fi
+	fi
 	log_action_end_msg 0
 	;;
   graceful-restart)
 	log_action_msg "Initiating graceful reload of ldap server(s)"
 	$0 graceful-stop
-	sleep 2 # give it some time to die
 	$0 start
 	;;
   *)
