* space/tab mix cleanup (Bug #23962)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.0/ucs@33154 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/management/univention-ldap/conffiles/etc/init.d/slapd b/management/univention-ldap/conffiles/etc/init.d/slapd
--- a/management/univention-ldap/conffiles/etc/init.d/slapd
+++ b/management/univention-ldap/conffiles/etc/init.d/slapd
@@ -1,11 +1,11 @@
 #!/bin/sh
 @%@UCRWARNING=# @%@
 ### BEGIN INIT INFO
-# Provides:          slapd
-# Required-Start:    $remote_fs $network $syslog
-# Required-Stop:     $remote_fs $network $syslog
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
+# Provides:			 slapd
+# Required-Start:	 $remote_fs $network $syslog
+# Required-Stop:	 $remote_fs $network $syslog
+# Default-Start:	 2 3 4 5
+# Default-Stop:		 0 1 6
 # Short-Description: OpenLDAP standalone server (Lightweight Directory Access Protocol)
 ### END INIT INFO
 #
@@ -34,7 +34,7 @@ bdbrecover ()
 		if [ $? = 0 ]; then
 			if echo "$dbstat_output" | grep -q 'Environment version'; then
 				stale_locks=$("${DBSTAT}" -Nc | sed -rn 's/([0-9]*)\t*Number of current locks/\1/p')
-				if [ "$stale_locks"  != 0 ]; then
+				if [ "$stale_locks" != 0 ]; then
 					log_action_msg "WARNING"
 					log_action_msg "WARNING: There are stale locks in LDAP backend Berkeley DB."
 					log_action_msg "WARNING: If slapd does not respond, manual LDAP dump/restore may be necessary."
@@ -58,59 +58,59 @@ bdbrecover ()
 
 check_subschema ()
 {
-    sleep 5
-    tmpfile=`mktemp`
-    res=1
+	sleep 5
+	tmpfile=`mktemp`
+	res=1
 	count=0
-    while [ $res != 0 ] ; do
-        ldapsearch -x -H ldapi:/// -s base -b cn=Subschema 'objectClass=subschema' objectClasses attributeTypes matchingRules matchingRuleUse dITStructureRules dITContentRules nameForms ldapSyntaxes >$tmpfile
+	while [ $res != 0 ] ; do
+		ldapsearch -x -H ldapi:/// -s base -b cn=Subschema 'objectClass=subschema' objectClasses attributeTypes matchingRules matchingRuleUse dITStructureRules dITContentRules nameForms ldapSyntaxes >$tmpfile
 		res=$?
-        if [ $res != 0 ]; then
+		if [ $res != 0 ]; then
 			count=$((count+1))
 			if [ $count = 2 ]; then
 				echo "Failed to search schema"
 				exit 1
 			fi
-            sleep 2
-        fi
-    done
+			sleep 2
+		fi
+	done
 
-    @!@
-if baseConfig.has_key('ldap/schema/export') and  baseConfig['ldap/schema/export'].lower() in ['yes', 'true']:
-        print 'cp $tmpfile /var/www/ldap-schema.txt'
-        print 'chmod a+r /var/www/ldap-schema.txt'
-    @!@
+	@!@
+if baseConfig.has_key('ldap/schema/export') and baseConfig['ldap/schema/export'].lower() in ['yes', 'true']:
+		print '\tcp $tmpfile /var/www/ldap-schema.txt'
+		print '\tchmod a+r /var/www/ldap-schema.txt'
+	@!@
 
-    md5=`md5sum $tmpfile | awk '{print $1}'`
-    if [ ! -d /var/lib/univention-ldap/schema ]; then
-        mkdir /var/lib/univention-ldap/schema
-    fi
-    if [ ! -e /var/lib/univention-ldap/schema/md5 ]; then
-        touch /var/lib/univention-ldap/schema/md5
-    fi
-    md5_old=`cat /var/lib/univention-ldap/schema/md5`
-    if [ "$md5" != "$md5_old" ]; then
-        if [ ! -d /var/lib/univention-ldap/schema/id ]; then
-           mkdir /var/lib/univention-ldap/schema/id
-        fi
-        if [ ! -e /var/lib/univention-ldap/schema/id/id ]; then
-           touch /var/lib/univention-ldap/schema/id/id
-        fi
-        id=`cat /var/lib/univention-ldap/schema/id/id`
-        if [ -z "$id" ]; then
-          id=0
-        fi
-        id=$((id+1))
-        echo "$md5" >/var/lib/univention-ldap/schema/md5
-        echo "$id" >/var/lib/univention-ldap/schema/id/id
-        chown listener /var/lib/univention-ldap/schema/id/id
-     else
-        id=`cat /var/lib/univention-ldap/schema/id/id`
-        if [ -z "$id" ]; then
-          echo "1" >/var/lib/univention-ldap/schema/id/id
-          chown listener /var/lib/univention-ldap/schema/id/id
-        fi
-    fi
+	md5=`md5sum $tmpfile | awk '{print $1}'`
+	if [ ! -d /var/lib/univention-ldap/schema ]; then
+		mkdir /var/lib/univention-ldap/schema
+	fi
+	if [ ! -e /var/lib/univention-ldap/schema/md5 ]; then
+		touch /var/lib/univention-ldap/schema/md5
+	fi
+	md5_old=`cat /var/lib/univention-ldap/schema/md5`
+	if [ "$md5" != "$md5_old" ]; then
+		if [ ! -d /var/lib/univention-ldap/schema/id ]; then
+			mkdir /var/lib/univention-ldap/schema/id
+		fi
+		if [ ! -e /var/lib/univention-ldap/schema/id/id ]; then
+			touch /var/lib/univention-ldap/schema/id/id
+		fi
+		id=`cat /var/lib/univention-ldap/schema/id/id`
+		if [ -z "$id" ]; then
+			id=0
+		fi
+		id=$((id+1))
+		echo "$md5" >/var/lib/univention-ldap/schema/md5
+		echo "$id" >/var/lib/univention-ldap/schema/id/id
+		chown listener /var/lib/univention-ldap/schema/id/id
+	else
+		id=`cat /var/lib/univention-ldap/schema/id/id`
+		if [ -z "$id" ]; then
+			echo "1" >/var/lib/univention-ldap/schema/id/id
+			chown listener /var/lib/univention-ldap/schema/id/id
+		fi
+	fi
 }
 
 check_replog_file ()
@@ -124,12 +124,12 @@ test -f /var/lib/univention-ldap/replog/replog.lock || \
 
 
 if [ -f "$SLAPDCONF" ]; then
-    pidfile=`grep ^pidfile $SLAPDCONF | awk '{print $2}'`
-    if [ -z "$pidfile" ]; then
-	pidfile="/var/run/slapd/slapd.pid"
-    fi
+	pidfile=`grep ^pidfile $SLAPDCONF | awk '{print $2}'`
+	if [ -z "$pidfile" ]; then
+		pidfile="/var/run/slapd/slapd.pid"
+	fi
 else
-    exit 0
+	exit 0
 fi
 
 test -f $DAEMON || exit 0
@@ -138,23 +138,23 @@ case "$1" in
   start)
 	# check ucr autostart setting
 	if [ -f "/usr/share/univention-config-registry/init-autostart.lib" ]; then
-	    . "/usr/share/univention-config-registry/init-autostart.lib"
-	    check_autostart ldap ldap/autostart
+		. "/usr/share/univention-config-registry/init-autostart.lib"
+		check_autostart ldap ldap/autostart
 	fi
 	# check that no slapd is running
 	if ! start-stop-daemon --start --quiet --pidfile "$pidfile" --exec $DAEMON	--test > /dev/null; then
 		log_action_msg "LDAP server already running."
 		exit 2
- 	fi
-   @!@
+	fi
+@!@
 if baseConfig['ldap/database/type'] == 'bdb':
 	print '\t# check backend database'
 	print '\tbdbrecover'
 if configRegistry.get('ldap/replog', '').lower() in ('true', 'yes'):
-	print 'check_replog_file'
-   @!@
+	print '\tcheck_replog_file'
+@!@
 
-    log_action_begin_msg "Starting ldap server(s): slapd "
+	log_action_begin_msg "Starting ldap server(s): slapd "
 	(
 @!@
 uris=['ldapi:///']
@@ -172,17 +172,15 @@ if configRegistry.get('ldap/maxopenfiles'):
 
 	test -e /var/run/slapd/ldapi && ln -sf /var/run/slapd/ldapi /var/run/ldapi
 
-   @!@
-if baseConfig['ldap/server/type']=="master":	   
-    print '\tlog_action_begin_msg "Checking Schema: "'
-    print '\tcheck_subschema >/dev/null 2>&1'
-    print '\tlog_action_end_msg 0'
-   @!@
-
-    echo "."
+@!@
+if baseConfig['ldap/server/type']=="master":
+	print '\tlog_action_begin_msg "Checking Schema: "'
+	print '\tcheck_subschema >/dev/null 2>&1'
+	print '\tlog_action_end_msg 0'
+@!@
 
 	if [ -e /var/lib/univention-directory-replication/failed.ldif ]; then
-    	log_action_begin_msg "Found failed.ldif. Importing "
+		log_action_begin_msg "Found failed.ldif. Importing "
 		test -x /usr/sbin/univention-directory-replication-resync && /usr/sbin/univention-directory-replication-resync /var/lib/univention-directory-replication/failed.ldif >>/var/log/univention/listener.log 2>&1
 		if [ $? = 0 ]; then
 			log_action_end_msg 0
@@ -193,25 +191,25 @@ if baseConfig['ldap/server/type']=="master":
 		fi
 	fi
 	
-    ;;
+	;;
   stop)
-    log_action_begin_msg "Stopping ldap server(s): slapd "
+	log_action_begin_msg "Stopping ldap server(s): slapd "
 	start-stop-daemon --stop --quiet --oknodo --retry 10 \
-	    --pidfile "$pidfile" \
-	    --exec /usr/sbin/slapd 2>&1
-    log_action_end_msg 0
-    ;;
+		--pidfile "$pidfile" \
+		--exec /usr/sbin/slapd 2>&1
+	log_action_end_msg 0
+	;;
   restart|force-reload)
-    log_action_msg "Restarting ldap server(s)"
-    $0 stop
-    sleep 2 # give it some time to die
-    $0 start
-    ;;
+	log_action_msg "Restarting ldap server(s)"
+	$0 stop
+	sleep 2 # give it some time to die
+	$0 start
+	;;
   force-stop)
-    log_action_msg "Stopping ldap servers (forced) "
-    killall slapd > /dev/null 2>&1
-    log_action_end_msg 0
-    ;;
+	log_action_begin_msg "Stopping ldap servers (forced) "
+	killall slapd > /dev/null 2>&1
+	log_action_end_msg 0
+	;;
   crestart)
 	if pidof slapd > /dev/null 2>&1
 		then
@@ -221,9 +219,9 @@ if baseConfig['ldap/server/type']=="master":
 	fi
 	;;
   *)
-    echo "Usage: $0 {start|stop|restart|force-stop|crestart}"
-    exit 1
-    ;;
+	echo "Usage: $0 {start|stop|restart|force-stop|crestart}"
+	exit 1
+	;;
 esac
 
 exit 0
