Bug #50616: The init script now looks for an already running process only below parent pid 1 specifically. This allows another process "slapd" to be run in a container

diff --git a/management/univention-ldap/conffiles/etc/init.d/slapd b/management/univention-ldap/conffiles/etc/init.d/slapd
--- a/management/univention-ldap/conffiles/etc/init.d/slapd
+++ b/management/univention-ldap/conffiles/etc/init.d/slapd
@@ -23,6 +23,11 @@ SLAPDCONF=/etc/ldap/slapd.conf
 
 . /lib/lsb/init-functions
 
+getpid ()
+{
+	pgrep -f "$DAEMON" -P 1
+}
+
 exit_if_start_is_running ()
 {
 	local pid
@@ -184,7 +189,7 @@ case "$1" in
 		check_autostart ldap ldap/autostart
 	fi
 	# check that no slapd is running
-	if ! start-stop-daemon --start --quiet --exec $DAEMON --test > /dev/null; then
+	if ! start-stop-daemon --start --ppid 1 --quiet --exec $DAEMON --test > /dev/null; then
 		log_action_msg "LDAP server already running"
 		exit 0
 	fi
@@ -208,7 +213,7 @@ for p in configRegistry.get('slapd/port/ldaps', '7636').split(','):
 print '\turis="%s"' % ' '.join(uris)
 if configRegistry.get('ldap/maxopenfiles'):
 	print '\t\tulimit -n %s' % configRegistry['ldap/maxopenfiles']
-@!@		start-stop-daemon --start --quiet \
+@!@		start-stop-daemon --start --ppid 1 --quiet \
 			--exec $DAEMON -- -h "${uris}"
 	rvalue=$?
 	fail_msg=""
@@ -217,7 +222,7 @@ if configRegistry.get('ldap/maxopenfiles'):
 		for i in $(seq 1 3); do
 			[ $rvalue -eq 0 ] && break
 			sleep 1
-			start-stop-daemon --start --quiet --exec $DAEMON -- -h "${uris}"
+			start-stop-daemon --start --ppid 1 --quiet --exec $DAEMON -- -h "${uris}"
 			rvalue=$?
 		done
 		[ $rvalue -ne 0 ] && fail_msg="slapd start failed, check if ldap/database/mdb/maxsize is supported on this architecture"
@@ -255,16 +260,16 @@ if configRegistry['ldap/server/type']=="master":
 	logger "/etc/init.d/slapd $1 (pid: $$, ppid:$(ps -p $PPID -o pid= -o comm=))"
 	log_action_begin_msg "Stopping ldap server(s): slapd "
 	## first try with pidfile
-	start-stop-daemon --stop --quiet --oknodo --retry 10 \
+	start-stop-daemon --stop --ppid 1 --quiet --oknodo --retry 10 \
 		--pidfile "$pidfile" -v | sed -rn 's/.*, (retry #|refused to die)/\1/p' \
 		| while read line; do log_action_cont_msg "$line"; done
 	## check process (instead of [ $? -eq 2 ])
-	pid=$(pgrep -f "^$DAEMON")
+	pid=$(getpid)
 	if [ -n "$pid" ]; then
 		log_action_end_msg 1
 		## try via executable name
 		log_action_begin_msg "Slapd still running ($pid), terminating via executable name"
-		start-stop-daemon --stop --quiet --oknodo --retry 10 \
+		start-stop-daemon --stop --ppid 1 --quiet --oknodo --retry 10 \
 			--exec $DAEMON -v | sed -rn 's/.*, (retry #|refused to die)/\1/p' \
 			| while read line; do log_action_cont_msg "$line"; done
 		rm -f "$pidfile"
@@ -280,7 +285,7 @@ if configRegistry['ldap/server/type']=="master":
   force-stop)
 	logger "/etc/init.d/slapd $1 (pid: $$, ppid:$(ps -p $PPID -o pid= -o comm=))"
 	log_action_begin_msg "Stopping ldap servers (forced) "
-	start-stop-daemon --stop --quiet --oknodo --retry forever/KILL \
+	start-stop-daemon --stop --ppid 1 --quiet --oknodo --retry forever/KILL \
 		--exec $DAEMON
 	rm -f "$pidfile"
 	log_action_end_msg 0
@@ -300,16 +305,16 @@ if configRegistry['ldap/server/type']=="master":
 	# log_action_begin_msg "Sending HUP to ldap server(s): slapd "
 	# signal_plan="HUP/10/TERM/5/KILL/1"
 	# ## first try with pidfile
-	# start-stop-daemon --stop --quiet --oknodo --retry "$signal_plan" \
+	# start-stop-daemon --stop --ppid 1 --quiet --oknodo --retry "$signal_plan" \
 	# 	--pidfile "$pidfile" -v | sed -rn 's/.*, (retry #|refused to die)/\1/p' \
 	# 	| while read line; do log_action_cont_msg "$line"; done
 	# ## check process (instead of [ $? -eq 2 ])
-	# pid=$(pgrep -f "^$DAEMON")
+	# pid=$(getpid)
 	# if [ -n "$pid" ]; then
 	# 	log_action_end_msg 1
 	# 	## try via executable name
 	# 	log_action_begin_msg "Slapd still running ($pid), sending HUP via executable name"
-	# 	start-stop-daemon --stop --quiet --oknodo --retry "$signal_plan" \
+	# 	start-stop-daemon --stop --ppid 1 --quiet --oknodo --retry "$signal_plan" \
 	# 		--exec $DAEMON -v | sed -rn 's/.*, (retry #|refused to die)/\1/p' \
 	# 		| while read line; do log_action_cont_msg "$line"; done
 	# 	rm -f "$pidfile"
