test[docker]: Do not pull from hub.docker.com
hub.docker.com is rate-limited to 100 requests / 6 hour for
unauthenticated users since 2020-11-20:
<https://www.docker.com/increase-rate-limits#:~:text=The%20rate%20limits%20of%20100,the%20six%20hour%20window%20elapses.>

tests/80_docker/11_registry_access pulls an image, which is executed
- 2* for UCS 4.4-8 and UCS-5.0-0
- 2* for AutotestJoin and AutotestUpgrade
- 4* for Master, Backup, Slave, Member-Server
- 2* with and without Samba 4
- 2* for yet unknown reason

Each start of the day (~06:00) we're already at 64 requests used, which
only slowly refills until noon; last Sunday we went over 100 and further
requests were blocked, leading to pipeline failures

Do not use an image from hub.docker.com, but an empty dummy image for
testing.
Refactor test for readability.

Bug #52344

diff --git a/test/ucs-test/tests/80_docker/11_registry_access b/test/ucs-test/tests/80_docker/11_registry_access
--- a/test/ucs-test/tests/80_docker/11_registry_access
+++ b/test/ucs-test/tests/80_docker/11_registry_access
@@ -1,70 +1,64 @@
 #!/usr/share/ucs-test/runner bash
+# shellcheck shell=bash
 ## desc: Check registry access - Anonymous pull shall succeed, push not
 ## tags: [docker]
 ## exposure: dangerous
 ## packages:
 ##   - docker.io
 
-base_image="alpine:3.10"
+set -u
 
-rm ~/.docker/config.json
+# shellcheck source=/dev/null
+. "$TESTLIBPATH/base.sh" || exit 137
 
-hub="docker.software-univention.de"
-image="$hub/$base_image"
-echo "=============="
-echo "TESTING $image"
-docker pull "$image" || exit 1
-docker push "$image" && exit 2
-docker rmi "$image"
-docker login -u ucs -p readonly "$hub" || exit 3
-docker pull "$image" || exit 4
-docker push "$image" && exit 5
-docker rmi "$image"
+IMG="alpine:3.10"
 
-rm ~/.docker/config.json
+main () {
+	local test upload
+	for upload in "" "-upload"
+	do
+		for test in "" "-test"
+		do
+			test_hub "docker${test}${upload}.software-univention.de"
+		done
+	done
+}
+test_hub () {
+	local hub="$1" image="$1/$IMG"
+	section "$image"
+	test_anonymous
+	test_authenticated
+}
+test_anonymous () {
+	log_and_execute docker logout "$hub"
+	test_pull_push
+}
+test_authenticated () {
+	if [ -n "$upload" ]
+	then
+		log_and_execute docker login -u ucs -p readonly "$hub" && { fail_test "Login failed"; return 1; }
+	else
+		log_and_execute docker login -u ucs -p readonly "$hub" || { fail_test "Login failed"; return 1; }
+	fi
+	test_pull_push
+}
+test_pull_push () {
+	test_pull
+	test_push
+}
+test_pull () {
+	if [ -n "$upload" ]
+	then
+		log_and_execute docker pull "$image" && fail_test "Pull should not succeed for '$image'"
+	else
+		log_and_execute docker pull "$image" || fail_test "Pull should succeed"
+	fi
+	docker rmi "$image"
+}
+test_push () {
+	docker import - "$image" </dev/null
+	log_and_execute docker push "$image" && fail_test "Push should never succeed"
+	docker rmi "$image"
+}
 
-hub="docker-test.software-univention.de"
-image="$hub/$base_image"
-echo "=============="
-echo "TESTING $image"
-docker pull "$image" || exit 6
-docker push "$image" && exit 7
-docker rmi "$image"
-docker login -u ucs -p readonly "$hub" || exit 8
-docker pull "$image" || exit 9
-docker push "$image" && exit 10
-docker rmi "$image"
-
-
-
-
-docker pull "$base_image"
-
-rm ~/.docker/config.json
-
-hub="docker-upload.software-univention.de"
-image="$hub/$base_image"
-echo "=============="
-echo "TESTING $image"
-docker pull "$image" && exit 11
-docker tag "$base_image" "$image"
-docker push "$image" && exit 12
-docker rmi "$image"
-docker login -u ucs -p readonly "$hub" && exit 13
-
-rm ~/.docker/config.json
-
-hub="docker-test-upload.software-univention.de"
-image="$hub/$base_image"
-echo "=============="
-echo "TESTING $image"
-docker pull "$image" && exit 14
-docker tag "$base_image" "$image"
-docker push "$image" && exit 15
-docker rmi "$image"
-docker login -u ucs -p readonly "$hub" && exit 16
-
-
-docker rmi "$base_image"
-
-exit 0
+main
