Bug #43385: test stderr/return value in 40_app_umc_install_latest_appbox
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.1/ucs-4.1-4@76593 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/80_docker/40_app_umc_install_latest_appbox b/test/ucs-test/tests/80_docker/40_app_umc_install_latest_appbox
--- a/test/ucs-test/tests/80_docker/40_app_umc_install_latest_appbox
+++ b/test/ucs-test/tests/80_docker/40_app_umc_install_latest_appbox
@@ -18,14 +18,56 @@ if __name__ == '__main__':
 	password = 'readonly'
 	resp = requests.get(url, auth=(username, password)).content
 	data = json.loads(resp)
-	latest_tag = max(data['tags'])
+	image = 'docker.software-univention.de/ucs-appbox-amd64:' + max(data['tags'])
 
+	# installation should fail if setup fails
+	with Appcenter() as appcenter:
+		app_name = get_app_name()
+		app = App(name=app_name, version='1.9', build_package=False)
+		app.set_ini_parameter( DockerImage=image, DockerScriptSetup='/usr/sbin/setup')
+		app.add_script(setup='''#!/bin/bash
+echo "This message goes to stdout"
+echo "This message goes to stderr" >&2
+exit 1
+'''		)
+		app.add_to_local_appcenter()
+		try:
+			appcenter.update()
+			app.install_via_umc()
+		except UCTTest_DockerApp_UMCInstallFailed:
+			pass
+		else:
+			raise UCSTest_Docker_Exception, 'test should have failed with UCTTest_DockerApp_UMCInstallFailed'
+		finally:
+			app.uninstall()
+			app.remove()
+
+	# installation should succeed if setup is fine
+	with Appcenter() as appcenter:
+		app_name = get_app_name()
+		app = App(name=app_name, version='1.9', build_package=False)
+		app.set_ini_parameter(DockerImage=image, DockerScriptSetup='/usr/sbin/setup')
+		app.add_script(setup='''#!/bin/bash
+echo "This message goes to stdout"
+echo "This message goes to stderr" >&2
+exit 0
+'''
+		)
+		app.add_to_local_appcenter()
+		try:
+			appcenter.update()
+			app.install_via_umc()
+		finally:
+			app.uninstall()
+			app.remove()
+
+	# test appbox app installation
 	with Appcenter() as appcenter:
 		app_name = get_app_name()
 		app_name = 'testapp'
 		app = App(name=app_name, version='1.9', build_package=False)
 		app.set_ini_parameter(
-			DockerImage='docker.software-univention.de/ucs-appbox-amd64:%s' % latest_tag,
+			DockerImage=image,
 			DefaultPackages='mc',
 		)
 		app.add_to_local_appcenter()
