Bug #50492: Adjust testcase for password sync

diff --git a/test/ucs-test/tests/55_adconnector/050sync_password_sync b/test/ucs-test/tests/55_adconnector/050sync_password_sync
--- a/test/ucs-test/tests/55_adconnector/050sync_password_sync
+++ b/test/ucs-test/tests/55_adconnector/050sync_password_sync
@@ -19,8 +19,6 @@ if is_ucr_true 'connector/ad/mapping/user/password/disabled'; then
 	echo "Password sync is disabled, skipping password sync check"
 	exit 131
 fi
-kerberos_mapping="$(ucr get connector/ad/mapping/user/password/kerberos/enabled)"
-ucr set 'connector/ad/mapping/user/password/kerberos/enabled=yes'
 SYNCMODE="$(ad_get_sync_mode)"
 ad_set_sync_mode "sync"
 invoke-rc.d univention-ad-connector restart
@@ -33,6 +31,7 @@ password3="W$(random_chars)987"
 password4="X$(random_chars)345"
 password5="Y$(random_chars)347"
 password6="Z$(random_chars)555"
+password7="A$(random_chars)782"
 
 old_minPwdAge="$(univention-adsearch objectClass=domain minPwdAge | sed -ne 's|^minPwdAge: ||p')"
 
@@ -163,18 +162,12 @@ test_auth_ad "$username" "$password4" || fail_test 110
 test_auth_ucs "$username" "$password2" && fail_test 110
 test_auth_ucs "$username" "$password3" && fail_test 110
 test_auth_ucs "$username" "$password4" || fail_test 110
-test_auth_ucs_kinit "$username" "$password2" && fail_test 110
-test_auth_ucs_kinit "$username" "$password3" && fail_test 110
-test_auth_ucs_kinit "$username" "$password4" || fail_test 110
 
 reset_password_in_ad "$username" "$password4" "$password5"
 
 test_auth_ucs "$username" "$password3" && fail_test 110
 test_auth_ucs "$username" "$password4" && fail_test 110
 test_auth_ucs "$username" "$password5" || fail_test 110
-test_auth_ucs_kinit "$username" "$password3" && fail_test 110
-test_auth_ucs_kinit "$username" "$password4" && fail_test 110
-test_auth_ucs_kinit "$username" "$password5" || fail_test 110
 
 test_auth_ad "$username" "$password3" && fail_test 110
 # It doesn't seem to be deterministic if the OLD password is valid or not. We are using
@@ -187,14 +180,31 @@ change_password_in_ucs "$username" "$password6"
 test_auth_ucs "$username" "$password4" && fail_test 110
 test_auth_ucs "$username" "$password5" && fail_test 110
 test_auth_ucs "$username" "$password6" || fail_test 110
-test_auth_ucs_kinit "$username" "$password4" && fail_test 110
-test_auth_ucs_kinit "$username" "$password5" && fail_test 110
-test_auth_ucs_kinit "$username" "$password6" || fail_test 110
 
 test_auth_ad "$username" "$password4" && fail_test 110
 test_auth_ad "$username" "$password5" || fail_test 110
 test_auth_ad "$username" "$password6" || fail_test 110
 
+# test sync of kerberos hashes
+
+kerberos_mapping="$(ucr get connector/ad/mapping/user/password/kerberos/enabled)"
+ucr set 'connector/ad/mapping/user/password/kerberos/enabled=yes'
+invoke-rc.d univention-ad-connector restart
+
+reset_password_in_ad "$username" "$password6" "$password7"
+
+test_auth_ucs "$username" "$password5" && fail_test 110
+test_auth_ucs "$username" "$password6" && fail_test 110
+test_auth_ucs "$username" "$password7" || fail_test 110
+test_auth_ucs_kinit "$username" "$password5" && fail_test 110
+test_auth_ucs_kinit "$username" "$password6" && fail_test 110
+test_auth_ucs_kinit "$username" "$password7" || fail_test 110
+
+test_auth_ad "$username" "$password5" && fail_test 110
+# It doesn't seem to be deterministic if the OLD password is valid or not. We are using
+# a password reset, so the password should be valid. But sometimes it is.
+#test_auth_ad "$username" "$password4" && fail_test 110
+test_auth_ad "$username" "$password7" || fail_test 110
 udm-test users/user remove --dn "uid=$username,cn=users,$ldap_base" || fail_test 110
 ad_wait_for_synchronization; fail_bool 0 110
 
@@ -211,5 +221,7 @@ if $kerberos_mapping; then
 else 
 	ucr unset connector/ad/mapping/user/password/kerberos/enabled
 fi
+invoke-rc.d univention-ad-connector restart
+
 exit "$RETVAL"
 
