refactor(ucs-test): shellcheck
Simplify concatenating multiple variables.

for((...)) loops.

Cleanup argument parsing.

White space changes.

Issue univention/ucs#1854

diff --git a/test/ucs-test/tests/55_adconnector/050sync_password_sync b/test/ucs-test/tests/55_adconnector/050sync_password_sync
--- a/test/ucs-test/tests/55_adconnector/050sync_password_sync
+++ b/test/ucs-test/tests/55_adconnector/050sync_password_sync
@@ -68,12 +68,12 @@ test_auth_ucs () {
 test_auth_ucs_kinit () {
 	local u="$1" p="$2" RET1=1 RET2
 	echo "## "
-	echo "## Test UCS kerberos auth for $username with password $p "
+	echo "## Test UCS kerberos auth for $username with password $p"
 	echo "## "
 	## test kerberos hashes
 	for type in $etypes;do
 		echo "$p" | kinit --password-file=STDIN -e "$type" "$u"
-		RET1=$?
+		RET1=$?  # FIXME: only the exit code for the LAST $ertype ???
 		kdestroy
 	done
 
