* The user import test cases for the connector have been adjusted. The   test case 08sync_create_and_modify_ad_to_ucs has been removed   because the code now checks only the password change in the way UCS   to AD/S4. For the main problem see Bug #18501 (Bug #30317)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@39428 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/55_adconnector/09sync_create_and_modify_ucs_to_ad b/test/ucs-test/tests/55_adconnector/09sync_create_and_modify_ucs_to_ad
--- a/test/ucs-test/tests/55_adconnector/09sync_create_and_modify_ucs_to_ad
+++ b/test/ucs-test/tests/55_adconnector/09sync_create_and_modify_ucs_to_ad
@@ -1,5 +1,5 @@
 #!/usr/share/ucs-test/runner bash 
-## desc: "Create and modify 10 users from UCS to AD in sync-mode"
+## desc: "Simulate an UCS import including pasword change from UCS to AD in sync-mode"
 ## exposure: dangerous
 ## packages:
 ## - univention-ad-connector
@@ -11,64 +11,57 @@
 . "adconnector.sh" || exit 137
 test -n "$connector_ad_ldap_host" || exit 137
 
-UDM_users_user_lastname="$(random_chars)"
-UDM_users_user_password="U$(random_chars)123"
-
-B00="$(random_chars)"
-B01="$(random_chars)"
-B02="$(random_chars)"
-B03="$(random_chars)"
-B04="$(random_chars)"
-B05="$(random_chars)"
-B06="$(random_chars)"
-B07="$(random_chars)"
-B08="$(random_chars)"
-B09="$(random_chars)"
-
-UDM_B00_DN="uid=$B00,cn=users,$ldap_base"
-UDM_B01_DN="uid=$B01,cn=users,$ldap_base"
-UDM_B02_DN="uid=$B02,cn=users,$ldap_base"
-UDM_B03_DN="uid=$B03,cn=users,$ldap_base"
-UDM_B04_DN="uid=$B04,cn=users,$ldap_base"
-UDM_B05_DN="uid=$B05,cn=users,$ldap_base"
-UDM_B06_DN="uid=$B06,cn=users,$ldap_base"
-UDM_B07_DN="uid=$B07,cn=users,$ldap_base"
-UDM_B08_DN="uid=$B08,cn=users,$ldap_base"
-UDM_B09_DN="uid=$B09,cn=users,$ldap_base"
-
 SYNCMODE="$(ad_get_sync_mode)"
 ad_set_sync_mode "sync"
 invoke-rc.d univention-ad-connector restart
 
-for b in "$B00" "$B01" "$B02" "$B03" "$B04" "$B05" "$B06" "$B07" "$B08" "$B09"; do
-	UDM_users_user_username="$b"
-	# udm_create "users/user" || fail_test 110
-	udm_create "users/user" "" "" "" "" || fail_test 110
-	sleep 1
-	udm users/user modify --dn "uid=$b,cn=users,$ldap_base" --set password=q1w2e3r4 || fail_test 110
-done
+# Make some import rounds with an increasing sleep time before changing the password
+for i in 0 3 6 12; do
+	UDM_users_user_lastname="$(random_chars)"
+	UDM_users_user_password="U$(random_chars)123"
 
-ad_wait_for_synchronization; fail_bool 0 110
+	B00="$(random_chars)"
+	B01="$(random_chars)"
+	B02="$(random_chars)"
+	B03="$(random_chars)"
+	B04="$(random_chars)"
 
-for b in "$B00" "$B01" "$B02" "$B03" "$B04" "$B05" "$B06" "$B07" "$B08" "$B09"; do
-	echo "Search in UCS LDAP as user $b with the new password"
-	univention-ldapsearch -x -D "uid=$b,cn=users,$ldap_base" -w q1w2e3r4 -LLL -s base dn || fail_test 110
-	echo "Search in AD as user $b with the new password"
-	univention-adsearch -x -D "cn=$b,cn=user,$(ad_get_base)" -w %q1w2e3r4 -s base dn || fail_test 110
-done
+	UDM_B00_DN="uid=$B00,cn=users,$ldap_base"
+	UDM_B01_DN="uid=$B01,cn=users,$ldap_base"
+	UDM_B02_DN="uid=$B02,cn=users,$ldap_base"
+	UDM_B03_DN="uid=$B03,cn=users,$ldap_base"
+	UDM_B04_DN="uid=$B04,cn=users,$ldap_base"
 
-section "Clean up"
+	for b in "$B00" "$B01" "$B02" "$B03" "$B04"; do
+		UDM_users_user_username="$b"
+		# udm_create "users/user" || fail_test 110
+		udm_create "users/user" "" "" "" "" || fail_test 110
+		sleep $i
+		udm users/user modify --dn "uid=$b,cn=users,$ldap_base" --set password=q1w2e3r4 || fail_test 110
+	done
 
-for b in "$B00" "$B01" "$B02" "$B03" "$B04" "$B05" "$B06" "$B07" "$B08" "$B09"; do
-	UDM_users_user_username="$b"
-	udm_remove "users/user" || fail_test 110
-done
+	ad_wait_for_synchronization; fail_bool 0 110
 
-ad_wait_for_synchronization; fail_bool 0 110
+	for b in "$B00" "$B01" "$B02" "$B03" "$B04"; do
+		echo "Search in UCS LDAP as user $b with the new password"
+		univention-ldapsearch -x -D "uid=$b,cn=users,$ldap_base" -w q1w2e3r4 -LLL -s base dn || fail_test 110
+		echo "Search in AD as user $b with the new password"
+		univention-adsearch -x -D "cn=$b,cn=user,$(ad_get_base)" -w %q1w2e3r4 -s base dn || fail_test 110
+	done
 
-for b in "$B00" "$B01" "$B02" "$B03" "$B04" "$B05" "$B06" "$B07" "$B08" "$B09"; do
-	UDM_users_user_username="$b"
-	udm_exists "users/user"; fail_bool 1 110
+	section "Clean up"
+
+	for b in "$B00" "$B01" "$B02" "$B03" "$B04"; do
+		UDM_users_user_username="$b"
+		udm_remove "users/user" || fail_test 110
+	done
+
+	ad_wait_for_synchronization; fail_bool 0 110
+
+	for b in "$B00" "$B01" "$B02" "$B03" "$B04"; do
+		UDM_users_user_username="$b"
+		udm_exists "users/user"; fail_bool 1 110
+	done
 done
 
 ad_set_sync_mode "$SYNCMODE"
