refactor(test): Shell style
quoting

Issue univention/ucs#1854

diff --git a/test/ucs-test/tests/53_samba-common/49share_local_conf b/test/ucs-test/tests/53_samba-common/49share_local_conf
--- a/test/ucs-test/tests/53_samba-common/49share_local_conf
+++ b/test/ucs-test/tests/53_samba-common/49share_local_conf
@@ -32,7 +32,7 @@ eval "$(ucr shell)"
 
 user1=$(user_randomname)
 user_create "$user1"
-user1_uidnumber=$(univention-ldapsearch uid=$user1 | VAL1 uidNumber)
+user1_uidnumber=$(univention-ldapsearch uid="$user1" | VAL1 uidNumber)
 
 sharename="$(random_chars)"
 sharepath1="/mnt/$(random_chars)"
@@ -47,7 +47,7 @@ share_create "$sharename" "$sharepath1"
 wait_for_replication_and_postrun
 # wait until the share is ready
 for((i=0;i<60;i++)); do
-	if smbclient -U ${user1}%univention //$hostname/$sharename -c ls; then
+	if smbclient -U "${user1}%univention" "//$hostname/$sharename" -c ls; then
 		echo "I: Share is ready"
 		break
 	fi
@@ -56,13 +56,13 @@ done
 
 ftemp=$(mktemp)
 echo "test" >>"$ftemp"
-ftemp_basename="$(basename $ftemp)"
+ftemp_basename="$(basename "$ftemp")"
 
-echo smbclient -U ${user1}%univention //$hostname/$sharename -c "put $ftemp $ftemp_basename" || fail_test 1
-smbclient -U ${user1}%univention //$hostname/$sharename -c "put $ftemp $ftemp_basename" || fail_test 1
+echo smbclient -U "${user1}%univention" "//$hostname/$sharename" -c "put $ftemp $ftemp_basename" || fail_test 1
+smbclient -U "${user1}%univention" "//$hostname/$sharename" -c "put $ftemp $ftemp_basename" || fail_test 1
 test -e "$sharepath1/$ftemp_basename" || fail_test 1 "$sharepath1/$ftemp_basename does not exist"
 
-ucr set "samba/share/$sharename/options/path"="$sharepath2"
+ucr set "samba/share/$sharename/options/path=$sharepath2"
 if [ -x /etc/init.d/samba-ad-dc ]; then
 	/etc/init.d/samba-ad-dc restart
 elif [ -x /etc/init.d/samba-ad-dc ]; then
@@ -71,8 +71,8 @@ fi
 # Samba need some time
 sleep 3
 
-echo smbclient -U ${user1}%univention //$hostname/$sharename -c "put $ftemp ${ftemp_basename}_2" || fail_test 1
-smbclient -U ${user1}%univention //$hostname/$sharename -c "put $ftemp ${ftemp_basename}_2" || fail_test 1
+echo smbclient -U "${user1}%univention" "//$hostname/$sharename" -c "put $ftemp ${ftemp_basename}_2" || fail_test 1
+smbclient -U "${user1}%univention" "//$hostname/$sharename" -c "put $ftemp ${ftemp_basename}_2" || fail_test 1
 test -e "$sharepath2/${ftemp_basename}_2" || fail_test 1 "$sharepath1/${ftemp_basename}_2 does not exist"
 
 ucr unset "samba/share/$sharename/options/path"
@@ -80,4 +80,4 @@ rm -f "$ftemp"
 user_remove "$user1"
 share_remove "$sharename"
 
-exit $RETVAL
+exit "$RETVAL"
