Bug #31369 SSL: Check SSL expiration date
UCW has "mawk" by default, which has not time-related functions as
"gawk" has.

Use "date" to generate time-stamp.

Make output more useful to user.
Also handle "E(xpired)" state

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.1/ucs-4.1-2@70642 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/base/univention-ssl/univention-certificate b/base/univention-ssl/univention-certificate
--- a/base/univention-ssl/univention-certificate
+++ b/base/univention-ssl/univention-certificate
@@ -124,16 +124,18 @@ renew () {
 }
 
 check () {
+		local rv=0
 		run_only backup shared
 		echo -n "Certificate \"$name\" is "
-		if has_valid_cert "$name" >/dev/null
-		then
-			echo "valid"
-			exit 0
-		else
-			echo "invalid"
-			exit 1
-		fi
+		has_valid_cert "$name" >/dev/null || rv=$?
+		case "$rv" in
+		0) echo "valid" ;;
+		1) echo "invalid (not found)" ;;
+		2) echo "invalid (revoked)" ;;
+		3) echo "invalid (expired)" ;;
+		*) echo "invalid" ;;
+		esac
+		exit $rv
 }
 
 list () {
