* start text-mode univention-system-setup if X11 is not available (Bug #23870) * switched output of u-s-s to UTF-8 * moved u-s-s to /usr/share/univention-system-setup/
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.0/ucs@28084 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/base/univention-system-setup/usr/share/univention-system-setup/startxwithfirefox b/base/univention-system-setup/usr/share/univention-system-setup/startxwithfirefox
--- a/base/univention-system-setup/usr/share/univention-system-setup/startxwithfirefox
+++ b/base/univention-system-setup/usr/share/univention-system-setup/startxwithfirefox
@@ -33,8 +33,21 @@
 if [ -z "$1" ] # no parameter --> called from init script
 then # call self in xinit as nobody, then start gdm
 	/usr/sbin/univention-config-registry set system/setup/boot/start=false
-	xinit /bin/su nobody -c "'$0' 'http://localhost/umc'"
-	/etc/init.d/gdm start
+
+	# save deadline (15 seconds from now on)
+	deadline="$(( $(date +%s) + 15))"
+	[ -x /usr/sbin/xinit ] && /usr/sbin/xinit /bin/su nobody -c "'$0' 'http://localhost/umc'"
+	# if xinit returns a non-zero exitcode or xinit does not exist or session returned within 15 seconds...
+	if [ ! $? = 0 ] || [ ! -x /usr/sbin/xinit ] || [[ $deadline > $(date +%s) ]] ; then
+		# ... then start console tool univention-system-setup
+		eval "$(ucr shell)"
+		plymouth quit
+		chvt 1
+		/usr/share/univention-system-setup/univention-system-setup --modules="password,net" < /dev/tty1 > /dev/tty1
+	fi
+	if [ -x /etc/init.d/gdm ] ; then
+		/etc/init.d/gdm start
+	fi
 	exit
 fi
 
