New versions of "05join_with_long_bind_dn", "10slapd_stop_start" and "20schema-download" in bash. Bug #27662.
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@39253 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/10_ldap/05join_with_long_bind_dn b/test/ucs-test/tests/10_ldap/05join_with_long_bind_dn
--- a/test/ucs-test/tests/10_ldap/05join_with_long_bind_dn
+++ b/test/ucs-test/tests/10_ldap/05join_with_long_bind_dn
@@ -1,127 +1,123 @@
-#!/usr/share/ucs-test/runner python2.6
-## desc: Join to a master when the dn of the bind-user is very long (provoking a linebreak #16210)
-## tags: [basic]
-## exposure: safe
+#!/usr/share/ucs-test/runner bash
+## desc: Join to a master when the dn of the bind-user is very long (provoking a linebreak #16210)##
+## roles:
+##  - domaincontroller_backup
+##  - domaincontroller_slave
+##  - memberslave
+## packages:
+##  - univention-join
+## exposure: dangerous
 
-import sys
-import os
-import subprocess
-import dns.resolver
-import socket
-from dns.exception import DNSException
-from univention.config_registry import ConfigRegistry
 
-def main():
-    """A main method stores almost completely code."""
+. "$TESTLIBPATH/base.sh" || exit 1
+. "$TESTLIBPATH/random.sh" || exit 1
+. "$TESTLIBPATH/joincheck.sh" || exit 1
 
-    dcname = None
-    try:
-        subprocess_join_check_status = subprocess.Popen(['univention-check-join-status'],
-        stdout=subprocess.PIPE) # subprocess (command line input)
+if check_join_status; then
+	error "Expected system not to be joined"
+	exit 135
+fi
 
-        subprocess_join_check_status.wait()
-        result = subprocess_join_check_status.returncode
+eval "$(ucr shell)"
 
-        if not result:
-            print >> sys.stderr, "Expected not to be joined"
-            #sys.exit(135)
+DCNAME=
+LDAP_BASE=
+BINDUSERNAME="$(random_chars)"
+BINDPASSWORD="$(random_chars)"
+DNPART="$(random_chars)"
 
-        print "Search DC Master:"
-        ucr = ConfigRegistry()
-        ucr.load()
-        interface_eth0_type =  ucr.get('interfaces/eth0/type')
-        interface_eth0_type_is_true = ucr.is_true('interface/eth0/type')
-        domainname = ucr.get('domainname')
-        print interface_eth0_type, interface_eth0_type_is_true, domainname
+#This code snippet is taken (almost) 1:1 from univention-join and sets the variable DCNAME
+echo -n "Search DC Master: "
+#echo "$interfaces_eth0_address"
+#echo "$nameserver1"
 
-        if False:# True: # interface_eth0_type_is_true and domainname and interface_eth0_type == "dhcp":
-            try:
-                dns_srv = dns.resolver.query("_domaincontroller_master._tcp."+ domainname, "SRV")
-                if dns_srv[0].target:
-                    dcname = dns_srv[0].target
-                if dcname:
-                    print "Done."
-            except dns.resolver.NXDOMAIN:
-                print >> sys.stderr, "No appropriate SRV record found."
-        else:
-             ucr_var_list = [ "nameserver", "nameserver1", "nameserver2", "nameserver3", "dnsforwarder1","dnsforwarder2", "dnsforwarder3", ]
-             for ucr_vars in ucr_var_list:
-                 ucr_value = ucr.get(ucr_vars)
-#                 print ucr_value
-                 if ucr_value:
-                     popen_string = "host -t SRV _domaincontroller_master._tcp." + domainname + " " + ucr_value
-                     subprocess_dcname = os.popen(popen_string).read().strip()
-                     #print subprocess_dcname
-                     #try:
-                     #conc = "liam.local%s" % ucr_value
-                     srv_query = "_domaincontroller_master._tcp" 
-                     #print srv_query
-                     dns_srv = dns.resolver.query("10.200.22.20", "SRV")
-                     print dns_srv[0]
-                     #print dns_srv[0].target
-                     #if dns_srv[0].target:
-                     #    dcname = dns_srv[0].target
-                     #if dcname:
-                     #    print "Done."
-                     #except dns.resolver.NXDOMAIN:
-                     print >> sys.stderr, "No appropriate SRV record found."
-        print "Equal None."
-        
-        print "dcname: ", dcname 
+if [ "$interfaces_eth0_type" = "dhcp" ]; then
+	DCNAME=`host -t SRV _domaincontroller_master._tcp.$domainname | grep -v "not found" | grep -v "reached" | tail -1 | sed -e 's|.* ||g' | sed -e 's|\.$||'`
+	if [ -n "$DCNAME" ]; then
+		echo -e "\033[60Gdone"
+	fi
+else
+	for i in "$nameserver" "$nameserver1" "$nameserver2" "$nameserver3" "$dns_forwarder1" "$dns_forwarder2" "$dns_forwarder3"; do
+		if [ -z "$i" ]; then continue; fi
+		DCNAME=`host -t SRV _domaincontroller_master._tcp.$domainname $i | grep -v "not found" | grep -v "reached" | tail -1 | sed -e 's|.* ||g' | sed -e 's|\.$||'`
+		if [ -n "$DCNAME" ]; then
+			echo -e "\033[60Gdone"
+			echo "domain $domainname" >/etc/resolv.conf
+			echo "nameserver $i" >>/etc/resolv.conf
+			test -x /etc/init.d/nscd && /etc/init.d/nscd restart >>/var/log/univention/join.log 2>&1
+			break
+		fi
+	done
+fi
 
-        if True: # interface_eth0_type_is_true:
-            if False: #interface_eth0_type == "dhcp":
-                dcname= "to define"
-                popen_string = "host -t SRV _domaincontroller_master._tcp." + domainname + " | grep -v 'not found' | grep -v 'reached' | tail -1 | sed -e 's|.* ||g' | sed -e 's|\.$||'"
-                subprocess_dcname = os.popen(popen_string).read()
+if [ -z "$DCNAME" ]; then
+	error "Unable to find a suitable master to join with"
+	exit 1 # This exit-code isn't defined, but there seems to
+	# be no suitable exit-code for this case
+fi
 
-                if subprocess_dcname.strip():
-                    print "Done."
 
-            else:
-                ucr_var_list = [ "nameserver", "nameserver1", "nameserver2", "nameserver3", "dnsforwarder1","dnsforwarder2", "dnsforwarder3", ]
-                for i in ucr_var_list:
-                    value = get_ucr_value(i)
-                    if value != None:
-                        popen_string = "host -t SRV _domaincontroller_master._tcp." + domainname + " " + value + " | grep -v 'not found' | grep -v 'reached' | tail -1 | sed -e 's|.* ||g' | sed -e 's|\.$||'"
-                        subprocess_dcname = os.popen(popen_string).read().strip()
-                        print subprocess_dcname
-                        if subprocess_dcname:
-                            print "Done"
-                            print "domain", domainname
-                            conf_file = open("/root/resolv.conf", 'w')
-                            domain_to_write = "domain " + domainname
-                            conf_file.write(domain_to_write)
-                            conf_file.write("\n")
-                            nameserver_to_write = "nameserver " + value
-                            conf_file.write(nameserver_to_write)
-                            test_string = "test -x /etc/init.d/nscd && /etc/init.d/nscd restart >>/root/join.log 2>&1"
-                            #subprocess_test = subprocess.Popen(['test', '-x', '/etc/init.d/nscd', '&&', '/etc/init.d/nscd', 'restart', '>>', '/root/join.log', '2>&1',],stdout=subprocess.PIPE) # subprocess (command line input)
-                            #return_message = subprocess_test.stdout.readline().strip()
-                            subprocess_test = os.popen(test_string).read()
-                            print subprocess_test
-                            conf_file.close()
-        else:
-            print "ELSE"
+pwfile="$(mktemp)"
+trap "rm -f '$pwfile'" EXIT
 
-    except OSError, error:
-        print >> sys.stderr, "An error occured with %s" % (error, )
-        sys.exit(1) # exit if something goes wrong on OS level
+echo -n "$ADMINISTRATOR_PASSWORD" > "$pwfile"
 
-def get_ucr_value(variable):
-    """This method provides a value of a ucr-variable only if it is not None"""
-    ucr = ConfigRegistry()
-    ucr.load()
-    value = ucr.get(variable)
-    is_true = ucr.is_true(variable)
-    return value
-    """if is_true:    
-        if value == None:
-            return None
-        else:
-            return value
-    else:
-        return None"""
+LDAP_BASE="$(univention-ssh "$pwfile" "root@$DCNAME" \
+	ucr get ldap/base)"
+LDAP_BASE="$(echo "$LDAP_BASE" | grep dc)"
 
-if __name__ == '__main__':
-   main()
+i=0
+while [ $i -le 10 ]
+do
+PREF=
+	j=0
+	while [ $j -lt $i ]
+	do
+		PREF+="cn=$DNPART,"
+		j=`expr $j + 1`
+	done
+
+	univention-ssh "$pwfile" "root@$DCNAME" \
+		univention-directory-manager container/cn create \
+		--set "name=${DNPART}" \
+		--position "${PREF}cn=users,$LDAP_BASE" || fail_test 1
+
+	i=`expr $i + 1`
+done
+
+if [ "$server_role" == "domaincontroller_backup" ]; then
+	univention-ssh "$pwfile" "root@$DCNAME" \
+		univention-directory-manager users/user create \
+		--set "username=${BINDUSERNAME}" \
+		--set "password=${BINDPASSWORD}" \
+		--set "lastname=$(random_chars)" \
+		--set '\"'primaryGroup=cn=Domain Admins,cn=groups,$LDAP_BASE'\"' \
+		--append '\"'groups=cn=DC Backup Hosts,cn=groups,$LDAP_BASE'\"' \
+		--position "${PREF}cn=users,$LDAP_BASE" || fail_test 1
+else
+	univention-ssh "$pwfile" "root@$DCNAME" \
+		univention-directory-manager users/user create \
+		--set "username=${BINDUSERNAME}" \
+		--set "password=${BINDPASSWORD}" \
+		--set "lastname=$(random_chars)" \
+		--set '\"'primaryGroup=cn=Domain Admins,cn=groups,$LDAP_BASE'\"' \
+		--position "${PREF}cn=users,$LDAP_BASE" || fail_test 1
+fi
+
+univention-ssh "${pwfile}" "root@$DCNAME" \
+  'while sleep 1s ; do echo waiting for nscd update ; if getent group \"Domain Admins\" | grep -F '"${BINDUSERNAME}"' ; then break; fi; done'
+
+BINDPWDFILE="/tmp/bindpwd"
+echo -n "$BINDPASSWORD" > "$BINDPWDFILE"
+/usr/sbin/univention-join -dcaccount "$BINDUSERNAME" -dcpwd "$BINDPWDFILE" || fail_test 1
+rm -f "$BINDPWDFILE"
+
+if ! check_join_status; then
+	fail_test 1
+fi
+
+univention-ssh "$pwfile" "root@$DCNAME" \
+	univention-directory-manager container/cn remove \
+	--dn "cn=${DNPART},cn=users,$LDAP_BASE" || fail_test 1
+
+exit "$RETVAL"
diff --git a/test/ucs-test/tests/10_ldap/10slapd_stop_start b/test/ucs-test/tests/10_ldap/10slapd_stop_start
--- a/test/ucs-test/tests/10_ldap/10slapd_stop_start
+++ b/test/ucs-test/tests/10_ldap/10slapd_stop_start
@@ -1,4 +1,4 @@
-#!/usr/share/ucs-test/runner python2.6
+#!/usr/share/ucs-test/runner bash
 ## desc: Test slapd for a correct stop and start
 ## tags: [basic]
 ## roles:
@@ -9,102 +9,61 @@
 ##  - slapd
 ## exposure: dangerous
 
-import sys
-import subprocess
-from os.path import basename
-from univention.config_registry import ConfigRegistry
+#Config
+returnOK=0
+returnERROR=1
+returnCode=$returnOK
 
-RETURN_PASS_CODE = 100
-RETURN_FAIL_CODE = 110
+#List of services to be stopped and started
+service_count=1
 
-def main():
-	"""A main method stores almost completely code."""
-	return_code = None # return code for
-	exit_code = RETURN_PASS_CODE # use for exitcode of the entire test, in further code it will be set only to RETURN_PASS_CODE
-	# List of services to be stopped and started
-	service_path = "/etc/init.d/slapd"
-	service_binarys = "/usr/sbin/slapd"
-	server_roles = [ 'domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', ]
-	print "Check if services can be correctly stopped."
+service_path[0]="/etc/init.d/slapd"
+service_binarys[0]="/usr/sbin/slapd"
+server_roles[0]="domaincontroller_master domaincontroller_backup domaincontroller_slave"
 
-	ucr = ConfigRegistry()
-	ucr.load() # load whole dict
-	ldap_schema_export_server_role = ucr.get("server/role")
-	base_name = basename(service_path) # basename of service_path
+echo "Check if services can be correctly stopped"
+role=$(/usr/sbin/univention-config-registry get server/role)
+nr=0
+while [ $nr -lt $service_count ] ; do
+        name="$(basename "${service_path[$nr]}")"
+        echo -ne "Check if we can test the service \"$name\" on server role \"$role\"\t"
+        found=0
+        for r in ${server_roles[$nr]} ; do
+                if [ "$r" == "$role" ] ; then
+                        found=1
+                fi
+        done
+        if [ $found -eq 1 ] ; then
+                echo "Yes"
+                echo -ne "Trying to stop service $name\t"
+                "${service_path[$nr]}" stop
+                echo "Done"
 
-	try:
-		print "Check if we can test the service", ldap_schema_export_server_role, "on server role", base_name
+                echo -ne "Has the service been stopped?\t"
+                running=$(ps axu | grep "${service_binarys[$nr]}" | grep -v grep)
+                if [ -z "$running" ] ; then
+                        echo "Ok"
+                else
+                        echo "Error"
+                        returnCode=$returnERROR
+                fi
 
-		found = False
-		for server_role in server_roles: # checks if an server role matches any role in the server_roles list
-			if ldap_schema_export_server_role == server_role:
-				found = True # if at least the is one match
+                echo -ne "Trying to start service $(basename "${service_path[$nr]}")\t"
+                "${service_path[$nr]}" start
+                echo "Done"
 
-		if found:
-			# stop the process
-			if not control_process(base_name, service_path, "stop"):
-				exit_code = RETURN_FAIL_CODE
-			print "Done."
+                echo -ne "Is this service running?\t"
+                running=$(ps axu | grep "${service_binarys[$nr]}" | grep -v grep)
+                if [ -z "$running" ] ; then
+                        echo "Error"
+                        returnCode=$returnERROR
+                else
+                        echo "Ok"
+                fi
+        else
+                echo "No - skipping test"
+        fi
+        nr=$(($nr + 1))
+done
 
-			print "Check if the process has been stopped."
-			if not check_process(service_binarys, "stop"):
-				exit_code = RETURN_FAIL_CODE
-
-			# start the prcocess
-			if not control_process(base_name, service_path, "start"):
-				exit_code = RETURN_FAIL_CODE
-
-			print "Check if the process has been started."
-			if not check_process(service_binarys, "start"):
-				exit_code = RETURN_FAIL_CODE
-		else:
-			print "No server role matched. Skipping test."
-			sys.exit(RETURN_FAIL_CODE) # test failed
-	except OSError, error:
-		print >> sys.stderr, "An error occured with: %s" % (error, )
-		sys.exit(RETURN_FAIL_CODE)
-
-	sys.exit(exit_code) # exit with appropriate returncode
-
-def check_process(process_name, status):
-	"""The method Check whether or not the given service/process-name is running."""
-	try:
-		process_one = subprocess.Popen(["ps", "axu", ], stdout=subprocess.PIPE) # command for first PIPE
-		process_to_pipe_grep_one = subprocess.Popen(["grep", process_name, ], stdin=process_one.stdout, stdout=subprocess.PIPE) # command for secon PIPE
-		process_one.stdout.close()  # Allow process_one to receive a SIGPIPE if process2 exits.
-		process_to_pipe_grep_two = subprocess.Popen(["grep", "-v", "grep", ], stdin=process_to_pipe_grep_one.stdout, stdout=subprocess.PIPE)
-		process_to_pipe_grep_one.stdout.close()  # Allow process2 to receive a SIGPIPE if process3 exits
-		output_check = process_to_pipe_grep_two.communicate()[0] # output with process
-		process_to_pipe_grep_two.stdout.close()
-
-		if status == "stop":
-			if process_name not in output_check[:]:
-				print "OK. The process is not active."
-				return True
-			else:
-				print >> sys.stderr, "ERROR. The process is active. (The process could not be started)"
-				return False
-		else:
-			if process_name in output_check[:]:
-				print "OK. The process is active."
-				return True
-			else:
-				print >> sys.stderr, "ERROR. The process is not active. (The process could not be started)"
-				return False
-	except subprocess.CalledProcessError, error:
-		print >> sys.stderr, "An error occured with: %s" % (error, )
-		return False
-
-def control_process(process_name, service_path, command):
-	"""This method tries wheather to stop or to start the given process. Depends on the 3rd given parameter."""
-	try:
-		print "Trying to " + command + " service ", process_name
-		subprocess_command_service = subprocess.Popen([service_path, command, ], stdout=subprocess.PIPE) # subprocess (command line input)
-		subprocess_command_service.wait() # waits for child process to terminate before goes on
-	except subprocess.CalledProcessError, error:
-		print >> sys.stderr, "An error occured with: %s" % (error, )
-		return False
-	return True
-
-if __name__ == '__main__':
-	main()
+exit $returnCode
