* 10_ldap/31ldapi: Added default shell to user nobody otherwise the   message 'This account is currently not available' is shown   (Bug #43438)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.2/ucs-4.2-0@76164 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/10_ldap/31ldapi b/test/ucs-test/tests/10_ldap/31ldapi
--- a/test/ucs-test/tests/10_ldap/31ldapi
+++ b/test/ucs-test/tests/10_ldap/31ldapi
@@ -49,7 +49,7 @@ then
 	fail_test 1
 fi
 echo -e "\n\n***Try to call ldapdelete via the ldapi interfaceas user nobody. This shouln't work."
-if ! su - "nobody" -c "ldapdelete -x -H ldapi:/// 'uid=$USERNAME,cn=users,$ldap_base' && echo 'Error: Removed the object as user nobody via ldapi socket.' && exit 1 || exit 0"
+if ! su -s /bin/bash - "nobody" -c "ldapdelete -x -H ldapi:/// 'uid=$USERNAME,cn=users,$ldap_base' && echo 'Error: Removed the object as user nobody via ldapi socket.' && exit 1 || exit 0"
 then
 	fail_test 1
 fi
