Bug #27662: ucs-test/ldap/: simplify shell
Remove ; from end of line.
Directly use command in if construct instead of evaluating $?

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.2/ucs-3.2-0@42550 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/10_ldap/31ldapi b/test/ucs-test/tests/10_ldap/31ldapi
--- a/test/ucs-test/tests/10_ldap/31ldapi
+++ b/test/ucs-test/tests/10_ldap/31ldapi
@@ -35,7 +35,7 @@ user_create "$USERNAME"
 
 # wait for the replication
 i=0
-while sleep 1s;
+while sleep 1s
 do
 	if [ $i -lt 120 ]; then
 		echo "Waiting for replication..."
@@ -51,9 +51,8 @@ do
 done
 
 echo -e "\n\n***Try to call ldapdelete via the ldapi interface. This shouln't work."
-su - "$USERNAME" -c "ldapdelete -x -H ldapi:/// 'uid=$USERNAME,cn=users,$ldap_base' && echo 'Error: Removed the object as user $USERNAME via ldapi socket.' && exit 1 || exit 0"
-
-if [ $? -ne 0 ]; then
+if ! su - "$USERNAME" -c "ldapdelete -x -H ldapi:/// 'uid=$USERNAME,cn=users,$ldap_base' && echo 'Error: Removed the object as user $USERNAME via ldapi socket.' && exit 1 || exit 0"
+then
 	fail_test 1
 fi
 
