Bug #27662: ucs-test double escape
Using univention-ssh passes the arguments to a second shell on the
remote hosts, so arguments must be double-escaped: once for the local
shell and once more for the remote shell.

Add a variant which passes on the arguments escaped.

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.2/ucs-3.2-0@42545 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/10_ldap/31ldapi b/test/ucs-test/tests/10_ldap/31ldapi
--- a/test/ucs-test/tests/10_ldap/31ldapi
+++ b/test/ucs-test/tests/10_ldap/31ldapi
@@ -51,7 +51,7 @@ do
 done
 
 echo -e "\n\n***Try to call ldapdelete via the ldapi interface. This shouln't work."
-su - "$USERNAME" -c "ldapdelete -x -H ldapi:/// \"uid=$USERNAME,cn=users,$ldap_base\" && echo \"Error: Removed the object as user $USERNAME via ldapi socket.\" && exit 1 || exit 0"
+su - "$USERNAME" -c "ldapdelete -x -H ldapi:/// 'uid=$USERNAME,cn=users,$ldap_base' && echo 'Error: Removed the object as user $USERNAME via ldapi socket.' && exit 1 || exit 0"
 
 if [ $? -ne 0 ]; then
 	fail_test 1
