Bugfixes. Test to prove. Bug #27662.
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@39581 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/10_ldap/31ldapi b/test/ucs-test/tests/10_ldap/31ldapi
--- a/test/ucs-test/tests/10_ldap/31ldapi
+++ b/test/ucs-test/tests/10_ldap/31ldapi
@@ -17,15 +17,19 @@
 
 eval "$(ucr shell)"
 
+setdomain=1
 # create domain part in configured mail domains list
 if ! udm mail/domain create --set name=$domainname ; then
 	echo "Mail/domain object already exists or could not be created. Continue testing..."
+	setdomain=0
 fi
 
 cleanup () {
 
-	if ! udm mail/domain remove --dn "cn=$domainname,$ldap_base" ; then
-		echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
+	if [[ "$setdomain" -ne 0 ]]; then
+		if ! udm mail/domain remove --dn "cn=$domainname,$ldap_base" ; then
+			echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
+		fi
 	fi
 
 }
diff --git a/test/ucs-test/tests/10_ldap/41listener b/test/ucs-test/tests/10_ldap/41listener
--- a/test/ucs-test/tests/10_ldap/41listener
+++ b/test/ucs-test/tests/10_ldap/41listener
@@ -35,8 +35,10 @@ __HERE__
 /etc/init.d/univention-directory-listener restart
 
 # create domain part in configured mail domains list
+setdomain=1
 if ! udm mail/domain create --set name=$DOMAIN ; then
 	echo "Mail/domain object already exists or could not be created. Continue testing..."
+	setdomain=0
 fi
 
 USERNAME=$(user_randomname)
@@ -74,8 +76,10 @@ rm -f "$tempFile" || fail_test 1
 #removing users/user
 user_remove "$USERNAME" || fail_test 1
 
-if ! udm mail/domain remove --dn "cn=$DOMAIN,$LDAPBASE" ; then
-	echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
+if [[ "$setdomain" -ne 0 ]]; then
+	if ! udm mail/domain remove --dn "cn=$DOMAIN,$LDAPBASE" ; then
+		echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
+	fi
 fi
 
 exit "$RETVAL"
diff --git a/test/ucs-test/tests/10_ldap/55slapd-crash-1270 b/test/ucs-test/tests/10_ldap/55slapd-crash-1270
--- a/test/ucs-test/tests/10_ldap/55slapd-crash-1270
+++ b/test/ucs-test/tests/10_ldap/55slapd-crash-1270
@@ -30,8 +30,10 @@ PRINTERNAME="$(getprintername)"
 create_localprinter "$PRINTERNAME" || fail_test 1
 
 # create domain part in configured mail domains list
+setdomain=1
 if ! udm mail/domain create --set name=$domainname ; then
 	echo "Mail/domain object already exists or could not be created. Continue testing..."
+	setdomain=0
 fi
 
 USERNAME=$(user_randomname)
@@ -67,9 +69,10 @@ group_remove "$GROUPNAME" || fail_test 1
 
 remove_printer "$PRINTERNAME" || fail_test 1
 
-
-if ! udm mail/domain remove --dn "cn=$domainname,$ldap_base" ; then
-	echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
+if [[ "$setdomain" -ne 0 ]]; then
+	if ! udm mail/domain remove --dn "cn=$domainname,$ldap_base" ; then
+		echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
+	fi
 fi
 
 if [ ! "$RET" = "0" ] ; then
diff --git a/test/ucs-test/tests/10_ldap/61getent_crash b/test/ucs-test/tests/10_ldap/61getent_crash
--- a/test/ucs-test/tests/10_ldap/61getent_crash
+++ b/test/ucs-test/tests/10_ldap/61getent_crash
@@ -19,8 +19,10 @@ section "Preparing"
 sleep 3s
 
 # create domain part in configured mail domains list
+setdomain=1
 if ! udm mail/domain create --set name=domain.de ; then
 	echo "Mail/domain object already exists or could not be created. Continue testing..."
+	setdomain=0
 fi
 
 udm groups/group remove --dn "cn=subgroup,cn=groups,$ldap_base"
@@ -35,9 +37,10 @@ _cleanup(){
   for i in $(seq 1 200) ; do
     udm users/user remove --dn "uid=nsstest$i,cn=users,$ldap_base" >/dev/null
   done
-
-  if ! udm mail/domain remove --dn "cn=domain.de,$ldap_base" ; then
-	  echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
+  if [[ "$setdomain" -ne 0 ]]; then
+	  if ! udm mail/domain remove --dn "cn=domain.de,$ldap_base" ; then
+		  echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
+	  fi
   fi
 }
 
diff --git a/test/ucs-test/tests/10_ldap/63univention-admingrp-user-passwordreset b/test/ucs-test/tests/10_ldap/63univention-admingrp-user-passwordreset
--- a/test/ucs-test/tests/10_ldap/63univention-admingrp-user-passwordreset
+++ b/test/ucs-test/tests/10_ldap/63univention-admingrp-user-passwordreset
@@ -1,5 +1,6 @@
 #!/usr/share/ucs-test/runner bash
-## desc: Checking univention-admingrp-user-passwordreset
+## desc: univention-admingrp-user-passwordreset (Bug #25408)
+## bugs: [25408]
 ## roles:
 ##  - domaincontroller_master
 ##  - domaincontroller_backup
@@ -17,15 +18,18 @@ eval "$(ucr shell)"
 
 cleanup_mail_domain () {
 
-		if ! udm mail/domain remove --dn "cn=$domainname,$ldap_base" ; then
-			echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
-		fi
-
+  if [[ "$setdomain" -ne 0 ]]; then
+	  if ! udm mail/domain remove --dn "cn=$domainname,$ldap_base" ; then
+		  echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
+	  fi
+  fi
 }
 
 # create domain part in configured mail domains list
+setdomain=1
 if ! udm mail/domain create --set name=$domainname ; then
 	echo "Mail/domain object already exists or could not be created. Continue testing..."
+	setdomain=1
 fi
 
 trap cleanup_mail_domain EXIT
