* Merge from UCS 3.2 (4.0.73-1)   [ Lukas Walter ]   * added variables containing DNs of univention temporary, default user and     default group containers to udm.py.UCSTestUDM (Bug #30560)   * added certain udm-groups tests (Bug #31657)   * fixed validation of sambaSID in udm-computer tests   * added certain udm-groups tests   * activated binary package ucs-test-udm-groups (Bug #27664)   * changed description of udm-tests. It now contains the effective module     name (e.g dns/host, users/user, dhcp/service)   * removed unused code from 64_udm-printers/41_check_ppd   * renamed udm-users tests   * fixed "nameserver" attribute related udm-dns tests (Bug #27664)   * cleanup for udm-dns, udm-containers, udm-dhcp and udm-computers tests     (Bug #27664)   * library performance and logging improvements   * increased granularity of udm-dhcp tests (Bug #31654)   * re-enabled 61_udm-users/20_create_user_just_person (Bug #31868)   * added test to verify that it is possible to create a user with only person     and mail options set (Bug #31868)   * passing attributes set to values interpreted as false (e.g False, None,     '') to UCSTestUDM._build_cmd_line() will lead to this attributes not     being set (Bug #30560)   * renamed another udm-computers test   * added more udm-computers tests   * also validate "univentionServerInstallationText" in     66_udm-computers/*create_maximal*   * removed debug tag from certain udm-computers test headers (Bug #31659)   [ Philipp Hahn ]   * lib: Fix ${var?-msg} to ${var:?msg} (Bug #28699)   * Use ucslint (Bug #28699)   * lib: Fix wait4replication to use function local variable.   * 10: Fix check for filename (Bug #27662)   * lib/group,user: Remove debug output of locale information.   * Use stored passwords (Bug #31250)   * Fix ldif comparator (Bug #29337)   * 10/05: Move to new section: 11_join   * 10/42: Check replication using LDIFf (Bug #31722)   * 10/43: Check replication performance (Bug #31721)   * 09/35: Workaround APT caching bug (Bug #31733)   [ Stefan Gohmann ]   * 00_base/45license_v2: limit test on DC master (Bug #31680)   * 02_import-performance: Except sqlite errors (Bug #31695)   * 02_import-performance/*.csv: fix import files (Bug #31695)   * 02_import-performance: increase the connector wait for connector     interval (Bug #31695)   * 60_umc/03_acls: Added test case for UMC ACLs (Bug #28059)   * tests/02_import-performance: Don't wait for the replication during     the user creation (Bug #31695)   * 03_ucr/67ucr_concurrent_set_get: activate for 3.1-1 since it was     fixed with errata130 (Bug #31725)   * 50_samba/42file_access_permissions: prevent an endless loop     (Bug #29054)   [ Tobias Peters ]   * Merged 36_printer from 51_samba4 and 50_samba to     53_samba-common/36_printer (Bug #31764)   * Merged 51_samba4/47file_access_permissions-unixmode and     50_samba/42file_access_permissions into     53_samba-common/47file_access_permissions-unixmode (Bug #29056)   * Merged the test 35smbclient_auth from 50_samba and 51_samba4     into 53_samba-common/35smbclient_auth (Bug #26807)   * Fixed the package dependencies in     53_samba-common/46file_access_permissions-samba_share_rules (Bug #29229)   * Add more checks to 51_samba4/46file_access_permissions-samba_share_rules and     move the test to 53_samba-common(Bug #29229)  [ Arvid Requate ]  * rename 25domain-join-without-admin-rights to run at the end    (Bug #31772)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs-3.1-1@42594 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/10_ldap/31ldapi b/test/ucs-test/tests/10_ldap/31ldapi
--- a/test/ucs-test/tests/10_ldap/31ldapi
+++ b/test/ucs-test/tests/10_ldap/31ldapi
@@ -1,5 +1,5 @@
 #!/usr/share/ucs-test/runner bash
-## desc: Try to bind to ldapi as normal user (Bug #10529)
+## desc: Try to bind to ldapi as normal user
 ## bugs: [10529]
 ## tags:
 ##  - basic
@@ -14,30 +14,23 @@
 ## exposure: dangerous
 
 
-. "$TESTLIBPATH/base.sh" || exit 1
-. "$TESTLIBPATH/random.sh" || exit 1
-. "$TESTLIBPATH/user.sh" || exit 1
-. "$TESTLIBPATH/maildomain.sh" || exit 1
-
-eval "$(ucr shell)"
-
-create_mail_domain "$domainname"
-rc=$?
-
-cleanup () {
-	if [ "$rc" = "0" ]; then
-		delete_mail_domain "$domainname" || fail_test 1
-	fi
-}
-
-trap cleanup EXIT
+. "$TESTLIBPATH/base.sh" || exit 137
+. "$TESTLIBPATH/random.sh" || exit 137
+. "$TESTLIBPATH/user.sh" || exit 137
+. "$TESTLIBPATH/maildomain.sh" || exit 137
+. "$TESTLIBPATH/undo.sh" || exit 137
 
 USERNAME=$(user_randomname)
-user_create "$USERNAME"
+
+create_mail_domain "$domainname" && undo delete_mail_domain "$domainname"
+
+user_create "$USERNAME" &&
+	undo user_remove "$USERNAME" ||
+	fail_fast 1 "Failed to create user $USERNAME"
 
 # wait for the replication
 i=0
-while sleep 1s;
+while sleep 1s
 do
 	if [ $i -lt 120 ]; then
 		echo "Waiting for replication..."
@@ -45,20 +38,15 @@ do
 			break
 		fi
 	else
-		echo "Waiting for replication longer than two minutes. Replication is probably broken. Test failed."
-		user_remove "$USERNAME"
-		exit 1
+		fail_fast 1 "Waiting for replication longer than two minutes. Replication is probably broken. Test failed."
 	fi
 	i=`expr $i + 1`
 done
 
 echo -e "\n\n***Try to call ldapdelete via the ldapi interface. This shouln't work."
-su - "$USERNAME" -c "ldapdelete -x -H ldapi:/// \"uid=$USERNAME,cn=users,$ldap_base\" && echo \"Error: Removed the object as user $USERNAME via ldapi socket.\" && exit 1 || exit 0"
-
-if [ $? -ne 0 ]; then
+if ! su - "$USERNAME" -c "ldapdelete -x -H ldapi:/// 'uid=$USERNAME,cn=users,$ldap_base' && echo 'Error: Removed the object as user $USERNAME via ldapi socket.' && exit 1 || exit 0"
+then
 	fail_test 1
 fi
-
-user_remove "$USERNAME"
 
 exit "$RETVAL"
diff --git a/test/ucs-test/tests/10_ldap/33slapcat_slapadd b/test/ucs-test/tests/10_ldap/33slapcat_slapadd
--- a/test/ucs-test/tests/10_ldap/33slapcat_slapadd
+++ b/test/ucs-test/tests/10_ldap/33slapcat_slapadd
@@ -8,18 +8,19 @@
 ##  - univention-config-registry
 ## exposure: dangerous
 
-. "$TESTLIBPATH/base.sh" || exit 1
-
-ldif=`mktemp`
-ldif2=`mktemp`
-
-/etc/init.d/slapd stop
-
-slapcat > "$ldif"
+. "$TESTLIBPATH/base.sh" || exit 137
 
 temp_dir=`mktemp -d`
+trap "rm -rf '$temp_dir'" EXIT
 
-mv /var/lib/univention-ldap/ldap/* "$temp_dir/"
+mkdir "$temp_dir/bak"
+ldif="$temp_dir/1"
+ldif2="$temp_dir/2"
+
+/etc/init.d/slapd stop
+slapcat > "$ldif"
+
+mv /var/lib/univention-ldap/ldap/* "$temp_dir/bak/"
 
 ucr commit /var/lib/univention-ldap/ldap/DB_CONFIG
 
@@ -29,25 +30,19 @@ slapcat > "$ldif2"
 
 /etc/init.d/slapd start
 
-test=`diff "$ldif" "$ldif2"`
-
-if [ ! "$test" = "" ]; then
-        echo "diff: $test"
-        echo "There was an error testing slapcat and slapadd, trying to restore the old ldap database"
-        /etc/init.d/slapd stop
-        rm /var/lib/univention-ldap/ldap/*
-        mv $temp_dir/* /var/lib/univention-ldap/ldap/
-        /etc/init.d/slapd start
-        fail_test 1
+if ! ldiff "$ldif" "$ldif2"
+then
+	error "There was an error testing slapcat and slapadd, trying to restore the old ldap database"
+	/etc/init.d/slapd stop
+	rm /var/lib/univention-ldap/ldap/*
+	mv "$temp_dir/bak/"* /var/lib/univention-ldap/ldap/
+	/etc/init.d/slapd start
+	fail_test 1
 fi
-
-rm "$ldif" "$ldif2"
-rm -r "$temp_dir"
 
 # check if slapd running
 if ! pidof -s "slapd" > /dev/null; then
-	echo "Slapd is not running. Test failed."
-    fail_test 1
+	fail_test 1 "Slapd is not running."
 fi
 
 exit $RETVAL
