Domain part in configured mail domains list entry created. Necessary for creating a user with MailPrimaryAdress. Bug #27662.
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@39571 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/10_ldap/31ldapi b/test/ucs-test/tests/10_ldap/31ldapi
--- a/test/ucs-test/tests/10_ldap/31ldapi
+++ b/test/ucs-test/tests/10_ldap/31ldapi
@@ -17,6 +17,11 @@
 
 eval "$(ucr shell)"
 
+# create domain part in configured mail domains list
+if ! udm mail/domain create --set name=$domainname ; then
+	echo "Mail/domain object already exists or could not be created. Continue testing..."
+fi
+
 USERNAME=$(user_randomname)
 user_create "$USERNAME"
 
@@ -46,5 +51,9 @@ if [ $? -ne 0 ]; then
 fi
 
 user_remove "$USERNAME"
+
+if ! udm mail/domain remove --dn "cn=$domainname,$ldap_base" ; then
+	echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
+fi
 
 exit "$RETVAL"
diff --git a/test/ucs-test/tests/10_ldap/41listener b/test/ucs-test/tests/10_ldap/41listener
--- a/test/ucs-test/tests/10_ldap/41listener
+++ b/test/ucs-test/tests/10_ldap/41listener
@@ -9,6 +9,9 @@
 . "$TESTLIBPATH/base.sh" || exit 1
 . "$TESTLIBPATH/user.sh" || exit 1
 
+DOMAIN="$(ucr get domainname)"
+LDAPBASE="$(ucr get ldap/base)"
+
 ucstest="$(random_chars)"
 touch /usr/lib/univention-directory-listener/system/"$ucstest".py
 
@@ -30,6 +33,11 @@ def handler(dn, new, old):
 __HERE__
 
 /etc/init.d/univention-directory-listener restart
+
+# create domain part in configured mail domains list
+if ! udm mail/domain create --set name=$DOMAIN ; then
+	echo "Mail/domain object already exists or could not be created. Continue testing..."
+fi
 
 USERNAME=$(user_randomname)
 user_create "$USERNAME"
@@ -57,11 +65,17 @@ else
         fail_test 1
 fi
 
-/etc/init.d/univention-directory-listener restart || fail_test 1
-
 #cleanup
 rm -f /usr/lib/univention-directory-listener/system/"$ucstest".py || fail_test 1
-rm -f "$tempFile"
+rm -f "$tempFile" || fail_test 1
+
+/etc/init.d/univention-directory-listener restart || fail_test 1
 
 #removing users/user
-user_remove "$USERNAME"
+user_remove "$USERNAME" || fail_test 1
+
+if ! udm mail/domain remove --dn "cn=$DOMAIN,$LDAPBASE" ; then
+	echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
+fi
+
+exit "$RETVAL"
