Added a cleanup function for a better cleanup performance on EXIT. Bug #27662.
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@39574 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/10_ldap/31ldapi b/test/ucs-test/tests/10_ldap/31ldapi
--- a/test/ucs-test/tests/10_ldap/31ldapi
+++ b/test/ucs-test/tests/10_ldap/31ldapi
@@ -22,6 +22,16 @@ if ! udm mail/domain create --set name=$domainname ; then
 	echo "Mail/domain object already exists or could not be created. Continue testing..."
 fi
 
+cleanup () {
+
+	if ! udm mail/domain remove --dn "cn=$domainname,$ldap_base" ; then
+		echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
+	fi
+
+}
+
+trap cleanup EXIT
+
 USERNAME=$(user_randomname)
 user_create "$USERNAME"
 
@@ -51,9 +61,5 @@ if [ $? -ne 0 ]; then
 fi
 
 user_remove "$USERNAME"
-
-if ! udm mail/domain remove --dn "cn=$domainname,$ldap_base" ; then
-	echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
-fi
 
 exit "$RETVAL"
diff --git a/test/ucs-test/tests/10_ldap/61getent_crash b/test/ucs-test/tests/10_ldap/61getent_crash
--- a/test/ucs-test/tests/10_ldap/61getent_crash
+++ b/test/ucs-test/tests/10_ldap/61getent_crash
@@ -35,6 +35,10 @@ _cleanup(){
   for i in $(seq 1 200) ; do
     udm users/user remove --dn "uid=nsstest$i,cn=users,$ldap_base" >/dev/null
   done
+
+  if ! udm mail/domain remove --dn "cn=domain.de,$ldap_base" ; then
+	  echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
+  fi
 }
 
 trap _cleanup EXIT
@@ -109,9 +113,5 @@ EOF
     fi
 done
 echo "The testscript, testing for the crash, doing a \"getent group\" went like it should, everything is fine."
-
-if ! udm mail/domain remove --dn "cn=domain.de,$ldap_base" ; then
-	echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
-fi
 
 exit "$RETVAL"
