Updated versions.Bug #27662.
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs-3.1-2@40016 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/10_ldap/64univention-admingrp-user-passwordreset-selfmodify b/test/ucs-test/tests/10_ldap/64univention-admingrp-user-passwordreset-selfmodify
--- a/test/ucs-test/tests/10_ldap/64univention-admingrp-user-passwordreset-selfmodify
+++ b/test/ucs-test/tests/10_ldap/64univention-admingrp-user-passwordreset-selfmodify
@@ -11,24 +11,18 @@
 . "$TESTLIBPATH/user.sh" || exit 1
 . "$TESTLIBPATH/group.sh" || exit 1
 . "$TESTLIBPATH/random.sh" || exit 1
+. "$TESTLIBPATH/maildomain.sh" || exit 1
 
 eval "$(ucr shell)"
 
+create_mail_domain "$domainname"
+rc=$?
+
 cleanup_mail_domain () {
-
-  if [[ "$setdomain" -ne 0 ]]; then
-	  if ! udm mail/domain remove --dn "cn=$domainname,$ldap_base" ; then
-		  echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
-	  fi
-  fi
+    if [ "$rc" = "0" ]; then
+        delete_mail_domain "$domainname" || fail_test 1
+    fi
 }
-
-# create domain part in configured mail domains list
-setdomain=1
-if ! udm mail/domain create --set name=$domainname ; then
-	echo "Mail/domain object already exists or could not be created. Continue testing..."
-	setdomain=0
-fi
 
 trap cleanup_mail_domain EXIT
 
@@ -96,7 +90,7 @@ cleanup() {
         /etc/init.d/slapd crestart
 
         for user in $U_HELPDESK $U_PROT $U_UNPROT ; do
-emac            user_remove $user
+			user_remove $user
         done
 
         for grp in $G_HELPDESK ; do
@@ -153,7 +147,7 @@ fi
 # test if unprotected user can set it's own password
 echo "==> Test 3"
 if ! hasPwdAccess "$U_PROT" "$U_PROT" ; then
-    echo "Helpdesk user $U_PROT cannot set its own password"
+    echo "Unportected user $U_PROT cannot set its own password"
 	fail_test 1
 	exit "$RETVAL"
 fi
