* various improvements in all samba4 Tests (Bug #28262)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@38546 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/51_samba4/10samba-share-options b/test/ucs-test/tests/51_samba4/10samba-share-options
--- a/test/ucs-test/tests/51_samba4/10samba-share-options
+++ b/test/ucs-test/tests/51_samba4/10samba-share-options
@@ -1,5 +1,5 @@
 #!/usr/share/ucs-test/runner bash
-## desc: "Checking all udm samba options in samba conf file"
+## desc: "Checking all udm share options in samba conf file"
 ## exposure: safe
 ## packages:
 ##  - univention-config
@@ -69,25 +69,35 @@ available_options="$(udm  shares/share create | grep  --regex "samba\w" | awk  {
 trap 'share_remove "$share_name"' INT TERM EXIT
 
 # create share
-udm shares/share create --position="$SHARE_POSITION" --option samba --set name="$share_name" --set path="/opt" --set host="$fqdn" --set sambaWriteList="workaround for bug #11972" || fail_test 1 "could not create share"
+echo "----create share"
+udm shares/share create --position="$SHARE_POSITION" \
+	--option samba --set name="$share_name" \
+	--set path="/opt" --set host="$fqdn" \
+	--set sambaWriteList="workaround for bug #11972"
+if [ $? != 0 ]; then
+	fail_fast 1 "could not create share"
+fi
 
 
 #waiting for share to be replicated
+echo "----waiting for share to be replicated"
 i=0
 while true
 do
-    let i=$i+1
-    sleep 3
-    if [ -f "$samba_etc/$share_name" ]; then
-	break
-    fi
-    if [ "$i" == 10 ]; then
-	echo "samba config file for share $share_name not found"
-	break
-    fi
+	let i=$i+1
+	sleep 3
+	if [ -f "$samba_etc/$share_name" ]; then
+		break
+	fi
+	if [ "$i" == 10 ]; then
+		echo "samba config file for share $share_name not found"
+		break
+	fi
 done
 
+
 # set samba options via udm and check samba config file
+echo "----set options via udm and check samba config file"
 while read option_line; do
 
 	echo "$option_line" | grep --regex "^\s*#" > /dev/null
@@ -119,13 +129,13 @@ while read option_line; do
 	# samba wants yes or no, that is why we grep for "locking 0" or "locking no"
 	case "$value" in
 		0)
-			s=${search//0/no}
-			search="$search\|$s"
-			;;
+		s="${search//0/no}"
+		search="$search\|$s"
+		;;
 		1)
-			s=${search//1/yes}
-			search="$search\|$s"
-			;;
+		s="${search//1/yes}"
+		search="$search\|$s"
+		;;
 	esac
 
 	# save search string and the rest in $samba_search, we can not perform the search here, because
@@ -134,7 +144,7 @@ while read option_line; do
 		samba_search="${udm_option}:DELIMETER:${search}:DELIMETER:${value}"
 	else
 		samba_search="$samba_search
-		${udm_option}:DELIMETER:${search}:DELIMETER:${value}"
+${udm_option}:DELIMETER:${search}:DELIMETER:${value}"
 	fi
 
 	# clear this options, later we want to check wether we have alle options tested or not
diff --git a/test/ucs-test/tests/51_samba4/40password-policies b/test/ucs-test/tests/51_samba4/40password-policies
--- a/test/ucs-test/tests/51_samba4/40password-policies
+++ b/test/ucs-test/tests/51_samba4/40password-policies
@@ -1,5 +1,5 @@
 #!/usr/share/ucs-test/runner bash
-## desc: "Test whether it works to set a password policy"
+## desc: "Test whether UDM attribute pwdChangeNextLogin is honored"
 ## exposure: safe
 ## packages:
 ##  - univention-samba4
@@ -8,7 +8,7 @@
 . "$TESTLIBPATH/user.sh" || exit 137
 . "$TESTLIBPATH/random.sh" || exit 137
 
-#create user
+## create user
 SAMBA="true"
 MAIL="false"
 KERBEROS="true"
@@ -21,94 +21,82 @@ second_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}ä�
 third_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}äöü)Ui8ÄÖÜ"
 
 trap 'user_remove "$username"' INT TERM EXIT
-user_create "$username" || fail_test 1 "Could not create user $username."
+user_create "$username" || fail_fast 1 "Could not create user $username."
 
-#in case passwort is not the default one
-if [ $(ucr get server/role) == "domaincontroller_master" -a -e /root/root.secret ];then
-    ADMINISTRATOR_PASSWORD="$(cat /root/root.secret)"
-fi
-
-#wait for the user to be created
-#wait for the samba-share.py Listener to synchronize /etc/samba/shares.conf and /etc/samba/shares.conf.d (Bug #29399)
+## wait for the user to be created
+echo "----wait for the user to be created"
 i=0
-while true
+while ! ldbsearch -H ldap://localhost -U "$username%$first_password" "samaccountname=$username" dn | grep -q '^dn:'
 do
-    let i=$i+1
-    sleep 1
-    samba-tool user list | grep "$username" > /dev/null 2>&1 && break
-    if [ $i == 20 ]; then
-	echo "TIMEOUT: The User which has been created in UDM could not be found in samba ldb after $i seconds"
-	break
-    fi
+	let i=$i+1
+	if [ $i = 20 ]; then
+		fail_fast 1 "TIMEOUT: The User which has been created in UDM could not be found in samba ldb after $i seconds"
+	fi
+	sleep 1
 done
 
-ADMINISTRATOR_DN="$(univention-directory-manager users/user list --filter uid="$ADMINISTRATOR_USER" | sed -ne 's/^DN: //p')"
 USER_DN="$(univention-directory-manager users/user list --filter uid="$username" | sed -ne 's/^DN: //p')"
 
-#test normal connection
-ldbsearch -U "$username%$first_password" -H ldap://localhost "cn=$username" > /dev/null || fail_test 1 "initial authentification failed"
-
-whenChanged="$(ldbsearch -H "ldap://localhost" -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" "cn=$username" | grep whenChanged)"
+whenChanged="$(ldbsearch -H /var/lib/samba/private/sam.ldb "samaccountname=$username" whenChanged | sed -ne 's/^whenChanged: //p')"
 
 #set pwdChangeNextLogin=1 so that the user hast to change the password at the next login
-univention-directory-manager users/user modify --binddn "$ADMINISTRATOR_DN" --bindpwd "$ADMINISTRATOR_PASSWORD" --dn "$USER_DN" --set pwdChangeNextLogin=1 || fail_test 1 "Could not modify the user using udm."
+univention-directory-manager users/user modify --dn "$USER_DN" \
+	--set pwdChangeNextLogin=1
+if [ $? != 0 ]; then
+	fail_fast 1 "Could not modify the user using udm."
+fi
 
 #wait until it is recognized in samba that the user has been modified
 i=0
 while true
 do
-    let i=$i+1
-    sleep 1
-    whenChanged2="$(ldbsearch -H "ldap://localhost" -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" "cn=$username" | grep whenChanged)"
-    if [ "$whenChanged" != "$whenChanged2" ]; then
-	break
-    fi
-    if [ $i == 20 ]; then
-	echo "TIMEOUT: A change of the variable pwdChangeNextLogin could not be recognized."
-	break
-    fi
+	whenChanged2="$(ldbsearch -H /var/lib/samba/private/sam.ldb "samaccountname=$username" whenChanged | sed -ne 's/^whenChanged: //p')"
+	if [ "$whenChanged" != "$whenChanged2" ]; then
+		break
+	fi
+	let i=$i+1
+	if [ $i = 20 ]; then
+		echo "TIMEOUT: A change of the variable pwdChangeNextLogin could not be recognized."
+		break
+	fi
+	sleep 1
 done
 
 #try to login without changing the password, should fail
-retval=$(ldbsearch -U "$username%$first_password" -H ldap://localhost "cn=$username" 2>&1)
-echo $retval | grep "NT_STATUS_PASSWORD_MUST_CHANGE" || fail_test 1 "Expected return value \"NT_STATUS_PASSWORD_MUST_CHANGE\", but received $retval"
+echo "-----Log in without changing the password"
+output=$(ldbsearch -U "$username%$first_password" -H ldap://localhost "samaccountname=$username" 2>&1)
+echo "$output" | grep -q "NT_STATUS_PASSWORD_MUST_CHANGE"
+if [ $? != 0 ]; then
+	if [ -n "$output" ]; then
+		echo "$output"
+	fi
+	fail_test 1 'Expected return value "NT_STATUS_PASSWORD_MUST_CHANGE"'
+fi
 
-pwdLastSet=$(ldbsearch -H "ldap://localhost" -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" "cn=$username" | grep pwdLastSet)
-
-#changing the password with samba-tool
+## change the password with samba-tool
+echo "----Changing the password"
 samba-tool user setpassword "$username" --newpassword="$second_password" 
 
-#wait until the password change is recognized by samba
+## login with the new password
+echo "----Checking password: "
 i=0
-while true
+
+while ! smbclient //localhost/netlogon -U "$username%$second_password" -c "exit" > /dev/null
 do
-    let i=$i+1
-    sleep 1
-    ldbsearch -U "$username%$second_password" -H ldap://localhost "cn=$username" > /dev/null && break
-    echo "$i"
-    if [ "$i" == 20 ]; then
-	fail_test 1 "Could not login using samba with new password after password change."
-	break
-    fi
+	let i=$i+1
+	echo '.'
+	if [ "$i" = 20 ]; then
+		fail_test 1 "Could not login using samba with new password after password change."
+		break
+	fi
+	sleep 1
 done
 
-#try to login with old password, should not work                                                                                                       
-ldbsearch -U "$username%$first_password" -H ldap://localhost "cn=$username" > /dev/null && fail_test 1 "Could login using samba with old password after password change."
-
-#--old password
-i=0
-while true
-do
-    let i=$i+1
-    sleep 1
-    /usr/sbin/univention-directory-manager users/user list --binddn "$USER_DN" --bindpwd "$second_password" > /dev/null && break
-    if [ "$i" == 20 ]; then
-	fail_test 1 "Could not login using UDM with new password after password change."
-	break
-    fi
-done
-
-#--new password
-/usr/sbin/univention-directory-manager users/user list --binddn "$USER_DN" --bindpwd "$first_password" > /dev/null && fail_test 1 "Could login using UDM with old password after password change."
+## try to login with old password, should not work                                                                                                       
+output="$(smbclient //localhost/netlogon -U "$username%$first_password" -c "exit" > /dev/null)"
+if [ $? = 0 ]; then
+	echo $output
+	fail_test 1 "Could login using samba with old password after password change."
+fi
 
 exit $RETVAL
diff --git a/test/ucs-test/tests/51_samba4/41password_change b/test/ucs-test/tests/51_samba4/41password_change
--- a/test/ucs-test/tests/51_samba4/41password_change
+++ b/test/ucs-test/tests/51_samba4/41password_change
@@ -24,175 +24,175 @@ third_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}äö
 fourth_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}äöü)z1AÄÖÜ"
 
 min_pwd_age="$(samba-tool domain passwordsettings show | grep "Minimum password age" | sed s/[^0-9]*/""/)"
-samba-tool domain passwordsettings show
-samba-tool domain passwordsettings set --complexity=off
-samba-tool domain passwordsettings set --min-pwd-age=0
-samba-tool domain passwordsettings show
-trap 'user_remove "$username";samba-tool domain passwordsettings set --min-pwd-age=$min_pwd_age;samba-tool domain passwordsettings set --complexity=on' INT TERM EXIT
+samba-tool domain passwordsettings set --complexity=off --min-pwd-age=0
+trap 'user_remove "$username"; samba-tool domain passwordsettings set --min-pwd-age=$min_pwd_age --complexity=on' INT TERM EXIT
 
-user_create "$username" || fail_test 1 "Could not create user $username."
+user_create "$username" || fail_fast 1 "Could not create user $username."
 
 echo "----initial connection"
 #wait for the user to be created
 i=0
-val_ldbsearch=1
-val_kinit=1
-val_udm=1
-while true
+while ! ldbsearch -U "$username%$first_password" -H ldap://localhost "samaccountname=$username" dn 2>&1 | grep -q '^dn:'
 do
-    ldbsearch -U "$username%$first_password" -H ldap://localhost "cn=$username" | grep "$username" > /dev/null && val_ldbsearch=0
-    /usr/sbin/univention-directory-manager users/user list --binddn "$USER_DN" --bindpwd "$first_password" > /dev/null && val_udm=0
-    echo "$first_password" | kinit --password-file=STDIN "$username" > /dev/null && val_kinit=0
-
-    if [ "$i" == 9 -o "$val_ldbsearch" == 0 -a "$val_kinit" == 0 -a "$val_udm" == 0  ]; then
-	echo i="$i"
-	echo "val_ldbsearch $val_ldbsearch"
-	echo "val_udm $val_udm"
-	echo "val_kinit $val_kinit"
-	break
-    fi
-    let i=$i+1
-    sleep 2
+	let i=$i+1
+	if [ "$i" = 10 ]; then
+		fail_fast 1 "Could not authenticate against samba."
+	fi
+	sleep 1
 done
-
-if [ "$val_ldbsearch" != 0 ]; then
-    fail_test 1 "Could not authentificate with samba."
-fi
-if [ "$val_udm" != 0 ]; then
-    fail_test 1 "Could not authentificate with UDM."
-fi
-if [ "$val_kinit" != 0 ]; then
-    fail_test 1 "Could not authentificate with kinit."
-fi
-
-
-USER_DN="$(univention-directory-manager users/user list --filter uid="$username" | sed -ne 's/^DN: //p')"
-
-echo "----password change with samba-tool"
-#--test starting point
-#----password change with samba-tool
-samba-tool user setpassword "$username" --newpassword="$second_password" 
 
 i=0
-val_ldbsearch=1
-val_kinit=1
-val_udm=1
-while true
+while ! echo "$first_password" | kinit --password-file=STDIN "$username" > /dev/null
 do
-    ldbsearch -U "$username%$second_password" -H ldap://localhost "cn=$username" | grep "$username" > /dev/null && val_ldbsearch=0
-    /usr/sbin/univention-directory-manager users/user list --binddn "$USER_DN" --bindpwd "$second_password" > /dev/null && val_udm=0
-    echo "$second_password" | kinit --password-file=STDIN "$username" > /dev/null && val_kinit=0
-
-    if [ "$i" == 9 -o "$val_ldbsearch" == 0 -a "$val_kinit" == 0 -a "$val_udm" == 0  ]; then
-	echo i="$i"
-	echo "val_ldbsearch $val_ldbsearch"
-	echo "val_udm $val_udm"
-	echo "val_kinit $val_kinit"
-	break
-    fi
-    let i=$i+1
-    sleep 2
+	let i=$i+1
+	if [ "$i" = 10 ]; then
+		fail_test 1 "Could not authenticate against kinit."
+		break
+	fi
+	sleep 2
 done
 
-if [ "$val_ldbsearch" != 0 ]; then
-    fail_test 1 "Could not authentificate with samba after password change with samba."
-fi
-if [ "$val_udm" != 0 ]; then
-    fail_test 1 "Could not authentificate with UDM after password change with samba."
-fi
-if [ "$val_kinit" != 0 ]; then
-    fail_test 1 "Could not authentificate with kinit after password change with samba."
-fi
+USER_DN=$(univention-directory-manager users/user list --filter uid="$username" | sed -ne 's/^DN: //p')
 
+
+#--test starting point
+#----password change with samba-tool
+echo "----password change with samba-tool"
+samba-tool user setpassword "$username" --newpassword="$second_password" 
+
+## first check trivial case: Samba4 password must work
+i=0
+while ! ldbsearch -U "$username%$second_password" -H ldap://localhost "samaccountname=$username" dn 2>&1 | grep -q '^dn:'
+do
+	let i=$i+1
+	if [ "$i" = 10 ]; then
+		fail_test 1 "Could not authenticate against samba after password change with samba."
+		break
+	fi
+	sleep 1
+done
+
+## second check complex case: UDM password must work after replication
+i=0
+while ! univention-ldapsearch -x -D "$USER_DN" -w "$second_password" > /dev/null
+do
+	let i=$i+1
+	if [ "$i" = 15 ]; then
+		fail_test 1 "Could not authenticate against UDM after password change with samba."
+		break
+	fi
+	sleep 2
+done
+
+## cross check
+i=0
+while ! echo "$second_password" | kinit --password-file=STDIN "$username" > /dev/null
+do
+	let i=$i+1
+	if [ "$i" = 10 ]; then
+		fail_test 1 "Could not authenticate against kinit after password change with samba."
+		break
+	fi
+	sleep 1
+done
 
 echo "----password change with udm"
 #----password change with udm
-/usr/sbin/univention-directory-manager users/user modify --binddn "$ADMINISTRATOR_DN" --bindpwd "$ADMINISTRATOR_PASSWORD" --dn "$USER_DN" --set "password=$third_password" || fail_test 1 "Could not change password with UDM"
+/usr/sbin/univention-directory-manager users/user modify \
+	--dn "$USER_DN" --set password="$third_password" || fail_fast 1 "Could not change password with UDM"
 
+## first check trivial case: UDM password must work
 i=0
-val_ldbsearch=1
-val_kinit=1
-val_udm=1
-while true
+while ! univention-ldapsearch -x -D "$USER_DN" -w "$third_password" > /dev/null
 do
-    ldbsearch -U "$username%$third_password" -H ldap://localhost "cn=$username" | grep "$username" > /dev/null && val_ldbsearch=0
-    /usr/sbin/univention-directory-manager users/user list --binddn "$USER_DN" --bindpwd "$third_password" > /dev/null && val_udm=0
-    echo "$third_password" | kinit --password-file=STDIN "$username" > /dev/null && val_kinit=0
-
-    if [ "$i" == 9 -o "$val_ldbsearch" == 0 -a "$val_kinit" == 0 -a "$val_udm" == 0  ]; then
-      	echo i="$i"
-	echo "val_ldbsearch $val_ldbsearch"
-	echo "val_udm $val_udm"
-	echo "val_kinit $val_kinit"
-	break
-    fi
-    let i=$i+1
-    sleep 2
+	let i=$i+1
+	if [ "$i" = 10 ]; then
+		fail_test 1 "Could not authenticate against UDM after password change with UDM."
+		break
+	fi
+	sleep 1
 done
 
-if [ "$val_ldbsearch" != 0 ]; then
-    fail_test 1 "Could not authentificate with samba after password change with UDM."
-fi
-if [ "$val_udm" != 0 ]; then
-    fail_test 1 "Could not authentificate with UDM after password change with UDM."
-fi
-if [ "$val_kinit" != 0 ]; then
-    fail_test 1 "Could not authentificate with kinit after password change with UDM."
-fi
+## second check complex case: Samba4 password must work after replication
+i=0
+while ! ldbsearch -U "$username%$third_password" -H ldap://localhost "samaccountname=$username" dn 2>&1 | grep -q '^dn:'
+do
+	let i=$i+1
+	if [ "$i" = 15 ]; then
+		fail_test 1 "Could not authenticate against samba after password change with UDM."
+		break
+	fi
+	sleep 2
+done
 
+## cross check
+i=0
+while ! echo "$third_password" | kinit --password-file=STDIN "$username" > /dev/null
+do
+	let i=$i+1
+	if [ "$i" = 10 ]; then
+		fail_test 1 "Could not authenticate against kinit after password change with UDM."
+		break
+	fi
+	sleep 1
+done
 
-echo "----password change with kpassword"
+echo "----password change with kpasswd"
 #----password change with kpassword
 i=0
 while true
 do
-    if [ $(ucr get server/role) == "domaincontroller_master" -a -e /root/root.secret ];then
-	retval="$(python kpasswd_change_pwd.py -u "$username" -r "$(cat /root/root.secret)" -n "$fourth_password" -p "$third_password" -a "$ADMINISTRATOR_USER")"
-    else
+	## in case passwort is not the default one
+	if [ $(univention-config-registry get server/role) = "domaincontroller_master" -a -e /root/root.secret ];then
+		echo "Found /root/root.secret, using that secret for Administrator access"
+		ADMINISTRATOR_PASSWORD="$(cat /root/root.secret)"
+	fi
+
 	retval="$(python kpasswd_change_pwd.py -u "$username" -r "$ADMINISTRATOR_PASSWORD" -n "$fourth_password" -p "$third_password" -a "$ADMINISTRATOR_USER")"
-    fi
-    echo "$retval"
-    echo "$retval" | grep "nSoft" || break
-    if [ "$i" == 20  ]; then
-	echo "Password change with kpasswd: Soft error."
-	break
-    fi
-    let i=$i+1
-    sleep 5
+	echo "$retval"
+	echo "$retval" | grep "nSoft" || break
+	let i=$i+1
+	if [ "$i" = 20  ]; then
+		echo "Password change with kpasswd: Soft error."
+		break
+	fi
+	sleep 5
 done
-echo "i: $i"
 
+## first check trivial case: Samba4 password must work
 i=0
-val_ldbsearch=1
-val_kinit=1
-val_udm=1
-while true
+while ! ldbsearch -U "$username%$fourth_password" -H ldap://localhost "samaccountname=$username" dn 2>&1 | grep -q '^dn:'
 do
-    ldbsearch -U "$username%$fourth_password" -H ldap://localhost "cn=$username" | grep "$username" > /dev/null && val_ldbsearch=0
-    /usr/sbin/univention-directory-manager users/user list --binddn "$USER_DN" --bindpwd "$fourth_password" > /dev/null && val_udm=0
-    echo "$fourth_password" | kinit --password-file=STDIN "$username" > /dev/null && val_kinit=0
-
-    if [ "$i" == 9 -o "$val_ldbsearch" == 0 -a "$val_kinit" == 0 -a "$val_udm" == 0  ]; then
-	echo i="$i"
-	echo "val_ldbsearch $val_ldbsearch"
-	echo "val_udm $val_udm"
-	echo "val_kinit $val_kinit"
-
-	break
-    fi
-    let i=$i+1
-    sleep 2
+	let i=$i+1
+	if [ "$i" = 10 ]; then
+		fail_test 1 "Could not authenticate against samba after password change with kpasswd."
+		break
+	fi
+	sleep 1
 done
 
-if [ "$val_ldbsearch" != 0 ]; then
-    fail_test 1 "Could not authentificate with samba after password change with kpasswd."
-fi
-if [ "$val_udm" != 0 ]; then
-    fail_test 1 "Could not authentificate with UDM after password change with kpasswd."
-fi
-if [ "$val_kinit" != 0 ]; then
-    fail_test 1 "Could not authentificate with kinit after password change with kpasswd."
-fi
+## second check complex case: UDM password must work after replication
+i=0
+while ! univention-ldapsearch -x -D "$USER_DN" -w "$fourth_password" > /dev/null
+do
+	let i=$i+1
+	if [ "$i" = 15 ]; then
+		fail_test 1 "Could not authenticate against UDM after password change with kpasswd."
+		break
+	fi
+	sleep 2
+done
 
+## cross check
+i=0
+while ! echo "$fourth_password" | kinit --password-file=STDIN "$username" > /dev/null
+do
+	let i=$i+1
+	if [ "$i" = 10 ]; then
+		fail_test 1 "Could not authenticate against kinit after password change with kpasswd."
+		break
+	fi
+	sleep 1
+done
 
 exit $RETVAL
diff --git a/test/ucs-test/tests/51_samba4/43sysvol b/test/ucs-test/tests/51_samba4/43sysvol
--- a/test/ucs-test/tests/51_samba4/43sysvol
+++ b/test/ucs-test/tests/51_samba4/43sysvol
@@ -12,7 +12,8 @@
 . "$TESTLIBPATH/shares.sh" || exit 137
 . "$TESTLIBPATH/random.sh" || exit 137
 
-#----create User
+##create User
+echo "----create User"
 SAMBA="true"
 MAIL="false"
 KERBEROS="true"
@@ -23,33 +24,49 @@ username="$(user_randomname)"
 password=univention
 
 trap 'user_remove "$username"' INT TERM EXIT
-user_create "$username" || fail_test 1 "Could not create user $username."
+user_create "$username" || fail_fast 1 "Could not create user $username."
 
-#waiting for user and share to be created
+##waiting for user and share to be created
 i=0
 while true
 do
-    let i=$i+1
-    sleep 3
-    ldbsearch -H "ldap://localhost" -U"$username%$password" "cn=$username" | grep dn: && break
-    if [ "$i" == 10 ]; then
-	echo "TIMEOUT: The user or share could not be found in samba ldb"
-	break
-    fi
+	let i=$i+1
+	sleep 3
+	ldbsearch -H ldap://localhost -U"$username%$password" "cn=$username" | grep dn: && break
+	if [ "$i" = 10 ]; then
+		echo "TIMEOUT: The user or share could not be found in samba ldb"
+		break
+	fi
 done
 
-
-#Put a file on sysvol as Administrator
-if [ $(ucr get server/role) == "domaincontroller_master" -a -e /root/root.secret ];then
-    smbclient //localhost/sysvol -U"$ADMINISTRATOR_USER%$(cat /root/root.secret)" -c "put /etc/hosts $domainname/t1" || fail_test 1 "Could not put file on sysvol as Administrator"
-    echo secret
-else 
-    smbclient //localhost/sysvol -U"$ADMINISTRATOR_USER%univention" -c "put /etc/hosts $domainname/t1" || fail_test 1 "Could not put file on sysvol as Administrator"
-    echo normale
+## in case password is not the default one
+if [ $(univention-config-registry get server/role) = "domaincontroller_master" -a -e /root/root.secret ];then
+	echo "Found /root/root.secret, using that secret for Administrator access"
+	ADMINISTRATOR_PASSWORD="$(cat /root/root.secret)"
 fi
-#Access the folder Policies on sysvol as a user
-smbclient //localhost/sysvol -U"$username%$password" -c "ls $domainname/Policies" || fail_test 1 "Could not access Policies on sysvol as a user"
-#Put a file in the folder Policies on sysvol as a user
-smbclient //localhost/sysvol -U"$username%$password" -c "put /etc/hosts $domainname/t1" && fail_test 1 "Successfully put a file on sysvol as a user"
+
+##Put a file on sysvol as Administrator
+echo "----Put a file on sysvol as Administrator"
+output="$(smbclient //localhost/sysvol -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" -c "put /etc/hosts $domainname/t1" 2>&1)"
+if [ $? != 0 ]; then
+	echo "$output"
+	fail_test 1 "Could not put file on sysvol as Administrator"
+fi
+
+echo "----Access the folder Policies on sysvol as a user"
+##Access the folder Policies on sysvol as a user
+output="$(smbclient //localhost/sysvol -U"$username%$password" -c "ls $domainname/Policies" 2>&1)"
+if [ $? != 0 ]; then
+	echo "$output"
+	fail_test 1 "Could not access Policies on sysvol as a user"
+fi
+
+echo "----Put a file in the folder Policies on sysvol as a user"
+##Put a file in the folder Policies on sysvol as a user
+output="$(smbclient //localhost/sysvol -U"$username%$password" -c "put /etc/hosts $domainname/t1"  2>&1)"
+if [ $? = 0 ]; then
+	echo "$output"
+	fail_test 1 "Successfully put a file on sysvol as a user"
+fi
 
 exit $RETVAL
diff --git a/test/ucs-test/tests/51_samba4/51create_gpo b/test/ucs-test/tests/51_samba4/51create_gpo
--- a/test/ucs-test/tests/51_samba4/51create_gpo
+++ b/test/ucs-test/tests/51_samba4/51create_gpo
@@ -11,72 +11,84 @@
 . "$TESTLIBPATH/shares.sh" || exit 137
 . "$TESTLIBPATH/random.sh" || exit 137
 
-#----create User
+##----create User
 SAMBA="true"
 MAIL="false"
 KERBEROS="true"
 PERSON="false"
 POSIX="true"
 
-gponame="$(user_randomname)"
+gponame=$(random_chars 8 "${_upperletters}${_lowerletters}${_ciphers}")	## samba RC6 seems to dislike UTF-8 in GPO names
 echo gponame "$gponame"
-#in case password is not the default one
-if [ $(ucr get server/role) == "domaincontroller_master" -a -e /root/root.secret ];then
+## in case password is not the default one
+if [ $(univention-config-registry get server/role) = "domaincontroller_master" -a -e /root/root.secret ];then
+	echo "Found /root/root.secret, using that secret for Administrator access"
     ADMINISTRATOR_PASSWORD="$(cat /root/root.secret)"
 fi
 
-trap 'samba-tool gpo del "$cn" -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD"' INT TERM EXIT
-
-#wait for the samba-share.py Listener to synchronize /etc/samba/shares.conf and /etc/samba/shares.conf.d (Bug #29399)
+## general sanity check: wait for the samba-share.py Listener to synchronize /etc/samba/shares.conf and /etc/samba/shares.conf.d (Bug #29399)
 i=0
-while true
+while ! samba-tool domain info 127.0.0.1 > /dev/null 2>&1
 do
-    let i=$i+1
-    sleep 1
-    samba-tool user list > /dev/null 2>&1 && break
-    if [ $i == 20 ]; then
-	echo "samba-tool Failure (Bug #29399)" >&2
-	break
-    fi
+	let i=$i+1
+	if [ $i = 15 ]; then
+		echo "samba-tool Failure (Bug #29399)" >&2
+		break
+	fi
+	sleep 2
 done
 
+## create the GPO
+echo "----create the GPO"
+gpo_cn=$(samba-tool gpo create "$gponame" -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" | sed -n "s/GPO '$gponame' created as //p")
+if [ -n "$gpo_cn" ]; then
+	trap 'samba-tool gpo del "$gpo_cn" -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD"' INT TERM EXIT
+else
+	fail_fast 1 "WARNING: samba-tool gpo create did not return a GPO cn"
+fi
 
-#create the GPO
-samba-tool gpo create "$gponame" -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" || echo "WARNING: samba-tool gpo create returned an exit status !=0 but the GPO may be created anyway"
-/usr/share/univention-samba4/scripts/sysvol-sync.sh
-#--local tests
+
+## --local tests
+echo "----search sam.ldb for GPO"
 i=0
-val_s4search=1
-val_sambatool=1
-val_dir=1
+
 while true
 do
-    cn="$(univention-s4search -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" "displayName=$gponame" | grep cn: | sed -ne 's/^cn: //p')" 
-    if [ "$?" == 0 -a -n "$cn" ]; then
-	val_s4search=0
-	ls "/var/lib/samba/sysvol/$domainname/Policies/$cn" > /dev/null 2>&1 && val_dir=0
-	samba-tool gpo listall | grep "$cn" > /dev/null && val_sambatool=0
-    fi
-    if [ "$i" == 20 -o "$val_s4search" == 0 -a "$val_sambatool" == 0 -a "$val_dir" == 0  ]; then
-	break
-    fi
-    let i=$i+1
-    sleep 3
+	displayName=$(ldbsearch -H /var/lib/samba/private/sam.ldb "(&(objectClass=groupPolicyContainer)(cn=$gpo_cn))" displayName | sed -ne 's/^displayName: //p')
+	if [ -n "$displayName" ]; then
+		break
+	fi
+
+	let i=$i+1
+	if [ "$i" = 20 ]; then
+		fail_fast 1 "Could not find displayName of GPO in sam.ldb"
+	fi
+	sleep 1
 done
 
-if [ "$val_s4search" != 0 ]; then
-    fail_test 1 "Could not find GPO with univention-s4search"
-fi
-if [ "$val_dir" != 0 ]; then
-    fail_test 1 "Directory for GPO has not been created"
-fi
-if [ "$val_sambatool" != 0 ]; then
-    fail_test 1 "GPO is not listed in samba-tool"
-fi
+echo "----check whether the directory for the GPO has been created"
+i=0
+while ! [ -d "/var/lib/samba/sysvol/$domainname/Policies/$gpo_cn" ]
+do
+	let i=$i+1
+	if [ "$i" = 20 ]; then
+		fail_fast 1 "Directory for GPO has not been created"
+	fi
+	sleep 1
+done
 
-echo "val_s4search: $val_s4search"
-echo "val_dir: $val_dir"
-echo "val_sambatool: $val_sambatool"
-
+echo "----check whether the GPO is listed in samba-tool"
+i=0
+while ! ( output=$(samba-tool gpo show "$gpo_cn") && grep -Eq "^GPO\s+:\s$gpo_cn" <<<"$output" > /dev/null )
+do
+	let i=$i+1
+	if [ "$i" = 10 ]; then
+		if [ -n "$output" ]; then
+			echo "$output"
+		fi
+		fail_fast 1 "GPO is not listed in samba-tool"
+	fi
+	sleep 1
+done
 
 exit $RETVAL
diff --git a/test/ucs-test/tests/51_samba4/52replication_sysvol b/test/ucs-test/tests/51_samba4/52replication_sysvol
--- a/test/ucs-test/tests/51_samba4/52replication_sysvol
+++ b/test/ucs-test/tests/51_samba4/52replication_sysvol
@@ -18,136 +18,120 @@ KERBEROS="true"
 PERSON="false"
 POSIX="true"
 
-saveIFS=$IFS
-IFS=$'\n'
-s4hosts=( $(ldapsearch -x -ZZ -LLL -D "$ldap_hostdn" -y /etc/machine.secret "(univentionService=Samba 4)" cn | grep "cn:" | sed -ne 's/^cn: //p') )
-for s4host_temp in ${s4hosts[@]}
+s4hosts=( $(univention-ldapsearch -xLLL "(univentionService=Samba 4)" cn | sed -ne 's/^cn: //p') )
+for s4host_temp in "${s4hosts[@]}"
 do
     ping -c 1 "$s4host_temp.$domainname" > /dev/null
-    if [ "$?" == 0 -a "$s4host_temp" != "$hostname" ]; then
+    if [ "$?" = 0 -a "$s4host_temp" != "$hostname" ]; then
 	s4host=$s4host_temp
 	break	
 
     fi
 done
-IFS=$saveIFS
+
 echo "HOSTNAME:$s4host"
 if [ -z "$s4host" ];then
     fail_fast 77 "Could not find another Samba4 Service in Domain"
 fi
 
 
-gponame="$(user_randomname)"
+gponame=$(random_chars 8 "${_upperletters}${_lowerletters}${_ciphers}")	## samba RC6 seems to dislike UTF-8 in GPO names
 echo gponame "$gponame"
 #in case passwort is not the default one
-if [ $(ucr get server/role) == "domaincontroller_master" -a -e /root/root.secret ];then
+if [ $(univention-config-registry get server/role) = "domaincontroller_master" -a -e /root/root.secret ];then
+	echo "Found /root/root.secret, using that secret for Administrator access"
     ADMINISTRATOR_PASSWORD="$(cat /root/root.secret)"
 fi
 
-#wait for the samba-share.py Listener to synchronize /etc/samba/shares.conf and /etc/samba/shares.conf.d (Bug #29399)
+## general sanity check: wait for the samba-share.py Listener to synchronize /etc/samba/shares.conf and /etc/samba/shares.conf.d (Bug #29399)
 i=0
-while true
+while ! samba-tool domain info 127.0.0.1 > /dev/null 2>&1
 do
-    let i=$i+1
-    sleep 1
-    samba-tool user list > /dev/null 2>&1 && break
-    if [ $i == 20 ]; then
-	echo "samba-tool Failure (Bug #29399)" >&2
-	break
-    fi
+	let i=$i+1
+	if [ $i = 15 ]; then
+		echo "samba-tool Failure (Bug #29399)" >&2
+		break
+	fi
+	sleep 2
 done
 
 
-trap 'samba-tool gpo del "$cn" -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD"' INT TERM EXIT
-#create the GPO
-samba-tool gpo create "$gponame" -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" || echo "WARNING: samba-tool gpo create returned an exit status !=0 but the GPO may be created anyway"
-#--local tests
-echo "Testing... fails after 300 seconds"
+## create the GPO
+echo "----create the GPO"
+gpo_cn=$(samba-tool gpo create "$gponame" -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" | sed -n "s/GPO '$gponame' created as //p")
+if [ -n "$gpo_cn" ]; then
+	trap 'samba-tool gpo del "$gpo_cn" -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD"' INT TERM EXIT
+else
+	fail_fast 1 "WARNING: samba-tool gpo create did not return a GPO cn"
+fi
+
+## --local tests
 i=0
-val_s4search=1
-val_sambatool=1
-val_dir=1
+echo "----search sam.ldb for GPO"
 while true
 do
-    cn="$(univention-s4search -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" "displayName=$gponame" | grep cn: | sed -ne 's/^cn: //p')" 
-    if [ "$?" == 0 -a -n "$cn" ]; then
-	val_s4search=0
-	ls "/var/lib/samba/sysvol/$domainname/Policies/$cn" > /dev/null 2>&1 && val_dir=0
-	samba-tool gpo listall | grep "$cn" > /dev/null && val_sambatool=0
-    fi
+	displayName=$(ldbsearch -H /var/lib/samba/private/sam.ldb "(&(objectClass=groupPolicyContainer)(cn=$gpo_cn))" displayName | sed -ne 's/^displayName: //p')
+	if [ -n "$displayName" ]; then
+		break
+	fi
 
-    if [ "$i" == 100 -o "$val_s4search" == 0 -a "$val_sambatool" == 0 -a "$val_dir" == 0  ]; then
-	echo "BREAK: $i"
-	break
-    fi
-    let i=$i+1
-    sleep 3
+	let i=$i+1
+	if [ "$i" = 20 ]; then
+		fail_fast 1 "Could not find displayName of GPO in sam.ldb"
+	fi
+	sleep 1
 done
-echo "val_s4search: $val_s4search"
-echo "val_dir: $val_dir"
-echo "val_sambatool: $val_sambatool"
 
-
-#tests on other DC
-echo "Testing... fails after 300 seconds"
+echo "----check whether the directory for the GPO hast been created"
 i=0
-val_s4search_remote=1
-val_sambatool_remote=1
-val_dir_remote=1
-while true
+while ! [ -d "/var/lib/samba/sysvol/$domainname/Policies/$gpo_cn" ]
 do
-    cn="$(echo "$BINDPWD" | univention-ssh /dev/stdin root@"$s4host.$domainname" univention-s4search -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" "displayName=$gponame" | grep cn: | sed -ne 's/^cn: //p')" 
-    if [ "$?" == 0 -a -n "$cn" ]; then
-	val_s4search_remote=0
-	echo "$BINDPWD" | univention-ssh /dev/stdin root@"$s4host.$domainname"	ls "/var/lib/samba/sysvol/$domainname/Policies/$cn" > /dev/null 2>&1 && val_dir_remote=0
-	echo "$BINDPWD" | univention-ssh /dev/stdin root@"$s4host.$domainname"	samba-tool gpo listall | grep "$cn" > /dev/null && val_sambatool_remote=0
-    fi
-
-    if [ "$i" == 100 -o "$val_s4search_remote" == 0 -a "$val_sambatool_remote" == 0 -a "$val_dir_remote" == 0  ]; then
-	echo "BREAK: $i"
-	break
-    fi
-    let i=$i+1
-    sleep 3
+	let i=$i+1
+	if [ "$i" = 20 ]; then
+		fail_fast 1 "Directory for GPO has not been created"
+	fi
+	sleep 1
 done
 
+echo "----check whether the GPO is listed in samba-tool"
+i=0
+while ! ( output=$(samba-tool gpo show "$gpo_cn") && grep -Eq "^GPO\s+:\s$gpo_cn" <<<"$output" > /dev/null )
+do
+	let i=$i+1
+	if [ "$i" = 10 ]; then
+		if [ -n "$output" ]; then
+			echo "$output"
+		fi
+		fail_fast 1 "GPO is not listed in samba-tool"
+	fi
+	sleep 1
+done
 
-#check local tests again, including the time used for the remote tests
-cn="$(univention-s4search -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" "displayName=$gponame" | grep cn: | sed -ne 's/^cn: //p')" 
-if [ "$?" == 0 -a -n "$cn" ]; then
-    val_s4search=0
-    ls "/var/lib/samba/sysvol/$domainname/Policies/$cn" > /dev/null 2>&1 && val_dir=0
-    samba-tool gpo listall | grep "$cn" > /dev/null && val_sambatool=0
-fi
+## Tests on remote DC
+echo "----check whether the directory has been replicated to another s4host"
+i=0
+while ! echo "$BINDPWD" | univention-ssh /dev/stdin root@"$s4host.$domainname" test -d "/var/lib/samba/sysvol/$domainname/Policies/$gpo_cn" > /dev/null
+do
+	let i=$i+1
+	if [ "$i" =  300 ]; then
+		fail_fast 1 "remote directory for GPO has not been created"
+	fi
+	sleep 3
+done
 
-#check local result
-if [ "$val_s4search" != 0 ]; then
-    fail_test 1 "Could not find GPO with univention-s4search"
-fi
-if [ "$val_dir" != 0 ]; then
-    fail_test 1 "Directory for GPO has not been created"
-fi
-if [ "$val_sambatool" != 0 ]; then
-    fail_test 1 "GPO is not listed in samba-tool"
-fi
+echo "----check whether samba-tool lists the GPO on another s4host."
+i=0
+while ! ( output=$(echo "$BINDPWD" | univention-ssh /dev/stdin root@"$s4host.$domainname" samba-tool gpo show "$gpo_cn") && grep -Eq "^GPO\s+:\s$gpo_cn" <<<"$output" > /dev/null )
+do
+	let i=$i+1
+	if [ "$i" = 10 ]; then
+		if [ -n "$output" ]; then
+			echo "$output"
+		fi
+		fail_fast 1 "remote GPO is not listed in samba-tool"
+	fi
+	sleep 1
+done
 
-#check remote result
-if [ "$val_s4search_remote" != 0 ]; then
-    fail_test 1 "Could not find GPO with univention-s4search on remote host"
-fi
-if [ "$val_dir_remote" != 0 ]; then
-    fail_test 1 "Directory for GPO has not been created on remote host"
-fi
-if [ "$val_sambatool_remote" != 0 ]; then
-    fail_test 1 "GPO is not listed in samba-tool on remote host"
-fi
-
-echo "val_s4search: $val_s4search"
-echo "val_dir: $val_dir"
-echo "val_sambatool: $val_sambatool"
-
-echo "val_s4search_remote: $val_s4search_remote"
-echo "val_dir_remote: $val_dir_remote"
-echo "val_sambatool_remote: $val_sambatool_remote"
 
 exit $RETVAL
