refactor(test): 51_samba4/40password-policies
Change `exposure` to `careful` as test is creating a user with a known
password.

Bug #29063

diff --git a/test/ucs-test/tests/51_samba4/40password-policies b/test/ucs-test/tests/51_samba4/40password-policies
--- a/test/ucs-test/tests/51_samba4/40password-policies
+++ b/test/ucs-test/tests/51_samba4/40password-policies
@@ -1,13 +1,14 @@
 #!/usr/share/ucs-test/runner bash
 # shellcheck shell=bash
 ## desc: "Test whether UDM attribute pwdChangeNextLogin is honored"
-## exposure: safe
+## exposure: careful
 ## packages:
 ##  - univention-samba4
 ## roles:
 ## - domaincontroller_master
 ## - domaincontroller_backup
 ## - domaincontroller_slave
+
 # shellcheck source=../../lib/user.sh
 . "$TESTLIBPATH/user.sh" || exit 137
 # shellcheck source=../../lib/random.sh
@@ -30,9 +31,8 @@ third_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}äö
 
 trap 'user_remove "$username"' INT TERM EXIT
 
-if ! user_create "$username"; then
+user_create "$username" ||
 	fail_fast 1 "User could not be created"
-fi
 
 wait_for_replication
 # force_drs_replication
@@ -40,41 +40,30 @@ wait_for_drs_replication "(sAMAccountName=$username)"
 
 USER_DN="$(udm-test users/user list --filter uid="$username" | sed -ne 's/^DN: //p')"
 
-whenChanged="$(ldbsearch -H /var/lib/samba/private/sam.ldb "samaccountname=$username" whenChanged | sed -ne 's/^whenChanged: //p')"
-whenChanged2="$whenChanged"
+get_changed () {
+	ldbsearch -H /var/lib/samba/private/sam.ldb "samaccountname=$username" whenChanged | sed -ne 's/^whenChanged: //p'
+}
+whenChanged="$(get_changed)"
 
 ##set pwdChangeNextLogin=1 so that the user hast to change the password at the next login
 echo "----set pwdChangeNextLogin=1"
-output="$(udm-test users/user modify --dn "$USER_DN" --set pwdChangeNextLogin=1)"
-if [ "$?" != 0 ];then
-	echo "$output"
-	fail_test 1 "Could not modify the user using udm."
-fi
+output="$(udm-test users/user modify --dn "$USER_DN" --set pwdChangeNextLogin=1)" ||
+	fail_test 1 "Could not modify the user using UDM: $output"
 
-#wait until it is recognized in samba that the user has been modified
-echo "----wait until it is recognized in samba that the user has been modified"
-i=0
-while [ "$whenChanged" = "$whenChanged2" ]
-do
-	whenChanged2="$(ldbsearch -H /var/lib/samba/private/sam.ldb "samaccountname=$username" whenChanged | sed -ne 's/^whenChanged: //p')"
-	let i="$i"+1
-	if [ "$i" = $DRS_REPLICATION_TIMEOUT ]; then
-		echo "TIMEOUT: A change of the variable pwdChangeNextLogin could not be recognized."
-		break
-	fi
-	sleep 1
-done
+echo "----wait until it is recognized in Samba that the user has been modified"
+wait_for_changed () {
+	local current
+	current="$(get_changed)"
+	[ "$current" != "$whenChanged" ]
+}
+retry "$DRS_REPLICATION_TIMEOUT" wait_for_changed ||
+	echo "TIMEOUT: A change of the variable pwdChangeNextLogin could not be recognized."
 
 #try to login without changing the password, should fail
 echo "-----Log in without changing the password"
 output="$(ldbsearch -U "$username%$first_password" -H ldap://localhost "samaccountname=$username" 2>&1)"
-echo "$output" | grep -q "LDAP_INVALID_CREDENTIALS"
-if [ "$?" != 0 ]; then
-	if [ -n "$output" ]; then
-		echo "$output"
-	fi
-	fail_test 1 'Expected return value "LDAP_INVALID_CREDENTIALS"'
-fi
+echo "$output" | grep -q "LDAP_INVALID_CREDENTIALS" ||
+	fail_test 1 "Expected return value \"LDAP_INVALID_CREDENTIALS\": $output"
 
 ## change the password with samba-tool
 echo "----Changing the password"
@@ -82,16 +71,8 @@ samba-tool user setpassword "$username" --newpassword="$second_password"
 
 ## login with the new password
 echo "----Checking new password: "
-i=0
-while ! smbclient //localhost/netlogon -U "$username%$second_password" -c "exit" > /dev/null
-do
-	i=$((i+1))
-	echo '.'
-	if [ "$i" = $DRS_REPLICATION_TIMEOUT ]; then
-		fail_fast 1 "Could not login using samba with new password after password change."
-	fi
-	sleep 1
-done
+retry "$DRS_REPLICATION_TIMEOUT" smbclient //localhost/netlogon -U "$username%$second_password" -c "exit" >/dev/null ||
+	fail_fast 1 "Could not login using samba with new password after password change."
 
 ## The behavior of NTLM authentication differs depending on password history
 ## See http://support.microsoft.com/kb/906305
@@ -103,19 +84,13 @@ echo "----old_password_allowed_period is $old_password_allowed_period"
 if [ "$pwdHistoryLength" = "0" ] || [ "$old_password_allowed_period" = "0" ]; then
 	echo "----Trying previous password (should not work): "
 	## try to login with previous password, should not work
-	output="$(smbclient //localhost/netlogon -U "$username%$first_password" -c "exit" > /dev/null)"
-	if [ "$?" = 0 ]; then
-		echo "$output"
-		fail_test 1 "Could login using samba with old password after password change."
-	fi
+	output="$(smbclient //localhost/netlogon -U "$username%$first_password" -c "exit" >/dev/null)" &&
+		fail_test 1 "Could login using samba with old password after password change: $output"
 else
 	echo "----Trying previous password (should work due to grace period): "
 	## try to login with previous password, should work for $old_password_allowed_period minutes
-	output="$(smbclient //localhost/netlogon -U "$username%$first_password" -c "exit" > /dev/null)"
-	if ! [ "$?" = 0 ]; then
-		echo "$output"
-		fail_test 1 "Could not login using samba with old password after password change during grace period."
-	fi
+	output="$(smbclient //localhost/netlogon -U "$username%$first_password" -c "exit" >/dev/null)" &&
+		fail_test 1 "Could not login using samba with old password after password change during grace period: $output"
 
 	## change the password again with samba-tool
 	echo "----Changing the password again to check grace period with password history"
@@ -123,32 +98,18 @@ else
 
 	## login with the new password
 	echo "----Checking new password again: "
-	i=0
-	while ! smbclient //localhost/netlogon -U "$username%$third_password" -c "exit" > /dev/null
-	do
-		i=$((i+1))
-		echo '.'
-		if [ "$i" = $DRS_REPLICATION_TIMEOUT ]; then
-			fail_fast 1 "Could not login using samba with new password after password change."
-		fi
-		sleep 1
-	done
+	retry "$DRS_REPLICATION_TIMEOUT" smbclient //localhost/netlogon -U "$username%$third_password" -c "exit" >/dev/null ||
+		fail_fast 1 "Could not login using samba with new password after password change."
 
 	echo "----Trying previous password (should work due to grace period): "
 	## try to login with previous password
-	output="$(smbclient //localhost/netlogon -U "$username%$second_password" -c "exit" > /dev/null)"
-	if ! [ "$?" = 0 ]; then
-		echo "$output"
-		fail_test 1 "Could not login using samba with previous password after password change during grace period."
-	fi
+	output="$(smbclient //localhost/netlogon -U "$username%$second_password" -c "exit" >/dev/null)" &&
+		fail_test 1 "Could not login using samba with previous password after password change during grace period: $output"
 
 	echo "----Trying initial password (should not work): "
 	## try to login with initial password
-	output="$(smbclient //localhost/netlogon -U "$username%$first_password" -c "exit" > /dev/null)"
-	if [ "$?" = 0 ]; then
-		echo "$output"
-		fail_test 1 "Could login using samba with initial password after password change."
-	fi
+	output="$(smbclient //localhost/netlogon -U "$username%$first_password" -c "exit" >/dev/null)" &&
+		fail_test 1 "Could login using samba with initial password after password change: $output"
 fi
 
-exit $RETVAL
+exit "$RETVAL"
