* improved stability of 51_samba4/41password_change (Bug #29057)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@37471 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/51_samba4/41password_change b/test/ucs-test/tests/51_samba4/41password_change
--- a/test/ucs-test/tests/51_samba4/41password_change
+++ b/test/ucs-test/tests/51_samba4/41password_change
@@ -138,14 +138,26 @@ if [ "$val_kinit" != 0 ]; then
     fail_test 1 "Could not authentificate with kinit after password change with UDM."
 fi
 
-sleep 20
+
 echo "----password change with kpassword"
 #----password change with kpassword
-if [ $(ucr get server/role) == "domaincontroller_master" -a -e /root/root.secret ];then
-    python kpasswd_change_pwd.py -u "$username" -r "$(cat /root/root.secret)" -n "$fourth_password" -p "$third_password" -a "$ADMINISTRATOR_USER"
-else
-    python kpasswd_change_pwd.py -u "$username" -r "$ADMINISTRATOR_PASSWORD" -n "$fourth_password" -p "$third_password" -a "$ADMINISTRATOR_USER"
-fi
+i=0
+while true
+do
+    if [ $(ucr get server/role) == "domaincontroller_master" -a -e /root/root.secret ];then
+	retval="$(python kpasswd_change_pwd.py -u "$username" -r "$(cat /root/root.secret)" -n "$fourth_password" -p "$third_password" -a "$ADMINISTRATOR_USER")"
+    else
+	retval="$(python kpasswd_change_pwd.py -u "$username" -r "$ADMINISTRATOR_PASSWORD" -n "$fourth_password" -p "$third_password" -a "$ADMINISTRATOR_USER")"
+    fi
+    echo "$retval"
+    echo "$retval" | grep "nSoft" || break
+    if [ "$i" == 5  ]; then
+	echo "Password change with kpasswd: Soft error."
+	break
+    fi
+    let i=$i+1
+done
+echo "i: $i"
 
 i=0
 val_ldbsearch=1
