* Fix 41samba-tool_user_password_change (Bug #34447) * Don't modifiy samba password policy settings in 41samba-tool_user_* * force_drs_replication: NOP if destination == source
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.2/ucs-3.2-1@49123 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/51_samba4/41samba-tool_user_password_change b/test/ucs-test/tests/51_samba4/41samba-tool_user_password_change
--- a/test/ucs-test/tests/51_samba4/41samba-tool_user_password_change
+++ b/test/ucs-test/tests/51_samba4/41samba-tool_user_password_change
@@ -28,17 +28,17 @@ third_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}äö
 check_domainadmin_credentials || fail_fast 77 "UCR variables for admin credentials are not set"
 ADMINISTRATOR_NAME="$(univention-ldapsearch -b "$tests_domainadmin_account" uid | grep uid | sed -ne 's/^uid: //p')"
 
-min_pwd_age="$(samba-tool domain passwordsettings show | grep "Minimum password age" | sed s/[^0-9]*/""/)"
-pwd_complexity="$(samba-tool domain passwordsettings show | grep complexity | sed "s/Password complexity: //")"
-samba-tool domain passwordsettings set --complexity=off --min-pwd-age=0
-trap 'user_remove "$username"; samba-tool domain passwordsettings set --min-pwd-age="$min_pwd_age" --complexity="$pwd_complexity"' INT TERM EXIT
+# min_pwd_age="$(samba-tool domain passwordsettings show | grep "Minimum password age" | sed s/[^0-9]*/""/)"
+# pwd_complexity="$(samba-tool domain passwordsettings show | grep complexity | sed "s/Password complexity: //")"
+# samba-tool domain passwordsettings set --complexity=off --min-pwd-age=0
+# trap 'user_remove "$username"; samba-tool domain passwordsettings set --min-pwd-age="$min_pwd_age" --complexity="$pwd_complexity"' INT TERM EXIT
+trap 'user_remove "$username"' INT TERM EXIT
 
 if ! user_create "$username"; then
 	fail_fast 1 "User could not be created"
 fi
 
 wait_for_replication
-# force_drs_replication
 wait_for_drs_replication "(sAMAccountName=$username)"
 
 max_i=10
@@ -63,7 +63,12 @@ sleep 10	## workaround for S4-Connector race
 #--test starting point
 #----password change with samba-tool
 echo "----password change with samba-tool"
+sambaPwdLastSet="$(univention-ldapsearch -x -b "$USER_DN" sambaPwdLastSet | sed -n 's/^sambaPwdLastSet: //p')"
 samba-tool user password -U"$username" --password="$first_password" --newpassword="$second_password" 
+echo "Setting new password: $second_password"
+if ! [ $? -eq 0 ]; then
+	fail_fast 1 "Password change with samba-tool failed"
+fi
 
 force_drs_replication -o
 
@@ -87,6 +92,23 @@ if [ "$i" -ne "$max_i" ]; then
 	echo "Authentication against samba after password change with samba succeeded at attempt $((i+1))."
 fi
 
+max_i=15
+delta_t=2
+i=0
+while [ "$(univention-ldapsearch -x -b "$USER_DN" sambaPwdLastSet | sed -n 's/^sambaPwdLastSet: //p')" == "$sambaPwdLastSet" ]; do
+	let i="$i"+1
+	if [ "$i" = "$max_i" ]; then
+		echo "sambaPwdLastSet did not change in UDM after $i attempts."
+		if output="$(univention-ldapsearch -x -D "$USER_DN" -w "$first_password" -b "$USER_DN" dn 2>&1 )"; then
+			echo "FAIL: Previous password still valid in LDAP"
+		fi
+		break
+	fi
+	sleep "$delta_t"
+done
+if [ "$i" -ne "$max_i" ]; then
+	echo "sambaPwdLastSet change check succeeded at attempt $((i+1))."
+fi
 
 ## second check complex case: UDM password must work after replication
 max_i=60
@@ -124,8 +146,11 @@ if [ "$i" -ne "$max_i" ]; then
 	echo "Authentication against kinit after password change with samba succeeded at attempt $((i+1))."
 fi
 
+sleep 10	## workaround for S4-Connector race
+
 echo "----password change with kpasswd"
 #----password change with kpassword
+sambaPwdLastSet="$(univention-ldapsearch -x -b "$USER_DN" sambaPwdLastSet | sed -n 's/^sambaPwdLastSet: //p')"
 max_i=20
 delta_t=5
 i=0
@@ -140,8 +165,7 @@ do
 	fi
 	sleep "$delta_t"
 done
-
-samba-tool domain passwordsettings show
+echo "Setting new password: $third_password"
 
 ## first check trivial case: Samba4 password must work
 max_i=10
@@ -163,6 +187,21 @@ if [ "$i" -ne "$max_i" ]; then
 	echo "Authentication against samba after password change with kpasswd succeeded at attempt $((i+1))."
 fi
 
+max_i=15
+delta_t=2
+i=0
+while [ "$(univention-ldapsearch -x -b "$USER_DN" sambaPwdLastSet | sed -n 's/^sambaPwdLastSet: //p')" == "$sambaPwdLastSet" ]; do
+	let i="$i"+1
+	if [ "$i" = "$max_i" ]; then
+		echo "sambaPwdLastSet did not change in UDM after $i attempts."
+		break
+	fi
+	sleep "$delta_t"
+done
+if [ "$i" -ne "$max_i" ]; then
+	echo "sambaPwdLastSet change check succeeded at attempt $((i+1))."
+fi
+
 ## second check complex case: UDM password must work after replication
 max_i=15
 delta_t=2
@@ -173,6 +212,9 @@ do
 	if [ "$i" = "$max_i" ]; then
 		echo "$output"
 		fail_test 1 "Could not authenticate against UDM after password change with kpasswd after $i attempts."
+		if output="$(univention-ldapsearch -x -D "$USER_DN" -w "$second_password" -b "$USER_DN" dn 2>&1 )"; then
+			echo "FAIL: Previous password still valid in LDAP"
+		fi
 		break
 	fi
 	sleep "$delta_t"
