refactor(test): 51_samba4/41samba-tool_user_setpassword
Change `exposure` to `careful` as test is creating a user with a known
password.

Bug #29063

diff --git a/test/ucs-test/tests/51_samba4/41samba-tool_user_setpassword b/test/ucs-test/tests/51_samba4/41samba-tool_user_setpassword
--- a/test/ucs-test/tests/51_samba4/41samba-tool_user_setpassword
+++ b/test/ucs-test/tests/51_samba4/41samba-tool_user_setpassword
@@ -1,7 +1,7 @@
 #!/usr/share/ucs-test/runner bash
-# shellcheck shell=bash
-## desc: "Administrative setting of user passwords with udm, samba and kerberos"
-## exposure: safe
+# shellcheck shell=bash disable=SC2015
+## desc: "Administrative setting of user passwords with UDM, Samba and kerberos"
+## exposure: careful
 ## packages:
 ##  - univention-samba4
 ## roles:
@@ -9,6 +9,9 @@
 ## - domaincontroller_backup
 ## - domaincontroller_slave
 ## tags: [SKIP-UCSSCHOOL,basic,apptest]
+
+# shellcheck source=../../lib/base.sh
+. "$TESTLIBPATH/base.sh" || exit 137
 # shellcheck source=../../lib/user.sh
 . "$TESTLIBPATH/user.sh" || exit 137
 # shellcheck source=../../lib/shares.sh
@@ -32,240 +35,101 @@ third_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}äö
 fourth_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}äöü)z1AÄÖÜ"
 
 check_domainadmin_credentials || fail_fast 77 "UCR variables for admin credentials are not set"
-ADMINISTRATOR_NAME="$(univention-ldapsearch -b "$tests_domainadmin_account" uid | grep uid | sed -ne 's/^uid: //p')"
+ADMINISTRATOR_NAME="$(univention-ldapsearch -b "${tests_domainadmin_account:?}" uid | sed -ne 's/^uid: //p')"
 
-min_pwd_age="$(samba-tool domain passwordsettings show | grep "Minimum password age" | sed s/[^0-9]*/""/)"
-pwd_complexity="$(samba-tool domain passwordsettings show | grep complexity | sed "s/Password complexity: //")"
+min_pwd_age="$(samba-tool domain passwordsettings show | sed -ne 's/Minimum password age.*: //p')"
+pwd_complexity="$(samba-tool domain passwordsettings show | sed -ne 's/Password complexity: //p')"
 samba-tool domain passwordsettings set --complexity=off --min-pwd-age=0
 trap 'user_remove "$username"; samba-tool domain passwordsettings set --min-pwd-age="$min_pwd_age" --complexity="$pwd_complexity"' INT TERM EXIT
 
-if ! user_create "$username"; then
+user_create "$username" ||
 	fail_fast 1 "User could not be created"
-fi
 
 wait_for_replication
 # force_drs_replication
 wait_for_drs_replication "(sAMAccountName=$username)"
 
-max_i=10
-delta_t=1
-i=0
-while ! command_output=$(echo "$first_password" | kinit --password-file=STDIN "$username" 2>&1)
-do
-	let i="$i"+1
-	if [ "$i" = "$max_i" ]; then
-		fail_test 1 "Could not authenticate against kinit. Last command output:"
-		echo "$command_output"
-		break
-	fi
-	sleep "$delta_t"
-done
-echo "Authentication against kinit succeeded at attempt $((i+1))."
+check_kinit () { output=$(kinit --password-file=STDIN "$username" 2>&1 <<<"$1"); }
+retry 10 check_kinit "$first_password" &&
+	echo "Authentication against kinit succeeded at attempt $retry_i." ||
+	fail_test 1 "Could not authenticate against kinit. Last command output: $output"
+
 
 USER_DN=$(udm-test users/user list --filter uid="$username" | sed -ne 's/^DN: //p')
 
 sleep 10	## workaround for S4-Connector race
 
-#--test starting point
-#----password change with samba-tool
-echo "----password change with samba-tool"
-samba-tool user setpassword "$username" --newpassword="$second_password"
 
+#--test starting point
+
+
+info "----password change with samba-tool"
+samba-tool user setpassword "$username" --newpassword="$second_password"
 force_drs_replication -o
 
 ## first check trivial case: Samba4 password must work
-max_i=10
-delta_t=1
-i=0
-while ! ldbsearch -U "$username%$second_password" -H ldap://localhost "sAMAccountName=$username" dn 2>&1 | grep -q '^dn:'
-do
-	let i="$i"+1
-	if [ "$i" = "$max_i" ]; then
-		fail_test 1 "Could not authenticate against samba after password change with samba."
-		break
-	fi
-	sleep "$delta_t"
-done
-if [ "$i" -ne 0 ]; then
-	echo -n "WARNING: "
-fi
-if [ "$i" -ne "$max_i" ]; then
-	echo "Authentication against samba after password change with samba succeeded at attempt $((i+1))."
-fi
-
+check_ldbsearch () { ldbsearch -U "${username}%${1}" -H ldap://localhost "sAMAccountName=${username}" dn 2>&1 | grep -q '^dn:'; }
+retry 10 check_ldbsearch "$second_password" &&
+	echo "Authentication against Samba after password change with Samba succeeded at attempt $retry_i." ||
+	fail_test 1 "Could not authenticate against Samba after password change with Samba after $retry_i attempts."
 
 ## second check complex case: UDM password must work after replication
-max_i=60
-delta_t=2
-i=0
-while ! output="$(univention-ldapsearch -D "$USER_DN" -w "$second_password" -b "$USER_DN" dn 2>&1 )"
-do
-	let i="$i"+1
-	if [ "$i" = "$max_i" ]; then
-		echo "$output"
-		fail_test 1 "Could not authenticate against LDAP after password change with samba after $i attempts."
-		break
-	fi
-	sleep "$delta_t"
-done
-if [ "$i" -ne "$max_i" ]; then
-	echo "Authentication against LDAP after password change with samba succeeded at attempt $((i+1))."
-fi
+check_ldapsearch () { output="$(univention-ldapsearch -D "$USER_DN" -w "$1" -b "$USER_DN" -s base dn 2>&1)"; }
+retry_delay=2 retry 60 check_ldapsearch "$second_password" &&
+	echo "Authentication against LDAP after password change with Samba succeeded at attempt $retry_i." ||
+	fail_test 1 "Could not authenticate against LDAP after password change with Samba after $retry_i attempts: $output"
 
 ## cross check
-max_i=10
-delta_t=1
-i=0
-while ! command_output=$(echo "$second_password" | kinit --password-file=STDIN "$username" 2>&1)
-do
-	let i="$i"+1
-	if [ "$i" = "$max_i" ]; then
-		fail_test 1 "Could not authenticate against kinit after password change with samba after $i attempts."
-		echo "$command_output"
-		break
-	fi
-	sleep "$delta_t"
-done
-if [ "$i" -ne "$max_i" ]; then
-	echo "Authentication against kinit after password change with samba succeeded at attempt $((i+1))."
-fi
+retry 10 check_kinit "$second_password" ||
+	echo "Authentication against kinit after password change with Samba succeeded at attempt $retry_i." ||
+	fail_test 1 "Could not authenticate against kinit after password change with Samba after $retry_i attempts: $output"
 
-echo "----password change with udm"
-#----password change with udm
+
+info "----password change with UDM"
 udm-test users/user modify \
-	--dn "$USER_DN" --set password="$third_password"
-if [ "$?" != 0 ]; then
+	--dn "$USER_DN" --set password="$third_password" ||
 	fail_fast 1 "Could not change password with UDM"
-fi
 
 ## first check trivial case: UDM password must work
-max_i=10
-delta_t=1
-i=0
-while ! output="$(univention-ldapsearch -D "$USER_DN" -w "$third_password" -b "$USER_DN" dn 2>&1 )"
-do
-	let i="$i"+1
-	if [ "$i" = "$max_i" ]; then
-		echo "$output"
-		fail_test 1 "Could not authenticate against LDAP after password change with UDM after $i attempts."
-		break
-	fi
-	sleep "$delta_t"
-done
-if [ "$i" -ne 0 ]; then
-	echo -n "WARNING: "
-fi
-if [ "$i" -ne "$max_i" ]; then
-	echo "Authentication against LDAP after password change with UDM succeeded at attempt $((i+1))."
-fi
+retry 10 check_ldapsearch "$third_password" &&
+	echo "Authentication against LDAP after password change with UDM succeeded at attempt $retry_i." ||
+	fail_test 1 "Could not authenticate against LDAP after password change with UDM after $retry_i attempts."
 
 ## second check complex case: Samba4 password must work after replication
-max_i=15
-delta_t=2
-i=0
-while ! ldbsearch -U "$username%$third_password" -H ldap://localhost "sAMAccountName=$username" dn 2>&1 | grep -q '^dn:'
-do
-	let i="$i"+1
-	if [ "$i" = "$max_i" ]; then
-		fail_test 1 "Could not authenticate against samba after password change with UDM after $i attempts."
-		break
-	fi
-	sleep "$delta_t"
-done
-if [ "$i" -ne "$max_i" ]; then
-	echo "Authentication against samba after password change with UDM succeeded at attempt $((i+1))."
-fi
+retry_delay=2 retry 15 check_ldbsearch "$third_password" &&
+	echo "Authentication against Samba after password change with UDM succeeded at attempt $retry_i." ||
+	fail_test 1 "Could not authenticate against Samba after password change with UDM after $retry_i attempts."
 
 ## cross check
-max_i=10
-delta_t=1
-i=0
-while ! output="$(echo "$third_password" | kinit --password-file=STDIN "$username" 2>&1)"
-do
-	let i="$i"+1
-	if [ "$i" = "$max_i" ]; then
-		echo "$output"
-		fail_test 1 "Could not authenticate against kinit after password change with UDM after $i attempts."
-		break
-	fi
-	sleep "$delta_t"
-done
-if [ "$i" -ne "$max_i" ];then
-	echo "Authentication against kinit after password change with UDM succeeded at attempt $((i+1))."
-fi
+retry 10 check_kinit "$third_password" &&
+	echo "Authentication against kinit after password change with UDM succeeded at attempt $retry_i." ||
+	fail_test 1 "Could not authenticate against kinit after password change with UDM after $retry_i attempts."
+
+
 echo "----password change with kpasswd"
-#----password change with kpassword
-max_i=20
-delta_t=5
-i=0
-while true
-do
-	retval="$(python3 kpasswd_change_pwd.py -u "$username" -n "$fourth_password" -p "$third_password" -a "$ADMINISTRATOR_NAME" -m "$tests_domainadmin_pwd")"
-	echo "$retval" | grep "nSoft" || break
-	let i="$i"+1
-	if [ "$i" = "$max_i" ]; then
-		echo "Password change with kpasswd: Soft error."
-		break
-	fi
-	sleep "$delta_t"
-done
+change_pwd () {
+	output="$(python3 kpasswd_change_pwd.py -u "$username" -n "$fourth_password" -p "$third_password" -a "$ADMINISTRATOR_NAME" -m "$tests_domainadmin_pwd")"
+	! grep -q "nSoft" <<<"$output"
+}
+retry_delay=5 retry 20 change_pwd ||
+	echo "Password change with kpasswd: Soft error: $output"
 
 samba-tool domain passwordsettings show
 
 ## first check trivial case: Samba4 password must work
-max_i=10
-delta_t=1
-i=0
-while ! ldbsearch -U "$username%$fourth_password" -H ldap://localhost "sAMAccountName=$username" dn 2>&1 | grep -q '^dn:'
-do
-	let i=$i+1
-	if [ "$i" = "$max_i" ]; then
-		fail_fast 1 "Could not authenticate against samba after password change with kpasswd after $i attempts."
-		break
-	fi
-	sleep "$delta_t"
-done
-if [ "$i" -ne 0 ]; then
-	echo -n "WARNING: "
-fi
-if [ "$i" -ne "$max_i" ]; then
-	echo "Authentication against samba after password change with kpasswd succeeded at attempt $((i+1))."
-fi
+retry 10 check_ldbsearch "$fourth_password" &&
+	echo "Authentication against Samba after password change with kpasswd succeeded at attempt $retry_i." ||
+	fail_fast 1 "Could not authenticate against Samba after password change with kpasswd after $retry_i attempts."
 
 ## second check complex case: UDM password must work after replication
-max_i=15
-delta_t=2
-i=0
-while ! output="$(univention-ldapsearch -D "$USER_DN" -w "$fourth_password" -b "$USER_DN" dn 2>&1 )"
-do
-	let i="$i"+1
-	if [ "$i" = "$max_i" ]; then
-		echo "$output"
-		fail_test 1 "Could not authenticate against UDM after password change with kpasswd after $i attempts."
-		break
-	fi
-	sleep "$delta_t"
-done
-if [ "$i" -ne "$max_i" ]; then
-	echo "Authentication against LDAP after password change with kpasswd succeeded at attempt $((i+1))."
-fi
+retry_delay=2 retry 15 check_ldapsearch "$fourth_password" &&
+	echo "Authentication against LDAP after password change with kpasswd succeeded at attempt $retry_i." ||
+	fail_test 1 "Could not authenticate against LDAP after password change with kpasswd after $retry_i attempts."
 
 ## cross check
-max_i=10
-delta_t=1
-i=0
-while ! output="$(echo "$fourth_password" | kinit --password-file=STDIN "$username" 2>&1)"
-do
-	let i="$i"+1
-	if [ "$i" = "$max_i" ]; then
-		echo "$output"
-		fail_test 1 "Could not authenticate against kinit after password change with kpasswd after $i attempts."
-		break
-	fi
-	sleep "$delta_t"
-done
-if [ "$i" -ne "$max_i" ]; then
-	echo "Authentication against kinit after password change with kpasswd succeeded at attempt $((i+1))."
-fi
+retry 10 check_kinit "$fourth_password" &&
+	echo "Authentication against kinit after password change with kpasswd succeeded at attempt $retry_i." ||
+	fail_test 1 "Could not authenticate against kinit after password change with kpasswd after $retry_i attempts."
 
-exit $RETVAL
+
+exit "$RETVAL"
