* 51_samba4/41samba-tool_user_password_change: use the previous   version to change the password via kkpasswd (Bug #35012)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.2/ucs-3.2-2@50860 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/51_samba4/41samba-tool_user_password_change b/test/ucs-test/tests/51_samba4/41samba-tool_user_password_change
--- a/test/ucs-test/tests/51_samba4/41samba-tool_user_password_change
+++ b/test/ucs-test/tests/51_samba4/41samba-tool_user_password_change
@@ -106,8 +106,21 @@ echo "Authentication against kinit after password change with samba succeeded."
 
 echo "----password change with kpasswd"
 #----password change with kpassword
+max_i=20
+delta_t=5
+i=0
+while true
+do
+	retval="$(python kpasswd_change_pwd.py -u "$username" -n "$third_password" -p "$second_password")"
+	echo "$retval" | grep "nSoft" || break
+	let i="$i"+1
+	if [ "$i" = "$max_i" ]; then
+		echo "Password change with kpasswd: Soft error."
+		break
+	fi
+	sleep "$delta_t"
+done
 echo "Setting new password: $third_password"
-python kpasswd_change_pwd.py -u "$username" -n "$third_password" -p "$second_password"
 
 ## first check trivial case: Samba4 password must work, at least after the DRS repliction was successful
 i=0
@@ -139,6 +152,7 @@ i=0
 while ! output="$(univention-ldapsearch -x -D "$USER_DN" -w "$third_password" -b "$USER_DN" dn 2>&1 )"
 do
 	i=$((i+1))
+	echo $output
 	if [ $i = $DRS_REPLICATION_TIMEOUT ]; then
 		if output="$(univention-ldapsearch -x -D "$USER_DN" -w "$second_password" -b "$USER_DN" dn 2>&1 )"; then
 			echo "FAIL: Previous password still valid in LDAP"
