* 51_samba4/46machine_secret_access_sysvol: extended the test to run on     memberserver (Bug #30818).
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.0/ucs-4.0-1@58134 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/51_samba4/46machine_secret_access_sysvol b/test/ucs-test/tests/51_samba4/46machine_secret_access_sysvol
--- a/test/ucs-test/tests/51_samba4/46machine_secret_access_sysvol
+++ b/test/ucs-test/tests/51_samba4/46machine_secret_access_sysvol
@@ -2,12 +2,10 @@
 ## desc: Test accessing sysvol with smbclient using machine.secret
 ## exposure: safe
 ## packages:
-##  - univention-samba4
+##  - smbclient
 ## bugs: [30818]
-## roles:
-## - domaincontroller_master
-## - domaincontroller_backup
-## - domaincontroller_slave
+## roles-not: [basesystem]
+
 
 . "$TESTLIBPATH/shares.sh" || exit 137
 
@@ -15,6 +13,10 @@ password="$(cat /etc/machine.secret)"
 
 target_host="$(univention-ldapsearch -xLLL "univentionService=S4 Connector" cn | sed -n 's/^cn: //p')"
 
+if [ -z "$target_host" ]; then
+    echo "Could not determine the target host for the test."
+    exit 137
+fi
 
 info "----Accessing sysvol on $target_host.$domainname using smbclient and hostname/machine.secret credentials"
 
