* Skip 52replication_sysvol on a lone Samba4 DC (Bug #29062)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.2/ucs-3.2-0@43530 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/51_samba4/52replication_sysvol b/test/ucs-test/tests/51_samba4/52replication_sysvol
--- a/test/ucs-test/tests/51_samba4/52replication_sysvol
+++ b/test/ucs-test/tests/51_samba4/52replication_sysvol
@@ -30,7 +30,8 @@ determine_neighbour_s4host() {
 	done
 
 	if [ -z "$s4host_fqdn" ];then
-		fail_fast 77 "Could not find another Samba4 Service in Domain"
+		echo "Skipping test: Could not find another Samba4 Service in Domain"
+		exit 134
 	fi
 
 	echo "$s4host_fqdn"
