server_password_change: Improved safety by checking for errors and rolling back changes as long as it is safe to do so (Bug #27577). Updated copyright lines.
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.0/ucs@33763 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/base/univention-server/server_password_change b/base/univention-server/server_password_change
--- a/base/univention-server/server_password_change
+++ b/base/univention-server/server_password_change
@@ -3,7 +3,7 @@
 # Univention Server
 #  helper script: creates new machine password
 #
-# Copyright 2004-2011 Univention GmbH
+# Copyright 2004-2012 Univention GmbH
 #
 # http://www.univention.de/
 #
@@ -72,7 +72,13 @@ if [ -e "/var/lib/univention-directory-replication/failed.ldif" ]; then
 	FAIL "failed to change server password: /var/lib/univention-directory-replication/failed.ldif exists"
 fi
 
-if expr $(date +%j | sed -e 's|^0*||') % $server_password_interval != 0 >/dev/null; then exit 0; fi
+# Allow password change only if it is scheduled.
+if expr $(date +%j | sed -e 's|^0*||') % $server_password_interval != 0 >/dev/null; then
+  echo "No server password change scheduled for today, terminating without a change" >&3
+  exit 0
+else
+  echo "Proceeding with regular server password change scheduled for today" >&3
+fi
 
 new_password=$(makepasswd --chars 8)
 old_password=$(cat /etc/machine.secret)
@@ -81,22 +87,59 @@ if [ -z "$new_password" ]; then
 	FAIL "failed to change server password: makepasswd returned an empty password"
 fi
 
-# run hook scripts for "prechange" (which are named '^[A-Za-z0-9_-]+$')
+# Try to run hook scripts for "prechange" (which are named '^[A-Za-z0-9_-]+$')
+# Never use --exit-on-error with run-parts scripts because after an exit-on-error
+# we wouldn't know which scripts have received a "prechange" and need a "nochange".
 run-parts --verbose --arg prechange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
+# If ANY of the scripts fails while doing "prechange", then rollback with "nochange".
+if [ $? != 0 ]; then
+	# Use run-parts without --exit-on-error; go through all scripts.
+	run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
+	FAIL "run-parts failed during prechange, rolling back with nochange, server password unchanged"
+fi
 
+# Try to modify the server password with UDM.
 /usr/sbin/univention-directory-manager "computers/$server_role" modify --binddn "$ldap_hostdn" --bindpwd "$old_password" --dn "$ldap_hostdn" --set password="$new_password" >&3 2>&3
-
+# If changing the server password with UDM failed for some unknown reason,
+# then rollback the previous run-parts operation. 
 if [ $? != 0 ]; then
 	# run hook scripts for "nochange" (which are named '^[A-Za-z0-9_-]+$')
 	run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
 	FAIL "failed to change server password for $ldap_hostdn"
 fi
 
+# Wait a moment, just in case distribution of password needs a moment.
+sleep 1
+
+# If the changed server password has really been set correctly, then we can already use it.
+# Try to use udm with a trivial command just to check that it works.
+/usr/sbin/univention-directory-manager "computers/computer" list  >&3 2>&3
+if [ $? != 0 ]; then
+	# The server is in an inconsistent state because the new password has
+	# been set with UDM but UDM does't work with it. Do not continue with
+	# changes that would only worsen the situation. Instead, try to rollback.
+	# Don't try to reset the old password with UDM, this is impossible
+	# because it is unclear which password is effective for UDM now.
+
+	# run hook scripts for "nochange" (which are named '^[A-Za-z0-9_-]+$')
+	run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
+	FAIL "new server password has been set for $ldap_hostdn, but cannot access udm any more with this password"
+fi
+
+# Now that we are sure the new password already works with UDM, we can
+# dare to overwrite the machine password.
 echo "$(date +"%y%m%d%H%M"): $old_password" >>/etc/machine.secret.old
 chmod 600 /etc/machine.secret.old
 
 echo -n "$new_password" >/etc/machine.secret
 chmod 600 /etc/machine.secret
+
+# At this point the server password has been changed.
+# The change has gone beyond the point-of-no-return and
+# we will not try to rollback any more. But all later
+# operations will be logged and any failure would become
+# obvious through the log file. It is essential now to
+# go all the way through all the run-parts scripts with postchange.
 
 if [ "$ldap_hostdn" = "$samba_user" ]; then
 	/usr/bin/smbpasswd -w "$new_password" >&3 2>&3
@@ -116,6 +159,7 @@ if [ "$server_role" != "domaincontroller_master" ] && [ "$server_role" != "domai
 fi
 
 # run hook scripts for "postchange" (which are named '^[A-Za-z0-9_-]+$')
+# Use run-parts without --exit-on-error; go through all scripts.
 run-parts --verbose --arg postchange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
 
 echo "done ($(date))" >&3
