server_password_change: Even more safety checking to avoid inconsistent states of the server (Bug #27577).
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.0/ucs@33768 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/base/univention-server/server_password_change b/base/univention-server/server_password_change
--- a/base/univention-server/server_password_change
+++ b/base/univention-server/server_password_change
@@ -80,6 +80,12 @@ else
   echo "Proceeding with regular server password change scheduled for today" >&3
 fi
 
+# Try to use a trivial command just to check that LDAP server is reachable.
+univention-ldapsearch -D "$ldap_hostdn" -w "$(cat /etc/machine.secret)" -s base > /dev/null 2>&3
+if [ $? -ne 0 ]; then
+	FAIL "failed to contact LDAP server: cannot connect with univention-ldapsearch"
+fi
+
 new_password=$(makepasswd --chars 8)
 old_password=$(cat /etc/machine.secret)
 
@@ -108,23 +114,31 @@ if [ $? != 0 ]; then
 	FAIL "failed to change server password for $ldap_hostdn"
 fi
 
-# Wait a moment, just in case distribution of password needs a moment.
-sleep 1
-
 # If the changed server password has really been set correctly, then we can already use it.
-# Try to use udm with a trivial command just to check that it works.
-/usr/sbin/univention-directory-manager "computers/computer" list  >&3 2>&3
-if [ $? != 0 ]; then
-	# The server is in an inconsistent state because the new password has
-	# been set with UDM but UDM does't work with it. Do not continue with
-	# changes that would only worsen the situation. Instead, try to rollback.
-	# Don't try to reset the old password with UDM, this is impossible
-	# because it is unclear which password is effective for UDM now.
+# Repeat this several times, just in case password distribution takes some time.
+trial_counter=10
+while sleep 1
+do
+	# Try to use a trivial command just to check that the new password works.
+	univention-ldapsearch -D "$ldap_hostdn" -w "$new_password" -s base > /dev/null 2>&3
+	if [ $? -eq 0 ]; then
+		# OK, password worked, go on with the script.
+		break
+	fi
+	# If the new password failed 10 times, give up.
+	if [ $trial_counter -eq 0 ]; then
+		# The server is in an inconsistent state because the new password has
+		# been set with UDM but UDM does't work with it. Do not continue with
+		# changes that would only worsen the situation. Instead, try to rollback.
+		# Don't try to reset the old password with UDM, this is impossible
+		# because it is unclear which password is effective for LDAP now.
 
-	# run hook scripts for "nochange" (which are named '^[A-Za-z0-9_-]+$')
-	run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
-	FAIL "new server password has been set for $ldap_hostdn, but cannot access udm any more with this password"
-fi
+		# run hook scripts for "nochange" (which are named '^[A-Za-z0-9_-]+$')
+		run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
+		FAIL "new server password has been set for $ldap_hostdn, but cannot access LDAP server any more with this password"
+	fi
+	trial_counter=$(( trial_counter - 1))
+done
 
 # Now that we are sure the new password already works with UDM, we can
 # dare to overwrite the machine password.
