check if makepasswd returned an empty password during the server password change
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/trunk/ucs@1451 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/base/univention-server/server_password_change b/base/univention-server/server_password_change
--- a/base/univention-server/server_password_change
+++ b/base/univention-server/server_password_change
@@ -61,6 +61,12 @@ if [ ! $((`date +"%j" | sed -e 's|^0*||'`%$server_password_interval)) = 0 ]; the
 new_password=`makepasswd --chars 8`
 old_password=`cat /etc/machine.secret`
 
+if [ -z "$new_password" ]; then
+	echo "failed to change server password: makepasswd returned an empty password"
+	echo "failed to change server password: makepasswd returned an empty password" >>/var/log/univention/server_password_change.log
+	exit 1
+fi
+
 /usr/sbin/univention-admin computers/$server_role modify --binddn "$ldap_hostdn" --bindpwd $old_password --dn "$ldap_hostdn" --set password=$new_password  >>/var/log/univention/server_password_change.log 2>&1
 
 if [ $? != 0 ]; then
