Bug #39283: Check pending listener transactions in server password change script

diff --git a/base/univention-server/server_password_change b/base/univention-server/server_password_change
--- a/base/univention-server/server_password_change
+++ b/base/univention-server/server_password_change
@@ -103,6 +103,32 @@ if [ $? != 0 ]; then
 	FAIL "run-parts failed during prechange, rolling back with nochange, server password unchanged"
 fi
 
+# check if we are in sync with the master, if not then rollback with "nochange".
+if [ "$server_role" = "domaincontroller_slave" -o "$server_role" = "domaincontroller_backup" ]; then
+	in_sync=false
+	for i in $(seq 1 120); do
+		if [ -e "/var/lib/univention-directory-listener/notifier_id" ]; then
+			my_listener_id=$(< /var/lib/univention-directory-listener/notifier_id)
+			if [ -x "/usr/share/univention-directory-listener/get_notifier_id.py" ]; then
+				master_listner_id=$(/usr/share/univention-directory-listener/get_notifier_id.py 2>&3)
+				test $? -eq 0 || echo "Could not get notifier id from master!" >&3
+			fi
+			if [ -n "$my_listener_id" -a -n "$master_listner_id" ]; then
+				if [  "$my_listener_id" = "$master_listner_id" ]; then
+					in_sync=true
+					break
+				fi
+			fi
+		fi
+		echo "Pending listener transactions (myself: $my_listener_id, master: $master_listner_id), waiting ..." >&3
+		sleep 2
+	done
+	if ! $in_sync; then
+		run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
+		FAIL "Pending listener transactions timeout, rolling back with nochange, server password unchanged"
+	fi
+fi
+
 # Try to modify the server password with UDM.
 /usr/sbin/univention-directory-manager "computers/$server_role" modify --binddn "$ldap_hostdn" --bindpwd "$old_password" --dn "$ldap_hostdn" --set password="$new_password" >&3 2>&3
 # If changing the server password with UDM failed for some unknown reason,
