Bug #31026 server: Cleanup scripts
check_connection was for Mobile / Managed Clients only and is unused

univention-ldap-server-available contains redundant code

server_password_change contains redundant code and passes credentials
via command line for everyone to see (security)

diff --git a/base/univention-server/server_password_change b/base/univention-server/server_password_change
--- a/base/univention-server/server_password_change
+++ b/base/univention-server/server_password_change
@@ -30,18 +30,61 @@
 # /usr/share/common-licenses/AGPL-3; if not, see
 # <https://www.gnu.org/licenses/>.
 
+# shellcheck disable=SC2154
+
+MSECRET='/etc/machine.secret'
+eval "$(/usr/sbin/univention-config-registry shell)"
+
+# shellcheck source=/dev/null
 . /usr/share/univention-lib/all.sh
 create_logfile_if_missing /var/log/univention/server_password_change.log "root:adm" 640
 
-exec 3>>/var/log/univention/server_password_change.log
+if [ -n "${SPCDEBUG:-}" ]
+then
+	exec 3>&2
+	BASH_XTRACEFD=3
+	PS4='+${BASH_SOURCE}:${LINENO}: '
+	set -x
+else
+	exec 3>>/var/log/univention/server_password_change.log
+fi
+
 echo "Starting server password change ($(date))" >&3
 FAIL () { # log error message to log file and std-err, then fail
 	echo "$@" >&3
 	echo "$@" >&2
 	exit 1
 }
+try_ldap () { # try to connect LDAP server
+	local i
+	for ((i=0;i<60;i++))
+	do
+		sleep 1
+		univention-ldapsearch \
+			-D "$ldap_hostdn" \
+			-y "$@" \
+			-s base \
+			1.1 >/dev/null 2>&3 &&
+			return 0
+	done
+	return 1
+}
+change_password () {  # old-password-file new-password-file
+	/usr/sbin/univention-directory-manager "computers/$server_role" modify \
+		--binddn "$ldap_hostdn" \
+		--bindpwdfile "$1" \
+		--dn "$ldap_hostdn" \
+		--set password="$(<"$2")" >&3 2>&3
+}
+run_hooks () {
+	# Never use --exit-on-error with run-parts scripts because after an exit-on-error
+	# we wouldn't know which scripts have received a "prechange" and need a "nochange".
+	run-parts --verbose --arg "$@" -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
+}
+restart_udl () {
+	invoke-rc.d univention-directory-listener try-restart >&3
+}
 
-eval "$(/usr/sbin/univention-config-registry shell)"
 
 # 0 -> set to true
 # 1 -> set to false
@@ -52,149 +95,131 @@ if [ $? = 1 ]; then
 	exit 0
 fi
 
-if [ -z "$server_role" ]; then
+[ -n "$server_role" ] ||
 	FAIL "failed to change server password: empty config-registry variable server/role"
-fi
-if [ -z "$ldap_hostdn" ]; then
+[ -n "$ldap_hostdn" ] ||
 	FAIL "failed to change server password: empty config-registry variable ldap/hostdn"
-fi
-
-if [ ! -e "/etc/machine.secret" ]; then
-	FAIL "failed to change server password: /etc/machine.secret not found"
-fi
-
-if [ -e "/var/lib/univention-directory-replication/failed.ldif" ]; then
+[ -e "$MSECRET" ] ||
+	FAIL "failed to change server password: $MSECRET not found"
+[ -e "/var/lib/univention-directory-replication/failed.ldif" ] &&
 	FAIL "failed to change server password: /var/lib/univention-directory-replication/failed.ldif exists"
-fi
 
 # Allow password change only if it is scheduled.
-epoch_last_change="$(stat --format %Y /etc/machine.secret)"
+epoch_last_change="$(stat --format %Y "$MSECRET")"
 epoch="$(date +%s)"
-seconds_last_change="$(($epoch - $epoch_last_change))"
-days_last_change="$(($seconds_last_change/60/60/24))"
-if (("$server_password_interval" > "$days_last_change")); then
+seconds_last_change="$((epoch- epoch_last_change))"
+days_last_change="$((seconds_last_change/60/60/24))"
+if [ "$server_password_interval" -gt "$days_last_change" ]; then
 	echo "No server password change scheduled for today, terminating without a change" >&3
 	exit 0
-else
-	echo "Proceeding with regular server password change scheduled for today" >&3
 fi
+
+echo "Proceeding with regular server password change scheduled for today" >&3
 
 # Try to use a trivial command just to check that LDAP server is reachable.
-univention-ldapsearch -D "$ldap_hostdn" -w "$(cat /etc/machine.secret)" -s base > /dev/null 2>&3
-if [ $? -ne 0 ]; then
+univention-ldapsearch -D "$ldap_hostdn" -y "$MSECRET" -s base 1.1 >/dev/null 2>&3 ||
 	FAIL "failed to contact LDAP server: cannot connect with univention-ldapsearch"
-fi
 
-new_password="$(create_machine_password)"
-old_password="$(cat /etc/machine.secret)"
+old_pass="$(mktemp "$MSECRET.XXXXXXXX")"
+new_pass="$(mktemp "$MSECRET.XXXXXXXX")"
+# shellcheck disable=SC2064
+trap "rm -f '$new_pass' '$old_pass'" EXIT
+chown --reference="$MSECRET" "$old_pass" "$new_pass"
+chmod --reference="$MSECRET" "$old_pass" "$new_pass"
 
-if [ -z "$new_password" ]; then
+ln -f "$MSECRET" "$old_pass"
+# shellcheck disable=SC2015
+create_machine_password >"$new_pass" &&
+	[ -s "$new_pass" ] ||
 	FAIL "failed to change server password: create_machine_password() returned an empty password"
-fi
 
-# Try to run hook scripts for "prechange" (which are named '^[A-Za-z0-9_-]+$')
-# Never use --exit-on-error with run-parts scripts because after an exit-on-error
-# we wouldn't know which scripts have received a "prechange" and need a "nochange".
-run-parts --verbose --arg prechange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
-# If ANY of the scripts fails while doing "prechange", then rollback with "nochange".
-if [ $? != 0 ]; then
-	# Use run-parts without --exit-on-error; go through all scripts.
-	run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
+if ! run_hooks prechange
+then
+	run_hooks nochange
 	FAIL "run-parts failed during prechange, rolling back with nochange, server password unchanged"
 fi
 
 # check if we are in sync with the master, if not then rollback with "nochange".
-if [ "$server_role" = "domaincontroller_slave" -o "$server_role" = "domaincontroller_backup" ]; then
-	in_sync=false
-	for i in $(seq 1 120); do
+check_in_sync () {
+	case "$server_role" in
+	domaincontroller_backup) ;;
+	domaincontroller_slave) ;;
+	*) return 0 ;;
+	esac
+	local i lid=0 nid=1
+	for ((i=0;i<120;i++))
+	do
 		if [ -e "/var/lib/univention-directory-listener/notifier_id" ]; then
-			my_listener_id=$(< /var/lib/univention-directory-listener/notifier_id)
+			read -r lid </var/lib/univention-directory-listener/notifier_id
 			if [ -x "/usr/share/univention-directory-listener/get_notifier_id.py" ]; then
-				master_listner_id=$(/usr/share/univention-directory-listener/get_notifier_id.py 2>&3)
-				test $? -eq 0 || echo "Could not get notifier id from master!" >&3
+				nid=$(/usr/share/univention-directory-listener/get_notifier_id.py 2>&3) ||
+					echo "Could not get notifier id from master!" >&3
 			fi
-			if [ -n "$my_listener_id" -a -n "$master_listner_id" ]; then
-				if [  "$my_listener_id" = "$master_listner_id" ]; then
-					in_sync=true
-					break
-				fi
-			fi
+			[ "${lid:-0}" = "${nid:-1}" ] &&
+					return 0
 		fi
-		echo "Pending listener transactions (myself: $my_listener_id, master: $master_listner_id), waiting ..." >&3
+		echo "Pending listener transactions (lid=$lid < nid=$nid), waiting ..." >&3
 		sleep 2
 	done
-	if ! $in_sync; then
-		run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
-		FAIL "Pending listener transactions timeout, rolling back with nochange, server password unchanged"
-	fi
-fi
+	run_hooks nochange
+	FAIL "Pending listener transactions timeout, rolling back with nochange, server password unchanged"
+}
+check_in_sync
 
 # Try to modify the server password with UDM.
-/usr/sbin/univention-directory-manager "computers/$server_role" modify --binddn "$ldap_hostdn" --bindpwd "$old_password" --dn "$ldap_hostdn" --set password="$new_password" >&3 2>&3
+if ! change_password "$old_pass" "$new_pass"
 # If changing the server password with UDM failed for some unknown reason,
 # then rollback the previous run-parts operation. 
-if [ $? != 0 ]; then
-	# run hook scripts for "nochange" (which are named '^[A-Za-z0-9_-]+$')
-	run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
+then
+	run_hooks nochange
 	FAIL "failed to change server password for $ldap_hostdn"
 fi
 
 # If the changed server password has really been set correctly, then we can already use it.
 # Try to use the new password with LDAP against the MASTER.
 # Repeat this several times, just in case password distribution takes some time.
-trial_counter=60
-while sleep 1
-do
-	# Try to use a trivial command just to check that the new password works.
-	univention-ldapsearch -D "$ldap_hostdn" -w "$new_password" -h "$ldap_master" -p "$ldap_master_port" -s base > /dev/null 2>&3
-	if [ $? -eq 0 ]; then
-		# OK, password worked against master, go on with the script.
-		break
-	fi
-	# If the new password failed for a long time, give up.
-	if [ $trial_counter -eq 0 ]; then
+if ! try_ldap "$new_pass" -h "$ldap_master" -p "$ldap_master_port"
+then
 		# The server is in an inconsistent state because the new password has
 		# been set with UDM but LDAP does not work with it. Do not continue with
 		# changes that would only worsen the situation. Instead, try to rollback.
 		# Reset the old password with UDM and give up.
-		/usr/sbin/univention-directory-manager "computers/$server_role" modify --binddn "$ldap_hostdn" --bindpwd "$new_password" --dn "$ldap_hostdn" --set password="$old_password" >&3 2>&3
+		change_password "$new_pass" "$old_pass"
 
-		# run hook scripts for "nochange" (which are named '^[A-Za-z0-9_-]+$')
-		run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
+		run_hooks nochange
 		FAIL "resetting old server password for $ldap_hostdn, because access to LDAP master did not work with the new password"
-	fi
-	trial_counter=$(( trial_counter - 1))
-done
+fi
 
 # Now that we are sure the new password already works with LDAP master,
 # we can dare to overwrite the machine password. The machine password is
 # needed by the Listener who replicates the changed password to the
 # local server's LDAP.
-echo "$(date +"%y%m%d%H%M"): $old_password" >>/etc/machine.secret.old
-chmod 600 /etc/machine.secret.old
+# shellcheck disable=SC2094
+{
+	chmod 600 "$MSECRET.old"
+	printf "%s: " "$(date +'%y%m%d%H%M')"
+	cat "$old_pass"
+	echo
+} >>"$MSECRET.old"
 
 # change machine.secret and restart listener
-echo -n "$new_password" >/etc/machine.secret
-chmod 600 /etc/machine.secret
-[ -e /etc/init.d/univention-directory-listener ] && invoke-rc.d univention-directory-listener restart >&3
+ln -f "$new_pass" "$MSECRET"
+restart_udl
 
 revert_password_change() {
-	# Reset to the old password with UDM
-	/usr/sbin/univention-directory-manager "computers/$server_role" modify --binddn "$ldap_hostdn" --bindpwd "$new_password" --dn "$ldap_hostdn" --set password="$old_password" >&3 2>&3
+	change_password "$new_pass" "$old_pass"
 
 	# Rollback /etc/machine.secret and restart listener
-	awk '{pwd=$2}; END {printf("%s", pwd)}' /etc/machine.secret.old > /etc/machine.secret
-	chmod 600 /etc/machine.secret
-	[ -e /etc/init.d/univention-directory-listener ] && invoke-rc.d univention-directory-listener restart >&3
+	ln -f "$old_pass" "$MSECRET"
+	restart_udl
 
-	# run hook scripts for "nochange" (which are named '^[A-Za-z0-9_-]+$')
-	run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
+	run_hooks nochange
 }
 
 # change samba password locally
-run-parts --verbose --arg localchange --regex '^univention-samba4' -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
+if ! run_hooks localchange --regex '^univention-samba4'
 # if samba-tool user setpassword fails, reset the old password.
-if [ $? != 0 ]; then
+then
 	revert_password_change
 	FAIL "Failed to set new password in samba, machine password set back to old password for $ldap_hostdn."
 fi
@@ -202,26 +227,15 @@ fi
 # The password is changed on the master now, but it is not clear if
 # this change has been replicated to the local host yet.
 # Do the same test as above but with the local LDAP replication.
-trial_counter=60
-while sleep 1
-do
-	# Try to use a trivial command just to check that the new password works.
-	univention-ldapsearch -D "$ldap_hostdn" -w "$new_password" -s base > /dev/null 2>&3
-	if [ $? -eq 0 ]; then
-		# OK, password worked, go on with the script.
-		break
-	fi
-	# If the new password failed for a long time, give up.
-	if [ $trial_counter -eq 0 ]; then
+if ! try_ldap "$new_pass"
+then
 		# The server is in an inconsistent state because the new password has
 		# been set with UDM but LDAP does not work with it. Do not continue with
 		# changes that would only worsen the situation. Instead, try to rollback.
 		# Reset the old password with UDM and give up.
 		revert_password_change
 		FAIL "Access to local LDAP did not work with the new password, machine password set back to old password for $ldap_hostdn."
-	fi
-	trial_counter=$(( trial_counter - 1))
-done
+fi
 
 # At this point the server password has been changed.
 # The change has gone beyond the point-of-no-return and
@@ -230,15 +244,13 @@ done
 # obvious through the log file. It is essential now to
 # go all the way through all the run-parts scripts with postchange.
 
-if [ "$server_role" != "domaincontroller_master" ] && [ "$server_role" != "domaincontroller_backup" ]; then
-	if [ -x /etc/init.d/univention-directory-listener ]; then
-		invoke-rc.d univention-directory-listener crestart >&3 2>&3
-	fi
-fi
+case "$server_role" in
+domaincontroller_master) ;;
+domaincontroller_backup) ;;
+*) restart_udl ;;
+esac
 
-# run hook scripts for "postchange" (which are named '^[A-Za-z0-9_-]+$')
-# Use run-parts without --exit-on-error; go through all scripts.
-run-parts --verbose --arg postchange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
+run_hooks postchange
 
 echo "done ($(date))" >&3
 exec 3<&-
