Bug #53205: change calls order to only change samba password if everything works before

diff --git a/base/univention-server/server_password_change b/base/univention-server/server_password_change
--- a/base/univention-server/server_password_change
+++ b/base/univention-server/server_password_change
@@ -219,14 +219,6 @@ revert_password_change() {
 	run_hooks nochange
 }
 
-# change samba password locally
-if ! run_hooks localchange --regex '^univention-samba4'
-# if samba-tool user setpassword fails, reset the old password.
-then
-	revert_password_change
-	FAIL "Failed to set new password in samba, machine password set back to old password for $ldap_hostdn."
-fi
-
 # The password is changed on the Primary Directory Node now, but it is not clear if
 # this change has been replicated to the local host yet.
 # Do the same test as above but with the local LDAP replication.
@@ -238,6 +230,14 @@ then
 		# Reset the old password with UDM and give up.
 		revert_password_change
 		FAIL "Access to local LDAP did not work with the new password, machine password set back to old password for $ldap_hostdn."
+fi
+
+# change samba password locally
+if ! run_hooks localchange --regex '^univention-samba4'
+# if samba-tool user setpassword fails, reset the old password.
+then
+	revert_password_change
+	FAIL "Failed to set new password in samba, machine password set back to old password for $ldap_hostdn."
 fi
 
 # At this point the server password has been changed.
