do not change the server password if a failed.ldif exists, Closes Bug #4777
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/trunk/ucs@301 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/base/univention-server/server_password_change b/base/univention-server/server_password_change
--- a/base/univention-server/server_password_change
+++ b/base/univention-server/server_password_change
@@ -50,6 +50,12 @@ if [ ! -e "/etc/machine.secret" ]; then
 	exit 1
 fi
 
+if [ -e "/var/lib/univention-ldap-replication/failed.ldif" ]; then
+	echo "failed to change server password: /var/lib/univention-ldap-replication/failed.ldif exists"
+	echo "failed to change server password: /var/lib/univention-ldap-replication/failed.ldif exists" >>/var/log/univention/server_password_change.log
+	exit 1
+fi
+
 if [ ! $((`date +"%j" | sed -e 's|^0*||'`%$server_password_interval)) = 0 ]; then exit 0; fi
 
 new_password=`makepasswd --chars 8`
