Bug #54019: Fixed timestamps for log messages (4.4)
Backported solution from 5.0 https://forge.univention.org/bugzilla/show_bug.cgi?id=53182

diff --git a/base/univention-server/server_password_change b/base/univention-server/server_password_change
--- a/base/univention-server/server_password_change
+++ b/base/univention-server/server_password_change
@@ -34,10 +34,11 @@
 create_logfile_if_missing /var/log/univention/server_password_change.log "root:adm" 640
 
 exec 3>>/var/log/univention/server_password_change.log
-echo "($(date '+%F %T.%N')) Starting server password change ($(date))" >&3
+echowithtimestamp "Starting server password change" >&3
 FAIL () { # log error message to log file and std-err, then fail
-	echo "$@" >&3
-	echo "$@" >&2
+	msg=$(echowithtimestamp "$@")
+	echo "$msg" >&3
+	echo "$msg" >&2
 	exit 1
 }
 
@@ -48,23 +49,23 @@ eval "$(/usr/sbin/univention-config-registry shell)"
 # 2 -> empty
 is_ucr_true server/password/change
 if [ $? = 1 ]; then
-	echo "($(date '+%F %T.%N')) Server password change is disabled by the UCR variable server/password/change" >&3
+	echowithtimestamp "Server password change is disabled by the UCR variable server/password/change" >&3
 	exit 0
 fi
 
 if [ -z "$server_role" ]; then
-	FAIL "($(date '+%F %T.%N')) failed to change server password: empty config-registry variable server/role"
+	FAIL "failed to change server password: empty config-registry variable server/role"
 fi
 if [ -z "$ldap_hostdn" ]; then
-	FAIL "($(date '+%F %T.%N')) failed to change server password: empty config-registry variable ldap/hostdn"
+	FAIL "failed to change server password: empty config-registry variable ldap/hostdn"
 fi
 
 if [ ! -e "/etc/machine.secret" ]; then
-	FAIL "($(date '+%F %T.%N')) failed to change server password: /etc/machine.secret not found"
+	FAIL "failed to change server password: /etc/machine.secret not found"
 fi
 
 if [ -e "/var/lib/univention-directory-replication/failed.ldif" ]; then
-	FAIL "($(date '+%F %T.%N')) failed to change server password: /var/lib/univention-directory-replication/failed.ldif exists"
+	FAIL "failed to change server password: /var/lib/univention-directory-replication/failed.ldif exists"
 fi
 
 # Allow password change only if it is scheduled.
@@ -73,23 +74,23 @@ epoch="$(date +%s)"
 seconds_last_change="$(($epoch - $epoch_last_change))"
 days_last_change="$(($seconds_last_change/60/60/24))"
 if (("$server_password_interval" > "$days_last_change")); then
-	echo "($(date '+%F %T.%N')) No server password change scheduled for today, terminating without a change" >&3
+	echowithtimestamp "No server password change scheduled for today, terminating without a change" >&3
 	exit 0
 else
-	echo "($(date '+%F %T.%N')) Proceeding with regular server password change scheduled for today" >&3
+	echowithtimestamp "Proceeding with regular server password change scheduled for today" >&3
 fi
 
 # Try to use a trivial command just to check that LDAP server is reachable.
 univention-ldapsearch -D "$ldap_hostdn" -w "$(cat /etc/machine.secret)" -s base > /dev/null 2>&3
 if [ $? -ne 0 ]; then
-	FAIL "($(date '+%F %T.%N')) failed to contact LDAP server: cannot connect with univention-ldapsearch"
+	FAIL "failed to contact LDAP server: cannot connect with univention-ldapsearch"
 fi
 
 new_password="$(create_machine_password)"
 old_password="$(cat /etc/machine.secret)"
 
 if [ -z "$new_password" ]; then
-	FAIL "($(date '+%F %T.%N')) failed to change server password: create_machine_password() returned an empty password"
+	FAIL "failed to change server password: create_machine_password() returned an empty password"
 fi
 
 # Try to run hook scripts for "prechange" (which are named '^[A-Za-z0-9_-]+$')
@@ -100,7 +101,7 @@ run-parts --verbose --arg prechange -- /usr/lib/univention-server/server_passwor
 if [ $? != 0 ]; then
 	# Use run-parts without --exit-on-error; go through all scripts.
 	run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
-	FAIL "($(date '+%F %T.%N')) run-parts failed during prechange, rolling back with nochange, server password unchanged"
+	FAIL "run-parts failed during prechange, rolling back with nochange, server password unchanged"
 fi
 
 # check if we are in sync with the master, if not then rollback with "nochange".
@@ -111,7 +112,7 @@ if [ "$server_role" = "domaincontroller_slave" -o "$server_role" = "domaincontro
 			my_listener_id=$(< /var/lib/univention-directory-listener/notifier_id)
 			if [ -x "/usr/share/univention-directory-listener/get_notifier_id.py" ]; then
 				master_listner_id=$(/usr/share/univention-directory-listener/get_notifier_id.py 2>&3)
-				test $? -eq 0 || echo "Could not get notifier id from master!" >&3
+				test $? -eq 0 || echowithtimestamp "Could not get notifier id from master!" >&3
 			fi
 			if [ -n "$my_listener_id" -a -n "$master_listner_id" ]; then
 				if [  "$my_listener_id" = "$master_listner_id" ]; then
@@ -120,12 +121,12 @@ if [ "$server_role" = "domaincontroller_slave" -o "$server_role" = "domaincontro
 				fi
 			fi
 		fi
-		echo "($(date '+%F %T.%N')) Pending listener transactions (myself: $my_listener_id, master: $master_listner_id), waiting ..." >&3
+		echowithtimestamp "Pending listener transactions (myself: $my_listener_id, master: $master_listner_id), waiting ..." >&3
 		sleep 2
 	done
 	if ! $in_sync; then
 		run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
-		FAIL "($(date '+%F %T.%N')) Pending listener transactions timeout, rolling back with nochange, server password unchanged"
+		FAIL "Pending listener transactions timeout, rolling back with nochange, server password unchanged"
 	fi
 fi
 
@@ -136,7 +137,7 @@ fi
 if [ $? != 0 ]; then
 	# run hook scripts for "nochange" (which are named '^[A-Za-z0-9_-]+$')
 	run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
-	FAIL "($(date '+%F %T.%N')) failed to change server password for $ldap_hostdn"
+	FAIL "failed to change server password for $ldap_hostdn"
 fi
 
 # If the changed server password has really been set correctly, then we can already use it.
@@ -161,7 +162,7 @@ do
 
 		# run hook scripts for "nochange" (which are named '^[A-Za-z0-9_-]+$')
 		run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
-		FAIL "($(date '+%F %T.%N')) resetting old server password for $ldap_hostdn, because access to LDAP master did not work with the new password"
+		FAIL "resetting old server password for $ldap_hostdn, because access to LDAP master did not work with the new password"
 	fi
 	trial_counter=$(( trial_counter - 1))
 done
@@ -196,7 +197,7 @@ run-parts --verbose --arg localchange --regex '^univention-samba4' -- /usr/lib/u
 # if samba-tool user setpassword fails, reset the old password.
 if [ $? != 0 ]; then
 	revert_password_change
-	FAIL "($(date '+%F %T.%N')) Failed to set new password in samba, machine password set back to old password for $ldap_hostdn."
+	FAIL "Failed to set new password in samba, machine password set back to old password for $ldap_hostdn."
 fi
 
 # The password is changed on the master now, but it is not clear if
@@ -218,7 +219,7 @@ do
 		# changes that would only worsen the situation. Instead, try to rollback.
 		# Reset the old password with UDM and give up.
 		revert_password_change
-		FAIL "($(date '+%F %T.%N')) Access to local LDAP did not work with the new password, machine password set back to old password for $ldap_hostdn."
+		FAIL "Access to local LDAP did not work with the new password, machine password set back to old password for $ldap_hostdn."
 	fi
 	trial_counter=$(( trial_counter - 1))
 done
@@ -240,7 +241,7 @@ fi
 # Use run-parts without --exit-on-error; go through all scripts.
 run-parts --verbose --arg postchange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
 
-echo "($(date '+%F %T.%N')) done ($(date))" >&3
+echowithtimestamp "done" >&3
 exec 3<&-
 
 exit 0
