Additional safety check; access to LDAP master and to local LDAP are now tested before finalizing password change. (Bug #27577).
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.0/ucs@33780 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/base/univention-server/server_password_change b/base/univention-server/server_password_change
--- a/base/univention-server/server_password_change
+++ b/base/univention-server/server_password_change
@@ -115,8 +115,36 @@ if [ $? != 0 ]; then
 fi
 
 # If the changed server password has really been set correctly, then we can already use it.
+# Try to use the new password with LDAP against the MASTER.
 # Repeat this several times, just in case password distribution takes some time.
-trial_counter=10
+trial_counter=30
+while sleep 1
+do
+	# Try to use a trivial command just to check that the new password works.
+	univention-ldapsearch -D "$ldap_hostdn" -w "$new_password" -h "$ldap_master" -p "$ldap_master_port" -s base > /dev/null 2>&3
+	if [ $? -eq 0 ]; then
+		# OK, password worked against master, go on with the script.
+		break
+	fi
+	# If the new password failed for a long time, give up.
+	if [ $trial_counter -eq 0 ]; then
+		# The server is in an inconsistent state because the new password has
+		# been set with UDM but LDAP does't work with it. Do not continue with
+		# changes that would only worsen the situation. Instead, try to rollback.
+		# Reset the old password with UDM and give up.
+		/usr/sbin/univention-directory-manager "computers/$server_role" modify --binddn "$ldap_hostdn" --bindpwd "$new_password" --dn "$ldap_hostdn" --set password="$old_password" >&3 2>&3
+
+		# run hook scripts for "nochange" (which are named '^[A-Za-z0-9_-]+$')
+		run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
+		FAIL "resetting old server password for $ldap_hostdn, because access to LDAP master did not work with the new password"
+	fi
+	trial_counter=$(( trial_counter - 1))
+done
+
+# The password is changed on the master now, but it is not clear if
+# this change has been replicated to the local host yet.
+# Do the same test as above but with the local LDAP replication.
+trial_counter=30
 while sleep 1
 do
 	# Try to use a trivial command just to check that the new password works.
@@ -125,23 +153,23 @@ do
 		# OK, password worked, go on with the script.
 		break
 	fi
-	# If the new password failed 10 times, give up.
+	# If the new password failed for a long time, give up.
 	if [ $trial_counter -eq 0 ]; then
 		# The server is in an inconsistent state because the new password has
-		# been set with UDM but UDM does't work with it. Do not continue with
+		# been set with UDM but LDAP does't work with it. Do not continue with
 		# changes that would only worsen the situation. Instead, try to rollback.
-		# Don't try to reset the old password with UDM, this is impossible
-		# because it is unclear which password is effective for LDAP now.
+		# Reset the old password with UDM and give up.
+		/usr/sbin/univention-directory-manager "computers/$server_role" modify --binddn "$ldap_hostdn" --bindpwd "$new_password" --dn "$ldap_hostdn" --set password="$old_password" >&3 2>&3
 
 		# run hook scripts for "nochange" (which are named '^[A-Za-z0-9_-]+$')
 		run-parts --verbose --arg nochange -- /usr/lib/univention-server/server_password_change.d >&3 2>&3
-		FAIL "new server password has been set for $ldap_hostdn, but cannot access LDAP server any more with this password"
+		FAIL "resetting old server password for $ldap_hostdn, because access to local LDAP did not work with the new password"
 	fi
 	trial_counter=$(( trial_counter - 1))
 done
 
-# Now that we are sure the new password already works with UDM, we can
-# dare to overwrite the machine password.
+# Now that we are sure the new password already works with LDAP master
+# and also with the local LDAP, we can dare to overwrite the machine password.
 echo "$(date +"%y%m%d%H%M"): $old_password" >>/etc/machine.secret.old
 chmod 600 /etc/machine.secret.old
 
