Fix bashism in server_password_change (Bug #22160)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.0/ucs@25779 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/base/univention-server/server_password_change b/base/univention-server/server_password_change
--- a/base/univention-server/server_password_change
+++ b/base/univention-server/server_password_change
@@ -36,82 +36,76 @@ if [ ! -e /var/log/univention/server_password_change.log ] ; then
 	chmod 640 /var/log/univention/server_password_change.log
 fi
 
-echo "Starting server password change (`date`)" >>/var/log/univention/server_password_change.log
+exec 3>>/var/log/univention/server_password_change.log
+echo "Starting server password change ($(date))" >&3
+FAIL () { # log error message to log file and std-err, than fail
+	echo "$@" >&3
+	echo "$@" >&2
+	exit 1
+}
 
 eval "$(/usr/sbin/univention-config-registry shell)"
 
-
 if [ -z "$server_role" ]; then
-	echo "failed to change server password: empty config-registry variable server/role"
-	echo "failed to change server password: empty config-registry variable server/role" >>/var/log/univention/server_password_change.log
-	exit 1
+	FAIL "failed to change server password: empty config-registry variable server/role"
 fi
 if [ -z "$ldap_hostdn" ]; then
-	echo "failed to change server password: empty config-registry variable ldap/hostdn"
-	echo "failed to change server password: empty config-registry variable ldap/hostdn" >>/var/log/univention/server_password_change.log
-	exit 1
+	FAIL "failed to change server password: empty config-registry variable ldap/hostdn"
 fi
 
 if [ ! -e "/etc/machine.secret" ]; then
-	echo "failed to change server password: /etc/machine.secret not found"
-	echo "failed to change server password: /etc/machine.secret not found" >>/var/log/univention/server_password_change.log
-	exit 1
+	FAIL "failed to change server password: /etc/machine.secret not found"
 fi
 
 if [ -e "/var/lib/univention-directory-replication/failed.ldif" ]; then
-	echo "failed to change server password: /var/lib/univention-directory-replication/failed.ldif exists"
-	echo "failed to change server password: /var/lib/univention-directory-replication/failed.ldif exists" >>/var/log/univention/server_password_change.log
-	exit 1
+	FAIL "failed to change server password: /var/lib/univention-directory-replication/failed.ldif exists"
 fi
 
-if [ ! $((`date +"%j" | sed -e 's|^0*||'`%$server_password_interval)) = 0 ]; then exit 0; fi
+if expr $(date +%j | sed -e 's|^0*||') % $server_password_interval != 0 >/dev/null; then exit 0; fi
 
-new_password=`makepasswd --chars 8`
-old_password=`cat /etc/machine.secret`
+new_password=$(makepasswd --chars 8)
+old_password=$(cat /etc/machine.secret)
 
 if [ -z "$new_password" ]; then
-	echo "failed to change server password: makepasswd returned an empty password"
-	echo "failed to change server password: makepasswd returned an empty password" >>/var/log/univention/server_password_change.log
-	exit 1
+	FAIL "failed to change server password: makepasswd returned an empty password"
 fi
 
-/usr/sbin/univention-directory-manager computers/$server_role modify --binddn "$ldap_hostdn" --bindpwd $old_password --dn "$ldap_hostdn" --set password=$new_password  >>/var/log/univention/server_password_change.log 2>&1
+/usr/sbin/univention-directory-manager "computers/$server_role" modify --binddn "$ldap_hostdn" --bindpwd "$old_password" --dn "$ldap_hostdn" --set password="$new_password" >&3 2>&3
 
 if [ $? != 0 ]; then
-	echo "failed to change server password for $ldap_hostdn"
-	echo "failed to change server password for $ldap_hostdn" >>/var/log/univention/server_password_change.log
-	exit 1
+	FAIL "failed to change server password for $ldap_hostdn"
 fi
 
-echo "`date +"%y%m%d%H%M"`: $old_password" >>/etc/machine.secret.old
+echo "$(date +"%y%m%d%H%M"): $old_password" >>/etc/machine.secret.old
 chmod 600 /etc/machine.secret.old
-
 
 echo -n "$new_password" >/etc/machine.secret
 chmod 600 /etc/machine.secret
 
 if [ "$ldap_hostdn" = "$samba_user" ]; then
-	/usr/bin/smbpasswd -w `cat /etc/machine.secret` >>/var/log/univention/server_password_change.log 2>&1
+	/usr/bin/smbpasswd -w "$new_password" >&3 2>&3
 	for idmap_ldap_config in alloc ${samba_idmap_domains}; do
-		echo "setting idmap secret for ${idmap_ldap_config} from /etc/machine.secret" >>/var/log/univention/server_password_change.log
-		net idmap secret ${idmap_ldap_config} `</etc/machine.secret` >>/var/log/univention/server_password_change.log 2>&1
+		echo "setting idmap secret for ${idmap_ldap_config} from /etc/machine.secret" >&3
+		net idmap secret "${idmap_ldap_config}" "$new_password" >&3 2>&3
 	done
 	if [ -n "$samba_ha_master" ]; then
 		if [ -x /etc/heartbeat/resource.d/samba ]; then
-			/etc/heartbeat/resource.d/samba reload >>/var/log/univention/server_password_change.log 2>&1
+			/etc/heartbeat/resource.d/samba reload >&3 2>&3
 		fi
 	else
 		if [ -x /etc/init.d/samba ]; then
-			/etc/init.d/samba restart >>/var/log/univention/server_password_change.log 2>&1
+			invoke-rc.d samba restart >&3 2>&3
 		fi
 	fi
 fi
 
-if [ "$server_role" != "domaincontroller_master" -a "$server_role" != "domaincontroller_backup" ]; then
+if [ "$server_role" != "domaincontroller_master" ] && [ "$server_role" != "domaincontroller_backup" ]; then
 	if [ -x /etc/init.d/univention-directory-listener ]; then
-		/etc/init.d/univention-directory-listener crestart >>/var/log/univention/server_password_change.log 2>&1
+		invoke-rc.d univention-directory-listener crestart >&3 2>&3
 	fi
 fi
 
-echo "done (`date`)" >>/var/log/univention/server_password_change.log 2>&1
+echo "done ($(date))" >&3
+exec 3<&-
+
 exit 0
