Bug #53182: Add timestamps to server_password_change log messages

diff --git a/base/univention-server/server_password_change b/base/univention-server/server_password_change
--- a/base/univention-server/server_password_change
+++ b/base/univention-server/server_password_change
@@ -49,10 +49,11 @@ else
 	exec 3>>/var/log/univention/server_password_change.log
 fi
 
-echo "($(date '+%F %T.%N')) Starting server password change" >&3
+echowithtimestamp "Starting server password change" >&3
 FAIL () { # log error message to log file and std-err, then fail
-	echo "$@" >&3
-	echo "$@" >&2
+	msg=$(echowithtimestamp "$@")
+	echo "$msg" >&3
+	echo "$msg" >&2
 	exit 1
 }
 try_ldap () { # try to connect LDAP server
@@ -70,11 +71,13 @@ try_ldap () { # try to connect LDAP server
 	return 1
 }
 change_password () {  # old-password-file new-password-file
+	echowithtimestamp "Performing LDAP modification, set new password .." >&3
 	/usr/sbin/univention-directory-manager "computers/$server_role" modify \
 		--binddn "$ldap_hostdn" \
 		--bindpwdfile "$1" \
 		--dn "$ldap_hostdn" \
 		--set password="$(<"$2")" >&3 2>&3
+	echowithtimestamp ".. done" >&3
 }
 run_hooks () {
 	# Never use --exit-on-error with run-parts scripts because after an exit-on-error
@@ -91,18 +94,18 @@ restart_udl () {
 # 2 -> empty
 is_ucr_true server/password/change
 if [ $? = 1 ]; then
-	echo "($(date '+%F %T.%N')) Server password change is disabled by the UCR variable server/password/change" >&3
+	echowithtimestamp "Server password change is disabled by the UCR variable server/password/change" >&3
 	exit 0
 fi
 
 [ -n "$server_role" ] ||
-	FAIL "($(date '+%F %T.%N')) failed to change server password: empty config-registry variable server/role"
+	FAIL "failed to change server password: empty config-registry variable server/role"
 [ -n "$ldap_hostdn" ] ||
-	FAIL "($(date '+%F %T.%N')) failed to change server password: empty config-registry variable ldap/hostdn"
+	FAIL "failed to change server password: empty config-registry variable ldap/hostdn"
 [ -e "$MSECRET" ] ||
-	FAIL "($(date '+%F %T.%N')) failed to change server password: $MSECRET not found"
+	FAIL "failed to change server password: $MSECRET not found"
 [ -e "/var/lib/univention-directory-replication/failed.ldif" ] &&
-	FAIL "($(date '+%F %T.%N')) failed to change server password: /var/lib/univention-directory-replication/failed.ldif exists"
+	FAIL "failed to change server password: /var/lib/univention-directory-replication/failed.ldif exists"
 
 # Allow password change only if it is scheduled.
 epoch_last_change="$(stat --format %Y "$MSECRET")"
@@ -110,15 +113,15 @@ epoch="$(date +%s)"
 seconds_last_change="$((epoch- epoch_last_change))"
 days_last_change="$((seconds_last_change/60/60/24))"
 if [ "$server_password_interval" -gt "$days_last_change" ]; then
-	echo "($(date '+%F %T.%N')) No server password change scheduled for today, terminating without a change" >&3
+	echowithtimestamp "No server password change scheduled for today, terminating without a change" >&3
 	exit 0
 fi
 
-echo "($(date '+%F %T.%N')) Proceeding with regular server password change scheduled for today" >&3
+echowithtimestamp "Proceeding with regular server password change scheduled for today" >&3
 
 # Try to use a trivial command just to check that LDAP server is reachable.
 univention-ldapsearch -D "$ldap_hostdn" -y "$MSECRET" -s base 1.1 >/dev/null 2>&3 ||
-	FAIL "($(date '+%F %T.%N')) failed to contact LDAP server: cannot connect with univention-ldapsearch"
+	FAIL "failed to contact LDAP server: cannot connect with univention-ldapsearch"
 
 old_pass="$(mktemp "$MSECRET.XXXXXXXX")"
 new_pass="$(mktemp "$MSECRET.XXXXXXXX")"
@@ -131,12 +134,12 @@ ln -f "$MSECRET" "$old_pass"
 # shellcheck disable=SC2015
 create_machine_password >"$new_pass" &&
 	[ -s "$new_pass" ] ||
-	FAIL "($(date '+%F %T.%N')) failed to change server password: create_machine_password() returned an empty password"
+	FAIL "failed to change server password: create_machine_password() returned an empty password"
 
 if ! run_hooks prechange
 then
 	run_hooks nochange
-	FAIL "($(date '+%F %T.%N')) run-parts failed during prechange, rolling back with nochange, server password unchanged"
+	FAIL "run-parts failed during prechange, rolling back with nochange, server password unchanged"
 fi
 
 # check if we are in sync with the Primary Directory Node, if not then rollback with "nochange".
@@ -153,16 +156,16 @@ check_in_sync () {
 			read -r lid </var/lib/univention-directory-listener/notifier_id
 			if [ -x "/usr/share/univention-directory-listener/get_notifier_id.py" ]; then
 				nid=$(/usr/share/univention-directory-listener/get_notifier_id.py 2>&3) ||
-					echo "($(date '+%F %T.%N')) Could not get notifier id from Primary Directory Node!" >&3
+					echowithtimestamp "Could not get notifier id from Primary Directory Node!" >&3
 			fi
 			[ "${lid:-0}" = "${nid:-1}" ] &&
 					return 0
 		fi
-		echo " ($(date '+%F %T.%N')) Pending listener transactions (lid=$lid < nid=$nid), waiting ..." >&3
+		echowithtimestamp "Pending listener transactions (lid=$lid < nid=$nid), waiting ..." >&3
 		sleep 2
 	done
 	run_hooks nochange
-	FAIL "($(date '+%F %T.%N')) Pending listener transactions timeout, rolling back with nochange, server password unchanged"
+	FAIL "Pending listener transactions timeout, rolling back with nochange, server password unchanged"
 }
 check_in_sync
 
@@ -172,7 +175,7 @@ if ! change_password "$old_pass" "$new_pass"
 # then rollback the previous run-parts operation. 
 then
 	run_hooks nochange
-	FAIL "($(date '+%F %T.%N')) failed to change server password for $ldap_hostdn"
+	FAIL "failed to change server password for $ldap_hostdn"
 fi
 
 # If the changed server password has really been set correctly, then we can already use it.
@@ -187,7 +190,7 @@ then
 		change_password "$new_pass" "$old_pass"
 
 		run_hooks nochange
-		FAIL "($(date '+%F %T.%N')) resetting old server password for $ldap_hostdn, because access to Primary Directory Node LDAP did not work with the new password"
+		FAIL "resetting old server password for $ldap_hostdn, because access to Primary Directory Node LDAP did not work with the new password"
 fi
 
 # Now that we are sure the new password already works with Primary Directory Node LDAP,
@@ -221,7 +224,7 @@ if ! run_hooks localchange --regex '^univention-samba4'
 # if samba-tool user setpassword fails, reset the old password.
 then
 	revert_password_change
-	FAIL "($(date '+%F %T.%N')) Failed to set new password in samba, machine password set back to old password for $ldap_hostdn."
+	FAIL "Failed to set new password in samba, machine password set back to old password for $ldap_hostdn."
 fi
 
 # The password is changed on the Primary Directory Node now, but it is not clear if
@@ -234,7 +237,7 @@ then
 		# changes that would only worsen the situation. Instead, try to rollback.
 		# Reset the old password with UDM and give up.
 		revert_password_change
-		FAIL "($(date '+%F %T.%N')) Access to local LDAP did not work with the new password, machine password set back to old password for $ldap_hostdn."
+		FAIL "Access to local LDAP did not work with the new password, machine password set back to old password for $ldap_hostdn."
 fi
 
 # At this point the server password has been changed.
@@ -252,7 +255,7 @@ esac
 
 run_hooks postchange
 
-echo "($(date '+%F %T.%N')) done" >&3
+echowithtimestamp "done" >&3
 exec 3<&-
 
 exit 0
