* Write changes to /var/lib/univention-ldap/listener/listener instead   of /var/lib/univention-ldap/notify/transaction (Bug #27625) * Stop slapd while adding a DN to the listener/listener file   (Bug #27625)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@35095 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/management/univention-directory-notifier/univention-replicate-one b/management/univention-directory-notifier/univention-replicate-one
--- a/management/univention-directory-notifier/univention-replicate-one
+++ b/management/univention-directory-notifier/univention-replicate-one
@@ -38,6 +38,8 @@ usage()
 	echo
 	echo "The given LDAP DN will be replicated as if it has been modified."
 	echo
+	echo "WARNING: This tool will stop the OpenLDAP and the Notifier daemon"
+	echo
 }
 
 if [ "$server_role" != "domaincontroller_master" ]; then
@@ -57,25 +59,63 @@ fi
 
 dn="$2"
 
-RESTART=0
+RESTART_NOTIFIER=0
 if pidof univention-directory-notifier >/dev/null ; then
-	RESTART=1
+	echo -n "Stopping notifier: "
+	RESTART_NOTIFIER=1
 	invoke-rc.d univention-directory-notifier stop >/dev/null
 	sleep 1
 	if pidof univention-directory-notifier >/dev/null ; then
+		echo "failed"
 		echo "Abort: Failed to stop the notifier daemon. Please check stop the daemon manually and try again."
 		exit 1
 	fi
+	echo "done"
 fi
 
+RESTART_SLAPD=0
+if pidof slapd >/dev/null ; then
+	echo -n "Stopping slapd: "
+	RESTART_SLAPD=1
+	invoke-rc.d slapd stop >/dev/null
+	sleep 1
+	if pidof slapd >/dev/null ; then
+		echo "failed"
+		echo "Abort: Failed to stop the OpenLDAP daemon. Please check stop the daemon manually and try again."
+		exit 1
+	fi
+	echo "done"
+fi
+
+
+echo -n "Write $dn to transaction file: "
 id="$(tail -n 1 /var/lib/univention-ldap/notify/transaction | awk '{print $1}')"
 
-nextid=$((id+1))
+last_line="$(tail -n 1 /var/lib/univention-ldap/listener/listener)"
+if [ -n "$last_line" ]; then
+	id_listener="$(tail -n 1 /var/lib/univention-ldap/listener/listener | awk '{print $1}')"
+fi
 
-echo "$nextid $dn m" >>/var/lib/univention-ldap/notify/transaction
+if [ -n "$id_listener" ] && [ "$id_listener" -gt "$id" ]; then
+	nextid=$((id_listener+1))
+else
+	nextid=$((id+1))
+fi
 
-if [ "$RESTART" = 1 ]; then
+echo "$nextid $dn m" >>/var/lib/univention-ldap/listener/listener
+echo -n "$nextid" >/var/lib/univention-ldap/last_id
+echo "done"
+
+if [ "$RESTART_NOTIFIER" = 1 ]; then
+	echo -n "Starting notifier: "
 	invoke-rc.d univention-directory-notifier start >/dev/null
+	echo "done"
+fi
+
+if [ "$RESTART_SLAPD" = 1 ]; then
+	echo -n "Starting slapd: "
+	invoke-rc.d slapd start >/dev/null
+	echo "done"
 fi
 
 exit 0
