* improved performance and stability for 50_samba tests (Bug #27654)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@37464 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/50_samba/20grouplist b/test/ucs-test/tests/50_samba/20grouplist
--- a/test/ucs-test/tests/50_samba/20grouplist
+++ b/test/ucs-test/tests/50_samba/20grouplist
@@ -15,14 +15,26 @@ PERSON="false"
 POSIX="false"
 
 
-NAME=`user_randomname`
+username="$(user_randomname)"
 
-trap 'user_remove "$NAME"' INT TERM EXIT
-user_create "$NAME"
+trap 'user_remove "$username"' INT TERM EXIT
+user_create "$username"
 
-sleep 20 # wait for replication
+#wait for the user to be created
+i=0
+while true
+do
+    let i=$i+1
+    sleep 1
+    net rpc user -U"$username%$password" | grep "$username" > /dev/null && break
+    if [ $i == 20 ]; then
+	echo "TIMEOUT: The User which has been created in UDM could not be found in samba."
+	break
+    fi
+done
 
-if net rpc group -U "$NAME%univention" | grep -q "Domain Users"
+
+if net rpc group -U "$username%univention" | grep -q "Domain Users"
 then
 	echo "***The test trying to display samba-Groups as a user went like it should, everything is ok"
 else
diff --git a/test/ucs-test/tests/50_samba/25domain-join-without-admin-rights b/test/ucs-test/tests/50_samba/25domain-join-without-admin-rights
--- a/test/ucs-test/tests/50_samba/25domain-join-without-admin-rights
+++ b/test/ucs-test/tests/50_samba/25domain-join-without-admin-rights
@@ -17,19 +17,29 @@ MAIL="false"
 KERBEROS="false"
 PERSON="false"
 POSIX="true"
-NAME=`user_randomname`
-trap 'user_remove "$NAME"' INT TERM EXIT
-user_create "$NAME"
+username="$(user_randomname)"
+trap 'user_remove "$username"' INT TERM EXIT
+user_create "$username"
 
-ADMINISTRATOR_DN=$(univention-directory-manager users/user list --filter uid="$ADMINISTRATOR_USER" | sed -ne 's/^DN: //p')
-USER_DN=$(univention-directory-manager users/user list --filter uid="$NAME" | sed -ne 's/^DN: //p')
+#wait for the user to be created
+i=0
+while true
+do
+    let i=$i+1
+    sleep 1
+    net rpc user -U"$username%$univention" | grep "$username" > /dev/null && break
+    if [ $i == 20 ]; then
+	echo "TIMEOUT: The User which has been created in UDM could not be found in samba."
+	break
+    fi
+done
 
-net rpc join -U "$NAME"%univention && \
+
+ADMINISTRATOR_DN="$(univention-directory-manager users/user list --filter uid="$ADMINISTRATOR_USER" | sed -ne 's/^DN: //p')"
+USER_DN="$(univention-directory-manager users/user list --filter uid="$username" | sed -ne 's/^DN: //p')"
+
+net rpc join -U "$username"%univention && \
 	{ fail_fast 1 "Did a Domain join without the SeMachineAccountPrivilege"; }
-
-#net rpc rights grant -U "$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" "$NAME" SeMachineAccountPrivilege || \
-#	{ fail_fast 1 "Couldn't assign SeMachineAccountPrivilege to the user"; }
-
 
 univention-directory-manager users/user modify --binddn "$ADMINISTRATOR_DN" \
                                  	--bindpwd "$ADMINISTRATOR_PASSWORD" \
@@ -38,7 +48,7 @@ univention-directory-manager users/user modify --binddn "$ADMINISTRATOR_DN" \
 
 for i in {0..10}
 do
-	net rpc join -U "$NAME"%univention || \
+	net rpc join -U "$username"%univention || \
 	{ fail_fast 1 "Domain join failed"; }
 done
 
