* improvements in all samba Tests (Bug #27654)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@38644 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/50_samba/36_printer b/test/ucs-test/tests/50_samba/36_printer
--- a/test/ucs-test/tests/50_samba/36_printer
+++ b/test/ucs-test/tests/50_samba/36_printer
@@ -11,6 +11,7 @@
 . "$TESTLIBPATH/random.sh" || exit 137
 
 #create user
+echo "----Create user"
 SAMBA="true"
 MAIL="false"
 KERBEROS="true"
@@ -18,74 +19,107 @@ PERSON="false"
 POSIX="true"
 
 username="$(user_randomname)"
-printername=test36printer
-password=univention
+printername="test36printer"
+password="univention"
 
 trap '
 user_remove "$username";
 rm -rf "/tmp/$printername"/ /tmp/print_input;
-univention-directory-manager shares/printer remove --dn="$PRINTER_DN"
+/usr/sbin/univention-directory-manager shares/printer remove --dn="$PRINTER_DN"
 ' INT TERM EXIT
-user_create "$username" || fail_test 1 "Could not create user $username."
 
-#wait for the user to be created
+if ! user_create "$username"; then
+	fail_fast 1 "User could not be created"
+fi
+
+##wait for the user to be created
+echo "----wait for the user to be created"
 i=0
-while true
+while ! output="$(net rpc user info $username -U"$username%$password" 2>&1)"
 do
-    let i=$i+1
-    sleep 1
-    net rpc user -U"$username%$password" | grep "$username" > /dev/null && break
-    if [ $i == 20 ]; then
-	echo "TIMEOUT: The User which has been created in UDM could not be found in samba."
-	break
-    fi
+	let i="$i"+1
+	if [ "$i" = 20 ]; then
+		echo "$output"
+		echo "TIMEOUT: The User which has been created in UDM could not be found in samba ldb"
+	fi
+	sleep 1
 done
 
-#create printer
-udm shares/printer create --set "name=$printername" --set "spoolHost=$hostname.$domainname" --set "uri=file:/ tmp/$printername" --set "model=None"
-sleep 5
-univention-directory-manager shares/printer list --filter cn="$printername" | sed -ne 's/^DN: //p' | grep "$printername"
-#initiate print
+##create printer
+/usr/sbin/univention-directory-manager shares/printer create \
+	--set "name=$printername" \
+	--set "spoolHost=$hostname.$domainname" \
+	--set "uri=file:/ tmp/$printername" \
+	--set "model=None"
+if [ "$?" != 0 ];then
+	fail_fast 1 "failed to create printer"
+fi
+
+##wait for printer
+sleep 10
+
+/usr/sbin/univention-directory-manager shares/printer list --filter cn="$printername" | sed -ne 's/^DN: //p' | grep "$printername"
+if [ "$?" != 0 ];then
+	fail_fast 1 "failed to modify printer"
+fi
+
+##get the printer DN
+echo "----get the printer DN"
 i=0
-while true
+while ! PRINTER_DN="$(univention-ldapsearch cn=test36printer | sed -ne 's/^dn: //p')"
 do
-    let i=$i+1
-    sleep 1
-    echo $i
-    PRINTER_DN="$(univention-directory-manager shares/printer list --filter cn="$printername" | sed -ne 's/^DN: //p' | grep "$printername")" && break
-    echo "$PRINTER_DN"
-    if [ $i == 100 ]; then
-	echo "Could not create print_input"
-	break
-    fi
+	let i="$i"+1
+	sleep 1
+	if [ $i = 100 ]; then
+		echo "Could not get printer DN"
+		break
+	fi
 done
+
+
+## look for printer
+echo "----Looking for samba printer share '$printername'"
+i=0
+while ! output="$(smbclient -NL localhost | grep -qE "^\s+$printername\s+Printer" 2>&1)"
+do
+	echo '.'
+	let i="$i"+1
+	if [ "$i" = 20 ]; then
+		print "output"
+		fail_fast 1 "Samba did not provide the printer share 20 seconds after creation"
+	fi
+	sleep 1
+done
+
+##create input file
+echo "----Creating input file"
 
 echo "$(uname -a)" > "/tmp/print_input"
 
-#initiate print
+## initiate print
+echo "----initiate print"
 i=0
-while true
+while ! output="$(smbclient -U"$username%$password" "//$hostname.$domainname/$printername" -c "print /tmp/print_input" 2>&1)"
 do
-    let i=$i+1
-    sleep 2
-    smbclient -U"$username%$password" "//$hostname.$domainname/$printername" -c "print /tmp/print_input" && break
-    if [ $i == 15 ]; then
-	echo "Initiate printing has not been successful."
-	break
-    fi
+	let i=$i+1
+	if [ "$i" = 20 ]; then
+		echo "$output"
+		fail_fast 1 "Initiate printing has not been successful."
+	fi
+	sleep 1
 done
 
-#initiate print
+## check output
+echo "----check output"
 i=0
-while true
+while ! output="$(grep "$(uname -a)" "/tmp/$printername")"
 do
-    let i=$i+1
-    sleep 1
-    grep "$(uname -a)" "/tmp/$printername" && break
-    if [ $i == 10 ]; then
-	fail_test "Nothing has been printed to the output file."
-	break
-    fi
+	let i="$i"+1
+	if [ "$i" = 10 ]; then
+		echo "$output"
+		fail_fast 1 "Nothing has been printed to the output file."
+	fi
+	sleep 1
 done
 
 exit $RETVAL
diff --git a/test/ucs-test/tests/50_samba/40password-policies b/test/ucs-test/tests/50_samba/40password-policies
--- a/test/ucs-test/tests/50_samba/40password-policies
+++ b/test/ucs-test/tests/50_samba/40password-policies
@@ -3,13 +3,16 @@
 ## exposure: safe
 ## packages:
 ##  - univention-samba
-## roles-not: [basesystem]
+## roles-not:
+## - basesystem
+## - memberserver
 ## tags: [basic]
 
 . "$TESTLIBPATH/user.sh" || exit 137
 . "$TESTLIBPATH/random.sh" || exit 137
 
-#create user
+##create user
+echo "----create user"
 SAMBA="true"
 MAIL="false"
 KERBEROS="true"
@@ -17,80 +20,105 @@ PERSON="false"
 POSIX="true"
 
 username="$(user_randomname)"
-first_password=univention
+first_password="univention"
 second_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}äöü)"
 third_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}äöü)"
 
 trap 'user_remove "$username"' INT TERM EXIT
 
-user_create "$username" || fail_test 1 "Could not create user $username."
+if ! user_create "$username"; then
+	fail_fast 1 "User could not be created"
+fi
 
-#sleep 20
-#wait for the user to be created
+
+##wait for the user to be created
+echo "----wait for the user to be created"
 i=0
-while true
+while ! output="$(net rpc user info $username -U"$username%$first_password" 2>&1)"
 do
-    let i=$i+1
-    sleep 1
-    net rpc user -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" | grep "$username" > /dev/null && break
-    if [ $i == 20 ]; then
-	echo "TIMEOUT: The user which has been created in UDM could not be found in samba after $i seconds"
-	break
-    fi
+	let i="$i"+1
+	sleep 1
+	if [ "$i" = 20 ]; then
+		echo "$output"
+		echo "TIMEOUT: The user which has been created in UDM could not be found in samba after $i seconds"
+		break
+	fi
 done
 
-ADMINISTRATOR_DN=$(univention-directory-manager users/user list --filter uid="$ADMINISTRATOR_USER" | sed -ne 's/^DN: //p')
-USER_DN=$(univention-directory-manager users/user list --filter uid="$username" | sed -ne 's/^DN: //p')
+ADMINISTRATOR_DN="$(/usr/sbin/univention-directory-manager users/user list --filter uid="$ADMINISTRATOR_USER" | sed -ne 's/^DN: //p')"
+USER_DN="$(/usr/sbin/univention-directory-manager users/user list --filter uid="$username" | sed -ne 's/^DN: //p')"
 
-#test normal connection
-net rpc user -U"$username%$first_password" | grep "$username" > /dev/null || fail_test 1 "initial authentification failed"
+##test normal connection
+echo "----net rpc:test normal connection"
+output="$(net rpc info -U"$username%$first_password")"
 
-#set pwdChangeNextLogin=1 so that the user hast to change the password at the next login
-univention-directory-manager users/user modify --binddn "$ADMINISTRATOR_DN" --bindpwd "$ADMINISTRATOR_PASSWORD" --dn "$USER_DN" --set pwdChangeNextLogin=1 || fail_test 1 "Could not modify the user using udm."
+if [ "$?" != 0 ];then
+	echo "$output"
+	fail_test 1 "initial authentification failed"
+fi
 
-sleep 5
+##set pwdChangeNextLogin=1 so that the user has to change the password at the next login
+echo "----set pwdChangeNextLogin=1"
+output="$(/usr/sbin/univention-directory-manager users/user modify --binddn "$ADMINISTRATOR_DN" --bindpwd "$ADMINISTRATOR_PASSWORD" --dn "$USER_DN" --set pwdChangeNextLogin=1)"
+if [ "$?" != 0 ];then
+	echo "$output"
+	fail_test 1 "Could not modify the user using udm."
+fi
 
-#try to login without changing the password, should fail
-net rpc user -U"$username%$first_password" | grep "$username" > /dev/null && fail_test 1 "Could login without changing the password."
+sleep 10
 
-#changing the password with net rpc / samba
-python net_rpc_change_pwd.py -u "$username" -a "$ADMINISTRATOR_USER" -n "$second_password" -r "$ADMINISTRATOR_PASSWORD"
+##try to login without changing the password, should fail
+echo "----net rpc: try to login without changing the password (should fail)"
+output="$(net rpc info -U"$username%$first_password")"
+if [ "$?" = 0 ];then
+	fail_test 1 "Could login without changing the password."
+fi
 
-#sleep 20
+##changing the password with net rpc / samba
+echo "----changing the password with net rpc"
+output="$(python net_rpc_change_pwd.py -u "$username" -a "$ADMINISTRATOR_USER" -n "$second_password" -r "$ADMINISTRATOR_PASSWORD")"
+if [ "$?" != 0 ]; then
+	echo "$output"
+	fail_test 1 "Could not change the password."
+fi
 
 
-#try to login with a new password
+##try to login with a new password
+echo "----net rpc:try to login with a new password"
 i=0
-while true
+while ! output="$(net rpc info -U"$username%$second_password" 2>&1)"
 do
-    let i=$i+1
-    sleep 1
-    net rpc user -U"$username%$second_password" | grep "$username" > /dev/null && break
-    if [ "$i" == 20 ]; then
-	fail_test 1 "Could not login using samba with new password after password change."
-    fi
+	let i="$i"+1
+	sleep 1
+	if [ "$i" = 20 ]; then
+		echo "$output"
+		fail_test 1 "Could not login using samba with new password after password change."
+	fi
 done
 
+##try to login with old password, should not work                                                                                                       
+echo "----net rpc:try to login with old password (should fail)"
+output="$(net rpc info -U"$username%$first_password")"
+if [ "$?" = 0 ];then
+	echo "$output"
+	fail_test 1 "Could login using samba with old password after password change."
+fi
 
-#try to login with old password, should not work                                                                                                       
-net rpc user -U"$username%$first_password" | grep "$username" > /dev/null && fail_test 1 "Could login using samba with old password after password change."
-
-#check authentification with UDM                                                                                                                                                             
-#--old password
-i=0
-while true
-do
-    let i=$i+1
-    sleep 1
-    /usr/sbin/univention-directory-manager users/user list --binddn "$USER_DN" --bindpwd "$second_password" > /dev/null
-    if [ "$?" == 0 ];then
-	break
-    fi
-    if [ "$i" == 20 ]; then
+##check authentification with UDM                                                                                                                                                            
+##--old password
+echo "----UDM:try to login with old password (should fail)"
+output="$(/usr/sbin/univention-directory-manager users/user list --filter uid="$username" --binddn "$USER_DN" --bindpwd "$second_password")"
+if [ "$?" != 0 ];then
+	echo "$output"
 	fail_test 1 "Could not login using UDM with new password after password change."
-    fi
-done
-#--new password
-/usr/sbin/univention-directory-manager users/user list --binddn "$USER_DN" --bindpwd "$first_password" > /dev/null && fail_test 1 "Could login using UDM with old password after password change."
+fi
+
+##--new password
+echo "----UDM:try to login with new password"
+output="$(/usr/sbin/univention-directory-manager users/user list --filter uid="$username" --binddn "$USER_DN" --bindpwd "$first_password")"
+if [ "$?" = 0 ];then
+	echo "$output"
+	fail_test 1 "Could login using UDM with old password after password change."
+fi
 
 exit $RETVAL
diff --git a/test/ucs-test/tests/50_samba/41password_change b/test/ucs-test/tests/50_samba/41password_change
--- a/test/ucs-test/tests/50_samba/41password_change
+++ b/test/ucs-test/tests/50_samba/41password_change
@@ -10,10 +10,10 @@
 
 . "$TESTLIBPATH/base.sh" || exit 137
 . "$TESTLIBPATH/user.sh" || exit 137
-. "$TESTLIBPATH/shares.sh" || exit 137
 . "$TESTLIBPATH/random.sh" || exit 137
 
-#setup:create user and share
+echo "----create user"
+##create user
 SAMBA="true"
 MAIL="false"
 KERBEROS="true"
@@ -21,40 +21,78 @@ PERSON="false"
 POSIX="true"
 
 username="$(user_randomname)"
-first_password=univention
+first_password="univention"
 second_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}äöü)1AÄÜÖ"
 third_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}äöü)1AÄÜÖ"
-sharename="$(random_share)"
 
-trap 'user_remove "$username";share_remove $sharename' INT TERM EXIT
+trap 'user_remove "$username"' INT TERM EXIT
 
-user_create "$username" || fail_test 1 "Could not create user $username."
+if ! user_create "$username"; then
+	fail_fast 1 "User could not be created"
+fi
 
-share_create "$sharename" /"$sharename"  || fail_test 1 "Could not create share $sharename."
 
-share_dn=$(univention-directory-manager shares/share list --filter sambaName="$sharename" | sed -ne 's/^DN: //p')
-udm shares/share modify --dn="$share_dn" --set sambaPublic=1  || fail_test 1 "Could not modify share $sharename."
+##wait for the user to be created
+echo "----wait for the user to be created"
+i=0
+while ! output="$(net rpc user info $username -U"$username%$password" 2>&1)"
+do
+	let i="$i"+1
+	if [ "$i" = 20 ]; then
+		echo "$output"
+		echo "TIMEOUT: The User which has been created in UDM could not be found in samba ldb"
+	fi
+	sleep 1
+done
 
-ADMINISTRATOR_DN=$(univention-directory-manager users/user list --filter uid="$ADMINISTRATOR_USER" | sed -ne 's/^DN: //p')
-USER_DN=$(univention-directory-manager users/user list --filter uid="$username" | sed -ne 's/^DN: //p')
+ADMINISTRATOR_DN="$(/usr/sbin/univention-directory-manager users/user list --filter uid="$ADMINISTRATOR_USER" | sed -ne 's/^DN: //p')"
+USER_DN="$(/usr/sbin/univention-directory-manager users/user list --filter uid="$username" | sed -ne 's/^DN: //p')"
 
-sleep 20
+##test normal connection with smbclient
+echo "----test normal connection with smbclient"
+output="$(smbclient -U "$username%$first_password" "//$hostname.$domainname/netlogon" -c "exit")"
+if [ "$?" != 0 ];then
+	echo "$output"
+	fail_test 1 "Could not connect to netlogon with smbclient."
+else
+	echo "OK"
+fi
 
-#test normal connection to the share
-smbclient -U "$username%$first_password" "//$hostname.$domainname/$sharename" -c "exit"  || fail_test 1 "Could not connect to the share."
+##changing the password with net rpc / samba
+echo "----changing the password with net rpc"
+output="$(python net_rpc_change_pwd.py -u "$username" -a "$ADMINISTRATOR_USER" -n "$second_password" -r "$ADMINISTRATOR_PASSWORD")"
+if [ "$?" != 0 ];then
+	echo "$output"
+	fail_test 1 "Failed to change the password"
+fi
 
-#changing the password with net rpc / samba
-python net_rpc_change_pwd.py -u "$username" -a "$ADMINISTRATOR_USER" -n "$second_password" -r "$ADMINISTRATOR_PASSWORD"
+##test login with udm with new password
+echo "----test login with udm with new password"
+i=0
+while ! output="$(univention-directory-manager users/user list --filter uid="$username" --binddn "$USER_DN" --bindpwd "$second_password")"
+do
+	let i="$i"+1
+	if [ "$i" = 20 ]; then
+		echo "$output"
+		fail_test 1 "Could not authentificate with UDM after password change with smbpasswd."
+	fi
+	sleep 1
+done
 
-sleep 5
+##change the password with udm
+echo "----change the password with udm"
+output="$(/usr/sbin/univention-directory-manager users/user modify --binddn "$ADMINISTRATOR_DN" --bindpwd "$ADMINISTRATOR_PASSWORD" --dn "$USER_DN" --set "password=$third_password")"
+if [ "$?" != 0 ];then
+	echo "$output"
+	fail_test 1 "Could not change password with UDM"
+fi
 
-#test login with udm with new password
-univention-directory-manager users/user list --binddn "$USER_DN" --bindpwd "$second_password" > /dev/null || fail_test 1 "Could not authentificate with UDM after password change with smbpasswd."
-
-#change the password with udm
-univention-directory-manager users/user modify --binddn "$ADMINISTRATOR_DN" --bindpwd "$ADMINISTRATOR_PASSWORD" --dn "$USER_DN" --set "password=$third_password" || fail_test 1 "Could not change password with UDM"
-
-#test login with smbclient with new password
-smbclient -U "$username%$third_password" "//$hostname.$domainname/$sharename" -c "exit" || fail_test 1 "Could not authentificate login with smbclient after password change with UDM"
+##test login with smbclient with new password
+echo "----test login with smbclient with new password"
+output="$(smbclient -U "$username%$third_password" "//$hostname.$domainname/netlogon" -c "exit")"
+if [ "$?" != 0 ];then
+	echo "$output"
+	fail_test 1 "Could not authentificate login with smbclient after password change with UDM"
+fi
 
 exit $RETVAL
diff --git a/test/ucs-test/tests/50_samba/42file_access_permissions b/test/ucs-test/tests/50_samba/42file_access_permissions
--- a/test/ucs-test/tests/50_samba/42file_access_permissions
+++ b/test/ucs-test/tests/50_samba/42file_access_permissions
@@ -13,7 +13,8 @@
 . "$TESTLIBPATH/shares.sh" || exit 137
 . "$TESTLIBPATH/random.sh" || exit 137
 
-#create user and share
+##create user and share
+echo "----create user and share"
 SAMBA="true"
 MAIL="false"
 KERBEROS="true"
@@ -21,37 +22,85 @@ PERSON="false"
 POSIX="true"
 
 username="$(user_randomname)"
-first_password=univention
+first_password="univention"
 second_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}äöü)1AÜÄÖ"
 third_password="$(random_chars 8 ${_upperletters}${_lowerletters}${_ciphers}äöü)1AÜÄÖ"
 sharename="$(random_share)"
 
-trap 'user_remove "$username";share_remove $sharename' INT TERM EXIT
-user_create "$username" || fail_test 1 "Could not create user $username."
+trap 'user_remove "$username";share_remove $sharename;rm -rf "/opt/${sharename:?}";' INT TERM EXIT
 
-share_create "$sharename" /"$sharename"  || fail_test 1 "Could not create share $sharename."
+if ! user_create "$username"; then
+	fail_fast 1 "Could not create user $username."
+fi
+
+if ! share_create "$sharename" "/opt/$sharename"; then
+	fail_fast 1 "Could not create share $sharename."
+fi
 
 ADMINISTRATOR_DN="$(univention-directory-manager users/user list --filter uid="$ADMINISTRATOR_USER" | sed -ne 's/^DN: //p')"
-USER_DN="$(univention-directory-manager users/user list --filter uid="$username" | sed -ne 's/^DN: //p')"
-SHARE_DN=$(univention-directory-manager shares/share list --filter sambaName="$sharename" | sed -ne 's/^DN: //p')
+USER_DN="$(/usr/sbin/univention-directory-manager users/user list --filter uid="$username" | sed -ne 's/^DN: //p')"
+SHARE_DN="$(/usr/sbin/univention-directory-manager shares/share list --filter sambaName="$sharename" | sed -ne 's/^DN: //p')"
 
-udm shares/share modify --dn="$SHARE_DN" --set sambaPublic=1  || fail_test 1 "Could not modify share $sharename."
+## modify share attribute to prepare it for the test
+echo "----modify share attribute to prepare it for the test"
+shareProp="$(ls -l /etc/samba/shares.conf.d/"$sharename")"
+shareProp2="$shareProp"
 
-sleep 20
+/usr/sbin/univention-directory-manager shares/share modify --dn="$SHARE_DN" --set sambaPublic=1
+if [ "$?" != 0 ]; then
+	fail_test 1 "Could not modify share $sharename."
+fi
 
-echo smbclient -U "$username%$first_password" "//$hostname.$domainname/$sharename" -c "exit"  || fail_test 1 "Could not connect to the share."
-#test normal connection to the share
-smbclient -U "$username%$first_password" "//$hostname.$domainname/$sharename" -c "exit"  || fail_test 1 "Could not connect to the share."
+## wait until it is recognized in samba that the user has been modified
+echo "----wait until it is recognized in samba that the user has been modified"
+i=0
+while [ "$shareProp" = "$shareProp2" ]
+do
+	let i="$i"+1
+	sleep 1
+	shareProp2="$(ls -l /etc/samba/shares.conf.d/"$sharename")"
+	if [ "$i" = 20 ]; then
+		echo "TIMEOUT: Modification of $sharename haven't had any impact on the file in /etc/samba/shares.conf.d yet."
+		break
+	fi
+done
 
-#try to create a folder as a user, should fail
-return_val="$(smbclient -U "$username%$first_password" "//$hostname.$domainname/$sharename" -c "mkdir folder")"
-echo $return_val | grep "NT_STATUS_ACCESS_DENIED" || fail_test 1 "Expected return value NT_STATUS_ACCESS_DENIED, but received: $return_val"
+## test normal connection to the share
+echo "----test normal connection to the share"
+i=0
+while ! output="$(smbclient -U "$username%$first_password" "//$hostname.$domainname/$sharename" -c "exit" >/dev/null 2>&1)"
+do
+	let i="$i"+1
+	sleep 1
+	if [ "$i" = 20 ]; then
+		echo "$output"
+		fail_test 1 "Could not connect to the share."
+	fi
+done
 
-#change directory mode, to enable write access for user
-univention-directory-manager shares/share modify --binddn "$ADMINISTRATOR_DN" --bindpwd "$ADMINISTRATOR_PASSWORD" --dn "$SHARE_DN" --set "directorymode=0777"
+## try to create a folder as a user, should fail
+echo "----try to create a folder as a use (should fail)"
+output="$(smbclient -U "$username%$first_password" "//$hostname.$domainname/$sharename" -c "mkdir folder")"
+if ! echo "$output" | grep "NT_STATUS_ACCESS_DENIED"; then
+	fail_test 1 "Expected return value NT_STATUS_ACCESS_DENIED, but received: $output"
+fi
 
-#try to create a folder as a user, should succeed
-return_val="$(smbclient -U "$username%$first_password" "//$hostname.$domainname/$sharename" -c "mkdir folder")"
-echo $return_val | grep "NT_STATUS_NOT_A_DIRECTORY" || fail_test 1 "Expected return value NT_STATUS_NOT_A_DIRECTORY, but received: $return_val"
+## change directory mode, to enable write access for user
+echo "----change directory mode, to enable write access for user"
+/usr/sbin/univention-directory-manager shares/share modify --binddn "$ADMINISTRATOR_DN" --bindpwd "$ADMINISTRATOR_PASSWORD" --dn "$SHARE_DN" --set "directorymode=0777"
 
+## try to create a folder as a user, should succeed
+echo "----try to create a folder as a user (should succeed)"
+retValue=1
+while ! [ "$retValue" = 0 ] &&  echo "$output"| grep "NT_STATUS_NOT_A_DIRECTORY" 
+do
+	output="$(smbclient -U "$username%$first_password" "//$hostname.$domainname/$sharename" -c "mkdir folder")"
+	retValue="$?"
+	let i="$i"+1
+	sleep 2
+	if [ "$i" = 10 ]; then
+		fail_test "Could not create a folder as a user after adjusting the directory mode."
+		break
+	fi
+done
 exit $RETVAL
