* run net rpc info against localhost (Bug #36208)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.0/ucs-4.0-0@54772 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/50_samba/40password-policies b/test/ucs-test/tests/50_samba/40password-policies
--- a/test/ucs-test/tests/50_samba/40password-policies
+++ b/test/ucs-test/tests/50_samba/40password-policies
@@ -46,8 +46,8 @@ wait_for_replication
 USER_DN="$(udm-test users/user list --filter uid="$username" | sed -ne 's/^DN: //p')"
 
 ##test normal connection
-echo "----net rpc:test normal connection"
-output="$(net rpc info -U"$username%$first_password")"
+echo "----net rpc: test normal connection"
+output="$(net rpc info -S localhost -U"$username%$first_password")"
 
 if [ "$?" != 0 ];then
 	echo "$output"
@@ -66,14 +66,15 @@ wait_for_replication
 
 ##try to login without changing the password, should fail
 echo "----net rpc: try to login without changing the password (should fail)"
-output="$(net rpc info -U"$username%$first_password")"
+output="$(net rpc info -S localhost -U"$username%$first_password")"
 if [ "$?" = 0 ];then
 	fail_test 1 "Could login without changing the password."
 fi
 
 ##changing the password with net rpc / samba
 echo "----changing the password with net rpc"
-net rpc user password "$username" "$second_password" -U"$admin_account%$tests_domainadmin_pwd" -S "$ldap_master"
+net rpc user password "$username" "$second_password" \
+	-U"$admin_account%$tests_domainadmin_pwd" -S "$ldap_master"
 if [ "$?" != 0 ]; then
 	error "net rpc user password change returned a non-zero exit code: $?. Continuing anyway, see Bug #31794"
 fi
@@ -81,9 +82,9 @@ fi
 wait_for_replication
 
 ##try to login with a new password
-echo "----net rpc:try to login with a new password"
+echo "----net rpc: try to login with a new password"
 i=0
-while ! output="$(net rpc info -U"$username%$second_password" 2>&1)"
+while ! output="$(net rpc info -S localhost -U"$username%$second_password" 2>&1)"
 do
 	let i="$i"+1
 	sleep 1
@@ -95,8 +96,8 @@ do
 done
 
 ##try to login with old password, should not work                                                                                                       
-echo "----net rpc:try to login with old password (should fail)"
-output="$(net rpc info -U"$username%$first_password")"
+echo "----net rpc: try to login with old password (should fail)"
+output="$(net rpc info -S localhost -U"$username%$first_password")"
 if [ "$?" = 0 ];then
 	echo "$output"
 	fail_test 1 "Could login using samba with old password after password change."
@@ -104,7 +105,7 @@ fi
 
 ##check authentification with UDM                                                                                                                                                            
 ##--old password
-echo "----UDM:try to login with old password (should fail)"
+echo "----UDM: try to login with old password (should fail)"
 output="$(udm users/user list --filter uid="$username" --binddn "$USER_DN" --bindpwd "$second_password")"
 if [ "$?" != 0 ];then
 	echo "$output"
@@ -112,7 +113,7 @@ if [ "$?" != 0 ];then
 fi
 
 ##--new password
-echo "----UDM:try to login with new password"
+echo "----UDM: try to login with new password"
 output="$(udm users/user list --filter uid="$username" --binddn "$USER_DN" --bindpwd "$first_password")"
 if [ "$?" = 0 ];then
 	echo "$output"
