fix[umc/dev]: CLI argument parsing
Bug #53108

diff --git a/management/univention-management-console/dev/umc-create-module b/management/univention-management-console/dev/umc-create-module
--- a/management/univention-management-console/dev/umc-create-module
+++ b/management/univention-management-console/dev/umc-create-module
@@ -31,32 +31,6 @@
 # /usr/share/common-licenses/AGPL-3; if not, see
 # <https://www.gnu.org/licenses/>.
 
-usage () {
-	cat <<EOF
-usage: $(basename $0) [<options>...] <moduleID> [<destinationDir>]
-
-destination dir:
-  If not given, it defaults to the current working directory.
-
-options:
-  --name         displayed name of the module
-  --description  verbose module description (shown as tooltip)
-  --category     category id (default: system)
-  --keywords     module keywords (default: 'dummy)
-  --package      package name
-  --icon         path to SVG icon file
-  --list         list available templates
-  --template     name of the template (default: grid_with_detailpage)
-  --no-debian    do not copy debian packages files
-
-EOF
-}
-
-if [ $# -eq 0 -o "$1" == "--help" -o "$1" == "-h" ]; then
-	usage
-	exit 1
-fi
-
 function err() {
 	echo
 	echo "ERROR: $@"
@@ -97,9 +71,38 @@ SRC_DIR="/usr/share/univention-management-console-dev/umc-module-templates"
 YEAR=$(date +'%Y')
 NO_DEBIAN=""
 
+usage () {
+	cat <<EOF
+usage: $(basename "$0") [<options>...] <moduleID> [<destinationDir>]
+
+destination dir:
+  If not given, it defaults to the current working directory.
+
+options:
+  --name         displayed name of the module
+  --description  verbose module description (shown as tooltip)
+  --category     category id (default: $CATEGORYNAME)
+  --keywords     module keywords (default: '$MODULEKEYWORDS)
+  --package      package name
+  --icon         path to SVG icon file
+  --list         list available templates
+  --template     name of the template (default: $TEMPLATE)
+  --no-debian    do not copy debian packages files
+
+EOF
+	exit "${1:-0}"
+}
+
 # parse the CLI parameters
-for iparam in "$@"; do
-	case "$iparam" in
+opts=$(getopt --options 'h' --longoptions 'help,name:,description:,keywords:,category:,package:,icon:,template:,list,no-debian' --name "${0##*/}" -- "$@") ||
+	usage 2
+eval set -- "$opts"
+while [ $# -ge 1 ]
+do
+	case "$1" in
+		--help|-h)
+			usage 0
+			;;
 		--name)
 			# shellcheck disable=SC2034
 			MODULENAME="$2"
@@ -140,6 +143,13 @@ for iparam in "$@"; do
 		--no-debian)
 			NO_DEBIAN="yes"
 			shift 1
+			;;
+		--)
+			shift
+			break
+			;;
+		*)
+			error "Internal error: $*"
 			;;
 	esac
 done
