univention-pkgdb (6.0.7-1) unstable; urgency=low
  * update database schema (Bug #21873, Bug #11364)
  * fix install/remove/purge (Bug #24096)
  * general cleanup (Bug #21873, Bug #13538)
  * support removal of systems from database (Bug #14929)

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@36144 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/services/univention-pkgdb/univention-pkgdb-check b/services/univention-pkgdb/univention-pkgdb-check
--- a/services/univention-pkgdb/univention-pkgdb-check
+++ b/services/univention-pkgdb/univention-pkgdb-check
@@ -32,26 +32,25 @@
 # /usr/share/common-licenses/AGPL-3; if not, see
 # <http://www.gnu.org/licenses/>.
 
-if [ ! -e /etc/postgresql/pkgdb.secret ] ;then
-  # no chance to do anything
-  echo "missing /etc/postgresql/pkgdb.secret"
-  exit 1
+if [ ! -e /etc/postgresql/pkgdb.secret ]
+then
+	# no chance to do anything
+	echo "missing /etc/postgresql/pkgdb.secret"
+	exit 1
 fi
 
-
-/usr/share/pyshared/univention/pkgdb.py --test-superuser
-if [ $? -ne 0 ] ;then
-  # or service record not found
-  echo "check the postgres installation, the command '/usr/share/pyshared/univention/pkgdb.py --test-superuser' failed"
-  exit 1
+if ! univention-pkgdb-scan --test-superuser
+then
+	# or service record not found
+	echo "check the postgres installation, the command 'univention-pkgdb-scan --test-superuser' failed"
+	exit 1
 fi
 
 find /var/lib/univention-pkgdb/add/ -type f | while read file; do
 	host=`basename $file`
-	/usr/share/pyshared/univention/pkgdb.py --add-system "$host"
-	ret=$?
-	if [ $ret = 0 ]; then
-		rm $file
+	if univention-pkgdb-scan --add-system "$host"
+	then
+		rm "$file"
 	else
 		echo "pkgdb: failed to remove $host"
 	fi
@@ -59,10 +58,9 @@ done
 
 find /var/lib/univention-pkgdb/delete/ -type f | while read file; do
 	host=`basename $file`
-	/usr/share/pyshared/univention/pkgdb.py --del-system "$host"
-	ret=$?
-	if [ $ret = 0 ]; then
-		rm $file
+	if univention-pkgdb-scan --del-system "$host"
+	then
+		rm "$file"
 	else
 		echo "pkgdb: failed to add $host"
 	fi
