* Bug #44635: Run dbcheck on update if required. Backup first.
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.2/ucs-4.2-1@82031 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/services/univention-samba4/debian/univention-samba4.postinst b/services/univention-samba4/debian/univention-samba4.postinst
--- a/services/univention-samba4/debian/univention-samba4.postinst
+++ b/services/univention-samba4/debian/univention-samba4.postinst
@@ -189,6 +189,37 @@ divert_univention_heimdal_service_cfg() {
 		--add "$univention_heimdal_service_cfg" || true
 }
 
+run_dbcheck() {
+	## run dbcheck on update but backup first.
+	if ! [ -d /var/lib/samba/private ]; then  # Hmm, well
+		return 0
+	fi
+
+	if samba-tool dbcheck --cross-ncs --quiet > /dev/null; then
+		return 0
+	fi
+
+	required_space=$(du -s -B 1024 /var/lib/samba/private | awk '{print $1}')
+	free_space=$(df -P -B 1024 /var/backups | tail -n1 | awk '{print $4}')
+	safety_margin=102400
+	if [ "$free_space" -lt $(($required_space + $safety_margin)) ]; then
+		echo "ERROR: Not enough space for backup, skipping samba-tool dbcheck --cross-ncs --fix --yes"
+		return 1
+	fi
+
+	backup_id=$(date +%Y%m%d-%H%M%S)
+	backup_dir="/var/backups/samba4_update_to_errata4.1-4.$backup_id"
+	if [ -d "$backup_dir" ]; then
+		rm -rf "$backup_dir"
+	fi
+	service samba stop
+	mkdir "$backup_dir" && \
+	cp -a /var/lib/samba/private "$backup_dir" && \
+	samba-tool dbcheck --cross-ncs --fix --yes \
+	> /var/backups/samba4_update_to_errata4.1-4.log 2>&1
+	service samba start
+}
+
 if [ "$1" = "configure" ]; then
 
 
@@ -316,21 +347,9 @@ secret: $machine_secret
 		if dpkg --compare-versions "$2" lt-nl "5.0.1-27"; then
 			divert_univention_heimdal_service_cfg
 		fi
-		### The following block of code may be removed after ucs_4.1-4
-		if dpkg --compare-versions "$2" lt-nl "5.0.1-53"; then
-			## run dbcheck on update but backup first.
-			if [ -d /var/lib/samba/private ]; then
-				backup_id=$(date +%Y%m%d-%H%M%S)
-				backup_dir="/var/backups/samba4_update_to_ucs4.1-4.$backup_id"
-				if [ -d "$backup_dir" ]; then
-					rm -rf "$backup_dir"
- 				fi
-				/etc/init.d/samba stop
-				mkdir "$backup_dir" && \
-				cp -a /var/lib/samba/private "$backup_dir" && \
-				samba-tool dbcheck --cross-ncs --fix --yes
-				/etc/init.d/samba start
- 			fi
+		### The following block of code may be removed after errata4.2-1
+		if dpkg --compare-versions "$2" lt-nl "6.0.10-26"; then
+			run_dbcheck
 		fi
 
 		# bug #41190 / bug #39806 - restart bind9 after bind-dlz changes
