* UCRV apache2/startsite will be set to correct values when reinstalling and uninstalling univention-system-setup-boot (Bug #31385) * Added error handling in case the download of required packages for univention-system-setup-boot failed. This could prevent a role switch when configuring the system in appliance setup. (Bug #30896) * Disabled Firefox update popups during appliance setup (Bug #30980) * Changelog entry
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs-3.1-2@40942 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/base/univention-system-setup/debian/univention-system-setup-boot.postinst b/base/univention-system-setup/debian/univention-system-setup-boot.postinst
--- a/base/univention-system-setup/debian/univention-system-setup-boot.postinst
+++ b/base/univention-system-setup/debian/univention-system-setup-boot.postinst
@@ -30,6 +30,17 @@
 # /usr/share/common-licenses/AGPL-3; if not, see
 # <http://www.gnu.org/licenses/>.
 
+check_returnvalue ()
+{
+	rval=$1
+	errormessage=$2
+	if [ "${rval}" != 0 ]; then
+		echo "${errormessage}"
+		exit "${rval}"
+	fi
+}
+
+
 eval "$(univention-config-registry shell)"
 
 . /usr/share/univention-lib/all.sh
@@ -59,15 +70,18 @@ if [ "$1" = "configure" ] && [ ! -e /var/univention-join/joined ]; then
 	install_cmd="$(univention-config-registry get update/commands/install)"
 	for package in server-master server-backup server-slave server-member basesystem; do
 		$install_cmd --reinstall -d -o Debug::NoLocking=1 -o Dir::Cache::Archives=/var/cache/univention-system-setup/packages univention-${package}
-	
+		check_returnvalue $? "Failed to download required packages for univention-${package}"
+
 		# Get all dependencies
 		dependencies="$(LC_ALL=C apt-cache show univention-${package} | grep Depends | head -n 1 | sed -e 's| \| [^,]*||g;s|,||g;s|([^(]*)||g;s|^Depends: ||')"
 		$install_cmd --reinstall -d -o Debug::NoLocking=1 -o Dir::Cache::Archives=/var/cache/univention-system-setup/packages ${dependencies}
+		check_returnvalue $? "Failed to download required dependency packages for univention-${package}"
 	done
 
 	(
 		cd /var/cache/univention-system-setup/packages/
 		apt-ftparchive packages . >Packages
+		check_returnvalue $? "Failed to create ftparchive directory"
 	)
 
 	if [ ! -e /etc/apt/sources.list.d/05univention-system-setup.list ]; then
@@ -75,13 +89,16 @@ if [ "$1" = "configure" ] && [ ! -e /var/univention-join/joined ]; then
 	fi
 fi
 
-if [ "$1" = configure ] && [ -z "$2" ]; then
+if [ "$1" = configure ]; then
 
 	# Redirect the apache start site to the wizard module
-	ucr set system/setup/prev/apache2/startsite="$(ucr get apache2/startsite)"
-	ucr set apache2/startsite='univention-management-console/?module=setup\&username=root'
-	if [ -x /etc/init.d/apache2 ]; then
-		/etc/init.d/apache2 restart
+	system_setup_boot_startsite='univention-management-console/?module=setup\&username=root'
+	if [ "$apache2_startsite" != "$system_setup_boot_startsite" ] ; then
+		ucr set system/setup/prev/apache2/startsite="$apache2_startsite"
+		ucr set apache2/startsite="$system_setup_boot_startsite"
+		if [ -x /etc/init.d/apache2 ]; then
+			/etc/init.d/apache2 restart
+		fi
 	fi
 fi
 
