Bug #42022: Apply patch from QA
What the QA said about the patch:
* The errors reported in the CHECK_RUN phase of univention-join are not
written to join.log but only to stdout. The attached patch would fix
both: a) log to join.log too and b) display the error message. If you
are installing from a DVD it's pretty hard for the user to retrieve the
join.log from that system (e.g. no ssh yet).

* The attached patch additionally adds another binddn search via GSSAPI
that could help avoid the issue reported on this bug itself: Currently,
in case the udm search fails, we only fall back to ldapsearch via LDAPI,
which only works for root, and finally anonymous LDAP search, which is
disabled by default. Both isn't likely to succeed. The GSSAPI search may
also fail, but it's at least something that could possibly work for
users != root.

diff --git a/management/univention-join/univention-join b/management/univention-join/univention-join
--- a/management/univention-join/univention-join
+++ b/management/univention-join/univention-join
@@ -106,6 +106,7 @@ display_version() {
 }
 
 failed_message () {
+	{
 	echo ""
 	echo ""
 	echo "**************************************************************************"
@@ -114,6 +115,7 @@ failed_message () {
 	echo "**************************************************************************"
 	echo "* Message:  Please visit https://help.univention.com/t/8842 for common problems during the join and how to fix them -- $@"
 	echo "**************************************************************************"
+	} | tee -a /var/log/univention/join.log
 	exit 1
 }
 
@@ -572,18 +574,27 @@ echo -n "Search LDAP binddn "
 
 # First use udm to search the user DN
 binddn="$(univention-ssh "$DCPWD" "${DCACCOUNT}@${DCNAME}" \
-	/usr/sbin/udm users/user list --filter uid="$DCACCOUNT" --logfile /dev/null | sed -ne 's|^DN: ||p')"
+	/usr/sbin/udm users/user list --filter uid="$DCACCOUNT" --logfile /dev/null  2> >(tee -a /var/log/univention/join.log >&2) | sed -ne 's|^DN: ||p')"
 
 if [ -z "$binddn" ]; then
-	# Next check is the local ldapi interface
+	echo "binddn search on ${DCNAME} with UDM failed" >>/var/log/univention/join.log
+	# Next try ldapsearch with GSSAPI against OpenLDAP
 	binddn="$(univention-ssh "$DCPWD" "${DCACCOUNT}@${DCNAME}" \
-		ldapsearch -x -LLL -H ldapi:/// "\'(&(uid=$DCACCOUNT)(objectClass=person))\'" dn | ldapsearch-wrapper | ldapsearch-decode64 | sed -ne 's|^dn: ||p;s|^DN: ||p')"
+		kinit --password-file=STDIN "${DCACCOUNT}" ldapsearch -Y GSSAPI -LLL -o ldif-wrap=no "\'(&(uid=$DCACCOUNT)(objectClass=person))\'" dn <"$DCPWD" 2>/dev/null | ldapsearch-decode64 | sed -ne 's|^dn: ||p;s|^DN: ||p')"
 fi
 
 if [ -z "$binddn" ]; then
-	# Check with anonymous bind
+	echo "binddn search on ${DCNAME} with GSSAPI failed" >>/var/log/univention/join.log
+	# Next try the local ldapi interface, unlikely to succeed because only accessible for root
 	binddn="$(univention-ssh "$DCPWD" "${DCACCOUNT}@${DCNAME}" \
-		ldapsearch -x -LLL "\'(&(uid=$DCACCOUNT)(objectClass=person))\'" dn | ldapsearch-wrapper | ldapsearch-decode64 | sed -ne 's|^dn: ||p;s|^DN: ||p')"
+		ldapsearch -x -LLL -o ldif-wrap=no -H ldapi:/// "\'(&(uid=$DCACCOUNT)(objectClass=person))\'" dn | ldapsearch-decode64 | sed -ne 's|^dn: ||p;s|^DN: ||p')"
+fi
+
+if [ -z "$binddn" ]; then
+	echo "binddn search on ${DCNAME} via LDAPI failed" >>/var/log/univention/join.log
+	# Finally try anonymous bind, unlikely to succeed because anonymous bind is disabled by default
+	binddn="$(univention-ssh "$DCPWD" "${DCACCOUNT}@${DCNAME}" \
+		ldapsearch -x -LLL -o ldif-wrap=no "\'(&(uid=$DCACCOUNT)(objectClass=person))\'" dn | ldapsearch-decode64 | sed -ne 's|^dn: ||p;s|^DN: ||p')"
 fi
 
 if [ -z "$binddn" ]; then
