Bug #40611: added -containerAdMemberMode
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.1/ucs-4.1-4@74073 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/management/univention-join/univention-join b/management/univention-join/univention-join
--- a/management/univention-join/univention-join
+++ b/management/univention-join/univention-join
@@ -47,6 +47,7 @@ VERSION_CHECK=true
 VERBOSE=false
 SKIPIPMAC=false
 SKIPADMEMBERMODE=false
+CONTAINERADMEMBERMODE=false
 
 trapOnExit() {
 	rm -rf "$USERTMP"
@@ -77,6 +78,7 @@ display_help() {
 	  -disableVersionCheck           Disable version check against _dcname_
 	  -skipIpMac                     Do not register IP and MAC in machine account
 	  -skipAdMemberMode              Do not activate ad member mode during join
+	  -containerAdMemberMode         Configure ad member in container mode
 	  -verbose                       Enable verbose logging (/var/log/univention/join.log)
 
 	  -h | --help | -?:              Print this usage message and exit program
@@ -220,17 +222,23 @@ check_and_configure_ad_member_mode () {
 		return 0
 	fi
 
+	# special handling for UCS in container
+	local role="$server_role"
+	if "$CONTAINERADMEMBERMODE"; then
+		role="container"
+	fi
+
 	# switch to ad member mode
 	if is_domain_in_admember_mode; then
 		if ! is_localhost_in_admember_mode; then
 			echo -n "Entering AD Member Mode: "
-			configure_nonmaster_as_ad_member "$server_role" >>/var/log/univention/join.log 2>&1 || failed_message "could not set AD Member Mode"
+			configure_nonmaster_as_ad_member "$role" >>/var/log/univention/join.log 2>&1 || failed_message "could not set AD Member Mode"
 			echo -e "\033[60Gdone"
 		fi
 	else
 		if is_localhost_in_admember_mode; then
 			echo -n "Leaving AD Member Mode: "
-			revert_nonmaster_ad_member "$server_role" >>/var/log/univention/join.log 2>&1 || failed_message "could not revert AD Member Mode"
+			revert_nonmaster_ad_member "$role" >>/var/log/univention/join.log 2>&1 || failed_message "could not revert AD Member Mode"
 			echo -e "\033[60Gdone"
 		fi
 	fi
@@ -298,6 +306,10 @@ do
 			;;
 		"-skipAdMemberMode")
 			SKIPADMEMBERMODE=true
+			shift
+			;;
+		"-containerAdMemberMode")
+			CONTAINERADMEMBERMODE=true
 			shift
 			;;
 		*)
