updated init script (Bug #36637)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.0/ucs-4.0-0@55761 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/mail/univention-postgrey/conffiles/etc/init.d/postgrey b/mail/univention-postgrey/conffiles/etc/init.d/postgrey
--- a/mail/univention-postgrey/conffiles/etc/init.d/postgrey
+++ b/mail/univention-postgrey/conffiles/etc/init.d/postgrey
@@ -1,4 +1,4 @@
-#!/bin/sh
+#! /bin/sh
 @%@UCRWARNING=# @%@
 #
 # Univention Postgrey
@@ -30,16 +30,16 @@
 # License with the Debian GNU/Linux or Univention distribution in file
 # /usr/share/common-licenses/AGPL-3; if not, see
 # <http://www.gnu.org/licenses/>.
-
+#
 #
 # postgrey      start/stop the postgrey greylisting deamon for postfix
-#		(priority should be smaller than that of postfix)
+#               (priority should be smaller than that of postfix)
 #
-# Author:	(c)2004-2006 Adrian von Bidder <avbidder@fortytwo.ch>
-#		Based on Debian sarge's 'skeleton' example
+# Author:       (c)2004-2006 Adrian von Bidder <avbidder@fortytwo.ch>
+#               Based on Debian sarge's 'skeleton' example
 #               Distribute and/or modify at will.
 #
-# Version:	$Id: postgrey.init 1436 2006-12-07 07:15:03Z avbidder $
+# Version:      $Id: postgrey.init 1436 2006-12-07 07:15:03Z avbidder $
 #
 ### BEGIN INIT INFO
 # Provides:          postgrey
@@ -52,23 +52,24 @@
 
 set -e
 
-PATH="/sbin:/bin:/usr/sbin:/usr/bin"
-DAEMON="/usr/sbin/postgrey"
-NAME="postgrey"
+PATH=/sbin:/bin:/usr/sbin:/usr/bin
+DAEMON=/usr/sbin/postgrey
+DAEMON_NAME=postgrey
 DESC="postfix greylisting daemon"
+DAEMON_USER=postgrey
 
-PIDFILE="/var/run/$NAME.pid"
-SCRIPTNAME="/etc/init.d/$NAME"
+PIDFILE=/var/run/$DAEMON_NAME.pid
+SCRIPTNAME=/etc/init.d/$DAEMON_NAME
 
 # Gracefully exit if the package has been removed.
-test -x "$DAEMON" || exit 0
+test -x $DAEMON || exit 0
 
 . /lib/lsb/init-functions
 
 # Read config file if it is present.
-if [ -r "/etc/default/$NAME" ]
+if [ -r /etc/default/$DAEMON_NAME ]
 then
-    . "/etc/default/$NAME"
+    . /etc/default/$DAEMON_NAME
 fi
 
 POSTGREY_OPTS="--pidfile=$PIDFILE --daemonize $POSTGREY_OPTS"
@@ -79,61 +80,104 @@ else
 fi
 
 ret=0
+
+do_start()
+{
+        # Return
+        #   0 if daemon has been started
+        #   1 if daemon was already running
+        #   2 if daemon could not be started
+        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+                || return 1
+        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+                $POSTGREY_OPTS "$POSTGREY_TEXT_OPT" \
+                || return 2
+}
+
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+        start-stop-daemon --user $DAEMON_USER --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
+        RETVAL="$?"
+        [ "$RETVAL" = 2 ] && return 2
+
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon --user $DAEMON_USER --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
+
+}
+
+do_reload()
+{
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE
+	return 0
+}
+
 case "$1" in
   start)
 	# check ucr autostart setting
 	if [ -f "/usr/share/univention-config-registry/init-autostart.lib" ]; then
-	    . "/usr/share/univention-config-registry/init-autostart.lib"
-	    check_autostart postgrey postgrey/autostart
+		. "/usr/share/univention-config-registry/init-autostart.lib"
+		check_autostart postgrey postgrey/autostart
 	fi
-	log_daemon_msg "Starting $DESC" "$NAME"
-	if start-stop-daemon --start --oknodo --quiet \
-		--pidfile $PIDFILE --name $NAME \
-		--startas $DAEMON -- $POSTGREY_OPTS "$POSTGREY_TEXT_OPT"
-	then
-	    log_end_msg 0
-	else
-	    ret=$?
-	    log_end_msg 1
-	fi
-	;;
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$DAEMON_NAME"
+        do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+        ;;
   stop)
-	log_daemon_msg "Stopping $DESC" "$NAME"
-	if start-stop-daemon --stop --oknodo --quiet \
-		--pidfile $PIDFILE --name $NAME
-	then
-	    log_end_msg 0
-	else
-	    ret=$?
-	    log_end_msg 1
-	fi
-        rm -f $PIDFILE
-	;;
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$DAEMON_NAME"
+        do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+        ;;
   reload|force-reload)
-	log_action_begin_msg "Reloading $DESC configuration..."
-	if start-stop-daemon --stop --signal 1 --quiet \
-		--pidfile $PIDFILE --name $NAME
-	then
-	    log_action_end_msg 0
-	else
-	    ret=$?
-	    log_action_end_msg 1
-	fi
+	[ "$VERBOSE" != no ] && log_daemon_msg "Reloading $DESC" "$DAEMON_NAME"
+        do_reload
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
         ;;
   restart)
-	$0 stop
-	$0 start
-	ret=$?
-	;;
+        # check ucr autostart setting
+        if [ -f "/usr/share/univention-config-registry/init-autostart.lib" ]; then
+                . "/usr/share/univention-config-registry/init-autostart.lib"
+                check_autostart postgrey postgrey/autostart
+        fi
+        do_stop
+        do_start
+        ;;
   status)
-	status_of_proc -p $PIDFILE $DAEMON "$NAME" 2>/dev/null
-	ret=$?
-	;;
+        status_of_proc -p $PIDFILE $DAEMON "$DAEMON_NAME" 2>/dev/null
+        ret=$?
+        ;;
 
   *)
-	echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload|status}" >&2
-	exit 1
-	;;
+        echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload|status}" >&2
+        exit 1
+        ;;
 esac
 
 exit $ret
