test[udl] Shellcheck
Bug #26089
univention/dev-issues/ucs2022#1

diff --git a/management/univention-directory-listener/debian/tests/lxc-ucs b/management/univention-directory-listener/debian/tests/lxc-ucs
--- a/management/univention-directory-listener/debian/tests/lxc-ucs
+++ b/management/univention-directory-listener/debian/tests/lxc-ucs
@@ -19,10 +19,15 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
+die () {
+    echo "${0##*/}: $*" >&2
+    exit 1
+}
+
 # Detect use under userns (unsupported)
 for arg in "$@"; do
     [ "$arg" = "--" ] && break
-    if [ "$arg" = "--mapped-uid" -o "$arg" = "--mapped-gid" ]; then
+    if [ "$arg" = "--mapped-uid" ] || [ "$arg" = "--mapped-gid" ]; then
         echo "This template can't be used for unprivileged containers." 1>&2
         echo "You may want to try the \"download\" template instead." 1>&2
         exit 1
@@ -55,7 +60,7 @@ configure_debian()
     done
 
     # configure the inittab
-    cat <<EOF > $rootfs/etc/inittab
+    cat <<EOF > "$rootfs/etc/inittab"
 id:3:initdefault:
 si::sysinit:/etc/init.d/rcS
 l0:0:wait:/etc/init.d/rc 0
@@ -82,7 +87,7 @@ EOF
     echo 0 > "$rootfs/selinux/enforce"
 
     # configure the network using the dhcp
-    cat <<EOF > $rootfs/etc/network/interfaces
+    cat <<EOF > "$rootfs/etc/network/interfaces"
 auto lo
 iface lo inet loopback
 
@@ -91,14 +96,14 @@ iface eth0 inet dhcp
 EOF
 
     # set the hostname
-    cat <<EOF > $rootfs/etc/hostname
+    cat <<EOF > "$rootfs/etc/hostname"
 $hostname
 EOF
 
     # reconfigure some services
 
     # but first reconfigure locales - so we get no noisy perl-warnings
-    if [ -z "$LANG" ] || echo $LANG | grep -E -q "^C(\..+)*$"; then
+    if [ -z "$LANG" ] || echo "$LANG" | grep -E -q "^C(\..+)*$"; then
         cat >> "$rootfs/etc/locale.gen" << EOF
 en_US.UTF-8 UTF-8
 EOF
@@ -150,6 +155,7 @@ EOF
         cat /etc/timezone > "$rootfs/etc/timezone"
         chroot "$rootfs" dpkg-reconfigure -f noninteractive tzdata
     elif [ -f /etc/sysconfig/clock ]; then
+        # shellcheck source=/dev/null
         . /etc/sysconfig/clock
         echo "$ZONE" > "$rootfs/etc/timezone"
         chroot "$rootfs" dpkg-reconfigure -f noninteractive tzdata
@@ -189,6 +195,7 @@ install_packages()
 
     chroot "${rootfs}" apt-get update
     if [ -n "${packages}" ]; then
+        # shellcheck disable=SC2086
         chroot "${rootfs}" apt-get install --force-yes -y --no-install-recommends ${packages}
     fi
 }
@@ -228,13 +235,13 @@ configure_debian_systemd()
     chroot "${rootfs}" ln -s /lib/systemd/system/multi-user.target /etc/systemd/system/default.target
     # Setup getty service on the ttys we are going to allow in the
     # default config.  Number should match lxc.tty
-    ( cd "${rootfs}/etc/systemd/system/getty.target.wants"
+    ( cd "${rootfs}/etc/systemd/system/getty.target.wants" &&
         for i in $(seq 1 "$num_tty") ; do ln -sf ../getty\@.service getty@tty"${i}".service; done )
 
     # Since we use static-getty.target; we need to mask container-getty@.service generated by
     # container-getty-generator, so we don't get multiple instances of agetty running.
     # See https://github.com/lxc/lxc/issues/520 and https://github.com/lxc/lxc/issues/484
-    ( cd "${rootfs}/etc/systemd/system/getty.target.wants"
+    ( cd "${rootfs}/etc/systemd/system/getty.target.wants" &&
         for i in $(seq 0 "$num_tty"); do ln -sf /dev/null container-getty\@"${i}".service; done )
 
     return 0
@@ -279,18 +286,18 @@ openssh-server
     # If debian-archive-keyring isn't installed, fetch GPG keys directly
     releasekeyring=/home/phahn/REPOS/ucs/base/univention-archive-key/univention-archive-key-ucs-4x.gpg
     # check the mini debian was not already downloaded
-    mkdir -p "$cache/partial-$release-$arch"
-    if [ $? -ne 0 ]; then
+    if ! mkdir -p "$cache/partial-$release-$arch"
+    then
         echo "Failed to create '$cache/partial-$release-$arch' directory"
         return 1
     fi
 
     # download a mini debian into a cache
     echo "Downloading debian minimal ..."
-    debootstrap --verbose --variant=minbase --arch="$arch" \
+    if ! debootstrap --verbose --variant=minbase --arch="$arch" \
         --include="$packages" --keyring="${releasekeyring}" \
         "$release" "$cache/partial-$release-$arch" "$MIRROR" /usr/share/debootstrap/scripts/sid
-    if [ $? -ne 0 ]; then
+    then
         echo "Failed to download the rootfs, aborting."
         return 1
     fi
@@ -327,30 +334,30 @@ install_debian()
     cache="$4/debian"
     mkdir -p $LOCALSTATEDIR/lock/subsys/
     (
-        flock -x 9
-        if [ $? -ne 0 ]; then
+        if ! flock -x 9
+        then
             echo "Cache repository is busy."
             return 1
         fi
 
         echo "Checking cache download in $cache/rootfs-$release-$arch ... "
         if [ ! -e "$cache/rootfs-$release-$arch" ]; then
-            download_debian "$cache" "$arch" "$release"
-            if [ $? -ne 0 ]; then
+            if ! download_debian "$cache" "$arch" "$release"
+            then
                 echo "Failed to download 'debian base'"
                 return 1
             fi
         fi
 
-        copy_debian "$cache" "$arch" "$rootfs" "$release"
-        if [ $? -ne 0 ]; then
+        if ! copy_debian "$cache" "$arch" "$rootfs" "$release"
+        then
             echo "Failed to copy rootfs"
             return 1
         fi
 
         return 0
 
-        ) 9>$LOCALSTATEDIR/lock/subsys/lxc-debian
+        ) 9>"$LOCALSTATEDIR/lock/subsys/lxc-debian"
 
     return $?
 }
@@ -386,13 +393,12 @@ copy_configuration()
     echo "# Container specific configuration" >> "$path/config"
     grep -q "^lxc.rootfs" "$path/config" 2> /dev/null || echo "lxc.rootfs = $rootfs" >> "$path/config"
 
-    cat <<EOF >> $path/config
+    if ! cat <<EOF >> "$path/config"
 lxc.tty = $num_tty
 lxc.utsname = $hostname
 lxc.arch = $arch
 EOF
-
-    if [ $? -ne 0 ]; then
+    then
         echo "Failed to add configuration"
         return 1
     fi
@@ -424,7 +430,7 @@ EOF
     fi
 
     # Write a new sources.list containing both native and multiarch entries
-    > "${rootfs}/etc/apt/sources.list"
+    : > "${rootfs}/etc/apt/sources.list"
     if [ "${arch}" = "${hostarch}" ]; then
         write_sourceslist "${rootfs}" "${release}" "${arch}"
     else
@@ -447,24 +453,19 @@ EOF
 clean()
 {
     cache=${LXC_CACHE_PATH:-"$LOCALSTATEDIR/cache/lxc/debian"}
-
-    if [ ! -e "$cache" ]; then
+    [ -e "$cache" ] ||
         exit 0
-    fi
 
     # lock, so we won't purge while someone is creating a repository
     (
-        flock -x 9
-        if [ $? != 0 ]; then
-            echo "Cache repository is busy."
-            exit 1
-        fi
+       flock -x 9 ||
+            die "Cache repository is busy."
 
         echo -n "Purging the download cache..."
         rm --preserve-root --one-file-system -rf "$cache" && echo "Done." || exit 1
         exit 0
 
-    ) 9>$LOCALSTATEDIR/lock/subsys/lxc-debian
+    ) 9>"$LOCALSTATEDIR/lock/subsys/lxc-debian"
 }
 
 usage()
@@ -507,8 +508,8 @@ EOF
     return 0
 }
 
-options=$(getopt -o hp:n:a:r:c -l arch:,clean,help,enable-non-free,mirror:,name:,packages:,path:,release:,rootfs:,security-mirror: -- "$@")
-if [ $? -ne 0 ]; then
+if ! options=$(getopt -o hp:n:a:r:c -l arch:,clean,help,enable-non-free,mirror:,name:,packages:,path:,release:,rootfs:,security-mirror: -- "$@")
+then
         usage "$(basename "$0")"
         exit 1
 fi
@@ -527,9 +528,9 @@ elif [ "$arch" = "ppc" ]; then
     arch="powerpc"
 elif [ "$arch" = "ppc64le" ]; then
     arch="ppc64el"
-elif [ "$arch" = "mips" -a "$littleendian" = "yes" ]; then
+elif [ "$arch" = "mips" ] && [ "$littleendian" = "yes" ]; then
     arch="mipsel"
-elif [ "$arch" = "mips64" -a "$littleendian" = "yes" ]; then
+elif [ "$arch" = "mips64" ] && [ "$littleendian" = "yes" ]; then
     arch="mips64el"
 fi
 hostarch=$arch
@@ -555,57 +556,40 @@ do
     esac
 done
 
-if [ ! -z "$clean" -a -z "$path" ]; then
+if [ -n "$clean" ] && [ -z "$path" ]; then
     clean || exit 1
     exit 0
 fi
 
-if [ "$arch" = "i686" ]; then
+[ "$arch" = "i686" ] &&
     arch=i386
-fi
-
-if [ "$arch" = "x86_64" ]; then
+[ "$arch" = "x86_64" ] &&
     arch=amd64
-fi
 
-if [ $hostarch = "i386" -a $arch = "amd64" ]; then
-    echo "can't create $arch container on $hostarch"
-    exit 1
-fi
+[ "$hostarch" = "i386" ] && [ "$arch" = "amd64" ] &&
+    die "can't create $arch container on $hostarch"
 
-if [ $hostarch = "armhf" -o $hostarch = "armel" ] && \
-   [ $arch != "armhf" -a $arch != "armel" ]; then
-    echo "can't create $arch container on $hostarch"
-    exit 1
-fi
+{ [ "$hostarch" = "armhf" ] || [ "$hostarch" = "armel" ]; } &&
+   [ "$arch" != "armhf" ] && [ "$arch" != "armel" ] &&
+    die "can't create $arch container on $hostarch"
 
-if [ $hostarch = "powerpc" -a $arch != "powerpc" ]; then
-    echo "can't create $arch container on $hostarch"
-    exit 1
-fi
+[ "$hostarch" = "powerpc" ] && [ "$arch" != "powerpc" ] &&
+    die "can't create $arch container on $hostarch"
 
-type debootstrap
-if [ $? -ne 0 ]; then
-    echo "'debootstrap' command is missing"
-    exit 1
-fi
+command -v debootstrap >/dev/null 2>&1 ||
+    die "'debootstrap' command is missing"
 
-if [ -z "$path" ]; then
-    echo "'path' parameter is required"
-    exit 1
-fi
+[ -n "$path" ] ||
+    die "'path' parameter is required"
 
-if [ "$(id -u)" != "0" ]; then
-    echo "This script should be run as 'root'"
-    exit 1
-fi
+[ "$(id -u)" = "0" ] ||
+    die "This script should be run as 'root'"
 
 release=${release:-stable}
 permanent_releases=('stable' 'testing' 'sid' 'unstable')
 if [[ ! "${permanent_releases[*]}" =~ (^|[^[:alpha:]])$release([^[:alpha:]]|$) ]]; then
     if ! wget "${MIRROR}/dists/${release}/Release" -O /dev/null 2> /dev/null; then
-	echo "Invalid release ${release} (not found in mirror)"
-	exit 1
+	die "Invalid release ${release} (not found in mirror)"
     fi
 fi
 
@@ -626,29 +610,20 @@ else
     num_tty=4
 fi
 
-install_debian "$rootfs" "$release" "$arch" "$LXC_CACHE_PATH"
-if [ $? -ne 0 ]; then
-    echo "failed to install debian"
-    exit 1
-fi
+install_debian "$rootfs" "$release" "$arch" "$LXC_CACHE_PATH" ||
+    die "failed to install debian"
 
-configure_debian "$rootfs" "$name" $num_tty
-if [ $? -ne 0 ]; then
-    echo "failed to configure debian for a container"
-    exit 1
-fi
+configure_debian "$rootfs" "$name" "$num_tty" ||
+    die "failed to configure debian for a container"
 
-copy_configuration "$path" "$rootfs" "$name" $arch $num_tty
-if [ $? -ne 0 ]; then
-    echo "failed write configuration file"
-    exit 1
-fi
+copy_configuration "$path" "$rootfs" "$name" $arch "$num_tty" ||
+    die "failed write configuration file"
 
-configure_debian_systemd "$path" "$rootfs" "$config" $num_tty
+configure_debian_systemd "$path" "$rootfs" "$config" "$num_tty"
 
 post_process "${rootfs}" "${release}" "${arch}" "${hostarch}" "${packages}"
 
-if [ ! -z "$clean" ]; then
+if [ -n "$clean" ]; then
     clean || exit 1
     exit 0
 fi
