Bug #29667: Fix pid file deletion
Fix minor error redirection issue.

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@38683 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/virtualization/univention-virtual-machine-manager-node/conffiles/etc/runit/univention-libvirt/run b/virtualization/univention-virtual-machine-manager-node/conffiles/etc/runit/univention-libvirt/run
--- a/virtualization/univention-virtual-machine-manager-node/conffiles/etc/runit/univention-libvirt/run
+++ b/virtualization/univention-virtual-machine-manager-node/conffiles/etc/runit/univention-libvirt/run
@@ -41,7 +41,7 @@ if [ -r "$PID" ]; then
 	exe=$(readlink "/proc/$pid/exe") &&
 	case "$exe" in
 	/usr/sbin/libvirtd*)
-		echo "ERROR: libvirtd running $pid" 2>&1
+		echo "ERROR: libvirtd running $pid" >&2
 		exit 1
 		;;
 	esac
