Copied uvvm-node from UCS 2.4; Bug #22893
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.0/ucs@27453 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/virtualization/univention-virtual-machine-manager-node/conffiles/etc/runit/univention-libvirt/run b/virtualization/univention-virtual-machine-manager-node/conffiles/etc/runit/univention-libvirt/run
--- a/virtualization/univention-virtual-machine-manager-node/conffiles/etc/runit/univention-libvirt/run
+++ b/virtualization/univention-virtual-machine-manager-node/conffiles/etc/runit/univention-libvirt/run
@@ -5,4 +5,17 @@ PATH=/sbin:/bin:/usr/sbin:/usr/bin
 
 source /etc/default/libvirt-bin
 
+if [ -f /var/run/libvirtd.pid ]; then
+	read pid </var/run/libvirtd.pid || pid=
+	if [ -d "/proc/$pid" ]; then
+		exe=$(readlink /proc/$pid/exe)
+		if [ /usr/sbin/libvirtd = "$exe" ]; then
+			echo "ERROR: libvirtd running $pid"
+			exit 1
+		fi
+	fi
+	rm -f /var/run/libvirtd.pid
+fi
+
+
 exec /usr/sbin/libvirtd ${libvirtd_opts/-d/}
