Bug #29667: Fix pid file deletion
UNIX daemons stores their PID without a trailing newline in their .pid
files. read returns exit code 1 on such lines, which the runit run
script for libvirtd detected as an error.

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@38355 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/virtualization/univention-virtual-machine-manager-node/conffiles/etc/runit/univention-libvirt/run b/virtualization/univention-virtual-machine-manager-node/conffiles/etc/runit/univention-libvirt/run
--- a/virtualization/univention-virtual-machine-manager-node/conffiles/etc/runit/univention-libvirt/run
+++ b/virtualization/univention-virtual-machine-manager-node/conffiles/etc/runit/univention-libvirt/run
@@ -36,15 +36,15 @@ PATH=/sbin:/bin:/usr/sbin:/usr/bin
 . /etc/default/libvirt-bin
 
 PID=/var/run/libvirtd.pid
-if [ -f "$PID" ]; then
-	read pid <"$PID" || pid=
-	if [ -d "/proc/$pid" ]; then
-		exe=$(readlink /proc/$pid/exe)
-		if [ /usr/sbin/libvirtd = "$exe" ]; then
-			echo "ERROR: libvirtd running $pid"
-			exit 1
-		fi
-	fi
+if [ -r "$PID" ]; then
+	read pid <"$PID" || true # no '\n' -> 'read' returns 1
+	exe=$(readlink "/proc/$pid/exe")
+	case "$exe" in
+	/usr/sbin/libvirtd*)
+		echo "ERROR: libvirtd running $pid" 2>&1
+		exit 1
+		;;
+	esac
 	rm -f "$PID"
 fi
 
