* call fix_primary_group_membership of univention-directory-manager-tools (Bug #21782) * added handling of users to fix_primary_group_membership
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/trunk/ucs@23065 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/management/univention-directory-manager-modules/scripts/fix_primary_group_membership b/management/univention-directory-manager-modules/scripts/fix_primary_group_membership
--- a/management/univention-directory-manager-modules/scripts/fix_primary_group_membership
+++ b/management/univention-directory-manager-modules/scripts/fix_primary_group_membership
@@ -2,48 +2,118 @@
 #
 eval "$(ucr shell)"
 
-if [ "$1" = "-h" -o "$1" = "--help" ] ; then
-	echo "$(basename "$0") [-h] [-f]"
-	echo "-h   prints this helptext"
-	echo "-f   perform changes"
-	echo "     (default is dry-run)"
-	exit 0
-fi
+usage () {
+	echo "$(basename "$0") [-h] [-u|-c] [-f]"
+	echo "    -c   check only computer objects"
+	echo "    -u   check only user objects"
+	echo "    -h   prints this helptext"
+	echo "    -f   perform changes"
+	echo "         (default is dry-run)"
+	exit $1
+}
+
 FORCE=""
-if [ "$1" = "-f" ] ; then
-	FORCE="1"
-fi
+ONLYUSER=""
+ONLYCOMPUTER=""
+while [ -n "$1" ]
+do
+        case "$1" in
+        -h|--help)
+                usage 0
+                ;;
+        -c)
+                ONLYCOMPUTER="1"
+                shift
+                ;;
+        -u)
+                ONLYUSER="1"
+				shift
+                ;;
+        -f)
+                FORCE="1"
+				shift
+                ;;
+        --)
+                shift
+                break
+                ;;
+        -*)
+                usage 2 >&2
+                ;;
+        *)
+                break
+                ;;
+        esac
+done
+
 
 OLDIFS="$IFS"
 IFS=$'\n'
-gidNumberList="$(ldapsearch -LLLx "(&(objectClass=univentionHost)(gidNumber=*))" gidNumber | sed -ne "s,^gidNumber: ,,p" | sort -u)"
-for gidNumber in $gidNumberList ; do
-	grpDn="$(ldapsearch -xLLL "(&(objectClass=univentionGroup)(gidNumber=${gidNumber}))" dn | sed -ne 's,dn: ,,p')"
-	for dn in $(ldapsearch -LLLx "(&(objectClass=univentionHost)(gidNumber=${gidNumber}))" dn | sed -ne "s,^dn: ,,p") ; do
-		if [ -z "$(ldapsearch -xLLL "(&(objectClass=univentionGroup)(gidNumber=${gidNumber})(uniqueMember=${dn}))")" ] ; then
-			echo "*** $dn is missing in group with gidNumber $gidNumber ($grpDn)"
-			if [ -n "$FORCE" ] ; then
-				ldapmodify -x -D "cn=admin,$ldap_base" -w "$(< /etc/ldap.secret)" <<EOF
+
+if [ -z "$ONLYUSER" ] ; then
+	# TEST COMPUTERS
+	gidNumberList="$(ldapsearch -LLLx "(&(objectClass=univentionHost)(gidNumber=*))" gidNumber | sed -ne "s,^gidNumber: ,,p" | sort -u)"
+	for gidNumber in $gidNumberList ; do
+	 	grpDn="$(ldapsearch -xLLL "(&(objectClass=univentionGroup)(gidNumber=${gidNumber}))" dn | sed -ne 's,dn: ,,p')"
+	 	for dn in $(ldapsearch -LLLx "(&(objectClass=univentionHost)(gidNumber=${gidNumber}))" dn | sed -ne "s,^dn: ,,p") ; do
+	 		if [ -z "$(ldapsearch -xLLL "(&(objectClass=univentionGroup)(gidNumber=${gidNumber})(uniqueMember=${dn}))")" ] ; then
+	 			echo "*** $dn is missing in group with gidNumber $gidNumber ($grpDn)"
+	 			if [ -n "$FORCE" ] ; then
+	 				ldapmodify -x -D "cn=admin,$ldap_base" -w "$(< /etc/ldap.secret)" <<EOF
 dn: $grpDn
 changetype: modify
 add: uniqueMember
 uniqueMember: $dn
 EOF
-		    fi
-		fi
-		hostuid="$(ldapsearch -xLLL -b "$dn" uid | sed -ne 's,^uid: ,,p')"
-		if [ -z "$(ldapsearch -xLLL "(&(objectClass=univentionGroup)(gidNumber=${gidNumber})(memberUid=${hostuid}))")" ] ; then
-			echo "*** $hostuid is missing in group with gidNumber $gidNumber ($grpDn)"
-			if [ -n "$FORCE" ] ; then
-				ldapmodify -x -D "cn=admin,$ldap_base" -w "$(< /etc/ldap.secret)" <<EOF
+	 		    fi
+	 		fi
+	 		hostuid="$(ldapsearch -xLLL -b "$dn" uid | sed -ne 's,^uid: ,,p')"
+	 		if [ -z "$(ldapsearch -xLLL "(&(objectClass=univentionGroup)(gidNumber=${gidNumber})(memberUid=${hostuid}))")" ] ; then
+	 			echo "*** $hostuid is missing in group with gidNumber $gidNumber ($grpDn)"
+	 			if [ -n "$FORCE" ] ; then
+	 				ldapmodify -x -D "cn=admin,$ldap_base" -w "$(< /etc/ldap.secret)" <<EOF
 dn: $grpDn
 changetype: modify
 add: memberUid
 memberUid: $hostuid
 EOF
-		    fi
-		fi
+	 		    fi
+	 		fi
+	 	done
 	done
-done
+fi
+
+if [ -z "$ONLYCOMPUTER" ] ; then
+	# TEST USERS
+	gidNumberList="$(ldapsearch -LLLx "(&(objectClass=posixAccount)(uid=*)(!(uid=*$))(gidNumber=*))" gidNumber | sed -ne "s,^gidNumber: ,,p" | sort -u)"
+	for gidNumber in $gidNumberList ; do
+	 	grpDn="$(ldapsearch -xLLL "(&(objectClass=univentionGroup)(gidNumber=${gidNumber}))" dn | sed -ne 's,dn: ,,p')"
+	 	for dn in $(ldapsearch -LLLx "(&(objectClass=posixAccount)(uid=*)(!(uid=*$))(gidNumber=${gidNumber}))" dn | sed -ne "s,^dn: ,,p") ; do
+	 		if [ -z "$(ldapsearch -xLLL "(&(objectClass=univentionGroup)(gidNumber=${gidNumber})(uniqueMember=${dn}))")" ] ; then
+	 			echo "*** $dn is missing in group with gidNumber $gidNumber ($grpDn)"
+	 			if [ -n "$FORCE" ] ; then
+	 				ldapmodify -x -D "cn=admin,$ldap_base" -w "$(< /etc/ldap.secret)" <<EOF
+dn: $grpDn
+changetype: modify
+add: uniqueMember
+uniqueMember: $dn
+EOF
+	 		    fi
+	 		fi
+	 		useruid="$(ldapsearch -xLLL -b "$dn" uid | sed -ne 's,^uid: ,,p')"
+	 		if [ -z "$(ldapsearch -xLLL "(&(objectClass=univentionGroup)(gidNumber=${gidNumber})(memberUid=${useruid}))")" ] ; then
+	 			echo "*** $useruid is missing in group with gidNumber $gidNumber ($grpDn)"
+	 			if [ -n "$FORCE" ] ; then
+	 				ldapmodify -x -D "cn=admin,$ldap_base" -w "$(< /etc/ldap.secret)" <<EOF
+dn: $grpDn
+changetype: modify
+add: memberUid
+memberUid: $useruid
+EOF
+	 		    fi
+	 		fi
+	 	done
+	done
+fi
 
 exit 0
