always use localhost as server, packaging fixes (Bug #37890)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.1/ucs-4.1-0@64800 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/management/univention-self-service/debian/univention-self-service-setpassword-frontend.postinst b/management/univention-self-service/debian/univention-self-service-setpassword-frontend.postinst
--- a/management/univention-self-service/debian/univention-self-service-setpassword-frontend.postinst
+++ b/management/univention-self-service/debian/univention-self-service-setpassword-frontend.postinst
@@ -41,9 +41,8 @@ univention-config-registry set \
 	"ucs/web/overview/entries/service/setpassword/port_http=" \
 	"ucs/web/overview/entries/service/setpassword/port_https=443"
 
-if [ "$1" = "configure" ] && [ -n "$2" ]; then
-	# restart, so apache reloads WSGI
-	# retry if fail because of to quick successive restarts (from other frontend packages)
-	invoke-rc.d apache2 restart || (sleep 2; invoke-rc.d apache2 restart)
-fi
+# restart, so apache reloads WSGI and sees activated plugin in its config
+# retry if fail because of to quick successive restarts (from other frontend packages)
+invoke-rc.d apache2 restart || (sleep 2; invoke-rc.d apache2 restart)
+
 exit 0
