cleanup after uninstalling (Bug #37890)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.1/ucs-4.1-0@64805 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/management/univention-self-service/debian/univention-self-service-setpassword-frontend.postrm b/management/univention-self-service/debian/univention-self-service-setpassword-frontend.postrm
--- a/management/univention-self-service/debian/univention-self-service-setpassword-frontend.postrm
+++ b/management/univention-self-service/debian/univention-self-service-setpassword-frontend.postrm
@@ -1,7 +1,5 @@
-#!/bin/bash
-#
-# Univention Self Service
-#  prerm file for the debian package
+#!/bin/sh
+# postrm script for univention-self-service-setpassword-frontend
 #
 # Copyright 2015 Univention GmbH
 #
@@ -32,11 +30,18 @@
 
 #DEBHELPER#
 
-case "$1" in
-	remove)
-		a2dissite univention-self-service
-		invoke-rc.d apache2 restart
-	;;
-esac
+univention-config-registry unset \
+	ucs/web/overview/entries/service/setpassword/description \
+	ucs/web/overview/entries/service/setpassword/description/de \
+	ucs/web/overview/entries/service/setpassword/icon \
+	ucs/web/overview/entries/service/setpassword/label \
+	ucs/web/overview/entries/service/setpassword/label/de \
+	ucs/web/overview/entries/service/setpassword/link \
+	ucs/web/overview/entries/service/setpassword/port_http \
+	ucs/web/overview/entries/service/setpassword/port_https
+
+# restart, so apache unloads WSGI and deactivats plugin in its config
+# retry if fail because of to quick successive restarts (from other frontend packages)
+invoke-rc.d apache2 restart || (sleep 2; invoke-rc.d apache2 restart)
 
 exit 0
