* use Univention namespace in LDAP schema (Bug #37890) * split and rename packages for frontend and backend * split join scripts * add single-server meta package * add appcenter data
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.1/ucs-4.1-0@64741 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/management/univention-self-service/debian/univention-management-console-module-passwordreset.postinst b/management/univention-self-service/debian/univention-management-console-module-passwordreset.postinst
--- a/management/univention-self-service/debian/univention-management-console-module-passwordreset.postinst
+++ b/management/univention-self-service/debian/univention-management-console-module-passwordreset.postinst
@@ -32,6 +32,13 @@
 
 #DEBHELPER#
 
+eval "$(univention-config-registry shell)"
+
+if ! [ "$server_role" = "domaincontroller_master" -o "$server_role" = "domaincontroller_backup" ]; then
+	echo "ERROR: This package must be installed on a DC master or DC backup!"
+	echo "ERROR: Please uninstall and install on a DC master or DC backup!"
+fi
+
 if [ "$1" = "configure" -a -z "$2" ] ; then
 	echo "Fresh installation..."
 	su - postgres -c "echo \"CREATE ROLE selfservice WITH LOGIN;\" | psql"
@@ -74,7 +81,7 @@ univention-config-registry set \
 	umc/self-service/passwordreset/sms/enabled?no
 
 if [ "$1" = "configure" ]; then
-	uinst=/usr/lib/univention-install/65univention-management-console-module-passwordreset.uinst
+	uinst=/usr/lib/univention-install/65univention-management-console-module-passwordreset-uninstall.uinst
 	[ -e "$uinst" ] && rm "$uinst"
 fi
 
diff --git a/management/univention-self-service/debian/univention-self-service-backend.postinst b/management/univention-self-service/debian/univention-self-service-backend.postinst
--- a/management/univention-self-service/debian/univention-self-service-backend.postinst
+++ b/management/univention-self-service/debian/univention-self-service-backend.postinst
@@ -1,5 +1,7 @@
-#!/bin/sh
-# postinst script for univention-self-service
+#!/bin/bash
+#
+# Univention Self Service backend
+#  postinst file for the debian package
 #
 # Copyright 2015 Univention GmbH
 #
@@ -30,28 +32,19 @@
 
 #DEBHELPER#
 
-# web site logging
-ACCESS_LOG=/var/log/univention/self-service-access.log
-ERROR_LOG=/var/log/univention/self-service-error.log
+eval "$(univention-config-registry shell)"
 
-if [ "$1" = "configure" -a -z "$2" ] ; then
-	echo "Fresh installation..."
-	adduser --system --no-create-home --group self-service
+if ! [ "$server_role" = "domaincontroller_master" -o "$server_role" = "domaincontroller_backup" ]; then
+	echo "ERROR: This package must be installed on a DC master or DC backup!"
+	echo "ERROR: Please uninstall and install on a DC master or DC backup!"
 fi
 
-touch $ACCESS_LOG $ERROR_LOG
-chown self-service:adm $ACCESS_LOG $ERROR_LOG
-chmod 640 $ACCESS_LOG $ERROR_LOG
+if [ "$1" = "configure" ]; then
+	uinst=/usr/lib/univention-install/66univention-self-service-backend-uninstall.uinst
+	[ -e "$uinst" ] && rm "$uinst"
+fi
 
-/usr/lib/univention-server/server_password_change.d/univention-self-service postchange
-
-MASTER=$(ucr get ldap/master)
-univention-config-registry set \
-	"self-service/backend-server?$MASTER" \
-	self-service/web/enabled?yes
-
-a2enmod wsgi
-a2ensite univention-self-service
-invoke-rc.d apache2 restart
+. /usr/share/univention-lib/base.sh
+call_joinscript 34univention-self-service-backend.inst
 
 exit 0
diff --git a/management/univention-self-service/debian/univention-self-service-frontend.postinst b/management/univention-self-service/debian/univention-self-service-frontend.postinst
--- a/management/univention-self-service/debian/univention-self-service-frontend.postinst
+++ b/management/univention-self-service/debian/univention-self-service-frontend.postinst
@@ -1,8 +1,5 @@
 #!/bin/sh
-
-#
-# Univention Management Console Module
-#  unjoin script
+# postinst script for univention-self-service
 #
 # Copyright 2015 Univention GmbH
 #
@@ -31,30 +28,32 @@
 # /usr/share/common-licenses/AGPL-3; if not, see
 # <http://www.gnu.org/licenses/>.
 
-VERSION=1
+#DEBHELPER#
 
-. /usr/share/univention-join/joinscripthelper.lib
-. /usr/share/univention-lib/ldap.sh
+# web site logging
+ACCESS_LOG=/var/log/univention/self-service-access.log
+ERROR_LOG=/var/log/univention/self-service-error.log
 
-joinscript_init
-
-ucs_removeServiceFromLocalhost "self-service-passwordreset-backend" "$@" || die
-
-if ucs_isServiceUnused "self-service-passwordreset-backend" "$@"
-then
-	eval "$(ucr shell)"
-	udm settings/extended_attribute remove "$@" \
-		--dn "cn=UniventionPasswordSelfServiceContactEmail,cn=custom attributes,cn=univention,$ldap_base"
-	udm settings/extended_attribute remove "$@" \
-		--dn "cn=UniventionPasswordSelfServiceContactMobile,cn=custom attributes,cn=univention,$ldap_base"
-	udm policies/umc "$@" modify \
-		--dn cn=selfservice-umc-servers,cn=UMC,cn=policies,$ldap_base \
-		--remove allow=cn=passwordreset-all,cn=operations,cn=UMC,cn=univention,$ldap_base
-	udm settings/umc_operationset remove "$@" \
-		--dn cn=passwordreset-all,cn=operations,cn=UMC,cn=univention,$ldap_base
-	ucs_unregisterLDAPExtension "$@" --schema /usr/share/univention-self-service/self-service-passwordreset.schema
+if [ "$1" = "configure" -a -z "$2" ] ; then
+	echo "Fresh installation..."
+	adduser --system --no-create-home --group self-service
 fi
 
-joinscript_remove_script_from_status_file univention-management-console-module-passwordreset
+touch $ACCESS_LOG $ERROR_LOG
+chown self-service:adm $ACCESS_LOG $ERROR_LOG
+chmod 640 $ACCESS_LOG $ERROR_LOG
+
+/usr/lib/univention-server/server_password_change.d/univention-self-service postchange
+
+MASTER=$(ucr get ldap/master)
+univention-config-registry set \
+	"self-service/backend-server?$MASTER" \
+	self-service/web/enabled?yes
+
+a2enmod wsgi
+a2ensite univention-self-service
+# restart, so apache reloads WSGI
+# retry if fail because of to quick successive restarts (from other frontend packages)
+invoke-rc.d apache2 restart || (sleep 2; invoke-rc.d apache2 restart)
 
 exit 0
diff --git a/management/univention-self-service/debian/univention-self-service-passwordreset-frontend.postinst b/management/univention-self-service/debian/univention-self-service-passwordreset-frontend.postinst
--- a/management/univention-self-service/debian/univention-self-service-passwordreset-frontend.postinst
+++ b/management/univention-self-service/debian/univention-self-service-passwordreset-frontend.postinst
@@ -41,4 +41,10 @@ univention-config-registry set \
 	"ucs/web/overview/entries/service/passwordreset/port_http=" \
 	"ucs/web/overview/entries/service/passwordreset/port_https=443"
 
+if [ "$1" = "configure" ] && [ -n "$2" ]; then
+	# restart, so apache reloads WSGI
+	# retry if fail because of to quick successive restarts (from other frontend packages)
+	invoke-rc.d apache2 restart || (sleep 2; invoke-rc.d apache2 restart)
+fi
+
 exit 0
diff --git a/management/univention-self-service/debian/univention-self-service-setpassword-backend.postinst b/management/univention-self-service/debian/univention-self-service-setpassword-backend.postinst
--- a/management/univention-self-service/debian/univention-self-service-setpassword-backend.postinst
+++ b/management/univention-self-service/debian/univention-self-service-setpassword-backend.postinst
@@ -1,8 +1,7 @@
-#!/bin/sh
-
+#!/bin/bash
 #
-# Univention Management Console Module
-#  unjoin script
+# Univention Self Service Change Password backend
+#  postinst file for the debian package
 #
 # Copyright 2015 Univention GmbH
 #
@@ -31,30 +30,21 @@
 # /usr/share/common-licenses/AGPL-3; if not, see
 # <http://www.gnu.org/licenses/>.
 
-VERSION=1
+#DEBHELPER#
 
-. /usr/share/univention-join/joinscripthelper.lib
-. /usr/share/univention-lib/ldap.sh
+eval "$(univention-config-registry shell)"
 
-joinscript_init
-
-ucs_removeServiceFromLocalhost "self-service-passwordreset-backend" "$@" || die
-
-if ucs_isServiceUnused "self-service-passwordreset-backend" "$@"
-then
-	eval "$(ucr shell)"
-	udm settings/extended_attribute remove "$@" \
-		--dn "cn=UniventionPasswordSelfServiceContactEmail,cn=custom attributes,cn=univention,$ldap_base"
-	udm settings/extended_attribute remove "$@" \
-		--dn "cn=UniventionPasswordSelfServiceContactMobile,cn=custom attributes,cn=univention,$ldap_base"
-	udm policies/umc "$@" modify \
-		--dn cn=selfservice-umc-servers,cn=UMC,cn=policies,$ldap_base \
-		--remove allow=cn=passwordreset-all,cn=operations,cn=UMC,cn=univention,$ldap_base
-	udm settings/umc_operationset remove "$@" \
-		--dn cn=passwordreset-all,cn=operations,cn=UMC,cn=univention,$ldap_base
-	ucs_unregisterLDAPExtension "$@" --schema /usr/share/univention-self-service/self-service-passwordreset.schema
+if ! [ "$server_role" = "domaincontroller_master" -o "$server_role" = "domaincontroller_backup" ]; then
+	echo "ERROR: This package must be installed on a DC master or DC backup!"
+	echo "ERROR: Please uninstall and install on a DC master or DC backup!"
 fi
 
-joinscript_remove_script_from_status_file univention-management-console-module-passwordreset
+if [ "$1" = "configure" ]; then
+	uinst=/usr/lib/univention-install/65univention-self-service-setpassword-backend-uninstall.uinst
+	[ -e "$uinst" ] && rm "$uinst"
+fi
+
+. /usr/share/univention-lib/base.sh
+call_joinscript 35univention-self-service-setpassword-backend.inst
 
 exit 0
diff --git a/management/univention-self-service/debian/univention-self-service-setpassword-frontend.postinst b/management/univention-self-service/debian/univention-self-service-setpassword-frontend.postinst
--- a/management/univention-self-service/debian/univention-self-service-setpassword-frontend.postinst
+++ b/management/univention-self-service/debian/univention-self-service-setpassword-frontend.postinst
@@ -1,8 +1,5 @@
 #!/bin/sh
-
-#
-# Univention Management Console Module
-#  unjoin script
+# postinst script for univention-self-service-setpassword
 #
 # Copyright 2015 Univention GmbH
 #
@@ -31,30 +28,22 @@
 # /usr/share/common-licenses/AGPL-3; if not, see
 # <http://www.gnu.org/licenses/>.
 
-VERSION=1
+#DEBHELPER#
 
-. /usr/share/univention-join/joinscripthelper.lib
-. /usr/share/univention-lib/ldap.sh
+univention-config-registry set \
+	self-service/setpassword/web/enabled?yes \
+	"ucs/web/overview/entries/service/setpassword/description=Change Password" \
+	"ucs/web/overview/entries/service/setpassword/description/de=Passwort ändern" \
+	"ucs/web/overview/entries/service/setpassword/icon=/univention-management-console/js/dijit/themes/umc/icons/50x50/apps-univention-demoapp.png" \
+	"ucs/web/overview/entries/service/setpassword/label=Change Password" \
+	"ucs/web/overview/entries/service/setpassword/label/de=Passwort ändern" \
+	"ucs/web/overview/entries/service/setpassword/link=/ucs-overview/setpassword.html" \
+	"ucs/web/overview/entries/service/setpassword/port_http=" \
+	"ucs/web/overview/entries/service/setpassword/port_https=443"
 
-joinscript_init
-
-ucs_removeServiceFromLocalhost "self-service-passwordreset-backend" "$@" || die
-
-if ucs_isServiceUnused "self-service-passwordreset-backend" "$@"
-then
-	eval "$(ucr shell)"
-	udm settings/extended_attribute remove "$@" \
-		--dn "cn=UniventionPasswordSelfServiceContactEmail,cn=custom attributes,cn=univention,$ldap_base"
-	udm settings/extended_attribute remove "$@" \
-		--dn "cn=UniventionPasswordSelfServiceContactMobile,cn=custom attributes,cn=univention,$ldap_base"
-	udm policies/umc "$@" modify \
-		--dn cn=selfservice-umc-servers,cn=UMC,cn=policies,$ldap_base \
-		--remove allow=cn=passwordreset-all,cn=operations,cn=UMC,cn=univention,$ldap_base
-	udm settings/umc_operationset remove "$@" \
-		--dn cn=passwordreset-all,cn=operations,cn=UMC,cn=univention,$ldap_base
-	ucs_unregisterLDAPExtension "$@" --schema /usr/share/univention-self-service/self-service-passwordreset.schema
+if [ "$1" = "configure" ] && [ -n "$2" ]; then
+	# restart, so apache reloads WSGI
+	# retry if fail because of to quick successive restarts (from other frontend packages)
+	invoke-rc.d apache2 restart || (sleep 2; invoke-rc.d apache2 restart)
 fi
-
-joinscript_remove_script_from_status_file univention-management-console-module-passwordreset
-
 exit 0
