Bug #31250: ucs-test: Use stored passwords
The Domain credentials are now stored in UCR variables.

Deprecate old shell variables and use exported UCR variables instead.

Directly read password from ldap.secret file.

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.2/ucs-3.2-0@42555 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/00_base/40univention-ssh_echo b/test/ucs-test/tests/00_base/40univention-ssh_echo
--- a/test/ucs-test/tests/00_base/40univention-ssh_echo
+++ b/test/ucs-test/tests/00_base/40univention-ssh_echo
@@ -6,11 +6,8 @@
 ## exposure: safe
 
 . "$TESTLIBPATH/base.sh" || exit 137
-pwfile="$(mktemp)"
-trap "rm -f '$pwfile'" EXIT
-echo -n "${BINDPWD}" >"$pwfile"
 
-result="$(univention-ssh "$pwfile" "root@${hostname}.${domainname}" echo -n | wc -c ; echo "${PIPESTATUS[0]}")" || exit 110 # ERROR
+result="$(univention-ssh "$tests_domainadmin_pwdfile" "root@${hostname}.${domainname}" echo -n | wc -c ; echo "${PIPESTATUS[0]}")" || exit 110 # ERROR
 if [ $'0\n0' = "$result" ]
 then
 	exit 100 # OK
