* 00_base/96rename_domain_admins: ignore slapd.conf check on   memberserver (Bug #34201)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.2/ucs-3.2-1@49161 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/00_base/96rename_domain_admins b/test/ucs-test/tests/00_base/96rename_domain_admins
--- a/test/ucs-test/tests/00_base/96rename_domain_admins
+++ b/test/ucs-test/tests/00_base/96rename_domain_admins
@@ -14,6 +14,8 @@
 . "$TESTLIBPATH/random.sh" || exit 137
 . "$TESTLIBPATH/group.sh" || exit 137
 
+eval "$(ucr shell")"
+
 GROUPNAME=$(group_randomnameme)
 
 udm-test groups/group modify --dn "cn=Domain Admins,cn=groups,$ldap_base" --set name="$GROUPNAME"
@@ -60,18 +62,20 @@ for file in /etc/security/access-*.conf; do
 	fi
 done
 
-for file in /etc/ldap/slapd.conf; do
-	echo -n "Checking if new admin group name is set to $file: "
-	if grep -q "$GROUPNAME" $file; then
-		echo "done"
-	else
-		echo "failed"
-		echo "************** $file ***************"
-		cat $file
-		echo "****************************************"
-		exit 1
-	fi
-done
+if [ "$server_role" != "memberserver" ]; then
+	for file in /etc/ldap/slapd.conf; do
+		echo -n "Checking if new admin group name is set to $file: "
+		if grep -q "$GROUPNAME" $file; then
+			echo "done"
+		else
+			echo "failed"
+			echo "************** $file ***************"
+			cat $file
+			echo "****************************************"
+			exit 1
+		fi
+	done
+fi
 
 exit "$RETVAL"
 
