* Bug #42602: Fixed quoting issues to support App installations with versions containing spaces * Bug #42603: When upgrading the underlying container, all available release updates are installed in one run * Bug #39803: Abort installation if the App is not found instead of doing nothing
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.2/ucs-4.2-0@73363 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/container/univention-docker-container-mode/usr/share/univention-docker-container-mode/update_app_version b/container/univention-docker-container-mode/usr/share/univention-docker-container-mode/update_app_version
--- a/container/univention-docker-container-mode/usr/share/univention-docker-container-mode/update_app_version
+++ b/container/univention-docker-container-mode/usr/share/univention-docker-container-mode/update_app_version
@@ -41,7 +41,7 @@ fi
 
 echo "Installing packages for $APP_ARG"
 univention-app update
-univention-app register "$APP_ARG" --component --do-it
+univention-app register "$APP_ARG" --component --do-it || die "Could not register Component"
 app_packages="$(univention-app get "$APP_ARG" default_packages --values-only --shell)"
 if [ -n "$app_packages" ]; then
 	if [ -n "$ERROR_FILE" ]; then
@@ -52,6 +52,7 @@ if [ -n "$app_packages" ]; then
 	if [ "$?" -ne 0 ]; then
 		die "Could not install the app"
 	fi
+	/usr/share/univention-updater/univention-updater-check
 
 	echo "Calling app join scripts..."
 	univention-run-join-scripts -dcaccount "$username" -dcpwd "$password_file"
