Bug #43177: install package updates update_app_version
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.2/ucs-4.2-0@75286 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/container/univention-docker-container-mode/usr/share/univention-docker-container-mode/update_app_version b/container/univention-docker-container-mode/usr/share/univention-docker-container-mode/update_app_version
--- a/container/univention-docker-container-mode/usr/share/univention-docker-container-mode/update_app_version
+++ b/container/univention-docker-container-mode/usr/share/univention-docker-container-mode/update_app_version
@@ -50,11 +50,15 @@ if [ -n "$app_packages" ]; then
 		univention-install -y $app_packages
 	fi
 	if [ "$?" -ne 0 ]; then
-		die "Could not install the app"
+		die "Could not update the app packages"
 	fi
-	/usr/share/univention-updater/univention-updater-check
-
-	echo "Calling app join scripts..."
-	univention-run-join-scripts -dcaccount "$username" -dcpwd "$password_file"
 fi
 
+echo "Installing package updates for $APP_ARG"
+univention-upgrade --noninteractive --updateto "$(ucr get version/version)-$(ucr get version/patchlevel)" --disable-app-updates
+if [ "$?" -ne 0 ]; then
+	die "Could not update the packages"
+fi
+
+echo "Calling app join scripts..."
+univention-run-join-scripts -dcaccount "$username" -dcpwd "$password_file"
