test(vm): Ignore AWS-EC2 issues
The boot device depends on the instance type:
- /dev/xdva on t2.large
- /dev/nvme0n1 on x5.xlarge

Re-enable tests disabled since 0122f28f9fc72b511240753333a2eb1f5ef9f18a
and turn them into warnings for now.

Bug #56447

diff --git a/test/utils/vm-ucs-image-check b/test/utils/vm-ucs-image-check
--- a/test/utils/vm-ucs-image-check
+++ b/test/utils/vm-ucs-image-check
@@ -31,6 +31,9 @@ die () {
 	echo "$exe: $*" >&2
 	exit 1
 }
+have () {
+	command -v "$1" >/dev/null 2>&1
+}
 
 cleanup () {
 	rm -f "$tmp"
@@ -64,9 +67,14 @@ parse_args () {
 	checks=("$@")
 }
 
-issue () {
+warn () {
 	[ -t 2 ] && tput bold
 	echo "W: $1" >&2
+	[ -t 2 ] && tput sgr0
+}
+error () {
+	[ -t 2 ] && tput bold
+	echo "E: $1" >&2
 	[ -t 2 ] && tput sgr0
 	ready=false
 	shift
@@ -81,76 +89,76 @@ check_apt () {
 	for deb in /var/cache/apt/archives/*.deb
 	do
 		[ -f "$deb" ] || continue
-		issue "APT cache contains files" apt-get clean
+		error "APT cache contains files" apt-get clean
 		break
 	done
 }
 
 check_bash_history () {
 	[ -s ~/.bash_history ] &&
-		issue "BASH history exists" truncate -s 0 ~/.bash_history
+		error "BASH history exists" truncate -s 0 ~/.bash_history
 }
 
-#check_ssh () {
-#	local key
-#	for key in /etc/ssh/ssh_host_*
-#	do
-#		[ -f "$key" ] || continue
-#		issue "SSH keys exist" rm -f /etc/ssh/ssh_host_*
-#		break
-#	done
-#}
+check_ssh () {
+	local key
+	for key in /etc/ssh/ssh_host_*
+	do
+		[ -f "$key" ] || continue
+		warn "SSH keys exist" rm -f /etc/ssh/ssh_host_*
+		break
+	done
+}
 
-#check_postfix () {
-#	local pfs
-#	for pfs in /etc/postfix/dh_*.pem
-#	do
-#		[ -f "$pfs" ] || continue
-#		issue "Postfix PFS files exist" rm -f /etc/postfix/dh_*.pem
-#		break
-#	done
-#}
+check_postfix () {
+	local pfs
+	for pfs in /etc/postfix/dh_*.pem
+	do
+		[ -f "$pfs" ] || continue
+		warn "Postfix PFS files exist" rm -f /etc/postfix/dh_*.pem
+		break
+	done
+}
 
 check_mail () {
 	find /var/mail -type f -not -empty -print0 >"$tmp" || :
 	[ -s "$tmp" ] &&
-		issue "Mail exist" find /var/mail -type f -not -empty -delete
+		error "Mail exist" find /var/mail -type f -not -empty -delete
 }
 
 check_backup () {
 	[ ! -e /var/univention-backup ] && return 0
 	find /var/univention-backup -mindepth 1 -not -empty -print0 >"$tmp" || :
 	[ -s "$tmp" ] &&
-		issue "Backup exist" find /var/univention-backup -mindepth 1 -not -empty -delete
+		error "Backup exist" find /var/univention-backup -mindepth 1 -not -empty -delete
 }
 
 check_udev () {
 	find /etc/udev/rules.d -name \*-persistent-\*.rules -print0 >"$tmp" || :
 	[ -s "$tmp" ] &&
-		issue "Persistent udev rules exist" find /etc/udev/rules.d -name \*-persistent-\*.rules -delete
+		error "Persistent udev rules exist" find /etc/udev/rules.d -name \*-persistent-\*.rules -delete
 }
 
 check_grub () {
 	local MAP dev debconf
 	MAP='/boot/grub/device.map'
 	[ -s "$MAP" ] ||
-		issue "GRUB device.map missing" grub-mkdevicemap
+		error "GRUB device.map missing" grub-mkdevicemap
 	dev=$(awk '/^\(hd0\)/{print $2}' "$MAP")
 	[ -b "$dev" ] ||
-		issue "GRUB boot device wrong" grub-mkdevicemap
+		warn "GRUB boot device wrong" grub-mkdevicemap
 	dev=$(awk '/^\(hd0\)/{print $2}' "$MAP")
 	debconf=$(echo 'get grub-pc/install_devices' | debconf-communicate | sed 's/^0 //')
 	[ -b "$debconf" ] ||
-		issue "DebConf GRUB device wrong" debconf-communicate <<<"set grub-pc/install_devices $dev"
+		warn "DebConf GRUB device wrong" debconf-communicate <<<"set grub-pc/install_devices $dev"
 	[ "${grub_rootdelay:-5}" -gt 0 ] &&
-		issue "grub/rootdelay != 0" ucr set grub/rootdelay='0'
+		error "grub/rootdelay != 0" ucr set grub/rootdelay='0'
 	[ "${grub_timeout:-5}" -gt 0 ] &&
-		issue "grub/timeout != 0" ucr set grub/timeout='0'
+		error "grub/timeout != 0" ucr set grub/timeout='0'
 }
 
 check_root () {
 	grep -q '^root:\*:' /etc/shadow ||
-		issue "root password exists" usermod -p \* root
+		error "root password exists" usermod -p \* root
 }
 
 check_ec2 () {
@@ -159,22 +167,22 @@ check_ec2 () {
 		return 0
 	echo "I: EC2"
 	[ "${server_amazon:-}" = true ] ||
-		issue "UCRV server/amazon" ucr set server/amazon='true'
+		error "UCRV server/amazon" ucr set server/amazon='true'
 	[ -z "${grub_generate_menu_lst:-}" ] ||
-		issue "generate-menu-lst is enabled" ucr set grub/generate-menu-lst='no'
+		error "generate-menu-lst is enabled" ucr set grub/generate-menu-lst='no'
 	[ -e /boot/grub/menu.lst ] &&
-		issue "menu.lst exists" rm -f /boot/grub/menu.lst*
+		error "menu.lst exists" rm -f /boot/grub/menu.lst*
 	case "${grub_append:-}" in
 	*console=ttyS*) ;;
-	*) issue "Missing serial console" ucr set grub/append="${grub_append:+$grub_append }console=tty0 console=ttyS0" ;;
+	*) error "Missing serial console" ucr set grub/append="${grub_append:+$grub_append }console=tty0 console=ttyS0" ;;
 	esac
 	case "${grub_terminal:-}" in
 	*serial*) ;;
-	*) issue "Missing GRUB terminal" ucr set grub/terminal='console serial' ;;
+	*) error "Missing GRUB terminal" ucr set grub/terminal='console serial' ;;
 	esac
 	case "${grub_serialcommand:-}" in
 	serial*) ;;
-	*) issue "Missing GRUB serial" ucr set grub/serialcommand='serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1' ;;
+	*) error "Missing GRUB serial" ucr set grub/serialcommand='serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1' ;;
 	esac
 }
 
@@ -183,7 +191,7 @@ check_dns () {
 	for ns in nameserver1 nameserver2 nameserver3 dns_forwarder1 dns_forwarder2 dns_forwarder3
 	do
 		case "${!ns:-}" in
-		8.8.8.8|8.8.4.4|208.67.22[02].22[02]|2602:0:cc[cd]::2) issue "Using public DNS in $ns" ucr unset "$ns" ;;
+		8.8.8.8|8.8.4.4|208.67.22[02].22[02]|2602:0:cc[cd]::2) error "Using public DNS in $ns" ucr unset "$ns" ;;
 		esac
 	done
 }
@@ -192,11 +200,11 @@ check_ucr () {
 	local key value
 	case "${repository_online:-}" in
 	false|no|disable|disabled|0) ;;
-	*) issue "online should be disabled" ucr set repository/online='false' ;;
+	*) error "online should be disabled" ucr set repository/online='false' ;;
 	esac
 	case "${repository_online_unmaintained:-}" in
 	false|no|disable|disabled|0|'') ;;
-	*) issue "unmaintained should be disabled" ucr set repository/online/unmaintained='no' ;;
+	*) error "unmaintained should be disabled" ucr set repository/online/unmaintained='no' ;;
 	esac
 	while IFS=': ' read -r key value
 	do
@@ -210,21 +218,21 @@ check_ucr () {
 	done </etc/univention/base.conf >"$tmp"
 	# shellcheck disable=SC2046
 	[ -s "$tmp" ] &&
-		issue "Wrong errata component" $(xargs -0 -a "$tmp" echo ucr set)
+		error "Wrong errata component" $(xargs -0 -a "$tmp" echo ucr set)
 }
 
 check_links () {
 	return 0  # FIXME
 	find / -xdev -xtype l -printf '%p -> %l\n' >"$tmp"
 	[ -s "$tmp" ] &&
-		issue "Broken sym-links"
+		error "Broken sym-links"
 }
 
-#check_home () {
-#	find /root -mindepth 1 -name .ssh -prune -o -not -name .profile -not -name .bashrc -not -name .bash_history -print0 >"$tmp"
-#	[ -s "$tmp" ] &&
-#		issue "Files in $HOME" find /root -mindepth 1 -name .ssh -prune -o -not -name .profile -not -name .bashrc -not -name .bash_history -delete
-#}
+check_home () {
+	find /root -mindepth 1 -name .ssh -prune -o -not -name .profile -not -name .bashrc -not -name .bash_history -print0 >"$tmp"
+	[ -s "$tmp" ] &&
+		warn "Files in $HOME" find /root -mindepth 1 -name .ssh -prune -o -not -name .profile -not -name .bashrc -not -name .bash_history -delete
+}
 
 check_dpkg () {
 	local desired status error pkg
@@ -233,8 +241,8 @@ check_dpkg () {
 	do
 		case "$desired $status $error" in
 		"install ok installed") ;;
-		"deinstall ok config-files") issue "Config-files" dpkg -P "$pkg" ;;
-		*) issue "Unknown status $pkg: $desired $status $error"
+		"deinstall ok config-files") error "Config-files" dpkg -P "$pkg" ;;
+		*) error "Unknown status $pkg: $desired $status $error"
 		esac
 	done <"$tmp"
 }
@@ -249,7 +257,7 @@ check_kernel () {  # Bug #37144
 		case "$desired $status $error $pkg" in
 		"install ok installed $current") ;;
 		"unknown ok not-installed "*) ;;
-		*) issue "Old Kernel" apt-get remove --purge "$pkg" ;;
+		*) error "Old Kernel" apt-get remove --purge "$pkg" ;;
 		esac
 	done <"$tmp"
 }
@@ -258,39 +266,40 @@ check_system_setup () {
 	local CACHE='/var/cache/univention-system-setup/packages'
 	find "$CACHE" -name \*.deb -printf '%f\n' >"$tmp" || :
 	[ -s "$tmp" ] ||
-		issue "No packages cached" /usr/share/univention-system-setup/download-packages
+		error "No packages cached" /usr/share/univention-system-setup/download-packages
 	find "$CACHE" -name \*.deb -printf '%f\n' |
 		sed -e '/^lib/d' -e 's/_.*//' |
 		xargs -n 1 apt-get -qq --print-uris install >"$tmp"
 	grep -F -v "$CACHE" "$tmp" &&
-		issue "Missing packages in cache" /usr/share/univention-system-setup/download-packages
+		error "Missing packages in cache" /usr/share/univention-system-setup/download-packages
 }
 
-#check_logs () {
-#	find /var/log \( -name '*.gz' -o -name '*.[0-9]' \) -print0 >"$tmp" || :
-#	[ -s "$tmp" ] &&
-#		issue "Old logfiles exist" find /var/log \( -name \*.gz -o -name \*.[0-9] \) -delete
-#	find /var/log \( -not -name '*.gz' -not -name '*.[0-9]' -type f -not -empty \) -print0 >"$tmp" || :
-#	[ -s "$tmp" ] &&
-#		issue "Logfiles exist" find /var/log \( -not -name \*.gz -not -name \*.[0-9] -type f -not -empty \) -delete
-#	[ -s /var/lib/logrotate/status ] &&
-#		issue "logrotate status exists" truncate -s 0 /var/lib/logrotate/status
-#}
+check_logs () {
+	find /var/log \( -name '*.gz' -o -name '*.[0-9]' \) -print0 >"$tmp" || :
+	[ -s "$tmp" ] &&
+		warn "Old logfiles exist" find /var/log \( -name \*.gz -o -name \*.[0-9] \) -delete
+	find /var/log \( -not -name '*.gz' -not -name '*.[0-9]' -type f -not -empty \) -print0 >"$tmp" || :
+	[ -s "$tmp" ] &&
+		warn "Logfiles exist" find /var/log \( -not -name \*.gz -not -name \*.[0-9] -type f -not -empty \) -delete
+	[ -s /var/lib/logrotate/status ] &&
+		warn "logrotate status exists" truncate -s 0 /var/lib/logrotate/status
+}
 
 check_journal () {
 	journalctl -q -b -1 -n 0 >"$tmp" 2>/dev/null
 	[ -s "$tmp" ] &&
-		issue "Old journald boot exists" journalctl --rotate
+		error "Old journald boot exists" journalctl --rotate
 	[ -s "$tmp" ] &&
-		issue "Old journald files exists" journalctl --vacuum-files=1
+		error "Old journald files exists" journalctl --vacuum-files=1
 }
 
-#check_machina_ide () {
-#	[ -s /var/lib/dbus/machine-id ] &&
-#		issue "/var/lib/dbus/machine-id exists" rm -f /var/lib/dbus/machine-id
-#	[ -s /etc/machine-id  ] &&
-#		issue "/etc/machine-id exists" truncate -s 0 /etc/machine-id
-#}
+check_machina_ide () {
+	[ -s /var/lib/dbus/machine-id ] &&
+	[ ! -L /var/lib/dbus/machine-id ] &&
+		warn "/var/lib/dbus/machine-id exists" ln -snf /etc/machine-id /var/lib/dbus/machine-id
+	[ -s /etc/machine-id  ] &&
+		warn "/etc/machine-id exists" truncate -s 0 /etc/machine-id
+}
 
 main "$@"
 # vim :set backupcopy=auto:
