* check for postgresql-8.3 and postgresql-7.4 (Bug #12754)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/trunk/ucs@11995 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/services/univention-pkgdb/debian/univention-pkgdb.postinst b/services/univention-pkgdb/debian/univention-pkgdb.postinst
--- a/services/univention-pkgdb/debian/univention-pkgdb.postinst
+++ b/services/univention-pkgdb/debian/univention-pkgdb.postinst
@@ -32,6 +32,15 @@ set -e
 
 #DEBHELPER#
 
+pkg_installed(){
+	PKGNAME="$1";
+	if dpkg -l $PKGNAME 2>/dev/null| grep $PKGNAME | grep -q ^ii; then
+		return 0;	# true
+	else
+		return 1;
+	fi
+}
+
 if [ "$1" = "configure" -o "$1" = "reconfigure" ]
 then
 
@@ -47,7 +56,14 @@ then
   	su - postgres -c "psql -d pkgdb -f /var/lib/postgres/pkgdb.indexes-2.0.2"
   fi
 
-  /etc/init.d/postgresql-8.3 reload
+  if pkg_installed postgresql-8.3 ; then
+    /etc/init.d/postgresql-8.3 reload
+  elif pkg_installed postgresql-7.4 ; then
+  	/etc/init.d/postgresql-7.4 reload
+  else
+	echo "ERROR: neither postgresql-8.3 nor postgresql-7.4 is installed."
+	exit 1
+  fi
 fi
 
 if [ -z "$2" ]; then
