fix(test): 00/03_check_release_signature_do_not_ignore_me
Return right REASONs on error, e.g. SKIP when using appcenter-test.

Bug #53528: Fix 00/03_check_release_signature_do_not_ignore_me
Fixes: a85b6e53084

diff --git a/test/ucs-test/tests/00_checks/03_check_release_signature_do_not_ignore_me b/test/ucs-test/tests/00_checks/03_check_release_signature_do_not_ignore_me
--- a/test/ucs-test/tests/00_checks/03_check_release_signature_do_not_ignore_me
+++ b/test/ucs-test/tests/00_checks/03_check_release_signature_do_not_ignore_me
@@ -10,7 +10,7 @@
 ## exposure: safe
 
 # shellcheck source=../../lib/base.sh
-. "$TESTLIBPATH/base.sh" || exit 137
+. "$TESTLIBPATH/base.sh" || exit 137  # INSTALL
 
 detect_lib () {
 	local arch
@@ -20,7 +20,7 @@ detect_lib () {
 		[ -f "$libfaketime" ] &&
 			return 0
 	done
-	fail_fast 77 "libfaketime not found"
+	fail_fast 137 "libfaketime not found"  # INSTALL
 }
 detect_lib
 
@@ -44,20 +44,20 @@ apt_update () {
 }
 
 case "$(ucr get repository/app_center/server)" in
-*appcenter-test*) exit 33
+*appcenter-test*) exit 77  # SKIP
 esac
 
 # check if apt-get update in now+2y works
 if apt_update '+2y'
 then
 	apt-key list
-	fail_fast 110 "warnings/error during apt-get update"
+	fail_fast 110 "warnings/error during apt-get update"  # FAIL
 fi
 
 # check if apt-get update in now+50y fails (just to test the test)
 if ! apt_update '+50y' -q
 then
-	fail_fast 110 "did not fail 50 years into the future, key should have expired by then"
+	fail_fast 110 "did not fail 50 years into the future, key should have expired by then"  # FAIL
 fi
 
-exit 0
+exit 0  # OKAY
