WIP: TODO adjust codes

diff --git a/test/ucs-test/tests/00_checks/42_admember_roles b/test/ucs-test/tests/00_checks/42_admember_roles
--- a/test/ucs-test/tests/00_checks/42_admember_roles
+++ b/test/ucs-test/tests/00_checks/42_admember_roles
@@ -8,7 +8,7 @@
 . "$TESTLIBPATH/base.sh" || exit 137
 . /usr/share/univention-lib/ucr.sh
 
-is_ucr_true ad/member || exit 137
+is_ucr_true ad/member || exit 137  # fail or skip?
 
 if [ "$server_role" = "domaincontroller_master" ]; then
 	if ! checkpkg univention-ad-connector; then
diff --git a/test/ucs-test/tests/01_base/45license_v2 b/test/ucs-test/tests/01_base/45license_v2
--- a/test/ucs-test/tests/01_base/45license_v2
+++ b/test/ucs-test/tests/01_base/45license_v2
@@ -23,7 +23,7 @@ eval "$(ucr shell)"
 licenseVersion="$(univention-ldapsearch '(&(cn=admin)(objectClass=univentionLicense))' -LLL univentionLicenseVersion | sed -ne 's|univentionLicenseVersion: ||p')"
 
 if [ "$licenseVersion" != 2 ]; then
-	exit 137
+	exit 137  # fail or skip?
 fi
 
 getManagedClient ()
diff --git a/test/ucs-test/tests/01_base/70telnet_off b/test/ucs-test/tests/01_base/70telnet_off
--- a/test/ucs-test/tests/01_base/70telnet_off
+++ b/test/ucs-test/tests/01_base/70telnet_off
@@ -26,6 +26,6 @@ then
 	exit 101
 else
 	echo "telnet is not present on this system"
-	exit 137
+	exit 137  # fail or skip?
 fi
 # vim: set ft=sh :
diff --git a/test/ucs-test/tests/50_samba/85domain-join-without-admin-rights b/test/ucs-test/tests/50_samba/85domain-join-without-admin-rights
--- a/test/ucs-test/tests/50_samba/85domain-join-without-admin-rights
+++ b/test/ucs-test/tests/50_samba/85domain-join-without-admin-rights
@@ -21,7 +21,7 @@ fi
 s4_dcs="$(univention-ldapsearch '(&(univentionService=Samba 4)(objectClass=univentionDomainController))' -LLL dn | sed -ne 's|dn: ||p')"
 if [ -n "$s4_dcs" ]; then
 	echo "This is a S4 domain, skip test"
-	exit 137
+	exit 137  # fail or skip?
 fi
 
 username="$(user_randomname)"
diff --git a/test/ucs-test/tests/51_samba4/46machine_secret_access_sysvol b/test/ucs-test/tests/51_samba4/46machine_secret_access_sysvol
--- a/test/ucs-test/tests/51_samba4/46machine_secret_access_sysvol
+++ b/test/ucs-test/tests/51_samba4/46machine_secret_access_sysvol
@@ -17,7 +17,7 @@ target_host="$(univention-ldapsearch -LLL "univentionService=S4 Connector" cn | 
 
 if [ -z "$target_host" ]; then
     echo "Could not determine the target host for the test."
-    exit 137
+    exit 137  # fail or skip?
 fi
 
 info "----Accessing sysvol on $target_host.$domainname using smbclient and hostname/machine.secret credentials"
