Bug #23394: Fix media change
Fix str("768") != int(768) bug preventing media change.

Synchronize xencommons to clean xenstore on reboot (Bug #28309)

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs-3.1-1@40888 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/virtualization/xen-4.1/debian/xen-4.1.xencommons.init b/virtualization/xen-4.1/debian/xen-4.1.xencommons.init
--- a/virtualization/xen-4.1/debian/xen-4.1.xencommons.init
+++ b/virtualization/xen-4.1/debian/xen-4.1.xencommons.init
@@ -31,15 +31,24 @@ test -f $xencommons_config/xencommons && . $xencommons_config/xencommons
 XENCONSOLED_PIDFILE=/var/run/xenconsoled.pid
 shopt -s extglob
 
+# not running in Xen dom0 or domU
+if ! test -d /proc/xen ; then
+	exit 0
+fi
+
+# mount xenfs in dom0 or domU with a pv_ops kernel
 if test "x$1" = xstart && \
-     test -d /proc/xen && \
    ! test -f /proc/xen/capabilities && \
-   ! grep -qs '^xenfs ' /proc/mounts >/dev/null;
+   ! grep '^xenfs ' /proc/mounts >/dev/null;
 then
 	mount -t xenfs xenfs /proc/xen
 fi
 
-if ! grep -qs "control_d" /proc/xen/capabilities ; then
+# run this script only in dom0:
+# no capabilities file in xenlinux domU kernel
+# empty capabilities file in pv_ops domU kernel
+if test -f /proc/xen/capabilities && \
+   ! grep -q "control_d" /proc/xen/capabilities ; then
 	exit 0
 fi
 
@@ -48,12 +57,15 @@ do_start () {
 	local timeout=30
 
 	mkdir -p /var/run/xenstored
-	modprobe xen-evtchn
-	modprobe xen-gntdev
-	modprobe blktap
+	modprobe xen-evtchn 2>/dev/null
+	modprobe xen-gntdev 2>/dev/null
+	modprobe evtchn 2>/dev/null
+	modprobe gntdev 2>/dev/null
+	modprobe blktap 2>/dev/null
+
 	if ! `xenstore-read -s / >/dev/null 2>&1`
 	then
-		test -z "$XENSTORED_ROOTDIR" || XENSTORED_ROOTDIR="/var/lib/xenstored"
+		test -z "$XENSTORED_ROOTDIR" && XENSTORED_ROOTDIR="/var/lib/xenstored"
 		rm -f "$XENSTORED_ROOTDIR"/tdb* &>/dev/null
 		test -z "$XENSTORED_TRACE" || XENSTORED_ARGS=" -T /var/log/xen/xenstored-trace.log"
 
@@ -91,7 +103,8 @@ do_stop () {
 		while kill -9 $pid >/dev/null 2>&1; do sleep 0.1; done
 		rm -f $XENCONSOLED_PIDFILE
 	fi
-        log_warning_msg "Not stopping xenstored, as it cannot be restarted."
+
+	log_warning_msg "Not stopping xenstored, as it cannot be restarted."
 }
 
 case "$1" in
