Revert "Bug #49967 nagios: Check for running nscd only"
This reverts commit 3f9a132e6e58f41a34f3629a8039cb70cec0cf2b.

diff --git a/nagios/univention-nagios/usr/lib/nagios/plugins/check_univention_nscd b/nagios/univention-nagios/usr/lib/nagios/plugins/check_univention_nscd
--- a/nagios/univention-nagios/usr/lib/nagios/plugins/check_univention_nscd
+++ b/nagios/univention-nagios/usr/lib/nagios/plugins/check_univention_nscd
@@ -1,4 +1,5 @@
-#!/bin/sh
+#!/usr/bin/env bash
+#
 #
 # Univention Nagios Plugin
 #  check_univention_nscd: check if nscd is bound to its socket.
@@ -33,24 +34,23 @@
 #
 
 VERSION="1.00"
-PROGNAME="${0##*/}"
+PROGNAME=`/usr/bin/basename $0`
 
 STATE_OK=0
 STATE_WARNING=1
 STATE_CRITICAL=2
 STATE_UNKNOWN=3
 
-state () {
-    local STATE="$1"
-    case "$STATE" in
-        "$STATE_OK") STATE_STRING="OK" ;;
-        "$STATE_WARNING") STATE_STRING="WARNING" ;;
-        "$STATE_CRITICAL") STATE_STRING="CRITICAL" ;;
-        *) STATE_STRING="UNKNOWN" ;;
-    esac
-    shift
-    echo "${STATE_STRING}: $*"
-    exit "$STATE"
+get_state_string() {
+	if [ "$1" = "$STATE_OK" ] ; then
+		STATE_STRING="OK"
+	elif [ "$1" = "$STATE_WARNING" ] ; then
+		STATE_STRING="WARNING"
+	elif [ "$1" = "$STATE_CRITICAL" ] ; then
+		STATE_STRING="CRITICAL"
+	else
+		STATE_STRING="UNKNOWN"
+    fi
 }
 
 print_revision() {
@@ -69,16 +69,23 @@ print_help() {
     print_usage
 }
 
-while [ $# -ge 1 ]
-do
+while test -n "$1"; do
     case "$1" in
-        --help|-h)
+        --help)
             print_help
-            exit "$STATE_OK"
+            exit $STATE_OK
             ;;
-        --version|-V)
+        -h)
+            print_help
+            exit $STATE_OK
+            ;;
+        --version)
             print_revision
-            exit "$STATE_OK"
+            exit $STATE_OK
+            ;;
+        -V)
+            print_revision
+            exit $STATE_OK
             ;;
     esac
     shift
@@ -86,10 +93,61 @@ done
 
 nscd_socket="/var/run/nscd/socket"
 
-[ -S $nscd_socket ] ||
-    state "$STATE_CRITICAL" "no nscd socket found! nscd not running?"
+if [ ! -S $nscd_socket ]; then
+	state=$STATE_CRITICAL
+	get_state_string $state
+	echo "${STATE_STRING}: no nscd socket found! nscd not running?"
+	exit $state
+fi
 
-timeout 3 nscd -g >/dev/null 2>/dev/null ||
-    state "$STATE_CRITICAL" "nscd not responding!"
+pids_on_nscd_socket=$(fuser "$nscd_socket" 2>/dev/zero)
+RET=$?
+if (( $RET != 0 )); then
+	fuser_error=$(fuser "$nscd_socket" 2>&1)
+	if [[ "$fuser_error" != "" ]]; then
+		state=$STATE_UNKNOWN
+		get_state_string $state
+		echo "${STATE_STRING}: fuser command failed"
+		exit $state
+	fi
+fi
 
-state "$STATE_OK" "nscd is running."
+nscd_processes_on_nscd_socket=0
+for pid in $pids_on_nscd_socket; do
+	process_path=$(readlink /proc/"$pid"/exe)
+	if (( $? != 0 )); then
+		#Process died?
+		continue
+	fi
+	process_name=$(basename "$process_path")
+	if [[ "$process_name" == "nscd" ]]; then
+		let nscd_processes_on_nscd_socket++
+	else
+		state=$STATE_CRITICAL
+		get_state_string $state
+		echo "${STATE_STRING}: Unknown program: \""$process_name"\" bound to nscd socket."
+		exit $state
+	fi
+done
+
+if (( $nscd_processes_on_nscd_socket == 1 )); then
+	state=$STATE_OK
+	get_state_string $state
+	echo "${STATE_STRING}: only one instance of nscd running."
+	exit $state
+elif (( $nscd_processes_on_nscd_socket > 1 )); then 
+	state=$STATE_WARNING
+	get_state_string $state
+	echo "${STATE_STRING}: more than one instance of nscd bound to nscd socket."
+	exit $state
+elif (( $nscd_processes_on_nscd_socket == 0 )); then
+	state=$STATE_CRITICAL
+	get_state_string $state
+	echo "${STATE_STRING}: no instance of nscd bound to nscd socket. nscd might have crashed."
+	exit $state
+fi
+
+state=$STATE_CRITICAL
+get_state_string $state
+echo "${STATE_STRING}: PLUGIN FAILED"
+exit $state
