* Bug #23367 Feedback from QA: * Fix FTBFS inline declarations * Declare file scope functions and variables static * Error handling for conversion * Fix comments still referencing BDB * Fix case in error messages * drop unused struct mdb_ctx * do not malloc fixed struct * use calloc instead of malloc+memset
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.2/ucs-4.2-0@76935 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/management/univention-directory-listener/debian/univention-directory-listener.postinst b/management/univention-directory-listener/debian/univention-directory-listener.postinst
--- a/management/univention-directory-listener/debian/univention-directory-listener.postinst
+++ b/management/univention-directory-listener/debian/univention-directory-listener.postinst
@@ -67,32 +67,37 @@ fi
 
 call_joinscript 03univention-directory-listener.inst
 
-convert_to_lmdb() {
-	if [ ! -f /var/lib/univention-directory-listener/cache/data.mdb ]; then
-		if [ ! -d /var/lib/univention-directory-listener/cache ]; then
-			mkdir /var/lib/univention-directory-listener/cache
-			chown listener.nogroup \
-				/var/lib/univention-directory-listener/cache
-			chmod 700 /var/lib/univention-directory-listener/cache
-		fi
-		if [ -f /var/lib/univention-directory-listener/cache.db ]; then
-			running=1
-			/etc/init.d/univention-directory-listener status >/dev/null \
-				&& running=1 || running=0
+convert_to_lmdb () {
+	local rv
+	local DIR="/var/lib/univention-directory-listener/cache"
+	local BDB="$DIR.db"
+	local MDB="$DIR/data.mdb"
 
-			if [ "$running" -eq 1 ]; then
-				/etc/init.d/univention-directory-listener stop
-			fi
+	[ -f "$BDB" ] || return 0
+	[ -d "$DIR" ] || install -d -o listener -m 0700 "$DIR"
+	[ -f "$MDB" ] && return 0
 
-			univention-directory-listener-convert
-			chown listener.nogroup \
-				/var/lib/univention-directory-listener/cache/*
+	local running=1
+	/etc/init.d/univention-directory-listener status >/dev/null ||
+		running=0
 
-			if [ "$running" -eq 1 ]; then
-				/etc/init.d/univention-directory-listener start
-			fi
-		fi
+	if [ "$running" -eq 1 ]; then
+		/etc/init.d/univention-directory-listener stop
 	fi
+
+	su -s /bin/sh -c "univention-directory-listener-convert '$BDB'" listener
+	rv=$?
+	if [ "$rv" -eq 0 ]; then
+		mv "$BDB" /var/backup/"udl-cache-db.$(date +%s)"
+	else
+		echo "ERROR: univention-directory-listener-convert failed" >&2
+		rm -rf "$DIR"
+	fi
+
+	if [ "$running" -eq 1 ]; then
+		/etc/init.d/univention-directory-listener start
+	fi
+	return $rv
 }
 
 if [ "$1" = "configure" -a -n "$2" ]; then
@@ -105,7 +110,7 @@ if [ "$1" = "configure" -a -n "$2" ]; then
 	fi
 
 	if dpkg --compare-versions "$2" lt 11.0.1-1; then
-		convert_to_lmdb
+		convert_to_lmdb || exit $?
 	fi
 
 	/etc/init.d/univention-directory-listener crestart
