* Bug #33839: Run univention-upgrade after initial join
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.0/ucs-4.0-0@54169 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/base/univention-system-setup/usr/lib/univention-system-setup/scripts/90_postjoin/20upgrade b/base/univention-system-setup/usr/lib/univention-system-setup/scripts/90_postjoin/20upgrade
--- a/base/univention-system-setup/usr/lib/univention-system-setup/scripts/90_postjoin/20upgrade
+++ b/base/univention-system-setup/usr/lib/univention-system-setup/scripts/90_postjoin/20upgrade
@@ -50,10 +50,14 @@ if [ "$server_role" = "domaincontroller_master" ]; then
 else
 	# Try to update to the same version as DC master
 	if [ -e /var/univention-join/joined ]; then
-		vv=$(univention-ssh /etc/machine.secret $hostname\$@$ldap_server_name /usr/sbin/ucr get version/version 2>/dev/null)
-		pl=$(univention-ssh /etc/machine.secret $hostname\$@$ldap_server_name /usr/sbin/ucr get version/patchlevel 2>/dev/null)
-		echo "Running upgrade to DC Master version: univention-upgrade --noninteractive --updateto $vv-$pl"
-		univention-upgrade --noninteractive --updateto "$vv-$pl"
+		version=$(univention-ssh /etc/machine.secret $hostname\$@$ldap_server_name "echo $(/usr/sbin/ucr get version/version)-$(/usr/sbin/ucr get version/patchlevel)" 2>>/var/log/univention/setup.log)
+		if [ $? = 0 ]; then
+			echo "Running upgrade to DC Master version: univention-upgrade --noninteractive --updateto $version"
+			univention-upgrade --noninteractive --updateto "$version"
+		else
+			echo "WARNING: Getting version from DC Master failed! Running normal upgrade: univention-upgrade --noninteractive --updateto $version_version-0"
+			univention-upgrade --noninteractive --updateto "$version_version-0"
+		fi
 	else
 		echo "Running normal upgrade: univention-upgrade --noninteractive --updateto $version_version-0"
 		univention-upgrade --noninteractive --updateto "$version_version-0"
