Bug #49399: redirect error message from tdbbackup to stderr so cron will email error

diff --git a/services/univention-samba4/sbin/univention-samba4-backup b/services/univention-samba4/sbin/univention-samba4-backup
--- a/services/univention-samba4/sbin/univention-samba4-backup
+++ b/services/univention-samba4/sbin/univention-samba4-backup
@@ -137,7 +137,7 @@ for d in $DIRS; do
 					tdbbackup $file
 					Status=$?
 					if [ $Status -ne 0 ]; then
-						echo "Error while backing up $file with tdbbackup - status $Status"
+						>&2 echo "Error while backing up $file with tdbbackup - status $Status"
 						exit 1
 					fi
 				fi
