* Upgrade to UCS Core Edition (Bug #38107)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.0/ucs-4.0-1@59954 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/management/univention-ldap/debian/univention-ldap-server.postinst b/management/univention-ldap/debian/univention-ldap-server.postinst
--- a/management/univention-ldap/debian/univention-ldap-server.postinst
+++ b/management/univention-ldap/debian/univention-ldap-server.postinst
@@ -184,7 +184,7 @@ fi
 
 test -f /var/lib/univention-ldap/ldap/DB_CONFIG || univention-config-registry commit /var/lib/univention-ldap/ldap/DB_CONFIG
 
-upgrade_ffpu () {
+upgrade_license () {
 	case "$server_role" in
 	domaincontroller_master)
 		;;
@@ -204,19 +204,15 @@ upgrade_ffpu () {
 	then
 		echo "No 'Free for personal use edition' found: nothing to do."
 		return 0
-	elif grep -Fxq 'univentionLicenseUsers: 50' "$tmp"
-	then
-		echo "New 'Free for personal use edition' found: nothing to do."
-		return 0
 	elif grep -q '^univentionLicenseKeyID: ' "$tmp"
 	then
-		echo "Activated 'Free for personal use edition' found: see <http://sdb.univention.de/1295>."
+		echo "Activated 'Free for personal use edition' found: see <http://sdb.univention.de/1324>."
 		return 1
 	else
 		echo "Old 'Free for personal use edition' found: performing upgrade..."
-		univention-config-registry filter </usr/share/univention-ldap/ffpu.ldif >"$tmp" &&
+		univention-config-registry filter </usr/share/univention-ldap/core-edition.ldif >"$tmp" &&
 		univention-license-import "$tmp" ||
-		echo "Failed to import new license: see <http://sdb.univention.de/1295>."
+		echo "Failed to import new license: see <http://sdb.univention.de/1324>."
 		return 1
 	fi
 }
@@ -224,7 +220,7 @@ upgrade_ffpu () {
 if [ "$server_role" = "domaincontroller_master" ] || [ "$server_role" = "domaincontroller_backup" ]; then
 	/usr/lib/univention-install/01univention-ldap-server-init.inst || true
 	/usr/lib/univention-install/10univention-ldap-server.inst || true
-	[ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 11.0.11-1 && upgrade_ffpu || :
+	[ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 11.0.12-2 && upgrade_license || :
 fi
 
 ## after this line slapd.conf is expected to be updated properly and slapd may restart
