* Bug #39817: Minor improvements for 47faillog-global and 47faillog

diff --git a/test/ucs-test/tests/01_base/47faillog-global b/test/ucs-test/tests/01_base/47faillog-global
--- a/test/ucs-test/tests/01_base/47faillog-global
+++ b/test/ucs-test/tests/01_base/47faillog-global
@@ -69,14 +69,14 @@ test_output=$(ldapsearch -LLL -D "$userdn" -y "$tests_domainadmin_pwdfile" -s ba
 if [ -n "$test_output" ]; then
 	fail_test 110 "E: user can still do LDAP search but should be disabled in UDM"
 	univention-directory-manager users/user list --filter "uid=$NAME"
-	exit 110
+	exit $RETVAL
 fi
 
 test_output=$(ldapwhoami -D "$userdn" -y "$tests_domainadmin_pwdfile")
 if [ -n "$test_output" ]; then
 	fail_test 110 "E: user can still do LDAP whoami but should be disabled in UDM"
 	univention-directory-manager users/user list --filter "uid=$NAME"
-	exit 110
+	exit $RETVAL
 fi
 
 ### Just locking would be good, but requires ppolicy LDAP overlay active and configured properly to temporarily block LDAP authentication too,
@@ -85,14 +85,14 @@ fi
 # if [ "$udm_locked" != "  locked: 1" ]; then
 # 	fail_test 110 "E: user was not locked in UDM"
 # 	univention-directory-manager users/user list --filter "uid=$NAME"
-# 	exit 110
+#	exit $RETVAL
 # fi
 
 udm_disabled=$(univention-directory-manager users/user list --filter "uid=$NAME" | grep "^  disabled: 1")
 if [ "$udm_disabled" != "  disabled: 1" ]; then
 	fail_test 110 "E: user was not disabled in UDM"
 	univention-directory-manager users/user list --filter "uid=$NAME"
-	exit 110
+	exit $RETVAL
 fi
 
 udm-test users/user modify --dn="$userdn" --set disabled=0 # --set locked=0
@@ -101,21 +101,23 @@ wait_for_replication_and_postrun
 
 ssh_hostname="$(ssh_login "$tests_domainadmin_pwdfile")"
 if [ "$ssh_hostname" != "$hostname" ]; then
-	fail_fast 110 "E: The login wasn't successful, but the fail counter should be resetted"
+	fail_test 110 "E: The login wasn't successful, but the fail counter should be resetted"
+	faillog -u "$NAME"
+	exit $RETVAL
 fi
 
 test_output=$(ldapsearch -LLL -D "$userdn" -y "$tests_domainadmin_pwdfile" -s base dn | sed -n 's/^dn: //p')
 if [ -z "$test_output" ]; then
 	fail_test 110 "E: The cannot do LDAP search, but the account should be re-enabled and un-locked again"
 	univention-directory-manager users/user list --filter "uid=$NAME"
-	exit 110
+	exit $RETVAL
 fi
 
 test_output=$(ldapwhoami -D "$userdn" -y "$tests_domainadmin_pwdfile")
 if [ -z "$test_output" ]; then
 	fail_test 110 "E: The cannot do LDAP whoami, but the account should be re-enabled and un-locked again"
 	univention-directory-manager users/user list --filter "uid=$NAME"
-	exit 110
+	exit $RETVAL
 fi
 
 exit $RETVAL
