univention-mail-postfix (9.0.0-1) unstable; urgency=medium
  * Update to UCS 4.0 (Bug #35264)

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.0/ucs-4.0-0@52892 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/mail/univention-mail-postfix/conffiles/etc/init.d/postfix b/mail/univention-mail-postfix/conffiles/etc/init.d/postfix
--- a/mail/univention-mail-postfix/conffiles/etc/init.d/postfix
+++ b/mail/univention-mail-postfix/conffiles/etc/init.d/postfix
@@ -11,8 +11,8 @@
 # Provides:          postfix mail-transport-agent
 # Required-Start:    $local_fs $remote_fs $syslog $named $network $time
 # Required-Stop:     $local_fs $remote_fs $syslog $named $network
-# Should-Start:      postgresql mysql clamav-daemon postgrey spamassassin
-# Should-Stop:       postgresql mysql clamav-daemon postgrey spamassassin
+# Should-Start:      postgresql mysql clamav-daemon postgrey spamassassin saslauthd dovecot
+# Should-Stop:       postgresql mysql clamav-daemon postgrey spamassassin saslauthd dovecot
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: start and stop the Postfix Mail Transport Agent
@@ -63,8 +63,19 @@ test -x $DAEMON && test -f /etc/postfix/main.cf || exit 0
 . /lib/lsb/init-functions
 #DISTRO=$(lsb_release -is 2>/dev/null || echo Debian)
 
+enabled_instances() {
+	postmulti -l -a | awk '($3=="y") { print $1}'
+}
+
 running() {
-    queue=$(postconf -h queue_directory 2>/dev/null || echo /var/spool/postfix)
+    INSTANCE="$1"
+    if [ "X$INSTANCE" = X ]; then
+	    POSTCONF="postconf"
+    else
+	    POSTCONF="postmulti -i $INSTANCE -x postconf"
+    fi
+
+    queue=$($POSTCONF -h queue_directory 2>/dev/null || echo /var/spool/postfix)
     if [ -f ${queue}/pid/master.pid ]; then
 	pid=$(sed 's/ //g' ${queue}/pid/master.pid)
 	# what directory does the executable live in.  stupid prelink systems.
@@ -75,104 +86,171 @@ running() {
     fi
 }
 
+configure_instance() {
+    INSTANCE="$1"
+    if [ "X$INSTANCE" = X ]; then
+	    POSTCONF="postconf"
+    else
+	    POSTCONF="postmulti -i $INSTANCE -x postconf"
+    fi
+
+
+    # if you set myorigin to 'ubuntu.com' or 'debian.org', it's wrong, and annoys the admins of
+    # those domains.  See also sender_canonical_maps.
+
+    MYORIGIN=$($POSTCONF -h myorigin | tr 'A-Z' 'a-z')
+    if [ "X${MYORIGIN#/}" != "X${MYORIGIN}" ]; then
+	MYORIGIN=$(tr 'A-Z' 'a-z' < $MYORIGIN)
+    fi
+    if [ "X$MYORIGIN" = Xubuntu.com ] || [ "X$MYORIGIN" = Xdebian.org ]; then
+	log_failure_msg "Invalid \$myorigin ($MYORIGIN), refusing to start"
+	log_end_msg 1
+	exit 1
+    fi
+
+    config_dir=$($POSTCONF -h config_directory)
+    # see if anything is running chrooted.
+    NEED_CHROOT=$(awk '/^[0-9a-z]/ && ($5 ~ "[-yY]") { print "y"; exit}' ${config_dir}/master.cf)
+
+    if [ -n "$NEED_CHROOT" ] && [ -n "$SYNC_CHROOT" ]; then
+	# Make sure that the chroot environment is set up correctly.
+	oldumask=$(umask)
+	umask 022
+	queue_dir=$($POSTCONF -h queue_directory)
+	cd "$queue_dir"
+
+	# copy the CA path if specified
+	ca_path=$($POSTCONF -h smtp_tls_CApath)
+	case "$ca_path" in
+	    '') :;; # no ca_path
+	    $queue_dir/*) :;;  # skip stuff already in chroot
+	    *)
+		if test -d "$ca_path"; then
+		    dest_dir="$queue_dir/${ca_path#/}"
+		    new=0
+		    if test -d "$dest_dir"; then
+			# write to a new directory ...
+			dest_dir="${dest_dir%/}.NEW"
+			new=1
+		    else
+			mkdir --parent ${dest_dir%/*}
+		    fi
+		    # handle files in subdirectories
+		    (cd "$ca_path" && find . -name '*.pem' -print0 | cpio -0pdL --quiet "$dest_dir") 2>/dev/null || 
+		        (log_failure_msg failure copying certificates; exit 1)
+		    c_rehash "$dest_dir" >/dev/null 2>&1
+		    if [ "$new" = 1 ]; then
+			# and replace the old directory
+			rm -r "${dest_dir%.NEW}"
+			mv "$dest_dir" "${dest_dir%.NEW}"
+		    fi
+		fi
+		;;
+	esac
+
+	# if there is a CA file, copy it
+	ca_file=$($POSTCONF -h smtp_tls_CAfile)
+	case "$ca_file" in
+	    $queue_dir/*) :;;  # skip stuff already in chroot
+	    '') # no ca_file
+		# or copy the bundle to preserve functionality
+		ca_bundle=/etc/ssl/certs/ca-certificates.crt
+		if [ -f $ca_bundle ]; then
+		    mkdir --parent "$queue_dir/${ca_bundle%/*}"
+		    cp -L "$ca_bundle" "$queue_dir/${ca_bundle%/*}"
+		fi
+		;;
+	    *)
+		if test -f "$ca_file"; then
+		    dest_dir="$queue_dir/${ca_path#/}"
+		    mkdir --parent "$dest_dir"
+		    cp -L "$ca_file" "$dest_dir"
+		fi
+		;;
+	esac
+
+	# if we're using unix:passwd.byname, then we need to add etc/passwd.
+	local_maps=$($POSTCONF -h local_recipient_maps)
+	if [ "X$local_maps" != "X${local_maps#*unix:passwd.byname}" ]; then
+	    if [ "X$local_maps" = "X${local_maps#*proxy:unix:passwd.byname}" ]; then
+		sed 's/^\([^:]*\):[^:]*/\1:x/' /etc/passwd > etc/passwd
+		chmod a+r etc/passwd
+	    fi
+	fi
+
+	FILES="etc/localtime etc/services etc/resolv.conf etc/hosts \
+	    etc/nsswitch.conf etc/nss_mdns.config"
+	for file in $FILES; do
+	    [ -d ${file%/*} ] || mkdir -p ${file%/*}
+	    if [ -f /${file} ]; then rm -f ${file} && cp /${file} ${file}; fi
+	    if [ -f  ${file} ]; then chmod a+rX ${file}; fi
+	done
+	# ldaps needs this. debian bug 572841
+	(echo /dev/random; echo /dev/urandom) | cpio -pdL --quiet . 2>/dev/null || true
+	rm -f usr/lib/zoneinfo/localtime
+	mkdir -p usr/lib/zoneinfo
+	ln -sf /etc/localtime usr/lib/zoneinfo/localtime
+
+	LIBLIST=$(for name in gcc_s nss resolv; do
+	    for f in /lib/*/lib${name}*.so* /lib/lib${name}*.so*; do
+	       if [ -f "$f" ]; then  echo ${f#/}; fi;
+	    done;
+	done)
+
+	if [ -n "$LIBLIST" ]; then
+	    for f in "$LIBLIST"; do
+		rm -f "$f"
+	    done
+	    tar cf - -C / $LIBLIST 2>/dev/null |tar xf -
+	fi
+	umask $oldumask
+    fi
+}
+
 case "$1" in
     start)
 	log_daemon_msg "Starting Postfix Mail Transport Agent" postfix
 	# check ucr autostart setting
 	if [ -f "/usr/share/univention-config-registry/init-autostart.lib" ]; then
-		. "/usr/share/univention-config-registry/init-autostart.lib"
-		check_autostart postfix postfix/autostart
+	    . "/usr/share/univention-config-registry/init-autostart.lib"
+	    check_autostart postfix postfix/autostart
 	fi
-	RUNNING=$(running)
-	if [ -n "$RUNNING" ]; then
-	    log_end_msg 0
-	else
-	    # if you set myorigin to 'ubuntu.com' or 'debian.org', it's wrong, and annoys the admins of
-	    # those domains.  See also sender_canonical_maps.
-
-	    MYORIGIN=$(postconf -h myorigin | tr 'A-Z' 'a-z')
-	    if [ "X${MYORIGIN#/}" != "X${MYORIGIN}" ]; then
-		MYORIGIN=$(tr 'A-Z' 'a-z' < $MYORIGIN)
-	    fi
-	    if [ "X$MYORIGIN" = Xubuntu.com ] || [ "X$MYORIGIN" = Xdebian.org ]; then
-		log_failure_msg "Invalid \$myorigin ($MYORIGIN), refusing to start"
-		log_end_msg 1
-		exit 1
-	    fi
-
-	    # see if anything is running chrooted.
-	    NEED_CHROOT=$(awk '/^[0-9a-z]/ && ($5 ~ "[-yY]") { print "y"; exit}' /etc/postfix/master.cf)
-
-	    if [ -n "$NEED_CHROOT" ] && [ -n "$SYNC_CHROOT" ]; then
-		# Make sure that the chroot environment is set up correctly.
-		oldumask=$(umask)
-		umask 022
-		cd $(postconf -h queue_directory)
-
-		# if we're using tls, then we need to add etc/ssl/certs/ca-certificates.crt.
-		if [ -f "/etc/ssl/certs/ca-certificates.crt" ]; then 
-		    smtp_use_tls=$(postconf -h smtp_use_tls)
-		    smtp_enforce_tls=$(postconf -h smtp_enforce_tls)
-		    smtpd_use_tls=$(postconf -h smtpd_use_tls)
-		    smtpd_enforce_tls=$(postconf -h smtpd_use_tls)
-		    case :$smtp_use_tls:$smtp_enforce_tls:$smtpd_use_tls:$smtpd_enforce_tls: in
-			*:yes:*)
-			    mkdir -p etc/ssl/certs
-			    cp /etc/ssl/certs/ca-certificates.crt etc/ssl/certs/
-		    esac
+	RET=0
+	# for all instances that are not already running, handle chroot setup if needed, and start
+	for INSTANCE in $(enabled_instances); do
+	    RUNNING=$(running $INSTANCE)
+	    if [ "X$RUNNING" = X ]; then
+		configure_instance $INSTANCE
+		CMD="/usr/sbin/postmulti -- -i $INSTANCE -x ${DAEMON}"
+		if ! start-stop-daemon --start --exec $CMD quiet-quick-start; then
+		    RET=1
 		fi
-
-		# if we're using unix:passwd.byname, then we need to add etc/passwd.
-		local_maps=$(postconf -h local_recipient_maps)
-		if [ "X$local_maps" != "X${local_maps#*unix:passwd.byname}" ]; then
-		    if [ "X$local_maps" = "X${local_maps#*proxy:unix:passwd.byname}" ]; then
-			sed 's/^\([^:]*\):[^:]*/\1:x/' /etc/passwd > etc/passwd
-			chmod a+r etc/passwd
-		    fi
-		fi
-
-		FILES="etc/localtime etc/services etc/resolv.conf etc/hosts \
-		    etc/nsswitch.conf etc/nss_mdns.config"
-		for file in $FILES; do 
-		    [ -d ${file%/*} ] || mkdir -p ${file%/*}
-		    if [ -f /${file} ]; then rm -f ${file} && cp /${file} ${file}; fi
-		    if [ -f  ${file} ]; then chmod a+rX ${file}; fi
-		done
-		rm -f usr/lib/zoneinfo/localtime
-		mkdir -p usr/lib/zoneinfo
-		ln -sf /etc/localtime usr/lib/zoneinfo/localtime
-		rm -f lib/libnss_*so*
-		tar cf - /lib/libnss_*so* 2>/dev/null |tar xf -
-		umask $oldumask
 	    fi
-
-	    if start-stop-daemon --start --exec ${DAEMON} -- quiet-quick-start; then
-		log_end_msg 0
-	    else
-		log_end_msg 1
-	    fi
-	fi
+	done
+	log_end_msg $RET
     ;;
 
     stop)
-	RUNNING=$(running)
 	log_daemon_msg "Stopping Postfix Mail Transport Agent" postfix
-	if [ -n "$RUNNING" ]; then
-	    if ${DAEMON} quiet-stop; then
-		log_end_msg 0
-	    else
-		log_end_msg 1
+	RET=0
+	# for all instances that are not already running, handle chroot setup if needed, and start
+	for INSTANCE in $(enabled_instances); do
+	    RUNNING=$(running $INSTANCE)
+	    if [ "X$RUNNING" != X ]; then
+		CMD="/usr/sbin/postmulti -i $INSTANCE -x ${DAEMON}"
+		if ! ${CMD} quiet-stop; then
+		    RET=1
+		fi
 	    fi
-	else
-	    log_end_msg 0
-	fi
+	done
+	log_end_msg $RET
     ;;
 
     restart)
         $0 stop
         $0 start
     ;;
-    
+
     force-reload|reload)
 	log_action_begin_msg "Reloading Postfix configuration"
 	if ${DAEMON} quiet-reload; then
@@ -183,9 +261,26 @@ case "$1" in
     ;;
 
     status)
-	RUNNING=$(running)
-	if [ -n "$RUNNING" ]; then
+	ALL=1
+	ANY=0
+	# for all instances that are not already running, handle chroot setup if needed, and start
+	for INSTANCE in $(enabled_instances); do
+	    RUNNING=$(running $INSTANCE)
+	    if [ "X$RUNNING" != X ]; then
+	    	ANY=1
+	    else
+	    	ALL=0
+	    fi
+	done
+	# handle the case when postmulti returns *no* configured instances
+	if [ $ANY = 0 ]; then
+	   ALL=0
+	fi
+	if [ $ALL = 1 ]; then
 	   log_success_msg "postfix is running"
+	   exit 0
+	elif [ $ANY = 1 ]; then
+	   log_success_msg "some postfix instances are running"
 	   exit 0
 	else
 	   log_success_msg "postfix is not running"
@@ -198,7 +293,7 @@ case "$1" in
     ;;
 
     *)
-	log_action_msg "Usage: /etc/init.d/postfix {start|stop|restart|reload|flush|check|abort|force-reload}"
+	log_action_msg "Usage: /etc/init.d/postfix {start|stop|restart|reload|flush|check|abort|force-reload|status}"
 	exit 1
     ;;
 esac
