Bug #38438 dhcp: Fix init script
Validate config file before start.
Use "dhcpd" when checking for running DHCP server.

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.2/ucs-4.2-0@75380 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/services/univention-dhcp/debian/univention-dhcp.init b/services/univention-dhcp/debian/univention-dhcp.init
--- a/services/univention-dhcp/debian/univention-dhcp.init
+++ b/services/univention-dhcp/debian/univention-dhcp.init
@@ -42,13 +42,33 @@
 # Description:       Dynamic Host Configuration Protocol Server
 ### END INIT INFO
 
-if [ ! -e /etc/runit/univention/univention-dhcp ]; then
-	exit 0
-fi
+PATH=/sbin:/bin:/usr/sbin:/usr/bin
+
+[ -x /usr/sbin/dhcpd ] || exit 0
+[ -x /etc/runit/univention/univention-dhcp ] || exit 0
 
 . /lib/lsb/init-functions
-NAME='univention-dhcp'
+NAME='dhcpd'
 DESC=$(get_lsb_header_val "$0" Short-Description)
+
+DHCPD_DEFAULT="${DHCPD_DEFAULT:-/etc/default/isc-dhcp-server}"
+[ -f "$DHCPD_DEFAULT" ] && . "$DHCPD_DEFAULT"
+DHCPD_CONF=${DHCPD_CONF:-/etc/dhcp/dhcpd.conf}
+# try to read pid file name from config file, with fallback to /var/run/dhcpd.pid
+if [ -z "$DHCPD_PID" ]; then
+	DHCPD_PID=$(sed -n -e 's/^[ \t]*pid-file-name[ \t]*"(.*)"[ \t]*;.*$/\1/p;T;q' < "$DHCPD_CONF" 2>/dev/null)
+fi
+DHCPD_PID="${DHCPD_PID:-/var/run/dhcpd.pid}"
+
+test_config () {
+	if ! dhcpd -t $OPTIONS -q -cf "$DHCPD_CONF" > /dev/null 2>&1; then
+		echo "dhcpd self-test failed. Please fix $DHCPD_CONF."
+		echo "The error was: "
+		dhcpd -t $OPTIONS -cf "$DHCPD_CONF"
+		exit 1
+	fi
+	touch /var/lib/dhcp/dhcpd.leases
+}
 
 case "$1" in
 	start)
@@ -57,6 +77,7 @@ case "$1" in
 			. "/usr/share/univention-config-registry/init-autostart.lib"
 			check_autostart dhcpd dhcpd/autostart
 		fi
+		test_config
 		log_daemon_msg "Starting $DESC" "$NAME"
 		sv start univention-dhcp
 		log_end_msg $?
@@ -72,6 +93,7 @@ case "$1" in
 			. "/usr/share/univention-config-registry/init-autostart.lib"
 			check_autostart dhcpd dhcpd/autostart
 		fi
+		test_config
 		log_daemon_msg "Restarting $DESC" "$NAME"
 		sv restart univention-dhcp 1>/dev/null
 		log_end_msg $?
@@ -82,6 +104,7 @@ case "$1" in
 			. "/usr/share/univention-config-registry/init-autostart.lib"
 			check_autostart dhcpd dhcpd/autostart
 		fi
+		test_config
 		if sv status /etc/runit/univention-dhcp | grep -q ^run:
 		then
 			"$0" restart
@@ -90,7 +113,7 @@ case "$1" in
 		fi
 		;;
 	status)
-		status_of_proc "$NAME" "$DESC" && exit 0 || exit $?
+		status_of_proc -p "$DHCPD_PID" "$NAME" "$DESC" && exit 0 || exit $?
 		;;
 	*)
 		echo "Usage: $0 {start|stop|restart|crestart|force-reload|status}"
