Bug #45065 dhcp: Always start DHCP runsv service
even when self test fails because the DNS server is currently
unreachable. If (that) underlying problem gets fixes, runsv will restart
dhcp after some time (up to 60s), which fixes the problem when DNS just
is too slow to start up during boot.

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.2/ucs-4.2-1@81356 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/services/univention-dhcp/debian/univention-dhcp.init b/services/univention-dhcp/debian/univention-dhcp.init
--- a/services/univention-dhcp/debian/univention-dhcp.init
+++ b/services/univention-dhcp/debian/univention-dhcp.init
@@ -61,11 +61,14 @@ fi
 DHCPD_PID="${DHCPD_PID:-/var/run/dhcpd.pid}"
 
 test_config () {
-	if ! dhcpd -t $OPTIONS -q -cf "$DHCPD_CONF" > /dev/null 2>&1; then
-		echo "dhcpd self-test failed. Please fix $DHCPD_CONF."
+	local tmp rv
+	tmp=$(dhcpd -t $OPTIONS -cf "$DHCPD_CONF" 2>&1)
+	rv=$?
+	if [ $rv -ne 0 ]; then
+		echo "dhcpd self-test failed with $rv. Check $DHCPD_CONF."
 		echo "The error was: "
-		dhcpd -t $OPTIONS -cf "$DHCPD_CONF"
-		exit 1
+		echo "$tmp"
+		# exit 1  # Bug #45065
 	fi
 	touch /var/lib/dhcp/dhcpd.leases
 }
