* Bug #35985: Adjust test case to support non-Samba4 DCs
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.0/ucs-4.0-0@56945 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/60_umc/07_expired_password b/test/ucs-test/tests/60_umc/07_expired_password
--- a/test/ucs-test/tests/60_umc/07_expired_password
+++ b/test/ucs-test/tests/60_umc/07_expired_password
@@ -1,5 +1,5 @@
 #!/usr/share/ucs-test/runner bash
-## desc: Test UMC password change on expired password
+## desc: Change of expired password at UMC logon (with password complexity)
 ## roles:
 ##  - domaincontroller_master
 ## packages:
@@ -11,30 +11,91 @@
 . "$TESTLIBPATH/user.sh" || exit 137
 . "$TESTLIBPATH/random.sh" || exit 137
 . "$TESTLIBPATH/undo.sh" || exit 137
+. "$TESTLIBPATH/ucr.sh" || exit 137
 
-COOKIEJAR="$(mktemp)"
-TARGET="localhost"
+## INITIAL_PASSWORD is chosen by user_create:
+INITIAL_PASSWORD=univention
+PASSWORD=Univention.1
+SHORT_PASSWORD=Test
+SIMPLE_PASSWORD=chocolate
+SIMILAR_PASSWORD=Univention.2
+COMPLEX_PASSWORD="fnGHX5%§d0"
 
 RETVAL=100
+TARGET="localhost"
+COOKIEJAR="$(mktemp)" && undo rm "$COOKIEJAR"
 
-PASSWORD=univention
-SHORT_PASSWORD=Test
-SIMPLE_PASSWORD=univention2
-NEW_PASSWORD=Univention.99
-
-# create test user
 test_username=$(user_randomname)
 user_create "$test_username" &&
 	undo user_remove "$test_username" ||
 	fail_fast 140 "cannot create user $test_username"
 
-## basic test #1: Login with invalid user
+test_userdn=$(user_dn "$test_username")
+
+
+
+
+if ! checkpkg "univention-samba4"; then
+	echo "### Preparation: Activate pwQualityCheck in policies/pwhistory"
+	echo "## Note: non-Samba4 DCs require this to activate univention.password.Check (for check_cracklib.py)"
+	orig_pwQualityCheck=$(udm policies/pwhistory list \
+		--filter name=default-settings \
+		| sed -n 's/^  pwQualityCheck: //p')
+
+	reset_pwpolicy() {
+		udm policies/pwhistory modify \
+			--dn "cn=default-settings,cn=pwhistory,cn=users,cn=policies,$ldap_base" \
+			--set pwQualityCheck="$orig_pwQualityCheck"
+	}
+
+	udm policies/pwhistory modify \
+		--dn "cn=default-settings,cn=pwhistory,cn=users,cn=policies,$ldap_base" \
+		--set pwQualityCheck=TRUE \
+		&& undo reset_pwpolicy \
+		|| fail_fast 140 "cannot adjust policies/pwhistory"
+
+	## Active Directory password comlexity is a bit different, but this ok to test check_cracklib.py:
+	ucr set password/quality/credit/lower=1 \
+		password/quality/credit/upper=1 \
+		password/quality/credit/other=1 \
+		password/quality/credit/digits=1 \
+		&& undo ucr_restore
+fi
+
+
+
+
+## simulate expiration of the user password, (required! otherwise UMC doesn't inititate password reset)
+echo "### Preparation: simulate password expiry"
+udm-test users/user modify --dn "$test_userdn" \
+	--set pwdChangeNextLogin=1 --set locked=posix
+
+wait_for_replication_and_postrun
+
+echo "### Preparation: set fresh complex password via UMC login password change dialog"
+output=$(curl -s -H 'Accept-Language: en-US' --cookie-jar "$COOKIEJAR" -d "{\"options\":{\"username\":\"$test_username\",\"password\":\"$INITIAL_PASSWORD\",\"new_password\":\"$PASSWORD\"}}" -H "Content-Type: application/json" "http://$TARGET/umcp/auth")
+if [ -n "$output" ]; then
+	fail_fast 110 "Unexpected output returned by UMC during password change: $output"
+fi
+
+wait_for_replication_and_postrun
+
+echo "### Preparation: confirm UMC login with fresh complex password"
+output=$(curl -s -H 'Accept-Language: en-US' --cookie-jar "$COOKIEJAR" -d "{\"options\":{\"username\":\"$test_username\",\"password\":\"$PASSWORD\"}}" -H "Content-Type: application/json" "http://$TARGET/umcp/auth")
+if [ -n "$output" ]; then
+	fail_fast 110 "Unexpected output returned by UMC after initial password change: $output"
+fi
+
+
+
+
+echo "### Basic test: UMC login with invalid user"
 output=$(curl -s -H 'Accept-Language: en-US' --cookie-jar "$COOKIEJAR" -d "{\"options\":{\"username\":\"UNKNOWN$test_username\",\"password\":\"$PASSWORD\"}}" -H "Content-Type: application/json" "http://$TARGET/umcp/auth")
 if [ -z "$output" ]; then
 	fail_fast 110 "UMC authentication with invalid user succeeded!"
 fi
 
-## basic test #2: Login with invalid password
+echo "### Basic test: UMC login with invalid password"
 output=$(curl -s -H 'Accept-Language: en-US' --cookie-jar "$COOKIEJAR" -d "{\"options\":{\"username\":\"$test_username\",\"password\":\"INVALID$PASSWORD\"}}" -H "Content-Type: application/json" "http://$TARGET/umcp/auth")
 if [ -z "$output" ]; then
 	fail_fast 110 "UMC authentication with invalid password succeeded!"
@@ -42,15 +103,16 @@ fi
 
 
 
-## Now simulate expiration of the user password
-test_userdn=$(user_dn "$test_username")
 
+
+## simulate expiration of the user password again, otherwise UMC doesn't inititate password reset
+echo "### Preparation: simulate password expiry"
 udm-test users/user modify --dn "$test_userdn" \
 	--set pwdChangeNextLogin=1 --set locked=posix
 
 wait_for_replication_and_postrun
 
-## And check the UMC logon:
+echo "### Basic test: UMC login against expired password"
 output=$(curl -s -H 'Accept-Language: en-US' --cookie-jar "$COOKIEJAR" -d "{\"options\":{\"username\":\"$test_username\",\"password\":\"$PASSWORD\"}}" -H "Content-Type: application/json" "http://$TARGET/umcp/auth")
 if [ -z "$output" ]; then
 	fail_fast 110 "UMC authentication against expired password succeeded!"
@@ -60,7 +122,11 @@ if [ "$(python -c "output=$output; print output['message']")" != "The password h
 	fail_test 110 "unexpected message returned by UMC: $output, expected: The password has expired"
 fi
 
-## Now change password case #1: short password, should fail
+
+
+
+
+echo "### Test: Try setting short password in UMC login password change dialog"
 output=$(curl -s -H 'Accept-Language: en-US' --cookie-jar "$COOKIEJAR" -d "{\"options\":{\"username\":\"$test_username\",\"password\":\"$PASSWORD\",\"new_password\":\"$SHORT_PASSWORD\"}}" -H "Content-Type: application/json" "http://$TARGET/umcp/auth")
 if [ -z "$output" ]; then
 	fail_fast 110 "'UMC allowed setting a too short password!"
@@ -73,31 +139,73 @@ if [ "$(python -c "output=$output; print output['status']")" != "411 Length Requ
 	fail_test 110 "unexpected status returned by UMC while trying to set short password: $output"
 fi
 
-## Now change password case #2: simple password, should fail
+
+
+
+
+echo "### Test: Try setting simple password in UMC login password change dialog"
 output=$(curl -s -H 'Accept-Language: en-US' --cookie-jar "$COOKIEJAR" -d "{\"options\":{\"username\":\"$test_username\",\"password\":\"$PASSWORD\",\"new_password\":\"$SIMPLE_PASSWORD\"}}" -H "Content-Type: application/json" "http://$TARGET/umcp/auth")
 if [ -z "$output" ]; then
 	fail_fast 110 "'UMC allowed setting a too simple password!"
 fi
 
-if [ "$(python -c "output=$output; print output['message']")" != "Changing password failed. The password is too simple" ]; then
+if checkpkg "univention-samba4"; then
+	expected_message="Changing password failed. The password is too simple"
+else
+	expected_message="Changing password failed. The password is based on a dictionary word"
+fi
+if [ "$(python -c "output=$output; print output['message']")" != "$expected_message" ]; then
 	fail_test 110 "unexpected message returned by UMC while trying to set simple password: $output"
 fi
 if [ "$(python -c "output=$output; print output['status']")" != "411 Length Required" ]; then
 	fail_test 110 "unexpected status returned by UMC while trying to set simple password: $output"
 fi
 
-## Now change password case #3: proper new password, must work
-output=$(curl -s -H 'Accept-Language: en-US' --cookie-jar "$COOKIEJAR" -d "{\"options\":{\"username\":\"$test_username\",\"password\":\"$PASSWORD\",\"new_password\":\"$NEW_PASSWORD\"}}" -H "Content-Type: application/json" "http://$TARGET/umcp/auth")
+
+
+
+
+echo "### Test: Set complex but similar password in UMC login password change dialog (should work currently)"
+output=$(curl -s -H 'Accept-Language: en-US' --cookie-jar "$COOKIEJAR" -d "{\"options\":{\"username\":\"$test_username\",\"password\":\"$PASSWORD\",\"new_password\":\"$SIMILAR_PASSWORD\"}}" -H "Content-Type: application/json" "http://$TARGET/umcp/auth")
 if [ -n "$output" ]; then
-	fail_fast 110 "Unexpected output returned by UMC during password change: $output"
+	fail_fast 110 "'UMC allowed didn't allow setting a similar complex passowrd!"
 fi
 
 wait_for_replication_and_postrun
 
-## Finally confirm logon with new password
-output=$(curl -s -H 'Accept-Language: en-US' --cookie-jar "$COOKIEJAR" -d "{\"options\":{\"username\":\"$test_username\",\"password\":\"$NEW_PASSWORD\"}}" -H "Content-Type: application/json" "http://$TARGET/umcp/auth")
+echo "### Test: Confirm UMC login with new password"
+output=$(curl -s -H 'Accept-Language: en-US' --cookie-jar "$COOKIEJAR" -d "{\"options\":{\"username\":\"$test_username\",\"password\":\"$SIMILAR_PASSWORD\"}}" -H "Content-Type: application/json" "http://$TARGET/umcp/auth")
 if [ -n "$output" ]; then
 	fail_test 110 "Unexpected output returned by UMC after password change: $output"
 fi
+
+
+
+
+
+### SIMILAR_PASSWORD check is currently enough
+#
+# ## simulate expiration of the user password again, otherwise UMC doesn't inititate password reset
+# echo "### Preparation: simulate password expiry"
+# udm-test users/user modify --dn "$test_userdn" \
+#	--set pwdChangeNextLogin=1 --set locked=posix
+#
+# wait_for_replication_and_postrun
+# 
+# echo "### Test: Set complex password in UMC login password change dialog"
+# output=$(curl -s -H 'Accept-Language: en-US' --cookie-jar "$COOKIEJAR" -d "{\"options\":{\"username\":\"$test_username\",\"password\":\"$PASSWORD\",\"new_password\":\"$COMPLEX_PASSWORD\"}}" -H "Content-Type: application/json" "http://$TARGET/umcp/auth")
+# if [ -n "$output" ]; then
+# 	fail_fast 110 "Unexpected output returned by UMC during password change: $output"
+# fi
+# 
+# wait_for_replication_and_postrun
+# 
+# echo "### Test: Finally confirm UMC login with new password"
+# output=$(curl -s -H 'Accept-Language: en-US' --cookie-jar "$COOKIEJAR" -d "{\"options\":{\"username\":\"$test_username\",\"password\":\"$COMPLEX_PASSWORD\"}}" -H "Content-Type: application/json" "http://$TARGET/umcp/auth")
+# if [ -n "$output" ]; then
+# 	fail_test 110 "Unexpected output returned by UMC after password change: $output"
+# fi
+
+
 
 exit "$RETVAL"
