Bug #28232 repl: autopep8 -i --max-line-width=220
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.1/ucs-4.1-2@69830 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/management/univention-directory-replication/univention-directory-replication-resync b/management/univention-directory-replication/univention-directory-replication-resync
--- a/management/univention-directory-replication/univention-directory-replication-resync
+++ b/management/univention-directory-replication/univention-directory-replication-resync
@@ -35,18 +35,19 @@ eval "$(univention-config-registry shell)"
 
 UDL='univention-directory-listener'
 LOG='/var/log/univention/ldap-replication-resync.log'
+
 die () {
 	echo "$1" >&2
 	exit ${2:-1}
 }
 
-display_header() {
-        echo ""
-        echo "univention-directory-replication-resync: Resync local LDAP using a failed.ldif"
-        echo "copyright (c) 2001-@%@copyright_lastyear@%@ Univention GmbH, Germany"
-		echo "usage: $0 <failed.ldif>"
-        echo ""
-		exit ${1:-0}
+display_header () {
+	echo ""
+	echo "univention-directory-replication-resync: Resync local LDAP using a failed.ldif"
+	echo "copyright (c) 2001-@%@copyright_lastyear@%@ Univention GmbH, Germany"
+	echo "usage: $0 <failed.ldif>"
+	echo ""
+	exit ${1:-0}
 }
 
 getdns () {
