Bug #49092: Extend testcases for new synchronized user attributes in s4-connector

diff --git a/test/ucs-test/tests/52_s4connector/120sync_create_and_modify_ucs_user b/test/ucs-test/tests/52_s4connector/120sync_create_and_modify_ucs_user
--- a/test/ucs-test/tests/52_s4connector/120sync_create_and_modify_ucs_user
+++ b/test/ucs-test/tests/52_s4connector/120sync_create_and_modify_ucs_user
@@ -11,8 +11,22 @@
 . "$TESTLIBPATH/udm.sh" || exit 137
 . "$TESTLIBPATH/random.sh" || exit 137
 
-
 . "s4connector.sh" || exit 137
+
+#check if ucs-version supports extended mapping of s4-attributes
+ext_mapping=false;
+if current_ucs_version_greater_equal 4.4-0; then
+	ext_mapping=true;
+fi
+
+#unset ignorelist for user attributes
+ignore_list_original="$(ucr get connector/s4/mapping/user/attributes/ignorelist)"
+echo $ignore_list_original
+ucr unset "connector/s4/mapping/user/attributes/ignorelist"
+echo "$(ucr get connector/s4/mapping/user/attributes/ignorelist)"
+
+ad_connector_restart
+
 test -n "$connector_s4_ldap_host" || exit 137
 connector_running_on_this_host || exit 137
 
@@ -29,6 +43,7 @@ SYNCMODE="$(ad_get_sync_mode)"
 ad_set_sync_mode "sync"
 
 udm_create "users/user" || fail_test 110
+
 ad_wait_for_synchronization; fail_bool 0 110
 
 ad_verify_attribute	"$AD_DN" "sAMAccountName" "$UDM_users_user_username"; fail_bool 0 110
@@ -47,7 +62,6 @@ UDM_users_user_city="$(random_chars)"
 UDM_users_user_postcode="$(random_chars)"
 UDM_users_user_profilepath="$(random_chars)"
 UDM_users_user_scriptpath="$(random_chars)"
-
 UDM_users_user_sambauserworkstations="$(random_chars)"
 UDM_users_user_homedrive="$(random_chars)"
 UDM_users_user_sambahome="$(random_chars)"
@@ -59,6 +73,27 @@ UDM_users_user_mobiletelephonenumber="$(random_chars 25 $_chipers)"
 UDM_users_user_pager1="$(random_chars 5 $_ciphers)"
 UDM_users_user_pager2="$(random_chars 7 $_ciphers)"
 UDM_users_user_pager3="$(random_chars 4 $_ciphers)"
+
+if $ext_mapping; then
+	UDM_users_user_employeeNumber="$(random_chars)"
+	UDM_users_user_employeeType="$(random_chars)"
+	UDM_users_user_country="DE"
+	UDM_users_user_loginShell="$(random_chars)"
+	UDM_users_user_unixhome="/$(random_chars)/"
+	UDM_users_user_unixhome2="/$(random_chars)/"
+	UDM_users_user_title="$(random_chars)"
+	UDM_users_user_gidNumber="$(udm-test 'users/user' list --filter uid=$UDM_users_user_username | egrep '^ *gidNumber: ' | sed 's/^ *gidNumber: //')"
+	UDM_users_user_uidNumber="$(udm-test 'users/user' list --filter uid=$UDM_users_user_username | egrep '^ *uidNumber: ' | sed 's/^ *uidNumber: //')"
+	UDM_users_user_departmentNumber1="$(random_chars)"
+	UDM_users_user_departmentNumber2="$(random_chars)"
+	UDM_users_user_roomNumber1="$(random_chars)"
+	UDM_users_user_roomNumber2="$(random_chars)"
+	UDM_users_user_initials="$(random_chars 2)"
+	UDM_users_user_physicalDeliveryOfficeName="$(random_chars)"
+	UDM_users_user_postOfficeBox1="$(random_chars)"
+	UDM_users_user_postOfficeBox2="$(random_chars)"
+	UDM_users_user_preferredLanguage="$(random_chars)"
+fi
 
 udm_modify "users/user" "" "" "" "" \
 		   --set firstname="$UDM_users_user_firstname" \
@@ -79,8 +114,28 @@ udm_modify "users/user" "" "" "" "" \
 		   --append phone="$UDM_users_user_phone3" \
 		   --append pagerTelephoneNumber="$UDM_users_user_pager1" \
 		   --append pagerTelephoneNumber="$UDM_users_user_pager2" \
-		   --append pagerTelephoneNumber="$UDM_users_user_pager3" || fail_test 110 
-ad_wait_for_synchronization; fail_bool 0 110
+		   --append pagerTelephoneNumber="$UDM_users_user_pager3" || fail_test 110
+ad_wait_for_synchronization ; fail_bool 0 110
+if $ext_mapping; then
+	udm_modify "users/user" "" "" "" "" \
+			   --set employeeNumber="$UDM_users_user_employeeNumber" \
+			   --set employeeType="$UDM_users_user_employeeType" \
+			   --set country="$UDM_users_user_country" \
+			   --set shell="$UDM_users_user_loginShell" \
+			   --set unixhome="$UDM_users_user_unixhome" \
+			   --set title="$UDM_users_user_title" \
+			   --append departmentNumber="$UDM_users_user_departmentNumber1" \
+			   --append departmentNumber="$UDM_users_user_departmentNumber2" \
+			   --append roomNumber="$UDM_users_user_roomNumber1" \
+			   --append roomNumber="$UDM_users_user_roomNumber2" \
+			   --set initials="$UDM_users_user_initials" \
+			   --set physicalDeliveryOfficeName="$UDM_users_user_physicalDeliveryOfficeName" \
+			   --append postOfficeBox="$UDM_users_user_postOfficeBox1" \
+			   --append postOfficeBox="$UDM_users_user_postOfficeBox2" \
+			   --set preferredLanguage="$UDM_users_user_preferredLanguage" || fail_test 110
+	ad_wait_for_synchronization ; fail_bool 0 110
+fi
+
 
 ad_verify_attribute "$AD_DN" "description" "$UDM_users_user_description"; fail_bool 0 121 "See #18501"
 ad_verify_attribute	"$AD_DN" "sAMAccountName" "$UDM_users_user_username"; fail_bool 0 121 "See #18501"
@@ -104,6 +159,25 @@ ad_verify_attribute "$AD_DN" "otherMobile" ""; fail_bool 0 121 "See #18501"
 ad_verify_attribute "$AD_DN" "pager" "$UDM_users_user_pager1"; fail_bool 0 121 "See #18501"
 ad_verify_multi_value_attribute_contains "$AD_DN" "otherPager" "$UDM_users_user_pager2"; fail_bool 0 121 "See #18501"
 ad_verify_multi_value_attribute_contains "$AD_DN" "otherPager" "$UDM_users_user_pager3"; fail_bool 0 121 "See #18501"
+if $ext_mapping;then
+	ad_verify_attribute "$AD_DN" "employeeNumber" "$UDM_users_user_employeeNumber"; fail_bool 0 121
+	ad_verify_attribute "$AD_DN" "employeeType" "$UDM_users_user_employeeType"; fail_bool 0 121
+	ad_verify_attribute "$AD_DN" "c" "$UDM_users_user_country"; fail_bool 0 121
+	ad_verify_attribute "$AD_DN" "loginShell" "$UDM_users_user_loginShell"; fail_bool 0 121
+	ad_verify_attribute "$AD_DN" "unixHomeDirectory" "$UDM_users_user_unixhome"; fail_bool 0 121
+	ad_verify_attribute "$AD_DN" "personalTitle" "$UDM_users_user_title"; fail_bool 0 121
+	ad_verify_attribute "$AD_DN" "gidNumber" "$UDM_users_user_gidNumber"; fail_bool 0 121
+	ad_verify_attribute "$AD_DN" "uidNumber" "$UDM_users_user_uidNumber"; fail_bool 0 121
+	ad_verify_multi_value_attribute_contains "$AD_DN" "departmentNumber" "$UDM_users_user_departmentNumber1"; fail_bool 0 121 "See #18501"
+	ad_verify_multi_value_attribute_contains "$AD_DN" "departmentNumber" "$UDM_users_user_departmentNumber2"; fail_bool 0 121 "See #18501"
+	ad_verify_multi_value_attribute_contains "$AD_DN" "roomNumber" "$UDM_users_user_roomNumber1"; fail_bool 0 121
+	ad_verify_multi_value_attribute_contains "$AD_DN" "roomNumber" "$UDM_users_user_roomNumber2"; fail_bool 0 121
+	ad_verify_attribute "$AD_DN" "initials" "$UDM_users_user_initials"; fail_bool 0 121
+	ad_verify_attribute "$AD_DN" "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName"; fail_bool 0 121
+	ad_verify_multi_value_attribute_contains "$AD_DN" "postOfficeBox" "$UDM_users_user_postOfficeBox1"; fail_bool 0 121 "See #18501"
+	ad_verify_multi_value_attribute_contains "$AD_DN" "postOfficeBox" "$UDM_users_user_postOfficeBox2"; fail_bool 0 121 "See #18501"
+	ad_verify_attribute "$AD_DN" "preferredLanguage" "$UDM_users_user_preferredLanguage"; fail_bool 0 121
+fi
 
 udm_verify_udm_attribute "username" "$UDM_users_user_username" "users/user"; fail_bool 0 110
 udm_verify_udm_attribute "firstname" "$UDM_users_user_firstname" "users/user"; fail_bool 0 110
@@ -124,6 +198,30 @@ udm_verify_udm_attribute "mobileTelephoneNumber" "$UDM_users_user_mobiletelephon
 udm_verify_multi_value_udm_attribute_contains "pagerTelephoneNumber" "$UDM_users_user_pager1" "users/user"; fail_bool 0 110
 udm_verify_multi_value_udm_attribute_contains "pagerTelephoneNumber" "$UDM_users_user_pager2" "users/user"; fail_bool 0 110
 udm_verify_multi_value_udm_attribute_contains "pagerTelephoneNumber" "$UDM_users_user_pager3" "users/user"; fail_bool 0 110
+if $ext_mapping; then
+	udm_verify_udm_attribute "employeeNumber" "$UDM_users_user_employeeNumber" "users/user"; fail_bool 0 110
+	udm_verify_udm_attribute "employeeType" "$UDM_users_user_employeeType" "users/user"; fail_bool 0 110
+	udm_verify_udm_attribute "country" "$UDM_users_user_country" "users/user"; fail_bool 0 110
+	udm_verify_udm_attribute "shell" "$UDM_users_user_loginShell" "users/user"; fail_bool 0 110
+	udm_verify_udm_attribute "unixhome" "$UDM_users_user_unixhome" "users/user" ; fail_bool 0 110
+	udm_verify_udm_attribute "title" "$UDM_users_user_title" "users/user" ; fail_bool 0 110
+	udm_verify_multi_value_udm_attribute_contains "departmentNumber" "$UDM_users_user_departmentNumber1" "users/user"; fail_bool 0 110
+	udm_verify_multi_value_udm_attribute_contains "departmentNumber" "$UDM_users_user_departmentNumber2" "users/user"; fail_bool 0 110
+	udm_verify_multi_value_udm_attribute_contains "roomNumber" "$UDM_users_user_roomNumber1" "users/user"; fail_bool 0 110
+	udm_verify_multi_value_udm_attribute_contains "roomNumber" "$UDM_users_user_roomNumber2" "users/user"; fail_bool 0 110
+	udm_verify_udm_attribute "initials" "$UDM_users_user_initials" "users/user" ; fail_bool 0 110
+	udm_verify_udm_attribute "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName" "users/user" ; fail_bool 0 110
+	udm_verify_multi_value_udm_attribute_contains "postOfficeBox" "$UDM_users_user_postOfficeBox1" "users/user"; fail_bool 0 110
+	udm_verify_multi_value_udm_attribute_contains "postOfficeBox" "$UDM_users_user_postOfficeBox2" "users/user"; fail_bool 0 110
+	udm_verify_udm_attribute "preferredLanguage" "$UDM_users_user_preferredLanguage" "users/user" ; fail_bool 0 110
+fi
+
+### Test if mapping of user-attributes is configurable via ucr variable 'connector/s4/mapping/user/attributes/ignorelist'
+ucr set 'connector/s4/mapping/user/attributes/ignorelist'='employeeNumber,employeeType,country,departmentNumber,loginShell,unixhome,title,uidNumber,gidNumber,roomNumber,initials,physicalDeliveryOfficeName,postOfficeBox,preferredLanguage'
+
+ad_connector_restart
+test -n "$connector_s4_ldap_host" || exit 137
+connector_running_on_this_host || exit 137
 
 udm_modify "users/user" "" "" "" "" \
 		   --set firstname="" \
@@ -139,9 +237,26 @@ udm_modify "users/user" "" "" "" "" \
 		   --set phone="" \
 		   --set homeTelephoneNumber="" \
 		   --set mobileTelephoneNumber="" \
-		   --set pagerTelephoneNumber="" \
-|| fail_test 110
+		   --set pagerTelephoneNumber="" || fail_test 110
 ad_wait_for_synchronization; fail_bool 0 110
+if $ext_mapping;then
+	udm_modify "users/user" "" "" "" "" \
+			   --set employeeNumber="" \
+			   --set employeeType="" \
+			   --set country=""\
+			   --set shell=""\
+			   --set unixhome="$UDM_users_user_unixhome2"\
+			   --set title=""\
+			   --set departmentNumber=""\
+			   --set roomNumber="" \
+			   --set initials="" \
+			   --set physicalDeliveryOfficeName="" \
+			   --set postOfficeBox="" \
+			   --set preferredLanguage=""|| fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+fi
+
+
 
 ad_verify_attribute "$AD_DN" "description" ""; fail_bool 0 121 "See #18501"
 ad_verify_attribute "$AD_DN" "givenName" ""; fail_bool 0 121 "See #18501"
@@ -161,6 +276,20 @@ ad_verify_attribute "$AD_DN" "mobile" ""; fail_bool 0 121 "See #18501"
 ad_verify_attribute "$AD_DN" "otherMobile" ""; fail_bool 0 121 "See #18501"
 ad_verify_attribute "$AD_DN" "pager" ""; fail_bool 0 121 "See #18501"
 ad_verify_attribute "$AD_DN" "otherPager" ""; fail_bool 0 121 "See #18501"
+if $ext_mapping; then
+	ad_verify_attribute "$AD_DN" "employeeNumber" ""; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	ad_verify_attribute "$AD_DN" "employeeType" ""; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	ad_verify_attribute "$AD_DN" "c" ""; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	ad_verify_attribute "$AD_DN" "loginShell" "" ; fail_bool 1 121
+	ad_verify_attribute "$AD_DN" "unixHomeDirectory" "$UDM_users_user_unixhome2"; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	ad_verify_attribute "$AD_DN" "personalTitle" "" ; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	ad_verify_attribute "$AD_DN" "departmentNumber" "" ; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	ad_verify_attribute "$AD_DN" "roomNumber" "" ; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	ad_verify_attribute "$AD_DN" "initials" "" ; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	ad_verify_attribute "$AD_DN" "physicalDeliveryOfficeName" ""; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	ad_verify_attribute "$AD_DN" "postOfficeBox" "" ; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	ad_verify_attribute "$AD_DN" "preferredLanguage" "" ; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+fi
 
 udm_verify_udm_attribute "firstname" None "users/user"; fail_bool 0 110
 udm_verify_udm_attribute "street" None "users/user"; fail_bool 0 110
@@ -175,7 +304,22 @@ udm_verify_udm_attribute "phone" "" "users/user"; fail_bool 0 110
 udm_verify_udm_attribute "homeTelephoneNumber" "" "users/user"; fail_bool 0 110
 udm_verify_udm_attribute "mobileTelephoneNumber" "" "users/user"; fail_bool 0 110
 udm_verify_udm_attribute "pagerTelephoneNumber" "" "users/user"; fail_bool 0 110
+if $ext_mapping; then
+	udm_verify_udm_attribute "employeeNumber" None "users/user"; fail_bool 0 110
+	udm_verify_udm_attribute "employeeType" None "users/user"; fail_bool 0 110
+	udm_verify_udm_attribute "country" None "users/user"; fail_bool 0 110
+	udm_verify_udm_attribute "shell" None "users/user"; fail_bool 0 110
+	udm_verify_udm_attribute "unixhome" "$UDM_users_user_unixhome2" "users/user"; fail_bool 0 110
+	udm_verify_udm_attribute "title" None "users/user" ; fail_bool 0 110
+	udm_verify_udm_attribute "departmentNumber" "" "users/user" ; fail_bool 0 110
+	udm_verify_udm_attribute "roomNumber" "" "users/user" ; fail_bool 0 110
+	udm_verify_udm_attribute "initials" None "users/user" ; fail_bool 0 110
+	udm_verify_udm_attribute "physicalDeliveryOfficeName" None "users/user" ; fail_bool 0 110
+	udm_verify_udm_attribute "postOfficeBox" "" "users/user" ; fail_bool 0 110
+	udm_verify_udm_attribute "preferredLanguage" None "users/user" ; fail_bool 0 110
+fi
 
+ucr set 'connector/s4/mapping/user/attributes/ignorelist'="$ignore_list_original"
 udm_remove "users/user" || fail_test 110
 ad_wait_for_synchronization; fail_bool 0 110
 
@@ -183,5 +327,6 @@ udm_exists "users/user"; fail_bool 1 110
 ad_exists "$AD_DN"; fail_bool 1 110
 
 ad_set_sync_mode "$SYNCMODE"
+ad_connector_restart
 
 exit "$RETVAL"
diff --git a/test/ucs-test/tests/52_s4connector/121sync_create_and_modify_ad_user b/test/ucs-test/tests/52_s4connector/121sync_create_and_modify_ad_user
--- a/test/ucs-test/tests/52_s4connector/121sync_create_and_modify_ad_user
+++ b/test/ucs-test/tests/52_s4connector/121sync_create_and_modify_ad_user
@@ -10,7 +10,19 @@
 . "$TESTLIBPATH/base.sh" || exit 137
 . "$TESTLIBPATH/udm.sh" || exit 137
 . "$TESTLIBPATH/random.sh" || exit 137
+. "s4connector.sh" || exit 137
 
+#check if ucs-version supports extended mapping of s4-attributes
+ext_mapping=false;
+if current_ucs_version_greater_equal 4.4-0; then
+	ext_mapping=true;
+fi
+
+#unset ignorelist for user attributes
+ignore_list_original="$(ucr get connector/s4/mapping/user/attributes/ignorelist)"
+ucr unset "connector/s4/mapping/user/attributes/ignorelist"
+
+ad_connector_restart || exit 137
 
 . "s4connector.sh" || exit 137
 test -n "$connector_s4_ldap_host" || exit 137
@@ -26,6 +38,17 @@ UDM_users_user_postcode="$(random_chars)"
 UDM_users_user_profilepath="$(random_chars)"
 UDM_users_user_scriptpath="$(random_chars)"
 AD_DN="CN=$UDM_users_user_username,CN=users,$(ad_get_base)"
+UDM_users_user_employeeNumber="a$(random_chars)"
+UDM_users_user_employeeType="a$(random_chars)"
+UDM_users_user_country="US"
+UDM_users_user_loginShell="a$(random_chars)"
+UDM_users_user_title="a$(random_chars)"
+UDM_users_user_departmentNumber="a$(random_chars)"
+UDM_users_user_roomNumber="a$(random_chars)"
+UDM_users_user_initials="a$(random_chars 1)"
+UDM_users_user_physicalDeliveryOfficeName="a$(random_chars)"
+UDM_users_user_postOfficeBox="a$(random_chars)"
+UDM_users_user_preferredLanguage="a$(random_chars)"
 
 SYNCMODE="$(ad_get_sync_mode)"
 
@@ -50,6 +73,28 @@ ad_set_attribute "$AD_DN" "profilePath" "$UDM_users_user_profilepath" || fail_te
 ad_wait_for_synchronization; fail_bool 0 110
 ad_set_attribute "$AD_DN" "scriptPath" "$UDM_users_user_scriptpath" || fail_test 110
 ad_wait_for_synchronization; fail_bool 0 110
+if $ext_mapping;then
+	ad_set_attribute "$AD_DN" "employeeNumber" "$UDM_users_user_employeeNumber" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "employeeType" "$UDM_users_user_employeeType" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "c" "$UDM_users_user_country" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "personalTitle" "$UDM_users_user_title" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "loginShell" "$UDM_users_user_loginShell" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "initials" "$UDM_users_user_initials" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "roomNumber" "$UDM_users_user_roomNumber" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "postOfficeBox" "$UDM_users_user_postOfficeBox" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "preferredLanguage" "$UDM_users_user_preferredLanguage" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+fi
 
 if [ "$connector_s4_windows_version" != "win2000" \
 	-o "$connector_s4_mapping_user_win2000_description" != "false" ]
@@ -64,6 +109,17 @@ udm_verify_udm_attribute "city" "$UDM_users_user_city" "users/user"; fail_bool 0
 udm_verify_udm_attribute "postcode" "$UDM_users_user_postcode" "users/user"; fail_bool 0 121 "See #18501"
 udm_verify_udm_attribute "profilepath" "$UDM_users_user_profilepath" "users/user"; fail_bool 0 121 "See #18501"
 udm_verify_udm_attribute "scriptpath" "$UDM_users_user_scriptpath" "users/user"; fail_bool 0 121 "See #18501"
+if $ext_mapping;then
+	udm_verify_udm_attribute "employeeNumber" "$UDM_users_user_employeeNumber" "users/user"; fail_bool 0 121 "See #18501"
+	udm_verify_udm_attribute "employeeType" "$UDM_users_user_employeeType" "users/user"; fail_bool 0 121 "See #18501"
+	udm_verify_udm_attribute "country" "$UDM_users_user_country" "users/user"; fail_bool 0 121 "See #18501"
+	udm_verify_udm_attribute "shell" "$UDM_users_user_loginShell" "users/user"; fail_bool 0 121 "See #18501"
+	udm_verify_udm_attribute "title" "$UDM_users_user_title" "users/user"; fail_bool 0 121 "See #18501"
+	udm_verify_udm_attribute "roomNumber" "$UDM_users_user_roomNumber" "users/user"; fail_bool 0 121 "See #18501"
+	udm_verify_udm_attribute "postOfficeBox" "$UDM_users_user_postOfficeBox" "users/user"; fail_bool 0 121 "See #18501"
+	udm_verify_udm_attribute "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName" "users/user"; fail_bool 0 121 "See #18501"
+	udm_verify_udm_attribute "preferredLanguage" "$UDM_users_user_preferredLanguage" "users/user"; fail_bool 0 121 "See #18501"
+fi
 
 ad_verify_attribute "$AD_DN" "description" "$UDM_users_user_description"; fail_bool 0 110
 ad_verify_attribute	"$AD_DN" "sAMAccountName" "$UDM_users_user_username"; fail_bool 0 110
@@ -74,6 +130,81 @@ ad_verify_attribute "$AD_DN" "postalCode" "$UDM_users_user_postcode"; fail_bool 
 ad_verify_attribute "$AD_DN" "profilePath" "$UDM_users_user_profilepath"; fail_bool 0 110
 ad_verify_attribute "$AD_DN" "scriptPath" "$UDM_users_user_scriptpath"; fail_bool 0 110
 ad_verify_attribute "$AD_DN" "streetAddress" "$UDM_users_user_street"; fail_bool 0 110
+if $ext_mapping;then
+	ad_verify_attribute "$AD_DN" "employeeNumber" "$UDM_users_user_employeeNumber"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "employeeType" "$UDM_users_user_employeeType"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "c" "$UDM_users_user_country"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "loginShell" "$UDM_users_user_loginShell"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "personalTitle" "$UDM_users_user_title"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "roomNumber" "$UDM_users_user_roomNumber"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "postOfficeBox" "$UDM_users_user_postOfficeBox"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "preferredLanguage" "$UDM_users_user_preferredLanguage"; fail_bool 0 110
+fi
+
+### Test if mapping of user-attributes is configurable via ucr variable 'connector/s4/mapping/user/attributes/ignorelist'
+ucr set 'connector/s4/mapping/user/attributes/ignorelist'='employeeNumber,employeeType,country,departmentNumber,loginShell,unixhome,title,uidNumber,gidNumber,roomNumber,initials,physicalDeliveryOfficeName,postOfficeBox,preferredLanguage'
+
+ad_connector_restart || exit 137
+test -n "$connector_s4_ldap_host" || exit 137
+connector_running_on_this_host || exit 137
+
+UDM_users_user_employeeNumber="b$(random_chars)"
+UDM_users_user_employeeType="b$(random_chars)"
+UDM_users_user_country="DE"
+UDM_users_user_loginShell="b$(random_chars)"
+UDM_users_user_title="b$(random_chars)"
+UDM_users_user_departmentNumber="b$(random_chars)"
+UDM_users_user_roomNumber="b$(random_chars)"
+UDM_users_user_initials="b$(random_chars 1)"
+UDM_users_user_physicalDeliveryOfficeName="b$(random_chars)"
+UDM_users_user_postOfficeBox="b$(random_chars)"
+UDM_users_user_preferredLanguage="b$(random_chars)"
+
+if $ext_mapping;then
+	ad_set_attribute "$AD_DN" "employeeNumber" "$UDM_users_user_employeeNumber" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "employeeType" "$UDM_users_user_employeeType" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "c" "$UDM_users_user_country" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "personalTitle" "$UDM_users_user_title" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "loginShell" "$UDM_users_user_loginShell" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "initials" "$UDM_users_user_initials" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "roomNumber" "$UDM_users_user_roomNumber" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "postOfficeBox" "$UDM_users_user_postOfficeBox" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+	ad_set_attribute "$AD_DN" "preferredLanguage" "$UDM_users_user_preferredLanguage" || fail_test 110
+	ad_wait_for_synchronization; fail_bool 0 110
+
+	ad_verify_attribute "$AD_DN" "employeeNumber" "$UDM_users_user_employeeNumber"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "employeeType" "$UDM_users_user_employeeType"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "c" "$UDM_users_user_country"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "loginShell" "$UDM_users_user_loginShell"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "personalTitle" "$UDM_users_user_title"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "roomNumber" "$UDM_users_user_roomNumber"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "postOfficeBox" "$UDM_users_user_postOfficeBox"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "preferredLanguage" "$UDM_users_user_preferredLanguage"; fail_bool 0 110
+
+	udm_verify_udm_attribute "employeeNumber" "$UDM_users_user_employeeNumber" "users/user"; fail_bool 1 121 "connector/s4/mapping/user/attributes/ignorelist does not apply"
+	udm_verify_udm_attribute "employeeType" "$UDM_users_user_employeeType" "users/user"; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	udm_verify_udm_attribute "country" "$UDM_users_user_country" "users/user"; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist'
+	udm_verify_udm_attribute "shell" "$UDM_users_user_loginShell" "users/user"; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	udm_verify_udm_attribute "title" "$UDM_users_user_title" "users/user"; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	udm_verify_udm_attribute "roomNumber" "$UDM_users_user_roomNumber" "users/user"; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	udm_verify_udm_attribute "postOfficeBox" "$UDM_users_user_postOfficeBox" "users/user"; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	udm_verify_udm_attribute "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName" "users/user"; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+	udm_verify_udm_attribute "preferredLanguage" "$UDM_users_user_preferredLanguage" "users/user"; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
+fi
+
+ucr set 'connector/s4/mapping/user/attributes/ignorelist'="$ignore_list_original"
 
 ad_delete "$AD_DN" || fail_test 110
 ad_wait_for_synchronization; fail_bool 0 110
@@ -82,5 +213,6 @@ udm_exists "users/user"; fail_bool 1 110
 ad_exists "$AD_DN"; fail_bool 1 110
 
 ad_set_sync_mode "$SYNCMODE"
+ad_connector_restart
 
 exit "$RETVAL"
