style(ucs-test): fail_bool -> fail_test
git grep -l 'fail_bool 0 ' | xargs sed -e 's/ *; *fail_bool 0 / || fail_test /g' -i

Issue univention/ucs#1854

diff --git a/test/ucs-test/tests/52_s4connector/121sync_create_and_modify_ad_user b/test/ucs-test/tests/52_s4connector/121sync_create_and_modify_ad_user
--- a/test/ucs-test/tests/52_s4connector/121sync_create_and_modify_ad_user
+++ b/test/ucs-test/tests/52_s4connector/121sync_create_and_modify_ad_user
@@ -62,91 +62,91 @@ ad_set_sync_mode "sync"
 
 #We have to wait between all the AD-Commands: See #18501
 ad_createuser "$UDM_users_user_username" || fail_test 110
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 ad_set_attribute "$AD_DN" "givenName" "$UDM_users_user_firstname" || fail_test 110
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 ad_set_attribute "$AD_DN" "sn" "$UDM_users_user_lastname" || fail_test 110
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 ad_set_attribute "$AD_DN" "description" "$UDM_users_user_description" || fail_test 110
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 ad_set_attribute "$AD_DN" "streetAddress" "$UDM_users_user_street" || fail_test 110
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 ad_set_attribute "$AD_DN" "l" "$UDM_users_user_city" || fail_test 110
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 ad_set_attribute "$AD_DN" "postalCode" "$UDM_users_user_postcode" || fail_test 110
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 ad_set_attribute "$AD_DN" "profilePath" "$UDM_users_user_profilepath" || fail_test 110
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 ad_set_attribute "$AD_DN" "scriptPath" "$UDM_users_user_scriptpath" || fail_test 110
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 if $ext_mapping; then
 	ad_set_attribute "$AD_DN" "preferredDeliveryMethod" "$AD_users_user_prefdev" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "employeeNumber" "$UDM_users_user_employeeNumber" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "employeeType" "$UDM_users_user_employeeType" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "c" "$UDM_users_user_country" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "personalTitle" "$UDM_users_user_title" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "loginShell" "$UDM_users_user_loginShell" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "roomNumber" "$UDM_users_user_roomNumber" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "initials" "$UDM_users_user_initials" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "postOfficeBox" "$UDM_users_user_postOfficeBox" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "preferredLanguage" "$UDM_users_user_preferredLanguage" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 fi
 
 if [ "${connector_s4_windows_version:-}" != "win2000" ] || [ "${connector_s4_mapping_user_win2000_description:-}" != "false" ]
 then
-	udm_verify_udm_attribute "description" "$UDM_users_user_description" "users/user"; fail_bool 0 121 "See #18501"
+	udm_verify_udm_attribute "description" "$UDM_users_user_description" "users/user" || fail_test 121 "See #18501"
 fi
-udm_verify_udm_attribute "username" "$UDM_users_user_username" "users/user"; fail_bool 0 121 "See #18501"
-udm_verify_udm_attribute "firstname" "$UDM_users_user_firstname" "users/user"; fail_bool 0 121 "See #18501"
-udm_verify_udm_attribute "lastname" "$UDM_users_user_lastname" "users/user"; fail_bool 0 121 "See #18501"
-udm_verify_udm_attribute "street" "$UDM_users_user_street" "users/user"; fail_bool 0 121 "See #18501"
-udm_verify_udm_attribute "city" "$UDM_users_user_city" "users/user"; fail_bool 0 121 "See #18501"
-udm_verify_udm_attribute "postcode" "$UDM_users_user_postcode" "users/user"; fail_bool 0 121 "See #18501"
-udm_verify_udm_attribute "profilepath" "$UDM_users_user_profilepath" "users/user"; fail_bool 0 121 "See #18501"
-udm_verify_udm_attribute "scriptpath" "$UDM_users_user_scriptpath" "users/user"; fail_bool 0 121 "See #18501"
+udm_verify_udm_attribute "username" "$UDM_users_user_username" "users/user" || fail_test 121 "See #18501"
+udm_verify_udm_attribute "firstname" "$UDM_users_user_firstname" "users/user" || fail_test 121 "See #18501"
+udm_verify_udm_attribute "lastname" "$UDM_users_user_lastname" "users/user" || fail_test 121 "See #18501"
+udm_verify_udm_attribute "street" "$UDM_users_user_street" "users/user" || fail_test 121 "See #18501"
+udm_verify_udm_attribute "city" "$UDM_users_user_city" "users/user" || fail_test 121 "See #18501"
+udm_verify_udm_attribute "postcode" "$UDM_users_user_postcode" "users/user" || fail_test 121 "See #18501"
+udm_verify_udm_attribute "profilepath" "$UDM_users_user_profilepath" "users/user" || fail_test 121 "See #18501"
+udm_verify_udm_attribute "scriptpath" "$UDM_users_user_scriptpath" "users/user" || fail_test 121 "See #18501"
 if $ext_mapping; then
-	udm_verify_udm_attribute "employeeNumber" "$UDM_users_user_employeeNumber" "users/user"; fail_bool 0 121 "See #18501"
-	udm_verify_udm_attribute "employeeType" "$UDM_users_user_employeeType" "users/user"; fail_bool 0 121 "See #18501"
-	udm_verify_udm_attribute "shell" "$UDM_users_user_loginShell" "users/user"; fail_bool 0 121 "See #18501"
-	udm_verify_udm_attribute "title" "$UDM_users_user_title" "users/user"; fail_bool 0 121 "See #18501"
-	udm_verify_udm_attribute "roomNumber" "$UDM_users_user_roomNumber" "users/user"; fail_bool 0 121 "See #18501"
-	udm_verify_udm_attribute "preferredDeliveryMethod" "$UDM_users_user_prefdev" "users/user"; fail_bool 0 121 "See #18501"
-	udm_verify_udm_attribute "postOfficeBox" "$UDM_users_user_postOfficeBox" "users/user"; fail_bool 0 121 "See #18501"
-	udm_verify_udm_attribute "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName" "users/user"; fail_bool 0 121 "See #18501"
-	udm_verify_udm_attribute "preferredLanguage" "$UDM_users_user_preferredLanguage" "users/user"; fail_bool 0 121 "See #18501"
+	udm_verify_udm_attribute "employeeNumber" "$UDM_users_user_employeeNumber" "users/user" || fail_test 121 "See #18501"
+	udm_verify_udm_attribute "employeeType" "$UDM_users_user_employeeType" "users/user" || fail_test 121 "See #18501"
+	udm_verify_udm_attribute "shell" "$UDM_users_user_loginShell" "users/user" || fail_test 121 "See #18501"
+	udm_verify_udm_attribute "title" "$UDM_users_user_title" "users/user" || fail_test 121 "See #18501"
+	udm_verify_udm_attribute "roomNumber" "$UDM_users_user_roomNumber" "users/user" || fail_test 121 "See #18501"
+	udm_verify_udm_attribute "preferredDeliveryMethod" "$UDM_users_user_prefdev" "users/user" || fail_test 121 "See #18501"
+	udm_verify_udm_attribute "postOfficeBox" "$UDM_users_user_postOfficeBox" "users/user" || fail_test 121 "See #18501"
+	udm_verify_udm_attribute "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName" "users/user" || fail_test 121 "See #18501"
+	udm_verify_udm_attribute "preferredLanguage" "$UDM_users_user_preferredLanguage" "users/user" || fail_test 121 "See #18501"
 fi
 
-ad_verify_attribute "$AD_DN" "description" "$UDM_users_user_description"; fail_bool 0 110
-ad_verify_attribute	"$AD_DN" "sAMAccountName" "$UDM_users_user_username"; fail_bool 0 110
-ad_verify_attribute "$AD_DN" "givenName" "$UDM_users_user_firstname"; fail_bool 0 110
-ad_verify_attribute "$AD_DN" "sn" "$UDM_users_user_lastname"; fail_bool 0 110
-ad_verify_attribute "$AD_DN" "l" "$UDM_users_user_city"; fail_bool 0 110
-ad_verify_attribute "$AD_DN" "postalCode" "$UDM_users_user_postcode"; fail_bool 0 110
-ad_verify_attribute "$AD_DN" "profilePath" "$UDM_users_user_profilepath"; fail_bool 0 110
-ad_verify_attribute "$AD_DN" "scriptPath" "$UDM_users_user_scriptpath"; fail_bool 0 110
-ad_verify_attribute "$AD_DN" "streetAddress" "$UDM_users_user_street"; fail_bool 0 110
+ad_verify_attribute "$AD_DN" "description" "$UDM_users_user_description" || fail_test 110
+ad_verify_attribute	"$AD_DN" "sAMAccountName" "$UDM_users_user_username" || fail_test 110
+ad_verify_attribute "$AD_DN" "givenName" "$UDM_users_user_firstname" || fail_test 110
+ad_verify_attribute "$AD_DN" "sn" "$UDM_users_user_lastname" || fail_test 110
+ad_verify_attribute "$AD_DN" "l" "$UDM_users_user_city" || fail_test 110
+ad_verify_attribute "$AD_DN" "postalCode" "$UDM_users_user_postcode" || fail_test 110
+ad_verify_attribute "$AD_DN" "profilePath" "$UDM_users_user_profilepath" || fail_test 110
+ad_verify_attribute "$AD_DN" "scriptPath" "$UDM_users_user_scriptpath" || fail_test 110
+ad_verify_attribute "$AD_DN" "streetAddress" "$UDM_users_user_street" || fail_test 110
 if $ext_mapping; then
-	ad_verify_attribute "$AD_DN" "preferredDeliveryMethod" "$AD_users_user_prefdev"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "employeeNumber" "$UDM_users_user_employeeNumber"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "employeeType" "$UDM_users_user_employeeType"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "loginShell" "$UDM_users_user_loginShell"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "personalTitle" "$UDM_users_user_title"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "roomNumber" "$UDM_users_user_roomNumber"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "postOfficeBox" "$UDM_users_user_postOfficeBox"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "preferredLanguage" "$UDM_users_user_preferredLanguage"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "preferredDeliveryMethod" "$AD_users_user_prefdev" || fail_test 110
+	ad_verify_attribute "$AD_DN" "employeeNumber" "$UDM_users_user_employeeNumber" || fail_test 110
+	ad_verify_attribute "$AD_DN" "employeeType" "$UDM_users_user_employeeType" || fail_test 110
+	ad_verify_attribute "$AD_DN" "loginShell" "$UDM_users_user_loginShell" || fail_test 110
+	ad_verify_attribute "$AD_DN" "personalTitle" "$UDM_users_user_title" || fail_test 110
+	ad_verify_attribute "$AD_DN" "roomNumber" "$UDM_users_user_roomNumber" || fail_test 110
+	ad_verify_attribute "$AD_DN" "postOfficeBox" "$UDM_users_user_postOfficeBox" || fail_test 110
+	ad_verify_attribute "$AD_DN" "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName" || fail_test 110
+	ad_verify_attribute "$AD_DN" "preferredLanguage" "$UDM_users_user_preferredLanguage" || fail_test 110
 fi
 ### Test if mapping of user-attributes is configurable via ucr variable 'connector/s4/mapping/user/attributes/ignorelist'
 ucr set 'connector/s4/mapping/user/attributes/ignorelist'='preferredDeliveryMethod, employeeNumber,employeeType,departmentNumber,loginShell,unixhome,title,uidNumber,gidNumber,roomNumber,initials,physicalDeliveryOfficeName,postOfficeBox,preferredLanguage'
@@ -168,33 +168,33 @@ UDM_users_user_preferredLanguage="b$(random_chars)"
 
 if $ext_mapping; then
 	ad_set_attribute "$AD_DN" "employeeNumber" "$UDM_users_user_employeeNumber" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "employeeType" "$UDM_users_user_employeeType" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "personalTitle" "$UDM_users_user_title" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "loginShell" "$UDM_users_user_loginShell" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "roomNumber" "$UDM_users_user_roomNumber" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "initials" "$UDM_users_user_initials" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "postOfficeBox" "$UDM_users_user_postOfficeBox" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 	ad_set_attribute "$AD_DN" "preferredLanguage" "$UDM_users_user_preferredLanguage" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 
-	ad_verify_attribute "$AD_DN" "employeeNumber" "$UDM_users_user_employeeNumber"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "employeeType" "$UDM_users_user_employeeType"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "loginShell" "$UDM_users_user_loginShell"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "personalTitle" "$UDM_users_user_title"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "roomNumber" "$UDM_users_user_roomNumber"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "postOfficeBox" "$UDM_users_user_postOfficeBox"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName"; fail_bool 0 110
-	ad_verify_attribute "$AD_DN" "preferredLanguage" "$UDM_users_user_preferredLanguage"; fail_bool 0 110
+	ad_verify_attribute "$AD_DN" "employeeNumber" "$UDM_users_user_employeeNumber" || fail_test 110
+	ad_verify_attribute "$AD_DN" "employeeType" "$UDM_users_user_employeeType" || fail_test 110
+	ad_verify_attribute "$AD_DN" "loginShell" "$UDM_users_user_loginShell" || fail_test 110
+	ad_verify_attribute "$AD_DN" "personalTitle" "$UDM_users_user_title" || fail_test 110
+	ad_verify_attribute "$AD_DN" "roomNumber" "$UDM_users_user_roomNumber" || fail_test 110
+	ad_verify_attribute "$AD_DN" "postOfficeBox" "$UDM_users_user_postOfficeBox" || fail_test 110
+	ad_verify_attribute "$AD_DN" "physicalDeliveryOfficeName" "$UDM_users_user_physicalDeliveryOfficeName" || fail_test 110
+	ad_verify_attribute "$AD_DN" "preferredLanguage" "$UDM_users_user_preferredLanguage" || fail_test 110
 
 	udm_verify_udm_attribute "employeeNumber" "$UDM_users_user_employeeNumber" "users/user"; fail_bool 1 121 "connector/s4/mapping/user/attributes/ignorelist does not apply"
 	udm_verify_udm_attribute "employeeType" "$UDM_users_user_employeeType" "users/user"; fail_bool 1 121 'connector/s4/mapping/user/attributes/ignorelist does not apply'
@@ -209,7 +209,7 @@ fi
 ucr set 'connector/s4/mapping/user/attributes/ignorelist'="$ignore_list_original"
 
 ad_delete "$AD_DN" || fail_test 110
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 
 udm_exists "users/user"; fail_bool 1 110
 ad_exists "$AD_DN"; fail_bool 1 110
diff --git a/test/ucs-test/tests/52_s4connector/513test_password_change_next_logon b/test/ucs-test/tests/52_s4connector/513test_password_change_next_logon
--- a/test/ucs-test/tests/52_s4connector/513test_password_change_next_logon
+++ b/test/ucs-test/tests/52_s4connector/513test_password_change_next_logon
@@ -81,10 +81,10 @@ UDM_users_user_lastname="test"
 UDM_users_user_password="Univention.99"
 AD_DN="CN=$UDM_users_user_username,CN=users,$(ad_get_base)"
 ad_create_user_with_must_change_at_next_login "$UDM_users_user_username" "$UDM_users_user_password"
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 #ad_set_attribute "$AD_DN" "pwdLastSet" "0" || fail_test 110
 echo "$UDM_users_user_password" >"$tmp/$UDM_users_user_username"
-#ad_wait_for_synchronization; fail_bool 0 110
+#ad_wait_for_synchronization || fail_test 110
 univention-adsearch "cn='$user1'"
 # check ad user
 ad_verify_attribute "$AD_DN" "pwdLastSet" "0"
@@ -107,7 +107,7 @@ AD_DN="CN=$UDM_users_user_username,CN=users,$(ad_get_base)"
 UDM_users_user_pwdChangeNextLogin="1"
 udm_create "users/user" || fail_test 110
 echo "$UDM_users_user_password" >"$tmp/$UDM_users_user_username"
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 # check ucs user
 udm_verify_ldap_attribute "shadowMax" "1" "users/user" || fail_test 110
 udm_verify_ldap_attribute "krb5PasswordEnd" "$(date +%Y%m%d000000Z)" "users/user" || fail_test 110
@@ -126,7 +126,7 @@ UDM_users_user_username="$user1"
 udm_remove "users/user" || fail_test 110
 UDM_users_user_username="$user2"
 udm_remove "users/user" || fail_test 110
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 udm_exists "users/user"; fail_bool 1 110
 ad_exists "$AD_DN"; fail_bool 1 110
 ad_set_sync_mode "$SYNCMODE"
diff --git a/test/ucs-test/tests/52_s4connector/517authentication_accountExpires b/test/ucs-test/tests/52_s4connector/517authentication_accountExpires
--- a/test/ucs-test/tests/52_s4connector/517authentication_accountExpires
+++ b/test/ucs-test/tests/52_s4connector/517authentication_accountExpires
@@ -27,7 +27,7 @@ ad_set_sync_mode "sync"
 cleanup () {
   #remove
   udm_remove "users/user" || fail_test 110
-  ad_wait_for_synchronization; fail_bool 0 110
+  ad_wait_for_synchronization || fail_test 110
   ad_exists "${AD_DN}"; fail_bool 1 110
   udm_exists "users/user"; fail_bool 1 110
   #restore
@@ -43,22 +43,22 @@ trap cleanup EXIT
 section "Create user account: "
 
 udm_create "users/user" || fail_test 110
-ad_wait_for_synchronization; fail_bool 0 110
-udm_exists "users/user"; fail_bool 0 110
-ad_exists "${AD_DN}"; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
+udm_exists "users/user" || fail_test 110
+ad_exists "${AD_DN}" || fail_test 110
 
 section "Trying authentication: SAMBA-KERBEROS-LDAP_UCS_BIND"
 
 HOST="$(ucr get connector/s4/ldap/host)"
-smbclient "//${HOST}/sysvol" -c 'exit' -U "${UDM_users_user_username}%${UDM_users_user_password}" ; fail_bool 0 110
-ldapsearch -D "$UCS_DN" -w "${UDM_users_user_password}" &>/dev/null; fail_bool 0 110
-echo "${UDM_users_user_password}" | kinit --password-file=STDIN "${UDM_users_user_username}" ; fail_bool 0 110
+smbclient "//${HOST}/sysvol" -c 'exit' -U "${UDM_users_user_username}%${UDM_users_user_password}" || fail_test 110
+ldapsearch -D "$UCS_DN" -w "${UDM_users_user_password}" &>/dev/null || fail_test 110
+echo "${UDM_users_user_password}" | kinit --password-file=STDIN "${UDM_users_user_username}" || fail_test 110
 
 section "Expire user account: LDAP_SAMBA --> LDAP_UCS"
 
 EXPIRED_DATE="$((($(date +%s) + 11644473600) * 10000000))"
 ad_set_attribute "$AD_DN" "accountExpires" "${EXPIRED_DATE}" || fail_test 20
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 
 section "Trying authentication second time: SAMBA-KERBEROS-LDAP_UCS_BIND"
 
@@ -70,24 +70,24 @@ section "Revert user account changes: LDAP_SAMBA"
 
 EXPIRED_DATE=$((($(date +%s -d "+20 day") + 11644473600) * 10000000))
 ad_set_attribute "$AD_DN" "accountExpires" "${EXPIRED_DATE}" || fail_test 20
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 
 section "Trying authentication three time: SAMBA-KERBEROS-LDAP_UCS_BIND"
 
-smbclient "//${HOST}/sysvol" -c 'exit' -U "${UDM_users_user_username}%${UDM_users_user_password}" ; fail_bool 0 110
-echo "${UDM_users_user_password}" | kinit --password-file=STDIN "${UDM_users_user_username}" ; fail_bool 0 110
-ldapsearch -D "$UCS_DN" -w "${UDM_users_user_password}" >/dev/null; fail_bool 0 100
+smbclient "//${HOST}/sysvol" -c 'exit' -U "${UDM_users_user_username}%${UDM_users_user_password}" || fail_test 110
+echo "${UDM_users_user_password}" | kinit --password-file=STDIN "${UDM_users_user_username}" || fail_test 110
+ldapsearch -D "$UCS_DN" -w "${UDM_users_user_password}" >/dev/null || fail_test 100
 
 section "Expire user account: LDAP_UCS --> LDAP_SAMBA"
 
 TOMORROW="$(date -d '+1 day' '+%Y-%m-%d')"
 udm "users/user" modify --dn "$UCS_DN" --set userexpiry="${TOMORROW}" || fail_test 110
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 
 section "Trying authentication three time: SAMBA-KERBEROS-LDAP_UCS_BIND"
 
-smbclient "//${HOST}/sysvol" -c 'exit' -U "${UDM_users_user_username}%${UDM_users_user_password}" ; fail_bool 0 110
-echo "${UDM_users_user_password}" | kinit --password-file=STDIN "${UDM_users_user_username}" ; fail_bool 0 110
-ldapsearch -D "$UCS_DN" -w "${UDM_users_user_password}" >/dev/null; fail_bool 0 110
+smbclient "//${HOST}/sysvol" -c 'exit' -U "${UDM_users_user_username}%${UDM_users_user_password}" || fail_test 110
+echo "${UDM_users_user_password}" | kinit --password-file=STDIN "${UDM_users_user_username}" || fail_test 110
+ldapsearch -D "$UCS_DN" -w "${UDM_users_user_password}" >/dev/null || fail_test 110
 
 exit "${RETVAL:-0}"
diff --git a/test/ucs-test/tests/55_adconnector/130sync_ucs_user_change_mail_attributes b/test/ucs-test/tests/55_adconnector/130sync_ucs_user_change_mail_attributes
--- a/test/ucs-test/tests/55_adconnector/130sync_ucs_user_change_mail_attributes
+++ b/test/ucs-test/tests/55_adconnector/130sync_ucs_user_change_mail_attributes
@@ -51,7 +51,7 @@ cleanup() {
 	section "==========Test done - Cleanup=========="
 
 	udm_remove "users/user" || fail_test 110
-	ad_wait_for_synchronization; fail_bool 0 110
+	ad_wait_for_synchronization || fail_test 110
 
 	udm_exists "users/user"; fail_bool 1 110
 	ad_exists "$AD_DN"; fail_bool 1 110
@@ -74,26 +74,26 @@ udm_modify "users/user" "" "" "" "" \
 	--set mailAlternativeAddress="$UDM_users_user_mailAlternativeAddress" \
 	--set e-mail="$UDM_users_user_mail" || fail_test 110
 
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 
-udm_exists "users/user"; fail_bool 0 110
-ad_exists "$AD_DN"; fail_bool 0 110
+udm_exists "users/user" || fail_test 110
+ad_exists "$AD_DN" || fail_test 110
 
-udm_verify_udm_attribute "mailPrimaryAddress" "$UDM_users_user_mailPrimaryAddress" "users/user"; fail_bool 0 110
-udm_verify_udm_attribute "mailAlternativeAddress" "$UDM_users_user_mailAlternativeAddress" "users/user"; fail_bool 0 110
-udm_verify_udm_attribute "e-mail" "$UDM_users_user_mail" "users/user"; fail_bool 0 110
-#udm_verify_udm_attribute "Exchange-Homeserver" "$UDM_users_user_Exchange_Homeserver" "users/user"; fail_bool 0 110
-#udm_verify_udm_attribute "Exchange-homeMDB" "$UDM_users_user_Exchange_homeMDB" "users/user"; fail_bool 0 110
-#udm_verify_udm_attribute "Exchange-Nickname" "$UDM_users_user_Exchange_Nickname" "users/user"; fail_bool 0 110
+udm_verify_udm_attribute "mailPrimaryAddress" "$UDM_users_user_mailPrimaryAddress" "users/user" || fail_test 110
+udm_verify_udm_attribute "mailAlternativeAddress" "$UDM_users_user_mailAlternativeAddress" "users/user" || fail_test 110
+udm_verify_udm_attribute "e-mail" "$UDM_users_user_mail" "users/user" || fail_test 110
+#udm_verify_udm_attribute "Exchange-Homeserver" "$UDM_users_user_Exchange_Homeserver" "users/user" || fail_test 110
+#udm_verify_udm_attribute "Exchange-homeMDB" "$UDM_users_user_Exchange_homeMDB" "users/user" || fail_test 110
+#udm_verify_udm_attribute "Exchange-Nickname" "$UDM_users_user_Exchange_Nickname" "users/user" || fail_test 110
 
 ad_verify_multi_value_attribute_contains "$AD_DN" \
-	"proxyAddresses" "SMTP:$UDM_users_user_mailPrimaryAddress"; fail_bool 0 110
+	"proxyAddresses" "SMTP:$UDM_users_user_mailPrimaryAddress" || fail_test 110
 ad_verify_multi_value_attribute_contains "$AD_DN" \
-	"proxyAddresses" "smtp:$UDM_users_user_mailAlternativeAddress"; fail_bool 0 110
-ad_verify_attribute "$AD_DN" "mail" "$UDM_users_user_mailPrimaryAddress"; fail_bool 0 110
-#ad_verify_attribute "$AD_DN" "msExchHomeServerName" "$UDM_users_user_Exchange_Homeserver"; fail_bool 0 110
-#ad_verify_attribute "$AD_DN" "homeMDB" "$UDM_users_user_Exchange_homeMDB"; fail_bool 0 110
-#ad_verify_attribute "$AD_DN" "mailNickname" "$UDM_users_user_Exchange_Nickname"; fail_bool 0 110
+	"proxyAddresses" "smtp:$UDM_users_user_mailAlternativeAddress" || fail_test 110
+ad_verify_attribute "$AD_DN" "mail" "$UDM_users_user_mailPrimaryAddress" || fail_test 110
+#ad_verify_attribute "$AD_DN" "msExchHomeServerName" "$UDM_users_user_Exchange_Homeserver" || fail_test 110
+#ad_verify_attribute "$AD_DN" "homeMDB" "$UDM_users_user_Exchange_homeMDB" || fail_test 110
+#ad_verify_attribute "$AD_DN" "mailNickname" "$UDM_users_user_Exchange_Nickname" || fail_test 110
 
 output=$(univention-adconnector-list-rejected 2>&1)
 if echo "$output" | grep -qi "$UDM_users_user_username"; then
@@ -114,23 +114,23 @@ udm_modify "users/user" "" "" "" "" \
 #		   --set Exchange-homeMDB="$UDM_users_user_Exchange_homeMDB" \
 #		   --set Exchange-Nickname="$UDM_users_user_Exchange_Nickname" \
 
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 
 ad_verify_multi_value_attribute_contains "$AD_DN" \
-	"proxyAddresses" "SMTP:$UDM_users_user_mailPrimaryAddress"; fail_bool 0 110
+	"proxyAddresses" "SMTP:$UDM_users_user_mailPrimaryAddress" || fail_test 110
 ad_verify_multi_value_attribute_contains "$AD_DN" \
-	"proxyAddresses" "smtp:$UDM_users_user_mailAlternativeAddress"; fail_bool 0 110
-ad_verify_attribute "$AD_DN" "mail" "$UDM_users_user_mailPrimaryAddress"; fail_bool 0 110
-#ad_verify_attribute "$AD_DN" "msExchHomeServerName" "$UDM_users_user_Exchange_Homeserver"; fail_bool 0 110
-#ad_verify_attribute "$AD_DN" "homeMDB" "$UDM_users_user_Exchange_homeMDB"; fail_bool 0 110
-#ad_verify_attribute "$AD_DN" "mailNickname" "$UDM_users_user_Exchange_Nickname"; fail_bool 0 110
+	"proxyAddresses" "smtp:$UDM_users_user_mailAlternativeAddress" || fail_test 110
+ad_verify_attribute "$AD_DN" "mail" "$UDM_users_user_mailPrimaryAddress" || fail_test 110
+#ad_verify_attribute "$AD_DN" "msExchHomeServerName" "$UDM_users_user_Exchange_Homeserver" || fail_test 110
+#ad_verify_attribute "$AD_DN" "homeMDB" "$UDM_users_user_Exchange_homeMDB" || fail_test 110
+#ad_verify_attribute "$AD_DN" "mailNickname" "$UDM_users_user_Exchange_Nickname" || fail_test 110
 
-udm_verify_udm_attribute "mailPrimaryAddress" "$UDM_users_user_mailPrimaryAddress" "users/user"; fail_bool 0 110
-udm_verify_udm_attribute "mailAlternativeAddress" "$UDM_users_user_mailAlternativeAddress" "users/user"; fail_bool 0 110
-udm_verify_udm_attribute "e-mail" "$UDM_users_user_mail" "users/user"; fail_bool 0 110
-#udm_verify_udm_attribute "Exchange-Homeserver" "$UDM_users_user_Exchange_Homeserver" "users/user"; fail_bool 0 110
-#udm_verify_udm_attribute "Exchange-homeMDB" "$UDM_users_user_Exchange_homeMDB" "users/user"; fail_bool 0 110
-#udm_verify_udm_attribute "Exchange-Nickname" "$UDM_users_user_Exchange_Nickname" "users/user"; fail_bool 0 110
+udm_verify_udm_attribute "mailPrimaryAddress" "$UDM_users_user_mailPrimaryAddress" "users/user" || fail_test 110
+udm_verify_udm_attribute "mailAlternativeAddress" "$UDM_users_user_mailAlternativeAddress" "users/user" || fail_test 110
+udm_verify_udm_attribute "e-mail" "$UDM_users_user_mail" "users/user" || fail_test 110
+#udm_verify_udm_attribute "Exchange-Homeserver" "$UDM_users_user_Exchange_Homeserver" "users/user" || fail_test 110
+#udm_verify_udm_attribute "Exchange-homeMDB" "$UDM_users_user_Exchange_homeMDB" "users/user" || fail_test 110
+#udm_verify_udm_attribute "Exchange-Nickname" "$UDM_users_user_Exchange_Nickname" "users/user" || fail_test 110
 
 output=$(univention-adconnector-list-rejected 2>&1)
 if echo "$output" | grep -qi "$UDM_users_user_username"; then
@@ -146,17 +146,17 @@ echo
 
 ad_set_attribute "$AD_DN" "mail" "$AD_user_mail" || fail_test 110
 
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 
-ad_verify_attribute "$AD_DN" "mail" "$AD_user_mail"; fail_bool 0 110
+ad_verify_attribute "$AD_DN" "mail" "$AD_user_mail" || fail_test 110
 
 ## Since "proxyAddress" is present in AD, it takes precendence over "mail"
-udm_verify_udm_attribute "mailPrimaryAddress" "$UDM_users_user_mailPrimaryAddress" "users/user"; fail_bool 0 110
+udm_verify_udm_attribute "mailPrimaryAddress" "$UDM_users_user_mailPrimaryAddress" "users/user" || fail_test 110
 udm_verify_multi_value_udm_attribute_contains "mailAlternativeAddress" \
 	"$AD_user_mail" "users/user"; fail_bool 1 110
 
 ## don't overwrite UDM/OpenLDAP:"mail", which is only informative
-udm_verify_udm_attribute "e-mail" "$UDM_users_user_mail" "users/user"; fail_bool 0 110
+udm_verify_udm_attribute "e-mail" "$UDM_users_user_mail" "users/user" || fail_test 110
 
 output=$(univention-adconnector-list-rejected 2>&1)
 if echo "$output" | grep -qi "$UDM_users_user_username"; then
@@ -182,38 +182,38 @@ ad_set_attribute "$AD_DN" "mail" "$UDM_users_user_mailPrimaryAddress3" || fail_t
 ad_set_attribute "$AD_DN" "proxyAddresses" "SMTP:$UDM_users_user_mailPrimaryAddress3" || fail_test 110
 ad_append_to_attribute "$AD_DN" "proxyAddresses" "smtp:$UDM_users_user_mailAlternativeAddress2" || fail_test 110
 ad_append_to_attribute "$AD_DN" "proxyAddresses" "$AD_preferred_sip_address" || fail_test 110
-#ad_set_attribute "$AD_DN" "msExchHomeServerName" "$UDM_users_user_Exchange_Homeserver"; fail_bool 0 110
-#ad_set_attribute "$AD_DN" "homeMDB" "$UDM_users_user_Exchange_homeMDB"; fail_bool 0 110
-#ad_set_attribute "$AD_DN" "mailNickname" "$UDM_users_user_Exchange_Nickname"; fail_bool 0 110
+#ad_set_attribute "$AD_DN" "msExchHomeServerName" "$UDM_users_user_Exchange_Homeserver" || fail_test 110
+#ad_set_attribute "$AD_DN" "homeMDB" "$UDM_users_user_Exchange_homeMDB" || fail_test 110
+#ad_set_attribute "$AD_DN" "mailNickname" "$UDM_users_user_Exchange_Nickname" || fail_test 110
 
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 
-ad_verify_attribute "$AD_DN" "mail" "$UDM_users_user_mailPrimaryAddress3"; fail_bool 0 110
+ad_verify_attribute "$AD_DN" "mail" "$UDM_users_user_mailPrimaryAddress3" || fail_test 110
 ad_verify_multi_value_attribute_contains "$AD_DN" \
-	"proxyAddresses" "SMTP:$UDM_users_user_mailPrimaryAddress3"; fail_bool 0 110
+	"proxyAddresses" "SMTP:$UDM_users_user_mailPrimaryAddress3" || fail_test 110
 ad_verify_multi_value_attribute_contains "$AD_DN" \
-	"proxyAddresses" "smtp:$UDM_users_user_mailAlternativeAddress2"; fail_bool 0 110
+	"proxyAddresses" "smtp:$UDM_users_user_mailAlternativeAddress2" || fail_test 110
 ad_verify_multi_value_attribute_contains "$AD_DN" \
-	"proxyAddresses" "$AD_preferred_sip_address"; fail_bool 0 110
-#ad_verify_attribute "$AD_DN" "msExchHomeServerName" "$UDM_users_user_Exchange_Homeserver"; fail_bool 0 110
-#ad_verify_attribute "$AD_DN" "homeMDB" "$UDM_users_user_Exchange_homeMDB"; fail_bool 0 110
-#ad_verify_attribute "$AD_DN" "mailNickname" "$UDM_users_user_Exchange_Nickname"; fail_bool 0 110
+	"proxyAddresses" "$AD_preferred_sip_address" || fail_test 110
+#ad_verify_attribute "$AD_DN" "msExchHomeServerName" "$UDM_users_user_Exchange_Homeserver" || fail_test 110
+#ad_verify_attribute "$AD_DN" "homeMDB" "$UDM_users_user_Exchange_homeMDB" || fail_test 110
+#ad_verify_attribute "$AD_DN" "mailNickname" "$UDM_users_user_Exchange_Nickname" || fail_test 110
 
-udm_verify_udm_attribute "mailPrimaryAddress" "$UDM_users_user_mailPrimaryAddress3" "users/user"; fail_bool 0 110
+udm_verify_udm_attribute "mailPrimaryAddress" "$UDM_users_user_mailPrimaryAddress3" "users/user" || fail_test 110
 udm_verify_multi_value_udm_attribute_contains "mailAlternativeAddress" \
-	"$UDM_users_user_mailAlternativeAddress2" "users/user"; fail_bool 0 110
+	"$UDM_users_user_mailAlternativeAddress2" "users/user" || fail_test 110
 udm_verify_multi_value_udm_attribute_contains "mailAlternativeAddress" \
 	"$UDM_users_user_mailPrimaryAddress3" "users/user"; fail_bool 1 110
 
 ## and the mailPrimaryAddress should get written back to AD:mail too
-ad_verify_attribute "$AD_DN" "mail" "$UDM_users_user_mailPrimaryAddress3"; fail_bool 0 110
+ad_verify_attribute "$AD_DN" "mail" "$UDM_users_user_mailPrimaryAddress3" || fail_test 110
 
 ## don't overwrite UDM/OpenLDAP:"mail", which is only informative
-udm_verify_udm_attribute "e-mail" "$UDM_users_user_mail" "users/user"; fail_bool 0 110
+udm_verify_udm_attribute "e-mail" "$UDM_users_user_mail" "users/user" || fail_test 110
 
-#udm_verify_udm_attribute "Exchange-Homeserver" "$UDM_users_user_Exchange_Homeserver" "users/user"; fail_bool 0 110
-#udm_verify_udm_attribute "Exchange-homeMDB" "$UDM_users_user_Exchange_homeMDB" "users/user"; fail_bool 0 110
-#udm_verify_udm_attribute "Exchange-Nickname" "$UDM_users_user_Exchange_Nickname" "users/user"; fail_bool 0 110
+#udm_verify_udm_attribute "Exchange-Homeserver" "$UDM_users_user_Exchange_Homeserver" "users/user" || fail_test 110
+#udm_verify_udm_attribute "Exchange-homeMDB" "$UDM_users_user_Exchange_homeMDB" "users/user" || fail_test 110
+#udm_verify_udm_attribute "Exchange-Nickname" "$UDM_users_user_Exchange_Nickname" "users/user" || fail_test 110
 
 output=$(univention-adconnector-list-rejected 2>&1)
 if echo "$output" | grep -qi "$UDM_users_user_username"; then
@@ -230,27 +230,27 @@ echo
 udm_modify "users/user" "" "" "" "" \
 		   --append mailAlternativeAddress="$UDM_users_user_mailAlternativeAddress3" || fail_test 110
 
-ad_wait_for_synchronization; fail_bool 0 110
+ad_wait_for_synchronization || fail_test 110
 
-ad_verify_attribute "$AD_DN" "mail" "$UDM_users_user_mailPrimaryAddress3"; fail_bool 0 110
+ad_verify_attribute "$AD_DN" "mail" "$UDM_users_user_mailPrimaryAddress3" || fail_test 110
 ad_verify_multi_value_attribute_contains "$AD_DN" \
-	"proxyAddresses" "SMTP:$UDM_users_user_mailPrimaryAddress3"; fail_bool 0 110
+	"proxyAddresses" "SMTP:$UDM_users_user_mailPrimaryAddress3" || fail_test 110
 ad_verify_multi_value_attribute_contains "$AD_DN" \
-	"proxyAddresses" "smtp:$UDM_users_user_mailAlternativeAddress2"; fail_bool 0 110
+	"proxyAddresses" "smtp:$UDM_users_user_mailAlternativeAddress2" || fail_test 110
 ad_verify_multi_value_attribute_contains "$AD_DN" \
-	"proxyAddresses" "$AD_preferred_sip_address"; fail_bool 0 110
+	"proxyAddresses" "$AD_preferred_sip_address" || fail_test 110
 ad_verify_multi_value_attribute_contains "$AD_DN" \
-	"proxyAddresses" "smtp:$UDM_users_user_mailAlternativeAddress3"; fail_bool 0 110
+	"proxyAddresses" "smtp:$UDM_users_user_mailAlternativeAddress3" || fail_test 110
 
 udm_verify_multi_value_udm_attribute_contains "mailPrimaryAddress" \
-	"$UDM_users_user_mailPrimaryAddress3" "users/user"; fail_bool 0 110
+	"$UDM_users_user_mailPrimaryAddress3" "users/user" || fail_test 110
 udm_verify_multi_value_udm_attribute_contains "mailAlternativeAddress" \
-	"$UDM_users_user_mailAlternativeAddress2" "users/user"; fail_bool 0 110
+	"$UDM_users_user_mailAlternativeAddress2" "users/user" || fail_test 110
 udm_verify_multi_value_udm_attribute_contains "mailAlternativeAddress" \
-	"$UDM_users_user_mailAlternativeAddress3" "users/user"; fail_bool 0 110
+	"$UDM_users_user_mailAlternativeAddress3" "users/user" || fail_test 110
 
 ## don't overwrite UDM/OpenLDAP:"mail", which is only informative
-udm_verify_udm_attribute "e-mail" "$UDM_users_user_mail" "users/user"; fail_bool 0 110
+udm_verify_udm_attribute "e-mail" "$UDM_users_user_mail" "users/user" || fail_test 110
 
 output=$(univention-adconnector-list-rejected 2>&1)
 if echo "$output" | grep -qi "$UDM_users_user_username"; then
