refactor(ucs-test/52/514): delete temporary files
Use undo.sh for cleanup.

Useless use of `echo $(...)` and `cat ... | grep ...`

Issue univention/ucs#1854

diff --git a/test/ucs-test/tests/52_s4connector/514disable_des_enctype b/test/ucs-test/tests/52_s4connector/514disable_des_enctype
--- a/test/ucs-test/tests/52_s4connector/514disable_des_enctype
+++ b/test/ucs-test/tests/52_s4connector/514disable_des_enctype
@@ -13,35 +13,34 @@
 . "$TESTLIBPATH/udm.sh" || exit 137
 # shellcheck source=../../lib/random.sh
 . "$TESTLIBPATH/random.sh" || exit 137
+# shellcheck source=../../lib/ucr.sh
+. "$TESTLIBPATH/ucr.sh" || exit 137
+# shellcheck source=../../lib/undo.sh
+. "$TESTLIBPATH/undo.sh" || exit 137
 
 . "s4connector.sh" || exit 137
+
+tmp="$(mktemp -d)"
+undo rm -rf "$tmp"
 
 SYNCMODE="$(ad_get_sync_mode)"
 ad_set_sync_mode "sync"
 
-ucr set kerberos/defaults/enctypes/permitted="aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arcfour-hmac-md5"
-ucr set kerberos/allow/weak/crypto="false"
+undo /etc/init.d/samba restart
+undo ad_wait_for_synchronization
+
+ucr set kerberos/defaults/enctypes/permitted="aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arcfour-hmac-md5" kerberos/allow/weak/crypto="false"
+undo ucr_restore
 /etc/init.d/samba restart
 
 UDM_users_user_username="$(random_chars)"
 UDM_users_user_lastname="$(random_chars)"
 UDM_users_user_password="Univention.99"
 
-#UDM_users_user_password="U$(random_chars)123"
-echo "$UDM_users_user_password" >> "/tmp/$UDM_users_user_username"
-udm_create "users/user" || fail_test 110
-
-## Cleanup
-cleanup () {
-	rm "514kinit.log"
-	udm_remove "users/user" || fail_test 110
-	ucr unset kerberos/defaults/enctypes/permitted
-	ucr unset kerberos/allow/weak/crypto
-	ad_wait_for_synchronization; fail_bool 0 110
-	/etc/init.d/samba restart
-}
-
-trap cleanup EXIT
+# UDM_users_user_password="U$(random_chars)123"
+echo "$UDM_users_user_password" >"$tmp/$UDM_users_user_username"
+udm_create "users/user" || fail_fast 110
+undo udm_remove "users/user"
 
 ad_wait_for_synchronization; fail_bool 0 110
 
@@ -50,25 +49,29 @@ echo "$rejects" | grep "$UDM_users_user_username" && fail_fast "$UDM_users_user_
 
 kdestroy
 # test if user really cant acquire an des-cbc-crc ticket
-kinit -e "des-cbc-crc" --password-file="/tmp/$UDM_users_user_username" "$UDM_users_user_username" > 514kinit.log 2>&1
-cat 514kinit.log | grep "no valid enctype" || fail_fast "$UDM_users_user_username was able to acquire des-cbc-crc ticket"
+kinit -e "des-cbc-crc" --password-file="$tmp/$UDM_users_user_username" "$UDM_users_user_username" >"$tmp/log" 2>&1
+grep "no valid enctype" "$tmp/log" || fail_fast "$UDM_users_user_username was able to acquire des-cbc-crc ticket"
+
 # test if user really cant acquire an des-cbc-md5 ticket
-kinit -e "des-cbc-md5" --password-file="/tmp/$UDM_users_user_username" "$UDM_users_user_username" > 514kinit.log 2>&1
-cat 514kinit.log | grep "no valid enctype" || fail_fast "$UDM_users_user_username was able to acquire des-cbc-md5 ticket"
+kinit -e "des-cbc-md5" --password-file="$tmp/$UDM_users_user_username" "$UDM_users_user_username" >"$tmp/log" 2>&1
+grep "no valid enctype" "$tmp/log" || fail_fast "$UDM_users_user_username was able to acquire des-cbc-md5 ticket"
 kdestroy
+
 # test if user is still able to acquire an aes128 ticket
-kinit -e "aes128-cts-hmac-sha1-96" --password-file="/tmp/$UDM_users_user_username" "$UDM_users_user_username" > 514kinit.log 2>&1
-cat 514kinit.log | grep "no valid enctype" && fail_fast "$UDM_users_user_username was not able to acquire aes128 ticket"
+kinit -e "aes128-cts-hmac-sha1-96" --password-file="$tmp/$UDM_users_user_username" "$UDM_users_user_username" >"$tmp/log" 2>&1
+grep "no valid enctype" "$tmp/log" && fail_fast "$UDM_users_user_username was not able to acquire aes128 ticket"
 klist | grep "$UDM_users_user_username" || fail_fast "$UDM_users_user_username was not able to acquire aes128 ticket"
 kdestroy
+
 # test if user is still able to acquire an aes256 ticket
-kinit -e "aes256-cts-hmac-sha1-96" --password-file="/tmp/$UDM_users_user_username" "$UDM_users_user_username" > 514kinit.log 2>&1
-cat 514kinit.log | grep "no valid enctype" && fail_fast "$UDM_users_user_username was not able to acquire aes128 ticket"
+kinit -e "aes256-cts-hmac-sha1-96" --password-file="$tmp/$UDM_users_user_username" "$UDM_users_user_username" >"$tmp/log" 2>&1
+grep "no valid enctype" "$tmp/log" && fail_fast "$UDM_users_user_username was not able to acquire aes128 ticket"
 klist | grep "$UDM_users_user_username" || fail_fast "$UDM_users_user_username was not able to acquire aes256 ticket"
 kdestroy
+
 # test if user is still able to acquire an arcfour ticket
-kinit -e "arcfour-hmac-md5" --password-file="/tmp/$UDM_users_user_username" "$UDM_users_user_username" > 514kinit.log 2>&1
-cat 514kinit.log | grep "no valid enctype" && fail_fast "$UDM_users_user_username was not able to acquire aes128 ticket"
+kinit -e "arcfour-hmac-md5" --password-file="$tmp/$UDM_users_user_username" "$UDM_users_user_username" >"$tmp/log" 2>&1
+grep "no valid enctype" "$tmp/log" && fail_fast "$UDM_users_user_username was not able to acquire aes128 ticket"
 klist | grep "$UDM_users_user_username" || fail_fast "$UDM_users_user_username was not able to acquire arcfour ticket"
 kdestroy
 
