* Added S4 connector tests (Bug #25818)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucs@36031 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-test/tests/52_s4connector/73sync_create_ad_groups_nest_on_ucs_side b/test/ucs-test/tests/52_s4connector/73sync_create_ad_groups_nest_on_ucs_side
--- a/test/ucs-test/tests/52_s4connector/73sync_create_ad_groups_nest_on_ucs_side
+++ b/test/ucs-test/tests/52_s4connector/73sync_create_ad_groups_nest_on_ucs_side
@@ -1,57 +1,54 @@
-#!/bin/bash
+#!/usr/share/ucs-test/runner bash 
+## desc: "Create two groups on ad-side and nest them on ucs-side in sync-mode. This will fail on w2k and w2k3. Can't consider that in the test, as I can't distinguish between w2k3 and w2k8 yet."
+## exposure: dangerous
+## packages:
+## - univention-s4-connector
 
-source "$TESTLIBPATH/base.lib"
-source "$TESTLIBPATH/udm.lib"
-source "$TESTLIBPATH/s4connector.lib"
 
-if [ -z "$connector_s4_ldap_host" ]; then
-	warning "connector/s4/ldap/host is empty."
-	warning "Assuming that the Ad-Connector isn't configured."
-	warning "Skipping test."
-	exit 137
-fi
+. "$TESTLIBPATH/base.sh" || exit 137
+. "$TESTLIBPATH/udm.sh" || exit 137
+. "$TESTLIBPATH/random.sh" || exit 137
 
-TEST_BASIC=false
-INFO_LINE="Create two groups on ad-side and nest them on ucs-side in sync-mode. This will fail on w2k and w2k3. Can't consider that in the test, as I can't distinguish between w2k3 and w2k8 yet."
-TEST_SERVER_ROLE="domaincontroller_master domaincontroller_backup"
-TEST_PACKAGES="univention-config univention-s4-connector"
 
-INNER_GROUP="$(randomchars)"
-OUTER_GROUP="$(randomchars)"
+. "s4connector.sh" || exit 137
+test -n "$connector_s4_ldap_host" || exit 137
+
+INNER_GROUP="$(random_chars)"
+OUTER_GROUP="$(random_chars)"
 
 SYNCMODE="$(ad_get_sync_mode)"
 ad_set_sync_mode "sync"
 
-ad_creategroup "$INNER_GROUP" || fail_test 110
-ad_creategroup "$OUTER_GROUP" || fail_test 110
+ad_group_create "$INNER_GROUP" || fail_test 110
+ad_group_create "$OUTER_GROUP" || fail_test 110
 
-ad_wait_for_synchronization; check_bool 0 110
+ad_wait_for_synchronization; fail_bool 0 110
 
 UDM_groups_group_name="$INNER_GROUP"
 udm_modify "groups/group" "" "" "" "" \
 	--append memberOf="cn=$OUTER_GROUP,cn=groups,$ldap_base" || fail_test 110
 
-ad_wait_for_synchronization; check_bool 0 110
+ad_wait_for_synchronization; fail_bool 0 110
 
-ad_exists "CN=$OUTER_GROUP,CN=groups,$(ad_get_base)"; check_bool 0 110
-ad_exists "CN=$INNER_GROUP,CN=groups,$(ad_get_base)"; check_bool 0 110
+ad_exists "CN=$OUTER_GROUP,CN=groups,$(ad_get_base)"; fail_bool 0 110
+ad_exists "CN=$INNER_GROUP,CN=groups,$(ad_get_base)"; fail_bool 0 110
 
 UDM_groups_group_name="$INNER_GROUP"
-udm_exists "groups/group"; check_bool 0 110
+udm_exists "groups/group"; fail_bool 0 110
 UDM_groups_group_name="$OUTER_GROUP"
-udm_exists "groups/group"; check_bool 0 110
+udm_exists "groups/group"; fail_bool 0 110
 
 UDM_groups_group_name="$OUTER_GROUP"
 udm_verify_multi_value_udm_attribute_contains "nestedGroup" \
-	"cn=$INNER_GROUP,cn=groups,$ldap_base" "groups/group"; check_bool 0 110
+	"cn=$INNER_GROUP,cn=groups,$ldap_base" "groups/group"; fail_bool 0 110
 UDM_groups_group_name="$INNER_GROUP"
 udm_verify_multi_value_udm_attribute_contains "memberOf" \
-	"cn=$OUTER_GROUP,cn=groups,$ldap_base" "groups/group"; check_bool 0 110
+	"cn=$OUTER_GROUP,cn=groups,$ldap_base" "groups/group"; fail_bool 0 110
 
 ad_verify_multi_value_attribute_contains "CN=$OUTER_GROUP,CN=groups,$(ad_get_base)" \
-	"member" "CN=$INNER_GROUP,CN=groups,$(ad_get_base)"; check_bool 0 110
+	"member" "CN=$INNER_GROUP,CN=groups,$(ad_get_base)"; fail_bool 0 110
 ad_verify_multi_value_attribute_contains "CN=$INNER_GROUP,CN=groups,$(ad_get_base)" \
-	"memberOf" "CN=$OUTER_GROUP,CN=groups,$(ad_get_base)"; check_bool 0 110
+	"memberOf" "CN=$OUTER_GROUP,CN=groups,$(ad_get_base)"; fail_bool 0 110
 
 section "Clean up"
 
