Bug #38517 Jenkins: UCS-3.2-6
Use new EC2 images of UCS 3.2-6:
-# AMI: Univention Corporate Server (UCS) 3.2 (official image) rev. 5 - ami-7e69da09
+# AMI: Univention Corporate Server (UCS) 3.2 (official image) rev. 7 - ami-cdb3c5ba

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.0/ucs-4.0-1@60866 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/test/ucs-ec2-tools/change-ami b/test/ucs-ec2-tools/change-ami
--- a/test/ucs-ec2-tools/change-ami
+++ b/test/ucs-ec2-tools/change-ami
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 # Change AMI in Jenkins configuration
 #
@@ -9,7 +9,7 @@ die () {
 	exit 1
 }
 check () {
-	command -v euca-describe-images >/dev/null 2>&1 || die "Missing euca2tools"
+	type euca-describe-images >/dev/null 2>&1 || die "Missing euca2tools"
 	[ $# -eq 2 ] || die "Usage: src-ami dst-ami"
 }
 args () {
@@ -50,7 +50,6 @@ __TXT__
 }
 replace () {
 	local cfg
-	cd "$(dirname "$0")"
 	for cfg in examples/jenkins/*.cfg
 	do
 		[ -f "$cfg" ] || continue
