* Package cleanup for UCS 3.0 (Bug #22431):   * Bump version for UCS 3.0   * Replace univention-baseconfig with univention-config-registry   * Replace static UCR header in the UCR templates with '@%@UCRWARNING=#     @%@'   * Removed no longer used univention-ldap-server.preinst   * Removed old transition code from postinst files   * Update copyright to 2011   * Update to debhelper 7 * Use slapcat for dumping the ldap backup (Bug #20215) * Set ldap/idetimeout by default to 360 seconds (Bug #17706)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.0/ucs@23894 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/management/univention-ldap/univention-ldap-backup b/management/univention-ldap/univention-ldap-backup
--- a/management/univention-ldap/univention-ldap-backup
+++ b/management/univention-ldap/univention-ldap-backup
@@ -3,7 +3,7 @@
 # Univention LDAP Server
 #  creates an LDIF backup on UCS master and UCS backup
 #
-# Copyright 2001-2010 Univention GmbH
+# Copyright 2001-2011 Univention GmbH
 #
 # http://www.univention.de/
 #
@@ -31,7 +31,7 @@
 # <http://www.gnu.org/licenses/>.
 
 
-eval `univention-baseconfig shell`
+eval `univention-config-registry shell`
 
 if [ "$server_role" = "domaincontroller_master" -o "$server_role" = "domaincontroller_backup" ]; then
 
@@ -41,7 +41,7 @@ if [ "$server_role" = "domaincontroller_master" -o "$server_role" = "domaincontr
 
 	chmod 600 $ldapbackupname
 
-	ldapsearch -h localhost -LLL -x -w `cat /etc/ldap.secret` -D "cn=admin,$ldap_base" -b "$ldap_base" >>$ldapbackupname 2>&1 || echo "LDAP could not be dumped!"
+	slapcat >$ldapbackupname 2>&1 || echo "LDAP could not be dumped!"
 
 	gzip -9 $ldapbackupname 2>/dev/null
 
